### ISSUE TITLE
wallet not syncing six months of blocks

### ISSUE THREAD

**Issue by peteratomic** [ethereum/mist#2101] opened 2017-04-01 21:56 UTC
Didn't open my wallet in quite a while. When I restart the wallet, for a moment I see a red error-like message "6 months since last block" and then that disappears and then it seems nothing happens after that. While I can see in my chain data folder than new blocks are downloading, nothing is happening in that six month gap. 

#### System information
``````
Version: `0.8.9`
OS & Version: osx
Node type: `geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files 

[nodelog.zip](https://github.com/ethereum/mist/files/888019/nodelog.zip)

 
![screen shot 2017-04-01 at 11 48 26 pm](https://cloud.githubusercontent.com/assets/7466182/24582732/66265ed4-1736-11e7-8a1c-76d8d7c09245.png)
![screen shot 2017-04-01 at 11 33 04 pm](https://cloud.githubusercontent.com/assets/7466182/24582733/6671a434-1736-11e7-9184-5bc21c18dce5.png)

![screen shot 2017-04-01 at 11 55 45 pm](https://cloud.githubusercontent.com/assets/7466182/24582744/c2d05072-1736-11e7-9c5b-411501af6e00.png)
![screen shot 2017-04-01 at 11 55 36 pm](https://cloud.githubusercontent.com/assets/7466182/24582743/c2cc193a-1736-11e7-9e6f-b4f1300d0251.png)

**Comment by peteratomic** [comment] 2017-04-02 08:44
Tried a system restart. Still showing several peers, the blocks have increased in number but it doesn't show anything in the cloud download icon. Which is odd because new blocks are definitely downloading. There's just a big gap between yesterday and last October (seemingly the last time I opened up the wallet).

Additionally, the transaction I made yesterday still hasn't synced locally.

**Comment by garretlaxton** [comment] 2017-04-02 15:29
Yes, your wallet will need to sync those blocks which may take some time. Has your percentage gone up since?

**Comment by peteratomic** [comment] 2017-04-03 06:53
You mean the download percentage? Its always at 0.
Always see 5-10 peers and the block numbers increasing, but never downloading anything but the latest blocks. The 6 or 7 month gap never goes away.

**Comment by luclu** [comment] 2017-04-08 10:47
@peteratomic could you please upload your `node.log` file? You can find the instructions below:

Also please make sure no firewall is blocking outgoing connections. 

#### Some more generic advice:

Please, make sure you are running the [latest version](https://github.com/ethereum/mist/releases) and your node is **fully** synced.
Although this may take between 1h (SSD) and 10 hours (HDD) you should be able to see a progress bar on the *splash-screen* or in the *main-window*.

Further recommendations: 
- check your account's balance using http://etherscan.io
- make a backup of all account's keyfiles via `menu -> accounts -> backup -> accounts`
- should the initial sync take very long, consider following [these instructions](https://ethereum.stackexchange.com/questions/6554/i-am-having-trouble-doing-the-initial-sync-of-ethereum-wallet-what-can-i-do-to/6569) to speed it up
- if the peer count stays at 0 and it does not sync, verify your firewall settings
- consider using http://myetherwallet.com in the meantime

If this didn't solve your issue, please follow [these instructions](https://github.com/ethereum/mist/issues/new) and upload the `node.log` files:
> - Log files
>   - go to menu -> accounts -> backup -> application data
>   - zip and upload node.log and all other node.log.X files

**Comment by peteratomic** [comment] 2017-04-08 11:49
Hi Luclu, thanks very much for the help!

- NODE files zipped and attached
- backup of Keystore folder done (assuming that's what you meant as the backup process wasn't obvious)
- I checked Etherscan last week and that has the correct amount
- running latest version
- show multiple peers in the top section of the app
- firewall wasn't set to block outgoing

Regarding syncing, that seems to be the problem. Only new blocks sync, nothing during the seven month gap between when I last opened the app and a week ago. 

When I launch the wallet, it almost instantly jumps into opening the full app. In the past it used to stay on the small window and start downloading blocks, then you'd have to click LAUNCH APP to see the app.

OK, so after checking all of the above, I followed the instructions about the "initial sync" which amounted to quitting the wallet, deleting or renaming the chaindata folder and restarting. But that didn't work. Got a bunch of errors including "Fatal: Error starting protocol stack: listen udp :30303: bind: address already in use" and then the splash window simply says "Ethereum node cannot run. Is another instance already running?"

Possible that geth is running via command line? I tried a bunch of geth help (geth -help, geth --help) commands but its not clear if it's running. Vaguely remember a friend setting this up for me and not 100% clear if he installed geth before the wallet app was released.

Any other ideas about how another instance could be running?

**Comment by peteratomic** [comment] 2017-04-08 11:54
Wondering if all this happened because I opened up Mist before the Wallet was fully synced. Could that be the other running instance, even if the app isn't open?

**Comment by peteratomic** [comment] 2017-04-08 12:01
Here's the full error message:

`...Ethereum/chaindata
I0408 13:57:54.630192 ethdb/database.go:176] closed db:/Users/userfoldername/Library/Ethereum/chaindata
I0408 13:57:54.631220 node/node.go:176] instance: Geth/v1.5.9-stable-a07539fb/darwin/go1.7.4
I0408 13:57:54.632430 ethdb/database.go:83] Allotted 1024MB cache and 1024 file handles to /Users/userfoldername/Library/Ethereum/chaindata
I0408 13:57:55.014285 eth/backend.go:187] Protocol Versions: [63 62], Network Id: 1
I0408 13:57:55.800010 eth/backend.go:205] WARNING: Wrote default ethereum genesis block
I0408 13:57:55.800455 eth/backend.go:215] Chain config: {ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000}
I0408 13:57:55.806191 core/blockchain.go:219] Last header: #0 [d4e56740…] TD=17179869184
I0408 13:57:55.806234 core/blockchain.go:220] Last block: #0 [d4e56740…] TD=17179869184
I0408 13:57:55.806249 core/blockchain.go:221] Fast block: #0 [d4e56740…] TD=17179869184
I0408 13:57:55.809429 p2p/server.go:340] Starting Server`

The chaindata folder is actually on an external hard drive, not the user folder in the error listed above. In this last attempt to relaunch I can see it successfully wrote a bunch of files to the right folder:

![screen shot 2017-04-08 at 2 00 51 pm](https://cloud.githubusercontent.com/assets/7466182/24828728/e2026200-1c63-11e7-910e-94ac4059644b.png)

**Comment by luclu** [comment] 2017-04-10 17:58
> When I launch the wallet, it almost instantly jumps into opening the full app. In the past it used to stay on the small window and start downloading blocks, then you'd have to click LAUNCH APP to see the app.

This was actually our mistake, will be fixed/reverted in the next version.

> Got a bunch of errors including "Fatal: Error starting protocol stack: listen udp :30303: bind: address already in use" and then the splash window simply says "Ethereum node cannot run. Is another instance already running?"

This message is likely caused by a changed datadir for geth, but a missing rpc flag in Mist to follow the change. 
If you want to change the datadir either:
1. create a symlink (see [here](https://github.com/ethereum/mist/issues/572#issuecomment-258017959))
2. append flags Mist (see [here](https://github.com/ethereum/mist/issues/1687#issuecomment-283461586))

Your node logs are mostly empty which could mean that either:
- geth was closed shortly after starting or
- geth tries to reorganize the chaindata, which might take a long time before the sync starts

**Comment by peteratomic** [comment] 2017-04-10 18:48
Hi Luca,

I had successfully moved the chaindata months ago. It was updating all of the newest blocks to that external drive, just not the missing gap. But now that I followed one of the other tutorials trying to wipe the chaindata so it would start over, things are now even worse than before as I cannot even launch the app.

Can see a working shortcut to the external drive on my main hard drive in my Library/Ethereum folder. But I couldn't parse what you meant by "append this flag to the executable/shortcut: --node-datadir D:\Ethereum --rpc D:\Ethereum\geth.ipc"

**Comment by evertonfraga** [comment] 2017-08-14 21:47
@peteratomic did you manage to solve this? Want any help?

**Comment by peteratomic** [comment] 2017-08-15 08:13
Nope. Gave up.

**Closed** 2017-09-05 00:14 UTC
Labels: Information needed, v0.8.9

**Comment by evertonfraga** [comment] 2017-09-28 19:44
Hi @peteratomic, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist
