### ISSUE TITLE
Mist error

### ISSUE THREAD

**Issue by cytos** [ethereum/mist#524] opened 2016-05-01 13:50 UTC
![aa](https://cloud.githubusercontent.com/assets/18901247/14942139/4eefd09a-0fb4-11e6-96b2-c2e61a9c2afa.jpg)
Hey guys, 

I wanted to install the ETH wallet and get this error. I took a look at the forum but did not found any help. Could you help me fixing it? 
Thanks!

Here my nod.log
I0501 15:46:59.847657    2824 flags.go:425] WARNING: No etherbase set and no accounts found as default
I0501 15:46:59.849657    2824 database.go:71] Alloted 433MB cache to C:\Users\xxxx\AppData\Roaming\Ethereum\chaindata
I0501 15:46:59.871658    2824 database.go:71] Alloted 78MB cache to C:\Users\xxxx\AppData\Roaming\Ethereum\dapp
I0501 15:46:59.880658    2824 backend.go:314] Protocol Versions: [63 62 61], Network Id: 1
I0501 15:46:59.880658    2824 backend.go:362] Blockchain DB Version: 3
I0501 15:46:59.881658    2824 blockchain.go:214] Last header: #0 [d4e56740…] TD=17179869184
I0501 15:46:59.881658    2824 blockchain.go:215] Last block: #0 [d4e56740…] TD=17179869184
I0501 15:46:59.881658    2824 blockchain.go:216] Fast block: #0 [d4e56740…] TD=17179869184
I0501 15:46:59.887659    2824 cmd.go:115] Starting Geth/v1.3.6/windows/go1.5.1
I0501 15:46:59.887659    2824 server.go:311] Starting Server

**Comment by luclu** [comment] 2016-05-01 13:59
Are you on a 32bit Windows?
Then you might need the 32bit version of Mist: https://github.com/ethereum/mist/issues/381

**Comment by cytos** [comment] 2016-05-01 14:01
I use Windows 64 and downloaded the 64bit version of the mist

**Comment by cytos** [comment] 2016-05-01 14:06
![asd](https://cloud.githubusercontent.com/assets/18901247/14942222/a26c4d5a-0fb6-11e6-80a2-ee65a7b93212.jpg)

**Comment by cytos** [comment] 2016-05-01 14:25
No one knows? :(

**Comment by cytos** [comment] 2016-05-02 05:54
Still not fixed

**Comment by frozeman** [comment] 2016-05-02 05:56
Looks like you geth is not starting the IPC connection. You could start the node yourself and see if it will start the pic connection. Go to the ..wallet/resources/node/geth folder and run the geth.exe.

Look for a message saying `IPC server started...` or so and then run the wallet.

It might be you firewall or something blocking the node.

**Comment by bas-vk** [comment] 2016-05-03 11:37
@frozeman, I'm not sure this is caused by not starting the IPC. The last part of the log indicates that it is trying to open the p2p port (`Starting server`). The IPC interface is only started after this step.

My guess is that your firewall doesn't allow geth to open this port. You should check your firewall and OS logs what is blocking geth and how give geth access.

**Comment by cytos** [comment] 2016-05-03 17:19
Well I turned my firewall off and it still does not work

**Comment by cytos** [comment] 2016-05-03 17:48
Anything more I could try? I mean I did like everything lol

**Comment by bas-vk** [comment] 2016-05-04 07:30
When you start the wallet it will start geth in the background. If you start geth from the command line manually it might be possible to get more information about the problem.

Open a command line, navigate to:
`<directory where you unzipped the wallet>/Ethereum-Wallet-win64-0-7-2/resources/node/geth`

In this directory there should be a geth.exe. Run this with:

`.\geth.exe --fast --verbosity 6 > geth.log`

Wait for 20 seconds, open a second command line and navigate to the directory with `geth.exe`. Start a second instance of geth with `.\geth.exe attach`. If this fails add a comment here with the `geth.log` created in the first step. If this succeeds try to start mist while having geth running in the background. In this case mist will not try to start geth but will try to connect to the running instance. Report if mist starts and begins synchronizing. If not, post the `geth.log`.

**Comment by cytos** [comment] 2016-05-04 09:09
My log is empty o.o

**Comment by cytos** [comment] 2016-05-04 09:11
I started with cmd and followed the instructions as above : .\geth.exe --fast --verbosity 6 > geth.log

after i did the same in a second windows with the attach command.
The log file is empty

**Comment by bas-vk** [comment] 2016-05-04 11:04
Sry, the command must be: `.\geth.exe --fast --verbosity 6 2> geth.log` (add the 2)

**Comment by cytos** [comment] 2016-05-06 18:38
Now my logfile shows: I0506 20:37:27.709173    7936 flags.go:425] WARNING: No etherbase set and no accounts found as default
I0506 20:37:27.711173    7936 database.go:71] Alloted 16MB cache to C:\Users\xxx\AppData\Roaming\Ethereum\chaindata
I0506 20:37:27.738175    7936 database.go:71] Alloted 16MB cache to C:\Users\xxx\AppData\Roaming\Ethereum\dapp
I0506 20:37:27.754175    7936 backend.go:314] Protocol Versions: [63 62 61], Network Id: 1
I0506 20:37:27.754175    7936 backend.go:362] Blockchain DB Version: 3
I0506 20:37:27.755175    7936 blockchain.go:214] Last header: #0 [d4e56740…] TD=17179869184
I0506 20:37:27.755175    7936 blockchain.go:215] Last block: #0 [d4e56740…] TD=17179869184
I0506 20:37:27.755175    7936 blockchain.go:216] Fast block: #0 [d4e56740…] TD=17179869184
I0506 20:37:27.762176    7936 cmd.go:115] Starting Geth/v1.3.6/windows/go1.5.1
I0506 20:37:27.763176    7936 server.go:311] Starting Server

**Comment by cytos** [comment] 2016-05-06 18:39
Isn´t it basicly the same as above?

**Comment by Ahaezod** [comment] 2016-05-08 16:08
Hi guys,

I do have the exact same issue as Cytos. If nothing has been found about this issue, i'd be glad to read about it. Running on Win 10 64 bits.

Using AlethZero I managed to download a part of the blockchain. But as the soft is deprecated, I tried to get back the basics, using Mist. I also tried Mist before using AlethZero btw, and I got the same message as Cytos again.

Firewall is off, time is sync.

Any guess?

Thanks

**Comment by cytos** [comment] 2016-05-08 17:08
@Ahaezod I´m sorry you got the same error. Guess nobody cares here or they simply dont have the solution. :(

**Comment by Ahaezod** [comment] 2016-05-08 18:23
@cytos Hi, at least, with the comment I left above in the EDIT section, you can start downloading the BChain. It solved a part of the issue.

**Comment by Ahaezod** [comment] 2016-05-10 17:03
@cytos Ok, I checked a dozen of different topics, and this issue was already solved in on of them.

Open a CMD command, through de CD command, reach the folder were you have download Ethereum:
cd Users\...\<folder with Ethereum>\resources\node\geth

Then you type : geth --nat=none

After that, just return into your Mist ethereum folder and execute the Ethereum-Wallet.exe and it should work just fine.

I advise you to delete the whole block chain you have download so far, and to download it back in fast mode, by typing: Geth --fast --nat=none --rpc 
It took me 2h30 to be sync this way. Without --fast, it took me a couple of day to get only 50% of the blockchain. If the download freezes, just kill the command by typing Ctrl+C 10 times and retype Geth --fast --nat=none --rpc 
It will start where the blockchain was left.

Once the whole BChain is DL'ed in fast mode, go back to first advice : geth --nat=none, and gogo Ethereum-Wallet.exe


Hope it helped ;)

**Comment by cytos** [comment] 2016-05-16 09:43
It worked. Thanks! But what does : geth --nat=none do?

**Comment by luclu** [comment] 2016-05-19 22:12
I will close this and link to duplicate https://github.com/ethereum/mist/issues/292.

**Closed by luclu** 2016-05-19 22:12 UTC

**Comment by mbithy** [comment] 2017-05-13 07:49
You did not create an account on the main network and somehow it's where you are looking... same error will occur if you also did not create an account on the test network and somehow it's where you are looking. It say it right there in the message.
**No etherbase set and no accounts found as default**

**simplest fix**, _applies if you had created an account in one of the networks_

1. go to "C:\Users\XXXXX\AppData\Roaming\Ethereum Wallet"
2. find the file called network
3. open it with notepad or whatever text editor you prefer
4. you will find the word "test" or "main"
5. change it to either where your account was. i.e. if you had an account in the main network and it says test change it to main, if you had an account in the test network and it says main change it to test

NB: creators should ensure in the next release they search for accounts in both networks, regardless of what the network file says before deciding to fail start up forever...

**how to Recreate the error**

1. Open mist
2. On the menu find Develop > Network > select any which is un-selected
3. restart
