### ISSUE TITLE
Need a socks 5 proxy

### ISSUE THREAD

**Issue by jnsday** [ethereum/mist#1792] opened 2017-03-23 07:34 UTC
We are in china,and the peer is only one or zero..
It's not ok..
and the wallet havn't a way to connect the network with socks5 proxy..
Can it be done?

**Comment by luclu** [comment] 2017-03-26 23:05
Duplicate of Duplicate of https://github.com/ethereum/mist/issues/1385

**Closed by luclu** 2017-03-26 23:05 UTC
