### ISSUE TITLE
Password works on Ethereum Wallet 0.7.2 but not on 0.7.4 or 0.7.5

### ISSUE THREAD

**Issue by cram123** [ethereum/mist#870] opened 2016-06-22 01:30 UTC
Node type: geth/eth
OS: windows
Network type: main/test
Mist version: 0.7.4

I originally installed/ran 0.7.2 everything was fine. Then I downloaded 0.7.4 and when I was trying to send ether it would not take my password saying it was wrong. If I ran 0.7.2 it works fine.

**Comment by luclu** [comment] 2016-06-22 03:16
Make sure you don't have multiple copies of a wallet's keyfile in your `%appdata%\Ethereum\keystore` - see here https://github.com/ethereum/mist/issues/780.

**Comment by cram123** [comment] 2016-06-22 12:28
Looks like that worked! Thank you!

I am not sure how that happened, Might be something that should be handled
gracefully by the app

**Comment by luclu** [comment] 2016-06-22 12:29
Yes, this is a bug - will be fixed!

Closed as duplicate of #780.

**Closed by luclu** 2016-06-22 12:29 UTC
