### ISSUE TITLE
Cannot see wallet contract when using mist wallet 8.3 or 8.4

### ISSUE THREAD

**Issue by Dynamo77** [ethereum/mist#1236] opened 2016-09-30 12:39 UTC
Hi, 

I have a contract wallet, that I can see when running off the mist wallet 8.2, but when using 8.3 or 8.4 I cannot see this contract wallet. How do I resolve this so I can see it in the latest version of the mist wallet?

#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files (Go to `menu -> accounts -> backup -> application data` and upload as zip-archive):
  -   osx: `~/Library/Application Support/Mist/node.log` 
  -   windows: `%APPDATA%/Roaming/Mist/node.log`
  -   linux: `~/.config/Mist/node.log`

**Comment by luclu** [comment] 2016-09-30 20:03
This issue has been identified. It is caused by the new installer which required to setup separate config folders for Ethereum Wallet and Mist - only retaining Mist's config folder used by both in release `<0.8.3`.
> Finally this the new installer split the config-folder into separate ones for **Ethereum Wallet** and **Mist**. As a result Ethereum Wallet won't display any previous *watched custom contracts and token* as well as *contract wallets* and *wallet names*. Although they are still available in Mist and Ethereum Wallet `< 0.8.3` you will need to re-added them manually to Ethereum Wallet `>= 0.8.3`.

Closed as duplicate of #1174.

**Closed by luclu** 2016-09-30 20:03 UTC
