### ISSUE TITLE
Backup

### ISSUE THREAD

**Issue by aznisa07** [ethereum/mist#1253] opened 2016-10-04 02:30 UTC
#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by luclu** [comment] 2016-10-04 07:58
Duplicate of https://github.com/ethereum/mist/issues/555.

**Closed by luclu** 2016-10-04 07:58 UTC
