### ISSUE TITLE
Create contract success on ethscan on rinkeby but still in creating state in ethereum wallet 0.9

### ISSUE THREAD

**Issue by blisscs** [ethereum/mist#3099] opened 2017-09-29 05:00 UTC
```
Version: `0.9.1`
OS & Version: ubuntu 17.04
Node version: `geth 1.7.0-stable-6c6c7b2a` 
Ethereumwallet version: 0.9.1
```
When creating a new contract in using ethereum wallet. 
The status on ethereum wallet is never completed. Eventhough I can see the contract on the ethscan aleady.

Thanks
Dev.

**Comment by evertonfraga** [comment] 2017-09-29 05:35
is it a wallet contract you’re creating from the interface, or are you
compiling your own code?

**Comment by blisscs** [comment] 2017-09-29 06:01
It's basic mitisig contract. I am creating through Add Wallet contract > MultiSig Contract

**Comment by evertonfraga** [comment] 2017-09-29 18:05
Duplicate of #2845.

I'm looking at this atm.

**Closed by evertonfraga** 2017-09-29 18:05 UTC
