### ISSUE TITLE
Contract Problems

### ISSUE THREAD

**Issue by CasaSky** [ethereum/mist#2886] opened 2017-08-04 22:11 UTC
``````
Version: `0.9.0`
OS & Version: linux
Node type: `geth`
Number of blocks synchronized: 4 117 617
``````
I bought 2 days ago a contract. Till now it's not been created -> "Creating..."
I had an issue by creating accidentally a second contract -> Caution! There is no delete functions after creating contracts. I don't know how this can't be implemented when a creation function exists.

When i bought the first contract it was not showing the price clearly ---> It shows 0 ETH that is confusing. Later i realized that the real price for a contract was 0.04 ETH. The real price was hidden  when clicking on add a contract. 

- Screenshots and files:

![console](https://user-images.githubusercontent.com/12476711/28988922-8e23c0cc-7972-11e7-9104-c6912d77f745.png)

![wallet](https://user-images.githubusercontent.com/12476711/28988921-8e235e34-7972-11e7-855c-6810a1091cb6.png)

[nodeLogs.zip](https://github.com/ethereum/mist/files/1201778/nodeLogs.zip)

**Comment by evertonfraga** [comment] 2017-08-17 00:45
Duplicate of https://github.com/ethereum/mist/issues/2845.

Please read the issue above to a hotfix, while it's not fixed in production.

**Closed by evertonfraga** 2017-08-17 00:45 UTC
Labels: v0.9.0

**Comment by CasaSky** [comment] 2017-08-25 15:49
@evertonfraga May a delete function of by accident created contracts be implemented in future releases?
