### ISSUE TITLE
0.8.0 Broken builds

### ISSUE THREAD

**Issue by ageyev** [ethereum/mist#940] opened 2016-07-08 16:26 UTC
Node type: geth/eth
OS: Linux - Ubuntu 16.04 x64
Network type: both: main/test
Mist version: 0.8.0

````sh
viktor@ThinkPad:~$ /home/viktor/Ethereum-Wallet-linux64-0-8-0/Ethereum-Wallet
[2016-07-08 19:19:02.443] [INFO] main - Running in production mode: true
[2016-07-08 19:19:02.525] [INFO] main - Starting in Wallet mode
[2016-07-08 19:19:02.933] [INFO] Windows - Creating commonly-used windows
[2016-07-08 19:19:02.937] [INFO] Windows - Create secondary window: loading, owner: notset
[2016-07-08 19:19:03.015] [INFO] updateChecker - Check for update...
[2016-07-08 19:19:04.647] [INFO] Windows - Create primary window: main, owner: notset
[2016-07-08 19:19:04.660] [INFO] Windows - Create primary window: splash, owner: notset
[2016-07-08 19:19:05.225] [INFO] ipcCommunicator - Backend language set to:  en-US
[2016-07-08 19:19:05.773] [ERROR] updateChecker - Error checking for update TypeError: Invalid Version: 0.8
    at new SemVer (/home/viktor/Ethereum-Wallet-linux64-0-8-0/resources/app.asar/node_modules/semver/semver.js:293:11)
    at compare (/home/viktor/Ethereum-Wallet-linux64-0-8-0/resources/app.asar/node_modules/semver/semver.js:566:10)
    at Function.gt (/home/viktor/Ethereum-Wallet-linux64-0-8-0/resources/app.asar/node_modules/semver/semver.js:595:10)
    at got.then (/home/viktor/Ethereum-Wallet-linux64-0-8-0/resources/app.asar/modules/updateChecker.js:49:20)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[2016-07-08 19:19:05.925] [INFO] (ui: splash) - Web3 already initialized, re-using provider.
[2016-07-08 19:19:06.069] [INFO] Sockets/node-ipc - Connect to {"path":"/home/viktor/.ethereum/geth.ipc"}
[2016-07-08 19:19:06.077] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2016-07-08 19:19:07.081] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2016-07-08 19:19:08.082] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2016-07-08 19:19:09.077] [ERROR] Sockets/node-ipc - Connection failed (3000ms elapsed)
[2016-07-08 19:19:09.082] [WARN] EthereumNode - Failed to connect to node. Maybe it's not running so let's start our own...
[2016-07-08 19:19:09.083] [INFO] EthereumNode - Node type: geth
[2016-07-08 19:19:09.083] [INFO] EthereumNode - Network: main
[2016-07-08 19:19:09.085] [INFO] EthereumNode - Start node: geth main
[2016-07-08 19:19:09.122] [ERROR] main - UNCAUGHT EXCEPTION { Error: spawn EACCES
    at exports._errnoException (util.js:949:11)
    at ChildProcess.spawn (internal/child_process.js:302:11)
    at exports.spawn (child_process.js:379:9)
    at logRotate (/home/viktor/Ethereum-Wallet-linux64-0-8-0/resources/app.asar/modules/ethereumNode.js:385:30)
    at /home/viktor/Ethereum-Wallet-linux64-0-8-0/resources/app.asar/node_modules/log-rotate/index.js:84:11
    at FSReqWrap.oncomplete (fs.js:117:15) code: 'EACCES', errno: 'EACCES', syscall: 'spawn' }
[2016-07-08 19:19:09.162] [INFO] main - Defer quitting until sockets and node are shut down
[2016-07-08 19:19:09.162] [INFO] Sockets - Destroy all sockets
[2016-07-08 19:19:09.163] [INFO] Sockets/7 - Disconnecting...
[2016-07-08 19:19:09.164] [INFO] Sockets/node-ipc - Disconnecting...
/home/viktor/Ethereum-Wallet-linux64-0-8-0/resources/app.asar/node_modules/solc/soljson.js:1
(function (exports, require, module, __filename, __dirname, process, global) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](fil

Error: spawn EACCES
    at exports._errnoException (util.js:949:11)
    at ChildProcess.spawn (internal/child_process.js:302:11)
    at exports.spawn (child_process.js:379:9)
    at logRotate (/home/viktor/Ethereum-Wallet-linux64-0-8-0/resources/app.asar/modules/ethereumNode.js:385:30)
    at /home/viktor/Ethereum-Wallet-linux64-0-8-0/resources/app.asar/node_modules/log-rotate/index.js:84:11
    at FSReqWrap.oncomplete (fs.js:117:15)
viktor@ThinkPad:~$ 

````

'Ethereum-Wallet-linux64-0-7-6' works
'geth' works

**Comment by emelbardis** [comment] 2016-07-08 16:30
Same for me when trying Mist on Fedora 24 x86_64
Ethereum Wallet 0.8.0 works great without issue though

**Comment by robertandrewsmith** [comment] 2016-07-08 16:44
Same for me on Mist-Linux 64 "Ubuntu 15.04"
Running Geth Node 1.4.9
Small white screen appears like a flash, then disappears, Mist shuts down.

**Comment by maxxflyer** [comment] 2016-07-08 16:57
Same here. 
Ubuntu 14.04.4 LTS
Previous Wallet works

**Comment by nicksavers** [comment] 2016-07-08 17:09
For me almost the same, but instead of `EACCESS` the word `ENOTDIR` is displayed

Mist version 0.8.0
Ubuntu 16.04 x64

As for Ethereum Wallet 0.8.0, it still works, but also displays the error
```
[2016-07-08 18:05:35.363] [ERROR] updateChecker - Error checking for update TypeError: Invalid Version: 0.8
    at new SemVer (/home/nick/Ethereum-Wallet-linux64-0-8-0/resources/app.asar/node_modules/semver/semver.js:293:11)
    at compare (/home/nick/Ethereum-Wallet-linux64-0-8-0/resources/app.asar/node_modules/semver/semver.js:566:10)
    at Function.gt (/home/nick/Ethereum-Wallet-linux64-0-8-0/resources/app.asar/node_modules/semver/semver.js:595:10)
    at got.then (/home/nick/Ethereum-Wallet-linux64-0-8-0/resources/app.asar/modules/updateChecker.js:49:20)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by luclu** [comment] 2016-07-08 18:33
@/all I am sorry to hear about these issues which are caused by some broken builds. Please try to redownload - the checksums have been updated accordingly.

**Comment by nicksavers** [comment] 2016-07-08 19:03
```
Error: spawn EACCES
    at exports._errnoException (util.js:949:11)
    at ChildProcess.spawn (internal/child_process.js:302:11)
    at exports.spawn (child_process.js:379:9)
    at logRotate (/home/nick/Ethereum-Wallet-linux64-0-8-0/resources/app.asar/modules/ethereumNode.js:385:30)
    at /home/nick/Ethereum-Wallet-linux64-0-8-0/resources/app.asar/node_modules/log-rotate/index.js:84:11
    at FSReqWrap.oncomplete (fs.js:117:15)
```
This error is fixed with the latest upload/

**Comment by emelbardis** [comment] 2016-07-09 04:14
Fixed for me as well. 
Can open and sync Mist 0.8.0 and also Ethereum-Wallet 0.8.0 as expected.

**Comment by 5chdn** [comment] 2016-07-09 08:52
> I am sorry to hear about these issues which are caused by some broken builds. Please try to redownload now - the checksums have been updated accordingly.

@luclu could you bump version numbers if you do that again in future? as a package maintainer it's a hell to keep checking for new _updates_ if the only hint is the new checksum.

**Comment by luclu** [comment] 2016-07-09 11:12
@5chdn sorry for this. I know as a Arch user that two days into a release is high pressure for a package maintainer. ;)
We will bump them as we merge the current develop into master: https://github.com/ethereum/mist/pull/934

**Closed** 2016-07-09 11:18 UTC

**Comment by 5chdn** [comment] 2016-07-09 11:37
@luclu thanks for feeling my pressure. I had three out-of-date notifications last night :-P

**Comment by luclu** [comment] 2016-07-09 11:58
@5chdn subscribe to https://github.com/ethereum/mist/pull/934 to get notified as soon as it get merged :)
