### ISSUE TITLE
Ethereum will not start right

### ISSUE THREAD

**Issue by BitcoinSHARK** [ethereum/mist#183] opened 2016-02-16 21:41 UTC
Hello,
Problem:
I cleared all old files from my pc an start the new ethereum Ethereum-Wallet-win64-0-4-0.
i think all is ok. i put my backup wallet into the right folder and start ethereum again...
but now... nothing ...

![ethereum](https://cloud.githubusercontent.com/assets/17280906/13092044/4e15b194-d4fe-11e5-93c5-ac193a1abf64.PNG)

can someone help me please ;)

**Comment by xcgabriel** [comment] 2016-02-17 06:51
Sync your windows clock to some NTP server. 15s time diff will make it stall and not find any peers.

**Comment by BitcoinSHARK** [comment] 2016-02-17 11:51
Hello xcgabriel,
thanks for your tip. i configured a new timeserver ( de.pool.ntp.org ) and changed my syncinterwall on registry to sync every one hour! i don´t know why, but ethereum will not sync....
cracy stuff....

**Comment by awrelll** [comment] 2016-02-17 12:26
I got the same issue under OSX. It seems there's a IPC related issue and integrated geth won't start .
`IPC Connection Error Object {address: "/Users/aurel/Library/Ethereum/geth.ipc", code: "ECONNREFUSED", errno: "ECONNREFUSED", syscall: "connect"}(anonymous function) @ /Users/aurel/Downloads/Ethereum-Wallet-macosx64-0-4-0/Ethereum-Wallet.app/Contents/Resources/app.as…:37(anonymous function) @ /Users/aurel/Downloads/Ethereum-Wallet-macosx64-0-4-0/Ethereum-Wallet.app/Contents/Resources/app.as…:51emitTwo @ events.js:87emit @ events.js:172`

<img width="1024" alt="screen shot 2016-02-17 at 14 21 58" src="https://cloud.githubusercontent.com/assets/6716597/13109510/55e9a9e6-d582-11e5-8587-c72cf0ad9555.png">

**Comment by frozeman** [comment] 2016-02-17 12:29
@awrelll please see your activity tab and see if youre already running a geth node, if so kill it and restart mist.

@BitcoinSHARK i assume you have a firewall on or something, there were already many more issues like this, please look in the issue history.

**Comment by awrelll** [comment] 2016-02-17 12:33
@frozeman i closed Mist, reviewed my processes list. Found no second instance of geth running. I started Mist again and it worked ! Can't reproduce the issue :) Thanks anyway !

**Comment by micronizerbattheend** [comment] 2016-02-20 08:04
I have the same problem as described here. It's stuck forever "looking for peers" even now that my clock is alright. However, someone suggested a workaround that worked for me: If you click "skip peer search" then wait a rather long time on the next screen, peers eventually may start to appear.

Also previously I may have had problems because of the unusual time zone of my country that maybe was wrongly perceived as time out of sync by Mist. For that problem I downloaded a hotfix from microsoft to stop daylight savings time corrections, but I don't know if it had an effect, as Mist has never outputted any kind of error message regarding system clock settings (which IMO would be a good thing to have on that splash screen)

**Comment by frozeman** [comment] 2016-02-22 11:46
@micronizerbattheend your issue was fixed in geth#develop, you need to wait for the over-next geth version, sorry..

**Closed** 2016-05-05 11:47 UTC
Labels: in progress
