### ISSUE TITLE
I can't import my wallet

### ISSUE THREAD

**Issue by v03dyx** [ethereum/mist#4047] opened 2018-08-02 17:04 UTC
Version: `0.11.1`
OS & Version: windows
Node version: `geth 0.0.0`
Number of blocks synchronized: 0
```

![2018-08-02_19-33-56](https://user-images.githubusercontent.com/42042522/43599115-3c10f9cc-968f-11e8-9ac4-cb5e6aad21c3.jpg)

**Comment by punimkani** [comment] 2018-08-03 12:55
HanyoPunim

**Comment by marcgarreau** [comment] 2018-08-13 20:17
duplicate of #4032. next release will contain a fix.

**Closed by marcgarreau** 2018-08-13 20:17 UTC
