### ISSUE TITLE
Send ether doesnt work

### ISSUE THREAD

**Issue by Zaz12** [ethereum/mist#367] opened 2016-03-16 01:54 UTC
I have some ether in my Mist Etherbase and with the old version it was no problem to send them. Now in the new wallet the ether is still shown but when i want to send them nothing happens. The sending box opens, i confirm with my password, box closes, no transaction, no message, nothing. but still the same amount of ether in my wallet.

Using Linux. Any idea? thx

**Comment by jacogr** [comment] 2016-03-16 19:47
Same here on OS X - two versions of the OS, both running 0.5.2.

There is a serious issue here. I'm sure it will be fixed ASAP.

**Comment by alexvandesande** [comment] 2016-03-17 14:10
We haven't been able to replicate the issue. Has anyone been able to do it or is this a system specific bug?

**Comment by Zaz12** [comment] 2016-03-17 23:05
finally i got my ether out. seems it just work with the fastest and most expensive transaction fee...would be nice to have a notification for that ;)

**Comment by jacogr** [comment] 2016-03-18 05:09
@alexvandesande I have the issue on both my machines with different versions. Honestly, it seems to be related to the time thing - when opening Mist everything is happy and then it just starts falling behind in blocks. (.i.e. 20s ago, 40s ago, 1min ago, etc.) Geth runs fine, can interact with it via the API fine.

Nothing I can do to fix - but can replicate. (And yes, time is synced to time servers)

**Comment by alexvandesande** [comment] 2016-03-18 11:17
@jacogr yes, you need to be in sync to be able to send transactions. Or better yet, you can send transactions and they will likely be accepted, but you won't see that until you sync

**Comment by jacogr** [comment] 2016-03-18 11:28
@alexvandesande I know that, however something broken from 0.5.0 onwards. With 0.4.0 no issues, with 0.5.2 I cannot send any ether.

Geth is fine, it runs, it keeps up to date. Mist however opens up fully synced (or starts syncing when opened and geth was not running), UI opens fine and then just stops getting any new blocks, falls behind and never works. i.e. it is broken on both my machines, i.e. it is not a specific local occurence.

I've had to resort to slapping together my own lil walllet via RPC calls just so I can move Ether around.

All the basics are checked - timeserver in place (europe.apple, closest, I'm in South Africa), geth runs happily, Mist however, not working at all.

**Comment by misternils** [comment] 2016-03-24 18:24
Hey @Jacogr are you still having this issue? I'm having this same problem.

I'm using Ubuntu 15.10 (most recent) 

When i load up Mist it syncs, has peers. It doesn't stay synced though, and doesn't update past the last block that was loaded on startup. 

@alexvandesande you still haven't found this issue? Is there any kind of error log, or something we could give you to help you find the issue?

This happens both when I load it up clean, and also when I have a geth node running in the background already.  Geth continues to stay up to date, while Mist doesn't update the block past starting up.

**Comment by jacogr** [comment] 2016-03-25 08:03
Sadly, yes.

On both my machines. Been tracking all the related issues and there really doesn't seem to be any movement apart from relating this to user error, having to restart Mist, rebooting, re-syncing from scratch, etc. (Believe me, been there, done that, it is just horribly broken and there doesn't seem to be related commits yet)

I've resorted to building a bare-bones wallet that connects to my local Geth (or Parity) instance so I'm actually able to send funds around.

**Comment by jalubin** [comment] 2016-05-01 19:16
Having this exact same issue as well on Mac OS X. Can't move my ether at all using Mist. About to write a script to move ether using command line.

**Comment by Tudd** [comment] 2016-05-03 15:30
I have exactly the same problem on Mac OS X, I downloaded the last version of Mist but I can't send ether from my main account.
The transaction is confirmed but my balance doesn't move. 
I tried to participate at the DAO since 3 days unsuccessfully and it will be soon too late :(
What can I do ?

**Comment by alexvandesande** [comment] 2016-05-03 18:04
@Tudd @jalubin are you unable to send ether to any account or just the DAO contract? If that's the case, I encourage you to increase the amount of gas sent. When the confirmation window appears, look for a blue underlined number and click it to edit it. Change it to at least 100,000 more, maybe 300k gas should be more than enough. It could be related to lack of gas.

**Comment by Tudd** [comment] 2016-05-03 18:30
@alexvandesande 
I'm unable to send ether to any account. I tried also to put 300k gas and also to reduce the amount of ether. Unsuccessfully
Mist doesn't stay synced ... I don't understand

**Comment by alexvandesande** [comment] 2016-05-03 18:36
The wallet won't send if you are not synced. Can you describe better the
issue you are having with sync?

On Tue, May 3, 2016 at 3:31 PM, Tudd <notifications@github.com> wrote:

> @alexvandesande <https://github.com/alexvandesande>
> I'm unable to send ether to any account. I tried also to put 300k gas and
> also to reduce the amount of ether. Unsuccessfully
> Mist doesn't stay synced ... I don't understand
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/ethereum/mist/issues/367#issuecomment-216622258>
>



-- 

Alex Van de Sande
UX Designer

**Comment by Tudd** [comment] 2016-05-03 18:46
When I access to my account after the synchronisation process, a count of past time from the last block immediately starts (.i.e. 20s ago, 40s ago, 1min ago, ... 20 min.). The indication about the last block doesn't evolve

**Comment by alexvandesande** [comment] 2016-05-03 18:49
Would you say this describes the same behavior as your issue? https://github.com/ethereum/meteor-dapp-wallet/issues/152

**Comment by Tudd** [comment] 2016-05-03 18:53
Yes, it's similar

**Comment by Tudd** [comment] 2016-05-03 18:56
I didn't try to send ether with the previous versions of Mist, my last version was the 6.2.
I downloaded the last version for the DAO

**Comment by sime** [comment] 2016-05-23 07:32
I attempted three times to send ether and wasn't successful until the fee was set to the maximum.

The UI doesn't give enough feedback that the transaction is "gone", and that it could be related to a low fee.

**Comment by jdc4429** [comment] 2016-05-26 16:13
Tried sending ETH for the first time today.  Same issue as everybody else.  Will not send unless you pick the max amount of gas.  Notes going back 3 weeks on here, why is this not fixed yet?  No notification, just drops the transaction.  Bad enough not being able to update the blockchain in a reasonable period of time, now have to deal with this.  Better get your act together.

**Comment by alexvandesande** [comment] 2016-05-26 21:36
The latest errors might be related to a estimate gas function that was broken on geth 1.4.4 This will be gone on the next version that includes geth 1.4.5

**Comment by undersun1** [comment] 2016-05-27 14:14
I am having the same issue - the ONLY way I was able to send ether was by shutting the program down and opening it again, and send the ether IMMEDIATELY upon opening the wallet.   Hope this helps...

**Comment by undersun1** [comment] 2016-05-27 14:43
I tried to send again, and this time, I get 12 confirmations, but the ether never leaves my account!  This is really frustrating...

**Comment by dragonu19** [comment] 2016-06-02 15:26
hi!
I am new at this, please help.
I sent some eth from kraken to my mist wallet but the account is not yet sync. have I lost the ETH or I have to wait for full sync? after 20 hours I still have 900 000 blcks left to sync and 0 ETH in my account.
Thank you!

**Comment by MaximoMax** [comment] 2016-06-09 15:36
Exact same problem here (except the very last comment from undersun1), also with Mist 0.5.2 as well as 0.7.3 on Ubuntu 14.04 (32bit) and 16.04 (64bit) both, all combinations.
If it helps:
I did have a clock sync issue recently (due to Dualboot with Windows), messing around with manually set time, but resolved it, shouldn't be causing it anymore. Its now synced at boot.
Also, I have a softlink set for the blockchain directory in Ubuntu to an external, truecrypt encrypted drive. And my Ubuntus are encrypted with the native LVM-encryption.
Also, I suffered from this bug (resolved): [https://github.com/ethereum/mist/issues/75](url),
but that seems purely graphical.
Located in Germany, GMT +2, currently (hardware clock is of course kept in UTC).

UPDATE: I have two Radio Alarm Clocks that seem to be exactly in sync, so they seem correct, but my Ubuntu system time seemed to be about 0.3 seconds out of sync with them, so I used 
sudo ntpdate -u ntp.ubuntu.com.
Now it seems to be exactly 1 second behind, even though I used
hwclock --hctosys
Though hwclock seems in snyc with UTC.
How odd is that? I guess its a clock related issue then after all..
My computer is a couple of years old, maybe weak clock battery??

**Comment by WireGhost** [comment] 2016-06-26 19:18
Tried transferring from Mist wallet to Jaxx and it sent to a random address. Don't know what to do, very disappointed in the Mist wallet.

**Comment by luclu** [comment] 2016-06-26 19:20
@WireGhost could you please update your post to be more detailed (versions used, addresses in question, step to reproduce)?

**Comment by WireGhost** [comment] 2016-06-26 20:26
Listed the from to address's, transaction #. On OSX Mavericks Mist stopped syncing, so I started a mist wallet on a Windows 10 PC. Works, or thought it did. When I copied pasted my send to address it went through sending, then I noticed I wasn't receiving. The pasted address was my correct one, as I have nothing that even remotely resembles the other address. I don't do my BTC on that PC. Version of Wallet is Win63 0-7-2. Was hoping it was just a transaction # or something, but it's been over an hour, the transaction is closing on 500 transactions. Just shows my account now empty from the send.

**Comment by luclu** [comment] 2016-06-26 20:43
Are you in control of [0xe16171A65715841DF329a582A5DfFA17f900aC8d](http://etherscan.io/address/0xe16171A65715841DF329a582A5DfFA17f900aC8d)? You might copied the wrong address or your copy-to-clipboard command didn't pick the new selection, so the old one stayed in the clipboard?

**Comment by WireGhost** [comment] 2016-06-26 20:49
No, I'm not in control of that address, I have no "0xe" address on ETH. The copy and paste was a copy and paste from my notepad with only the  0x649DC0330f27235DCb5835b92711510cB1Ff7e9 address. Did find this which alarms me: https://forum.ethereum.org/discussion/4743/eth-sent-to-wrong-address-how-1-eth-reward

**Comment by luclu** [comment] 2016-06-26 20:54
> Did find this which alarms me: https://forum.ethereum.org/discussion/4743/eth-sent-to-wrong-address-how-1-eth-reward

This was due to some wrong code of the user. He forgot the quotation mark on the address:
```javascript
eth.sendTransaction({from:eth.coinbase, to:eth.accounts[0x7efd7bafbad1817f6c7a2017bd6acbcb634ad058], value: web3.toWei(14, "ether")})
```
So `eth.accounts[0x7efd7bafbad1817f6c7a2017bd6acbcb634ad058]` open account number zero as `eth.accounts[0]`.

**Comment by WireGhost** [comment] 2016-06-26 20:58
Not sure why it would accept and randomize on lack of quote to a totally diff address, though.

**Comment by WireGhost** [comment] 2016-06-27 15:50
Still stuck here. Any ideas? I'm going through all the files, keystores, trying to find this address. Keep coming up with nothing.

**Comment by MaximoMax** [comment] 2016-06-27 16:19
Could you please move to a different thread? This one is about not being able to send at all, not about ethers being sent to unknown addresses.
(Sorry to hear that, though..)

**Comment by luclu** [comment] 2016-06-27 21:40
@MaximoMax moved the conversation to #898.

**Comment by MaximoMax** [comment] 2016-06-27 21:48
Great, thank you!
That way everyone here can stay updated if anyone comes up with a fix here, without having to follow the unrelated problem.

**Comment by luclu** [comment] 2016-07-19 12:08
@/all do you still encounter this issue as of verision `0.8.1`?

**Comment by MaximoMax** [comment] 2016-07-19 21:52
I cant check right now, havent installed the new version yet, but will around 27.7., I'll report then.

**Comment by tjayrush** [comment] 2016-07-21 12:38
@luclu Yes. I am using 0.8.1 on Mac 10.10.5. Until recently, the Send always worked well. Since two days ago, it has not worked once. It opens send window, it takes my password, and then the send window just hangs. When I close the send window, I get a red message saying "Method 'eth_sendTransaction' not allowed."  I tried entering 300,000 for gas in the send window. I tried sliding the 'fastest' slider to the right. No luck. Can't get any sends to work.

**Comment by MaximoMax** [comment] 2016-08-14 01:24
Sorry, forgot to comment back on the question:
Yes, now it works without a hitch.
I had upgraded 0.8.1 from 0.7.3 recently, didn't pay attention if that solved it, but I believe so.
So it seems solved with 0.8.1 or earlier.

**Comment by luclu** [comment] 2016-08-18 15:39
Thank you @tjayrush and @MaximoMax.

@tjayrush the error `'eth_sendTransaction' not allowed` could be triggered if you are using **eth** (`< 1.3.0`) as backend. This will be fixed in the upcoming `0.8.2` release.

I will close this issue for now. Feel free to add anything meaningful to this discussion.

**Closed by luclu** 2016-08-18 15:39 UTC

**Comment by tjayrush** [comment] 2016-08-18 15:48
I haven't been using Mist since. I'll go back to using Mist and report only if problem reappears.

**Comment by Lucif666** [comment] 2016-08-29 21:02
I had exactly the same issue in Ubuntu 14.04. Using Ethereum Wallet 0.8.2 with geth 1.5.0. Perfectly synced (using NTP), incoming transactions no problem. But when I tried to send ether to some address, even choosing max. fee and 350 000 gas always ended up with message "Transaction from <account name> to <address> couldn't be successfully executed", and balance returned back. Tried 3 times with no success. Transactions didn't even appear in "pending" on blockchain. Then out of the blue, 20 minutes later, balance dissapeared from the account. And all 3 transactions were executed.

**Comment by luclu** [comment] 2016-08-30 09:39
@Lucif666 could you kindly open a new issue on this - so this thread won't be necrobumbed? You can copy your comment's text over there.

**Comment by Lucif666** [comment] 2016-08-30 17:51
@luclu I wanted to do that just now. But when I tried the same thing as yesterday, it works without problems now. No clue what was the hiccup yesterday (and it wasn't me, I think)...

**Comment by stevenericspector** [comment] 2016-09-05 13:41
I'm getting a Method Not Found error whenever I try to send coins from my Mist wallet to any address and with any amount of gas. I'm using 0.8.2. I also have a wallet that vanished when I upgraded from 0.8.1 that I had not backed up, but i've pretty much written that one off at this point :-1:  
Is there a fix for this?

**Comment by luclu** [comment] 2016-09-07 15:58
@stevenericspector please open up a new issue. I will lock this thread for now.
> [...] could you kindly open a new issue on this - so this thread won't be necrobumbed?
