### ISSUE TITLE
Ethereum not showing up in my mist wallet after a confirmed transfer

### ISSUE THREAD

**Issue by Jedimindtrick77** [ethereum/mist#2725] opened 2017-07-06 22:28 UTC
``````
Version: `0.8.10`
OS & Version: osx
Node type: geth 1.6.6
Number of blocks synchronized: 3980000
``````
Admission: I am a true beginner.  I transferred 3 ethereum from a Coinbase account to my Mist wallet and it never showed up.  The transaction has been confirmed, and I've checked on ether.scan and the address is correct.  It also shows that my wallet address has the ether in it, but when I check my wallet on my laptop, it is not shown.  I updated my wallet, and no result.

What are my next steps?

Thanks, guys!

**Comment by sathishvj** [comment] 2017-07-09 08:05
For it to show on Mist/EthereumWallet, all the blocks have to be synced. That typically takes hours.

**Comment by Terence1117** [comment] 2017-07-10 20:04
Hi can I also ask , as a beginner , 
i too have sent ETH from cointree to my Etherium wallet , 
not the TEST NET , the other one the MAIN network , account remains empty 
i had created a second account and sent it to that , it has not shown up , main account does not begin to sync, only the test net is syncing ...very slowly , please any advise will be useful...

thanks ... Terry

**Comment by sathishvj** [comment] 2017-07-10 20:07
You have to switch to the main net (Develop -> Network -> MainNet) if that has to sync.  Sync will usually take many hours if you are starting from the beginning.

Meanwhile, you can always check the balance in your account at etherscan.io/address/0x... put your address at the end.

**Comment by Terence1117** [comment] 2017-07-10 20:10
Hi , main net does not begin sync at all , only test net , and that has taken days so fat with 320677 blocks left , please any info is gold to me... 

TxHash | Block | Age | From |   | To | Value | [TxFee]
-- | -- | -- | -- | -- | -- | -- | --
0x79e20b4635c6e17e09912ec83269527b5002c441ee7178c1af08076b3646e334 | 4002704 | 9 hrs 17 mins ago | 0xeed16856d551569d134530ee3967ec79995e2051 | IN | 0x83a4f2ab844b1ad177dda2b36b225d63ae40212c | 0.25611649 Ether | 0.001071

thanks Terry

main account says 0 peers and stays that way.. the test net only shows 2 users ...

**Comment by sathishvj** [comment] 2017-07-10 20:13
https://etherscan.io/address/0x83a4f2ab844b1ad177dda2b36b225d63ae40212c

Transaction seems to have gone through fine and your balance is there.  You will have to wait for the full sync to finish if you want to use Mist/EthereumWallet.

But you have other options while that is happening.  You can also use the same account at https://www.myetherwallet.com to do any transactions.

**Comment by Terence1117** [comment] 2017-07-10 20:16
how can i force sync the main wallet as its not downloading blocks or connecting to peers..
the test net was working on the download ..

**Comment by Terence1117** [comment] 2017-07-10 20:40
so i had settings in the firewall that had not been enabled to allow the incoming port connection !
Voila, 

thanks for assist !

**Comment by Jedimindtrick77** [comment] 2017-07-11 01:14
So I am now getting this error.  What exactly is this telling me to do?

![image](https://user-images.githubusercontent.com/29962996/28046879-b7c07e42-65b4-11e7-9b81-03860b30c6d9.png)

**Comment by sathishvj** [comment] 2017-07-11 07:23
Usually a restart of the app has solved that for me.

**Comment by jesse8o8** [comment] 2017-08-20 02:49
Check your wallet balance at etherscan.io or myetherwallet.com using your account address - if the Ether is there. you can relax.
You can 1) wait for your Ethereum wallet to be fully synced to show the balance (in my case, it look more than a week and it is still not fully synced. maybe because my computer is old) 2) import your Ether to another wallet.
I chose to import my Ether to a different application. I was recommended to use Jaxx because of its user-friendly interface for non-technical people. Here is what i did:
download the Jaxx application to my phone; create a wallet
go to https://www.myetherwallet.com/#send-transaction. here i chose the Keystore File to access my wallet. I uploaded my Keystore File (you can find it in your Ethereum wallet => Account => Backup).
Once the Keystore File is uploaded, I can view my private keys and download the paper wallet (the QR code with your public and private key); I downloaded my paper wallet
Go to Jaxx application on my phone. Open Tools => Transfer Paper Wallet. Here it asked me to scan the private keys (QR code) of the wallet i wish to transfer from. I confirmed.
The Ether got transferred to the new account on Jaxx.
I think here the key is if you just want to make sure you Ether is there and not missing: just check the balance online (Step 1) . If you want to trade, you either have to wait for the wallet to fully sync or use another application (https://www.myetherwallet.com or Jaxx) to access your wallet with your private keys.

**Comment by jesse8o8** [comment] 2017-08-20 02:53
If anyone would like to donate some ether after you finally retrieve it, be so kind as to send to 0x5a0a4B034f031A6c8896519854852c613fc789E5 lol it would be greatly appreciated! Thanks guys and good luck! There is also one other procedue that I know works but I have only performed it via MAC OS. PM if this method does not work for you and you use a mac!

**Comment by evertonfraga** [comment] 2017-09-28 20:01
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist

**Closed by evertonfraga** 2017-09-28 20:01 UTC
Labels: v0.8.10
