### ISSUE TITLE
My Ether doesn't appear

### ISSUE THREAD

**Issue by hugoubeda** [ethereum/mist#3558] opened 2018-01-12 16:13 UTC
- [*] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.9.3`
OS & Version: windows
Node version: `geth 1.7.2` 
Number of blocks synchronized: 0
```

I sent Ether from Binance to my wallet but is not shown in the wallet yet. I have a really good Internet connection but I cant sync the last 200 +/- blocks.

**Comment by evertonfraga** [comment] 2018-01-12 17:25
Duplicate of #3097. Please follow the conversation from that thread.

**Closed by evertonfraga** 2018-01-12 17:25 UTC
Labels: Status: Duplicate
