### ISSUE TITLE
can't fetch trie key xxxx: no suitable peers available

### ISSUE THREAD

**Issue by jacktang** [ethereum/mist#3393] opened 2017-12-08 04:34 UTC
```
Version: `0.9.2`
OS & Version: windows/linux/osx
Node version: `geth 1.7.2` 
Number of blocks synchronized: N/A
OS: OSX
Mode: light wallet
```
My mist wallet was sync blocks about 5% percent and I shutdown the application yesterday. When I restart the application. It tells `Ethereum node connected` and I can't launch the main application. I check the log(attched). And it shows error message `can't fetch trie key cb4fc7eee3d463bef0958e03a385071ba472ade9c4bc6b64cca038d1b20ac332: no suitable peers available`. Then I try to restart geth and it stops at current screenshot ![current](https://pbs.twimg.com/media/DQf1s8-UIAAwHp9.png). 

[node.log](https://github.com/ethereum/mist/files/1541374/node.log)
[node.log.0.txt](https://github.com/ethereum/mist/files/1541375/node.log.0.txt)

If I run `geth removedb`, it will re-sync from the beginning, should I keep my laptop always on to keep the sync running? or just wait `checking the network` with patience ? Thanks!

**Comment by jacktang** [comment] 2017-12-08 05:56
Update the [node.log](https://github.com/ethereum/mist/files/1541543/node.log).
It seems enter a loop: restart geth -> sync -> sync failed(download cancel) -> no suitable peer -> have to restart geth ...

**Comment by tobiv** [comment] 2017-12-08 13:09
Please try it with the new version 0.9.3

**Comment by gamerate** [comment] 2017-12-08 19:27
I have same problem with 0.9.3 of Fedora geth removedb don't helps too
Is there any workaround about this problem known yet?

**Comment by ShamanReaper** [comment] 2017-12-09 00:35
Same issue here... not syncing light wallet.

**Comment by jacktang** [comment] 2017-12-09 07:42
@tobiv thanks, 0.9.3 with geth 1.7.2 works fine :)

**Comment by KainniaK** [comment] 2017-12-12 07:26
I have the same problem, in light mode it only ever finds one or two peers and it dissconects from them all the time. When I don't run ethereum wallet for a while and then load it it takes a long time in light mode to get all the blocks but now since a couple of days ago it just won't completely sync. Is there a bug in the software or are there just not enough light peers? I have geth 1.7.3 and I don't know how to go back to 1.7.2

**Comment by vaioco** [comment] 2017-12-12 12:37
Hi,
same here, running latest Mist on Mac OSX I keep getting errors because of "no suitable peers available".
thanks

**Comment by richh94** [comment] 2017-12-13 01:54
I've got sort-of the same problem, here on Windows. I cannot start Ethereum-Wallet, it gives me an error popup. Translated from Dutch, the error message says something like: "_it seems like the node cannot be started, is it already running? Is is upgrading the database?_"

The log gives me the same message (that's why I'm posting it here): 
`ERROR [12-13|01:32:24] Failed to retrieve current release    err="can't fetch trie key [xxx]: no suitable peers available"`

Anyhow, this sync to the blockchain is now blocking the whole application. And that's a big problem...

Is there any possibility to create an JSON backup file of my wallet in this case? Now I cannot start the application to do that. 

Where is the **keystore file** these days to do that manually? Is it still `%appdata%/Ethereum`? Sidenote: I symlinked that folder to another disk due the size of the full sync. Later I switched to lightmode but that's still on the same disk.

Anyhow, I tried if an old installation of Ethereum Wallet would work. Version 0.9.2 did! That asked an password from me after starting, so I entered mine because I thought it would restore my wallet file, but what that actually did is creating a new wallet address. 

It would be really stupid if the application in that case would just empty the /keystore folder before putting a backup of the new wallet in there, right? Starting to think that's what happend, because where else would my wallet file be?

Getting really afraid that I lost my funds now.

**Comment by 0sm3l** [comment] 2017-12-13 02:12
Getting the same error as well just now

` 
ERROR[12-12|21:10:05] Failed to retrieve current release       err="can't fetch trie key ......: no suitable peers available"`

**Comment by kbirken** [comment] 2017-12-13 17:51
Same problem here, 0.9.3 with geth 1.7.2 on MacOS 10.13.2 (High Sierra).

**Comment by brandoncurtis** [comment] 2017-12-13 23:45
I was having this problem intermittently when trying to sync both the Kovan and Mainnet chains using `parity --light`.  Since it was announced that everyone needs to update their Parity Kovan nodes for tomorrow's hard fork, the problem has disappeared on Parity.  It's also fixed by providing the light node with a list of known-good fully-updated Parity full nodes using `--reserved-peers FILE --reserved-only`.  It persists with Mainnet light nodes.

This suggests to me that the problem is related to a lack of full nodes willing to sync Parity light clients and/or deficiencies in a Parity light client's ability to manage its connections to ensure that it only connects to full nodes that are willing to play ball.  For a Parity Mainnet light client this might be especially challenging, because Geth is running Light Ethereum Subprotocol v2 (LESv2), so the universe of compatible LESv1-friendly full nodes might be fairly small.

Geth has `geth --lightserv`, which allows a full node to decide how much time it wants to spend serving light clients.  Does Parity have anything like this?  Is it hardcoded, and if so at what value?  What Parity versions are willing and able to serve to light nodes?

**Comment by cryzed** [comment] 2017-12-14 17:29
This is ridiculous. This is not the first time I've run into this bug (and I think even reported it), the only workaround is to delete the light chaindata and restart the whole synchronization -- after that is done don't close geth, start Mist and do your transactions. After quitting geth once, you'll most likely get this error and it won't ever synchronize again. I'm surprised how Ethereum got this big, this quickly, with such terrible bugs in some of the core software.

**Comment by brandoncurtis** [comment] 2017-12-14 19:22
@cryzed "no suitable peers" is just a peering problem.  By default, Geth nodes are configured to ignore light clients, and node operaters need to set `geth --lightserv` to a non-zero value to change that.  Parity nodes only support Ethereum Light Subprotocol v1 (Geth uses LESv2), so Parity nodes can't serve Geth light clients either.  The universe of compatible LESv2-friendly full nodes might be very small.

If you wait patiently, the light client _eventually_ finds a suitable full node and syncs.  This should also be remedied by passing Geth a list of known-good fully-updated Geth light-client-friendly full nodes with [the `--bootnodes` option](https://github.com/ethereum/go-ethereum/wiki/Command-Line-Options).  Not great, but this should become less of a problem as LES matures and Parity also supports LESv2!

**Comment by cryzed** [comment] 2017-12-14 21:49
@brandoncurtis given the messages in the debug log, it really looks like as if all connections to peers are dropped and the synchronization stops entirely. I assumed that this was a bug (and not simply me being impatient) because finding peers is no issue if you start synchronizing the light blockchain from the beginning, however once you restart geth, you suddenly run into this issue. While it initially takes a few minutes to find peers with a new light blockchain, it's not comparable to the time you presumably have to wait for peers to be discovered after getting this error, at least in my experience.

Regarding the bootnodes option, is there any chance you such a list?

**Comment by KainniaK** [comment] 2017-12-16 01:21
Is this finally going to get fixed? I only have internet a couple of hours a day and right now I have been unable to use the application for over a week! Please fix!!!!!!!!!!!

**Comment by marteenmcneesh** [comment] 2017-12-16 03:05
I've been experiencing the same issue with the same error at startup, but I'll echo @brandoncurtis and say that Geth does eventually find peers... for a little while, at least. It's very start-and-stop, and there's no consistent syncing, but it works. Seems to have been getting better during the day, though, even if the peak number of peer connections indicated in Ethereum Wallet has been 1. For now I'll just assume there aren't enough `--lightserv` nodes for the demand.

**Comment by one10** [comment] 2017-12-17 23:11
Same here, even in non-light mode was getting 5-6 peers max, then stopped finding any. I removed all chaindata (in full mode), resync took several days and >50GB of data, I had to keep deleting files to make room, finally lost patience and switched to light mode. It synced like 4,000,000 out of 4,000,100 (you gotta be joking, right?) and now stuck forever in this "node connected" "no suitable peers available" mode, does't retry, doesn't try to find peers, just sits there forever. How is this software even usable? In light mode there are no peers, in full mode it blows past 50GB of data and never stops.

**Comment by garyng2000** [comment] 2017-12-18 17:34
while ethereum is designed to be a P2P, in actual usage it seems that only a handful of dedicated nodes(say infura) is reliable enough to be used for anything that is production quality. I have at least 3 separate machines at 3 different locations(in different countries) running both full and light. NONE can last a few days before they are stalled which requires me to stop and start again. Each time, they will catch up eventually but during that period, no transaction submission is possible.
Our whole Dapp architecture needs to be designed around this reliability issue of nodes.

**Comment by cryzed** [comment] 2017-12-18 18:14
... hence my confused comment from above:
> I'm surprised how Ethereum got this big, this quickly, with such terrible bugs in some of the core software.

If the software at least didn't simply stall and continued searching for peers instead, I'm sure the problem wouldn't even exist in the first place. IMHO this is completely unacceptable for the core software of an emerging cryptocurrency.

**Comment by garyng2000** [comment] 2017-12-18 19:19
You mean my router works sometimes but not other times ? Not sure how geth does its port things but it is not like it never worked. It is more like it works for a few days then stalled forever because it cannot find peers or whatever. Whenever I see this, I would just cancel(ctrl-c) and restart it and it would be fine(for the full mode almost always, light mode however is a matter of luck like it can find peers with 10 minutes or so but at a bad day, can wait a few hours).
So I would say it is a matter of luck what peers it finds. also when it is in the 'stalled' state, it cannot even gracefully shutdown and I need the 'kill' command to kill the process.

**Comment by KainniaK** [comment] 2017-12-19 03:07
@ garyng2000  If Ethereum is designed to work in P2P why don't Ethereum Wallet users connect to other Ethereum Walllet users, even in client mode, why don't clients help other client? Just give the clients an option to set a limit to upload rate or maximum upload amount. That would probably help with node discovery

**Comment by garyng2000** [comment] 2017-12-19 03:13
I believe that is basically what geth(or parity) is already doing. Ethereum Wallet(or Mist or any other Dapp accessing via rpc/ipc) just use geth as their 'service manager'. I would say it is the availability of the node that is the problem. We have these issue since the very early day of P2P be it Napster or Skype or bitorrent, it took time for it to get mature. For now it probably is easier to delegate that to infura but that means 'trust infura' which kind of beat the original intend of everyone runs their own node(not mining but at least verifying)

**Comment by Riifta** [comment] 2018-01-02 07:15
I got this with the light version and might have a fix (still downloading/testing). In my node.log I received the same _can't fetch trie key_ error. 

I went into my lightchaindata folder and renamed the last .ldb file (by alphanumeric name) by appending OLD to the front (effectively removing it as far as Mist is concerned). I then started up the client again and although I'm still on the Ethererum Node Connected screen, the error no longer appears in my node.log file and I can see that the lightchaindata folder has redownloaded the .ldb file successfully and continued on.

For reference, the .ldb file that seemed to fail for me was 001517.ldb. It was only 1kb in size whereas the others are all 2079KB. It may be a different file for others.

**Comment by evertonfraga** [comment] 2018-01-12 18:49
The Geth Light Client mode is still experimental, as informed. 

I invite you to the Light Client gitter channel so you can talk with the maintainers in order to troubleshoot/debug this issue: http://gitter.im/ethereum/light-client

I'm closing this for now as the provided link is the best place to keep this discussion.

**Closed by evertonfraga** 2018-01-12 18:49 UTC

**Comment by ryanvolum** [comment] 2018-01-29 16:42
I haven't found a clean fix to this problem, but when running geth --syncmode light --verbosity 4 I see more details. With verbosity on high you can see the geth client attempting to connect to peers over time - eventually (every half hour or so...) I generally seem to connect to one or two

**Comment by KainniaK** [comment] 2018-01-30 02:07
I stopped using Ethereum all together. But if I would ever use it again I would use it over myetherwallet 
Light clients are apparently very low priority for the devs and I have had enough.
