### ISSUE TITLE
Ethereum-Wallet-macosx 64-0-4-0 won't run on OS X 10.8.5. The application requires OS X 10.9 or later?? 

### ISSUE THREAD

**Issue by bulibasa** [ethereum/mist#211] opened 2016-02-25 23:53 UTC
Why would you limit the Ethereum-Wallet only to the newest versions of OS? 

This is really annoying, I hope there is a solid reason for this

**Comment by juniorparker** [comment] 2016-02-27 01:05
I have Mac OS X 10.11.3 (Capitan) running on a mid 2011 Mac Mini and I am trying to install  Mist 0.3.6 and I am getting an error message that says:

geth cannot be opened because of a problem.

Check with the developer to make sure geth works with this version of OS X. You may need to reinstall the application. Be sure to install any available updates for the application and OS X.

**Comment by frozeman** [comment] 2016-02-29 13:11
Please read existing issues this is the 10 duplicate of #163

**Closed by frozeman** 2016-02-29 13:11 UTC

**Comment by bulibasa** [comment] 2016-03-05 23:31
frozeman, I don't think this is a duplication I see #163 is about a different issue "Crash on startup libgmp not found", or maybe I don't understand what the problem is about. my question was why the new beta version was only limited to OS X 10.9 or later? 

my issue is: I've been trying to install the previous versions of the nod on my OS X 10.8.5 for weeks. I tried all the older versions, neither worked, I get stuck in "Starting Etherum node" forever, I've never been able to get over this. Trying the last 2 new beta versions I get the message:  "Ethereum-Wallet-macosx 64-0-4-0 won't run on OS X 10.8.5. The application requires OS X 10.9 or later" which is very disappointing. 

I am not good with computers, I read the other issues but I can get the wallet installed, I tried everything but I was not able to start the node, I kept the computer on for hours, nothing. 

Can I please have some help? I am not a computer geek so I will need someone to tell me exactly, step by step what to do please, thanks.
