### ISSUE TITLE
Sync always stops at 99%

### ISSUE THREAD

**Issue by stna1981** [ethereum/mist#3498] opened 2017-12-31 08:16 UTC
Hello,

I tried Mist and Ethereum Wallet so far, both have the same issue. They stop syncing the blocks when only 100-200 blocks are left. Sometimes new chain data is being loaded, but blocks are stuck. If new blocks are detected, some more blocks are loaded, but always about 100 or so are left, so that it never finishes.

I already deleted the chandata folder etc. and made a complete fresh setup, but it's always the same. Had a look at this for some days now, but it's getting annoying.

Any ideas on that issue?

Best regards

Stefan

**Comment by JonathanLS** [comment] 2017-12-31 11:54
The same is happening here!

**Comment by orripid** [comment] 2017-12-31 22:21
same thing.  I cant wait for cardona to take over so this shit would never happen.  So fucking annoying

**Comment by alecperkey** [comment] 2017-12-31 23:32
yeah same. also been 'creating wallet' for a few hours now with no success. are the other software wallets any better? 

screenshot:
![image](https://user-images.githubusercontent.com/1241041/34464678-b7300c54-ee3f-11e7-9483-fe4116ddbbdb.png)

**Comment by orripid** [comment] 2018-01-01 00:28
looks like were stuck using myetherwallet.  i really didnt want to resort to having to use that

**Comment by orripid** [comment] 2018-01-01 04:44
i figured it out,  install both ethwallet and mist have them point to the same blockchaindata which they do by default but if you have data on external have both of them point same directory and use full node not light,  with both mist and ethereum wallet installed data syncs quickly

donate some eth if this solution helps
0x96173D1991ec642FdD1f55Cf78a7b9e94836796A

**Comment by stna1981** [comment] 2018-01-01 08:05
And which of them did you actually use, Mist or Ethereum Wallet?

**Comment by orripid** [comment] 2018-01-01 15:27
I like the use ethereum wallet,  I feel safer

**Comment by AustinWerner-KAI** [comment] 2018-01-02 13:26
This Ethereum Wallet is proper rubbish! Mine has been stuck for about 2 weeks. it seems to still be loading stuff but not progressing much at all --- are there any fixs out there for Mac users?

**Comment by taekten** [comment] 2018-01-03 16:07
def does not help to have both installed. it's never ending state entries on the last 100 blocks never fully syncs. thing is straight trash.

**Comment by taekten** [comment] 2018-01-03 16:08
I'm beginning to think this is all a ruse to get ether locked up. what a load of hot ****

**Comment by JonathanLS** [comment] 2018-01-03 16:42
Really does not help to have both installed. I've have been trying to install since 12/27/2017. It always stop on last blocks. On January 1st I did the procedures below and the sync stopped 68 blocks behind.
1. Put my laptop near to the internet router to assure that the internet connection would be stable.
2. Renamed the chaindata folder as chaindata_old and so created a new one.
3. Used the command line geth --syncmode fast --cache 1024.

After 24 hours I got downloaded about 4,000,000 of blocks. Since then the synchronization stopped several times and It's hard to download blocks. At 09:55 AM of 03/01/2018 I got 68 blocks behind, but the sync never finish. Its possible to download some blocks, but never finish the process.

**Comment by lowlanda** [comment] 2018-01-03 17:02
Got within 9 blocks using --light, then failed after 12-13 hours. Still couldn't see my balance

Now trying again with --syncmode fast --cache 1024. Not expecting any success after reading dozens of threads now.

How many people is this actually affecting I wonder. Are we just unlucky?

**Comment by orripid** [comment] 2018-01-03 19:03
use mist,  I had the same issue but if you use mist wallet and not the ethereum wallet it downloads fast.  I am keeping both wallets installed because eventually I want to use ethereum wallet instead of mist,  since having both installed mist has been downloading fast

**Comment by stna1981** [comment] 2018-01-03 20:23
Mist is having the same issue, so this is no solution. The software is just crap, and the devs are not caring about it obviously.

**Comment by lowlanda** [comment] 2018-01-04 00:24
This solution works (or workaround): #2466 Find nadimaj's post about MyEtherWallet

(fyi, I did successfully sync Ethereum Wallet using --fast, but now I get "unable to connect to socket: timeout" errors when trying to send funds. Absolutely useless...)

**Comment by evertonfraga** [comment] 2018-02-01 19:38
Duplicate of #3097.

Please refer to [this issue](https://github.com/ethereum/mist/issues/3097) for more information and our [Wiki](https://github.com/ethereum/mist/wiki) for troubleshooting steps.

**Closed by evertonfraga** 2018-02-01 19:38 UTC
Labels: Status: Triage
