### ISSUE TITLE
deploy contract didn't finish

### ISSUE THREAD

**Issue by yanglinux** [ethereum/mist#2909] opened 2017-08-08 14:15 UTC
I deployed a contract of create a new CRYPTO-CURRENCY by  0.9.0 wallet.
but it can't be finished at the result page. 

I changed to  0.8.10.  the contract was finished at the result page.

**Comment by evertonfraga** [comment] 2017-08-17 00:47
Duplicate of https://github.com/ethereum/mist/issues/2845.

Will be fixed in the next version. Thanks!

**Closed by evertonfraga** 2017-08-17 00:47 UTC
Labels: v0.9.0
