### ISSUE TITLE
 For more than an hour the etherium has not arrived at the wallet. How long should I wait for them?

### ISSUE THREAD

**Issue by IvanLimarev** [ethereum/mist#1727] opened 2017-03-14 02:29 UTC
![2017-03-14_09-41-25](https://cloud.githubusercontent.com/assets/26397050/23883117/f622bbb8-089f-11e7-8f49-0922c127a62f.png)
#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by luclu** [comment] 2017-03-14 13:43
Please make sure that your wallet is fully synced

(Duplicate of https://github.com/ethereum/mist/issues/1720)

**Closed** 2018-02-01 18:43 UTC
Labels: Status: Duplicate
