### ISSUE TITLE
Running Ethereum wallet behind a proxy server

### ISSUE THREAD

**Issue by priyankpalod** [ethereum/mist#1740] opened 2017-03-15 17:28 UTC
I am a beginner and want to start developing on ethereum. I am running ethereum wallet behind a proxy server. I can't download the blocks and hence cannot use the testnet. Is there any solution to this problem?

#### System information
``````
OS & Version: Ubuntu 16.04
Node type: tried both eth and geth
``````
Screenshot : Notice the "0 peers"
![etherum](https://cloud.githubusercontent.com/assets/9404328/23961291/8008ab0e-09d0-11e7-8ace-7a6c26b2a602.png)

**Comment by luclu** [comment] 2017-03-26 23:05
Duplicate of https://github.com/ethereum/mist/issues/1385

**Closed by luclu** 2017-03-26 23:05 UTC
