### ISSUE TITLE
Couldn't Connect to Node - Fatal Error

### ISSUE THREAD

**Issue by btcmacroecon** [ethereum/mist#374] opened 2016-03-16 15:13 UTC
Installed 0.5.2 as my MIST would never carry over old balance from (terminal) November. I got it to synch and it made it to like 158,000 and then I got a fatal error message. The wallet would stop several times synching of which if I shut it down and started it up it seemed to synch (at least I could see blocks moving rapidly).

**Comment by alexvandesande** [comment] 2016-03-17 19:08
It seems your node is crashing. Thanks for reporting I'll close this as a duplicate of https://github.com/ethereum/mist/issues/243

**Closed by alexvandesande** 2016-03-17 19:08 UTC

**Comment by btcmacroecon** [comment] 2016-03-17 19:50
OK I figured one issue. I was running out of memory, but I bought some
Ethereum in November when I set up my wallet in Linux terminal. When I set
up the MIST wallet, it never carried over, nor did it when I upgraded to
the new one this week 0.5.2
The balance is still showing from etherchain.org so it's still there but
it's not carrying that balance from GETH. What do I need to do?
I have no idea how to import private key with MIST.
Also, part of my problem, I am running out of memory. How do I get
datadirectory to recognize Ethereum? It's not like other wallets. I need to
get this fixed or will run out of memory.
So sort of 2 issues. Please advise or if I need to resubmit via Github

**Comment by alexvandesande** [comment] 2016-03-18 11:13
Hi @btcmacroecon 
Do you remember the name of the program you installed in linux in November? Eth, Geth?

**Comment by btcmacroecon** [comment] 2016-03-18 15:20
good question, i think both! I tried everything in Hello World!
I now run just geth, so may be that, but think there may have been a time I
did eth (when I was trying it all out).
I just came across this one

geth import blockchain.bin


 <goog_1753911507>

https://github.com/ethereum/go-ethereum/wiki/Command-Line-Options

Thanks! Work in progress!
