### ISSUE TITLE
Ethereum Wallet

### ISSUE THREAD

**Issue by spl2** [ethereum/mist#2640] opened 2017-06-27 07:02 UTC
``````
Version: `0.8.10
OS & Version: windows 10
Node type: `geth`
Number of blocks synchronized: 0
``````

Desktop cashed and now my wallet is show zero ether.

Is it possible to verify the amount?

Thanks

Stephen

**Comment by sathishvj** [comment] 2017-06-27 08:42
You can check the account balance at etherscan.io/address/0x... Put your ethereum address at the end.

**Comment by spl2** [comment] 2017-06-27 10:34
Thanks for the quick reply. Looks like I have lost the ether.

Regards

Stephen

**Comment by sathishvj** [comment] 2017-06-27 10:38
The desktop crashing usually has no effect on the actual account.  As a crude and not very good analogy, a browser crashing does not affect the web page.  If you have the keystore file and the password and if the account actually has received ether, you should be able to retrieve it.

**Comment by spl2** [comment] 2017-06-27 10:41
How do I do that?

Thanks

**Comment by sathishvj** [comment] 2017-06-27 11:24
You can look at MyEtherWallet: https://youtu.be/phht73IvUDI?t=2m20s

**Comment by spl2** [comment] 2017-06-27 18:38
Sorry to be a pain. Looks like the ether has gone.

I have started mining again to see what happens.
Thanks


Stephen


*
*

**Comment by sathishvj** [comment] 2017-06-28 06:19
Mining?  Are you on the test-net?  And not on the main-net?

**Comment by spl2** [comment] 2017-06-28 06:22
On the main net.

I have started mining since yesterday and no ether are appearing in the 
wallet.

I have broken something. I am not sure what.

Thanks

Regards

Stephen

**Comment by sathishvj** [comment] 2017-06-28 06:27
It's almost impossible to get ether mining on the main-net.  There is too much other competition for you to even have a chance of mining a block.  So if you haven't got any ether mining on the main-net, that's normal.

**Comment by spl2** [comment] 2017-06-28 06:32
Thanks for your help. I will reboot my machine and see what happens.

**Comment by jesse8o8** [comment] 2017-08-20 02:49
Check your wallet balance at etherscan.io or myetherwallet.com using your account address - if the Ether is there. you can relax.
You can 1) wait for your Ethereum wallet to be fully synced to show the balance (in my case, it look more than a week and it is still not fully synced. maybe because my computer is old) 2) import your Ether to another wallet.
I chose to import my Ether to a different application. I was recommended to use Jaxx because of its user-friendly interface for non-technical people. Here is what i did:
download the Jaxx application to my phone; create a wallet
go to https://www.myetherwallet.com/#send-transaction. here i chose the Keystore File to access my wallet. I uploaded my Keystore File (you can find it in your Ethereum wallet => Account => Backup).
Once the Keystore File is uploaded, I can view my private keys and download the paper wallet (the QR code with your public and private key); I downloaded my paper wallet
Go to Jaxx application on my phone. Open Tools => Transfer Paper Wallet. Here it asked me to scan the private keys (QR code) of the wallet i wish to transfer from. I confirmed.
The Ether got transferred to the new account on Jaxx.
I think here the key is if you just want to make sure you Ether is there and not missing: just check the balance online (Step 1) . If you want to trade, you either have to wait for the wallet to fully sync or use another application (https://www.myetherwallet.com or Jaxx) to access your wallet with your private keys.

**Comment by jesse8o8** [comment] 2017-08-20 02:53
If anyone would like to donate some ether after you finally retrieve it, be so kind as to send to 0x5a0a4B034f031A6c8896519854852c613fc789E5 lol it would be greatly appreciated! Thanks guys and good luck! There is also one other procedue that I know works but I have only performed it via MAC OS. PM if this method does not work for you and you use a mac!

**Comment by evertonfraga** [comment] 2017-09-28 20:06
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist

**Closed by evertonfraga** 2017-09-28 20:06 UTC
Labels: v0.8.10
