### ISSUE TITLE
Error while syncing

### ISSUE THREAD

**Issue by Zmeu213** [ethereum/mist#2304] opened 2017-05-21 11:55 UTC
#### System information
``````
Version: `0.8.10`
OS & Version: linux
Node type: `geth(default)`
``````
Got following error while using mist. It appears every time I start mist in main network / test-network. Cant start mist at all. It stucks in "Ethereum node up-to-date..."
```
[2017-05-21 14:33:22.019] [ERROR] main - Error starting up node and/or syncing { statusCode: undefined,
  body: undefined,
  jsonBody: undefined,
  thrown: 
   Error: Cannot write after close
   Ln: 6
   Col: 0
   Chr: undefined
       at Error (native)
       at emitError (/opt/Mist/resources/app.asar/node_modules/oboe/dist/oboe-node.js:635:20)
       at handleData (/opt/Mist/resources/app.asar/node_modules/oboe/dist/oboe-node.js:689:15)
       at applyEach (/opt/Mist/resources/app.asar/node_modules/oboe/dist/oboe-node.js:496:20)
       at Object.emit (/opt/Mist/resources/app.asar/node_modules/oboe/dist/oboe-node.js:1929:10)
       at Web3IpcSocket.<anonymous> (/opt/Mist/resources/app.asar/node_modules/oboe/dist/oboe-node.js:1128:34)
       at emitOne (events.js:96:13)
       at Web3IpcSocket.emit (events.js:188:7)
       at Socket._socket.on (/opt/Mist/resources/app.asar/modules/sockets/web3Ipc.js:49:26)
       at emitOne (events.js:96:13)
       at Socket.emit (events.js:188:7)
       at readableAddChunk (_stream_readable.js:176:18)
       at Socket.Readable.push (_stream_readable.js:134:10)
       at Pipe.onread (net.js:543:20) }
```

**Comment by bedorlan** [comment] 2017-05-27 16:28
+1

**Comment by bedorlan** [comment] 2017-05-27 17:12
I added a password and the app started to working

**Comment by Zmeu213** [comment] 2017-05-27 17:31
Well i changed my settings to privatenet and it works fine

**Comment by PatchRanger** [comment] 2017-08-21 09:32
I guess #2141 is not a debug issue and is related. I had the same stack of errors as in #2141 recently. In my case it happens at Rinkeby network - where I don't have any account at all and one of the Mist windows suggests me to create one, while this error occurs. Taking into account https://github.com/ethereum/mist/issues/2304#issuecomment-304464853 , I assume that the problem is: a network requires account - while in some valid cases it could be absent. So in order to fix this issue, some special case should be added to handle such situations. I hope, my thought is clear enough.

**Comment by evertonfraga** [comment] 2017-09-28 19:51
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist

**Closed by evertonfraga** 2017-09-28 19:51 UTC
Labels: v0.8.10
