### ISSUE TITLE
Where is my Ether?

### ISSUE THREAD

**Issue by netaction23** [ethereum/mist#2182] opened 2017-04-28 23:47 UTC
#### System information
``````
Version: `0.8.9`
OS & Version: osx
Node type: `eth/geth(default)`
``````
Transferred to my new ethereum wallet:
https://etherscan.io/address/0x155659096b28E7e9c0fd97B5c46016181010Ac0e

but main account (etherbase) balance shows as 0

PLEASE HELP!

**Comment by garretlaxton** [comment] 2017-04-29 15:22
Your wallet most likely needs to sync first, then you will see your balance. Your wallet can take anywhere from 1-20 hours to sync. You can use myetherwallet.com in the mean time to see/send your ETH.

**Comment by netaction23** [comment] 2017-04-29 22:31
Hi  - Is been over 30 hours already and only 35% synced?  Is there a way to speed up the process.

Also how do I access ether using myetherwallet.com <http://myetherwallet.com/>, I can’t understand the interface?

Thanks Tim

**Comment by garretlaxton** [comment] 2017-04-29 23:39
Version 0.8.9 seems to be a little buggy with syncing, so you could be effected by that. You can go here https://myetherwallet.com/#send-transaction & import your backup if you'd like to send your ETH, & you can also use this link https://myetherwallet.com/#view-wallet-info to import your backup an view your wallet balance etc.

**Comment by netaction23** [comment] 2017-04-30 00:53
HI Garret,

it got to 37% then went back to 0%, is there something I am doing wrong?

What do you mean import you back up - I sent ether from my exchange to my newly created Eterium wallet, and It asks me how I want to access it:? 

I have no Idea what to select?


How would you like to access your wallet?
Keystore File (UTC / JSON)
Private Key
Mnemonic Phrase
Parity Phrase
Ledger Nano S
TREZOR

**Comment by garretlaxton** [comment] 2017-04-30 00:56
Have you made a backup of your account yet?

**Comment by netaction23** [comment] 2017-04-30 01:29
A back up of what account Garret, I don't understand what I have meant to make a back up of. I bought the ether on an exchange and sent it to my etherium wallet...

**Comment by garretlaxton** [comment] 2017-04-30 02:14
Yup. When you first use the wallet it asks you to create an account with a password. To backup that account go to `menu -> accounts -> backup -> accounts` & that UTC file is your backup, and very important to keep in a safe place like a USB that way if anything happens to your computer you will have your account with your ETH on a USB & can access it on another system.

**Comment by netaction23** [comment] 2017-04-30 03:50
Hey Garret,

thanks for your help, the UTC file is now backed up to USB, that was in the keystone folder, I assume you don’t need to back up the geth folder?

OK, So now moving forward to getting the Etherium wallet synced? Its back to just 1% now.

Tim

**Comment by samideluxe** [comment] 2017-05-09 12:13
If you don't need the bloody wallet, then here is an easy solution to get back your ether under control:

If you need access to your Ether you can always extract the wallet file and open it in myetherwallet.com
On a mac your wallet is in /Library/Ethereum/keystore ( being your home folder)

Once you have your keystore file, generate a wallet.
Select the file and password you used when creating your ethereum wallet
You access your wallet and are in control of checking balance, receiving or sending ether
Remember to download and print out all the passwords and keys and store them on a safe place like a usb or external hard disk etc...

**Comment by Anutek1364** [comment] 2017-05-13 11:25
I think you need to create a contract to catch the transfers ?

**Comment by Rgkc361** [comment] 2017-10-25 01:11
I'm having exactly the same problem as netaction23.  I transferred some ether to my newly created Ethereum wallet yesterday and it still shows 0 balance now.  And I followed the instruction to create a contract, which was just a name (because I don't know how). now it's still " Creating..." with a small ball keep rolling

**Comment by Rgkc361** [comment] 2017-10-25 01:23
what type of contract should I create to catch the transfers ?

**Comment by garretlaxton** [comment] 2017-10-25 01:28
@Rgkc361 You don't need to create a contract, you just need to let the wallet sync. You can switch to light client for a faster sync or you can use myetherwallet.com to access your ETH.

**Comment by netaction23** [comment] 2017-10-25 02:04
Why am I receiving this email what does it have to do with me?

**Comment by evertonfraga** [comment] 2018-02-01 19:32
Duplicate of #3097.

Please refer to [this issue](https://github.com/ethereum/mist/issues/3097) for more information and our [Wiki](https://github.com/ethereum/mist/wiki) for troubleshooting steps.

**Closed by evertonfraga** 2018-02-01 19:32 UTC
Labels: Status: Triage, v0.8.9
