### ISSUE TITLE
Couldn't start an Ethereum node

### ISSUE THREAD

**Issue by souljah1h** [ethereum/mist#360] opened 2016-03-15 01:52 UTC
Windows 7 64 Bit 
Mist Wallet: Ethereum-Wallet-win64-0-5-2 (latest)

After 1 minute I get this message (same as title)

Node log:

I0315 02:47:11.433486    9220 flags.go:425] WARNING: No etherbase set and no accounts found as default
I0315 02:47:11.435487    9220 database.go:71] Alloted 433MB cache to C:\Users\souljah1h\AppData\Roaming\Ethereum\chaindata
I0315 02:47:11.454488    9220 database.go:71] Alloted 78MB cache to C:\Users\souljah1h\AppData\Roaming\Ethereum\dapp
I0315 02:47:11.473489    9220 backend.go:314] Protocol Versions: [63 62 61], Network Id: 1
I0315 02:47:11.473489    9220 backend.go:362] Blockchain DB Version: 3
I0315 02:47:11.473489    9220 blockchain.go:214] Last header: #0 [d4e56740…] TD=17179869184
I0315 02:47:11.473489    9220 blockchain.go:215] Last block: #0 [d4e56740…] TD=17179869184
I0315 02:47:11.473489    9220 blockchain.go:216] Fast block: #0 [d4e56740…] TD=17179869184
I0315 02:47:11.478489    9220 cmd.go:114] Starting Geth/v1.3.5/windows/go1.5.1
I0315 02:47:11.478489    9220 server.go:311] Starting Server

**Comment by Amauche** [comment] 2016-03-15 11:38
Kill geth process and restart it. ;)

**Comment by alexvandesande** [comment] 2016-03-17 19:06
This is a duplicate of this issue: https://github.com/ethereum/mist/issues/355 see if that discussion helps

**Closed by alexvandesande** 2016-03-17 19:06 UTC
