### ISSUE TITLE
 The wallet says "Creating..." and has been for the last few days.

### ISSUE THREAD

**Issue by jenniferdejonge** [ethereum/mist#3239] opened 2017-11-02 11:52 UTC
In the Ethereum wallet application, I tried creating a Wallet Contract. The wallet says "Creating..." and has been for the last few days.

Any ideas on why it still says creating and what the fix here is? I've tried closing and re-opening the app but it stays in the same state. 

Appreciate your help!

**Comment by jontis** [comment] 2017-11-02 22:35
Same here.
Version: 0.9.2
OS & Version: linux mint 18.1
Node version: geth 1.7.2
Number of blocks synchronized: full

also, related or not, who knows:
https://github.com/ethereum/mist/issues/3222

**Comment by zakzak987654321** [comment] 2017-11-06 22:04
same BUG here.
says creating for hours and creating nothing an looping
I do not know if i delete this and reinstall it, i will lose al the accounts i made and the ether that i have mined or not. ======================== this need answer
and
i have to go and download 35 giga byte of STUFF that will take another few DAYS  even if i have a fiber connection at 11 MEGA BYTE A SECOND and 35 GB sghould take an hour, but takes DAYS.

OS windows 10
ethereum wallet itself (not myst) 092

**Comment by evertonfraga** [comment] 2017-11-10 16:17
Duplicate of #3269.

Please refer to that issue for further discussion. Thanks

**Closed by evertonfraga** 2017-11-10 16:17 UTC
