### ISSUE TITLE
Mist showing 72.6498X my correct DAO token balance. 

### ISSUE THREAD

**Issue by 9600-** [ethereum/mist#735] opened 2016-05-28 17:50 UTC
Node type: geth
OS: Windows 10
Network type: main
Mist version: 0.7.4

I hope this is me fundamentally misunderstanding something about the DAO token generation...

Setup a watcher and DAO contract according to the JSON and decimal figures provided by DAOHub. When viewing through Etherbase account, the correct token amount is shown.

When viewing through "contracts", token amount is 72.6498 times the correct amount and the client will let me start a transaction with that token amount. 

Mist Console Output on Launch - 

![mist_console](https://cloud.githubusercontent.com/assets/7446395/15628850/1d97c832-24c1-11e6-8d53-625ab8d2a0db.PNG)

Actual Owned Tokens

![mist_tokens_owned](https://cloud.githubusercontent.com/assets/7446395/15628852/2b2e5196-24c1-11e6-9eb6-c03a2dc86ef8.PNG)

Correct Send Amount 

![mist_send_correct](https://cloud.githubusercontent.com/assets/7446395/15628903/abce8f68-24c2-11e6-98e8-46be1fcc115c.PNG)

Incorrect Watcher 

![mist_contracts](https://cloud.githubusercontent.com/assets/7446395/15628856/36860dc2-24c1-11e6-90e0-dce152c27308.PNG)

Watcher Detail - 

![mist_watcher_detail](https://cloud.githubusercontent.com/assets/7446395/15628877/ce8927e4-24c1-11e6-9602-632092a2df98.PNG)

DAO Contract - Showing incorrect balance

![mist_dao_contract](https://cloud.githubusercontent.com/assets/7446395/15628857/49dd489a-24c1-11e6-8ade-d3dff952d341.PNG)

Incorrect Token Amount for TX - 

![mist_send_incorrect](https://cloud.githubusercontent.com/assets/7446395/15628904/bbd6d758-24c2-11e6-9831-b648fffb216c.PNG)

Last Transactions recorded by Mist 

![Uploading MIST_DAO_Transactions.PNG…]()

DAO Contract JSON used. 

[ { "constant": true, "inputs": [ { "name": "", "type": "uint256" } ], "name": "proposals", "outputs": [ { "name": "recipient", "type": "address", "value": "0x0000000000000000000000000000000000000000" }, { "name": "amount", "type": "uint256", "value": "0" }, { "name": "description", "type": "string", "value": "" }, { "name": "votingDeadline", "type": "uint256", "value": "0" }, { "name": "open", "type": "bool", "value": false }, { "name": "proposalPassed", "type": "bool", "value": false }, { "name": "proposalHash", "type": "bytes32", "value": "0x0000000000000000000000000000000000000000000000000000000000000000" }, { "name": "proposalDeposit", "type": "uint256", "value": "0" }, { "name": "newCurator", "type": "bool", "value": false }, { "name": "yea", "type": "uint256", "value": "0" }, { "name": "nay", "type": "uint256", "value": "0" }, { "name": "creator", "type": "address", "value": "0x0000000000000000000000000000000000000000" } ], "type": "function" }, { "type": "function", "outputs": [ { "type": "uint256", "name": "", "value": "1.1727751591980739956782275e+25" } ], "name": "totalSupply", "inputs": [], "constant": true }, { "type": "function", "outputs": [ { "type": "uint256", "name": "", "value": "1464426000" } ], "name": "closingTime", "inputs": [], "constant": true }, { "type": "function", "outputs": [ { "type": "address", "name": "", "value": "0xda4a4626d3e16e094de3225a751aab7128e96526" } ], "name": "curator", "inputs": [], "constant": true }, { "type": "function", "outputs": [ { "type": "uint256", "name": "balance", "value": "0" } ], "name": "balanceOf", "inputs": [ { "type": "address", "name": "_owner" } ], "constant": true }, { "type": "function", "outputs": [ { "type": "uint256", "name": "_numberOfProposals", "value": "2" } ], "name": "numberOfProposals", "inputs": [], "constant": true }, { "type": "function", "outputs": [ { "type": "address", "name": "", "value": "0x807640a13483f8ac783c557fcdf27be11ea4ac7a" } ], "name": "extraBalance", "inputs": [], "constant": true }, { "type": "function", "outputs": [ { "type": "bool", "name": "success" } ], "name": "createTokenProxy", "inputs": [ { "type": "address", "name": "_tokenHolder" } ], "constant": false }, { "type": "function", "outputs": [ { "type": "uint256", "name": "_voteID" } ], "name": "vote", "inputs": [ { "type": "uint256", "name": "_proposalID" }, { "type": "bool", "name": "_supportsProposal" } ], "constant": false }, { "type": "event", "name": "FuelingToDate", "inputs": [ { "type": "uint256", "name": "value", "indexed": false } ], "anonymous": false }, { "type": "event", "name": "ProposalAdded", "inputs": [ { "type": "uint256", "name": "proposalID", "indexed": true }, { "type": "address", "name": "recipient", "indexed": false }, { "type": "uint256", "name": "amount", "indexed": false }, { "type": "bool", "name": "newCurator", "indexed": false }, { "type": "string", "name": "description", "indexed": false } ], "anonymous": false }, { "type": "event", "name": "ProposalTallied", "inputs": [ { "type": "uint256", "name": "proposalID", "indexed": true }, { "type": "bool", "name": "result", "indexed": false }, { "type": "uint256", "name": "quorum", "indexed": false } ], "anonymous": false } ]

**Comment by taoteh1221** [comment] 2016-05-28 22:07
Can confirm same exact issue here.

**Comment by taoteh1221** [comment] 2016-05-29 02:27
I just realized why it seems to be showing the wrong DAO token amounts: TheDAO itself seems to have tokens that were sent to it. It adds up the tokens that are in the dao contract itself, with whatever tokens you have in your accounts.

**Comment by hautdoge** [comment] 2016-05-29 05:55
I have the exact same issue and same platform (windows)

**Comment by luclu** [comment] 2016-05-30 15:29
This will be fixed in the next release.
I will close this as a duplicate of https://github.com/ethereum/mist/issues/608.

**Closed by luclu** 2016-05-30 15:29 UTC
