### ISSUE TITLE
Many issues with 0.7.4 on OSX & DAO token purchase

### ISSUE THREAD

**Issue by PacketSmuggler** [ethereum/mist#729] opened 2016-05-27 19:25 UTC
Node type: geth 1.3.6
OS: OSX
Network type: main
Mist version: 0.7.4

I funded an account and a wallet contract with 40kbits BTC each. Account has 1.70 in ETH, wallet contract got 1.67 - exchange rate volatility?

I can not transfer funds from the account to the wallet contract. Tried that multiple times, then funded the wallet contract directly.

When I attempt to send 1.5 ETH to The DAO token purchase address:

0xbb9bc244d798123fde783fcc1c72d3bb8c189413

I set up to set 1.50, but the transaction shows up as sending 0.00.

I am new to this, I presume since I have more than the 1.50 I am sending the 'gas' will come from the remaining ETH in the account.

This is pretty frustrating as it's the last day to purchase DAO tokens.

<img width="409" alt="screen shot 2016-05-27 at 12 17 33 pm" src="https://cloud.githubusercontent.com/assets/18205308/15618825/05de835a-2405-11e6-89c9-1bc3addc65d5.png">

<img width="568" alt="screen shot 2016-05-27 at 11 39 39 am" src="https://cloud.githubusercontent.com/assets/18205308/15618765/bd1e5b54-2404-11e6-87f4-3bf9db5b4727.png">
<img width="544" alt="screen shot 2016-05-27 at 11 47 31 am" src="https://cloud.githubusercontent.com/assets/18205308/15618769/c0815274-2404-11e6-9cd7-057276cd093e.png">
<img width="956" alt="screen shot 2016-05-27 at 11 47 42 am" src="https://cloud.githubusercontent.com/assets/18205308/15618772/c44465b8-2404-11e6-8138-53a7d974b255.png">

**Comment by PacketSmuggler** [comment] 2016-05-27 19:38
To be clear here, I'm sending 1.50, it reports 0.00 after I approve, but the transaction shows up as -.150, as seen in the last shot.

And now, as I enter this, suddenly the earlier transaction from account to wallet contract AND the 1.5 sent for DAO tokens just cleared. Delay here was on the order of more than an hour. I chose cheapest for one transaction, speedy for the rest. Something is funny here, not as bad as initial bug report, but unless there is extraordinary congestion, it's just not right.

**Comment by luclu** [comment] 2016-06-20 01:44
> I funded an account and a wallet contract with 40kbits BTC each. Account has 1.70 in ETH, wallet contract got 1.67 - exchange rate volatility?

Most likely.

> I can not transfer funds from the account to the wallet contract. Tried that multiple times, then funded the wallet contract directly.

Make sure to have your etherbase account funded. This will be used to pay for contract wallet creation.

> When I attempt to send 1.5 ETH to The DAO token purchase address:
0xbb9bc244d798123fde783fcc1c72d3bb8c189413

> I set up to set 1.50, but the transaction shows up as sending 0.00.

This is some inconvenience caused by the differentiation of internal and external transactions within Ethereum.

I will close this for now, feel free to stay if you have further questions.

**Closed by luclu** 2016-06-20 01:44 UTC
