### ISSUE TITLE
Master Password Crash

### ISSUE THREAD

**Issue by crazyearner** [ethereum/mist#484] opened 2016-04-08 23:43 UTC
Node type: eth
OS: l/windows
Network type: main/test
Mist version: 0.6.2

Problem when opend mist and going into settings to use eth nodes enter master password windows remains open after entering current master password for wallet. Block chain syncs up master password does not close after updating if you close it then closes the entire wallet.

Add the following to issue, when possible:
Screen [Shot](http://puu.sh/obhq3.png)

**Comment by bikerboy4489** [comment] 2016-04-12 10:33
I'm having the same issue!

**Comment by luclu** [comment] 2016-05-03 19:33
Duplicate of https://github.com/ethereum/mist/issues/484

**Closed** 2016-05-03 19:33 UTC
