### ISSUE TITLE
Ether converted from BTC never arrived in wallet

### ISSUE THREAD

**Issue by oan027** [ethereum/mist#3572] opened 2018-01-15 19:27 UTC
Hi guys. I opened a new Ethereum Wallet three days ago and transfered BTC using the wallets own conversion option to ether. The BTC has been withdrawn from my Bitfinex account, but never showed up in my Ethereum wallet. It´s not present in Etherscan either so it seems something happened during the conversion. My wallet should be fully synced. Any advice? Would it help if I posted the recipient address?

<img width="808" alt="skjermbilde 2018-01-25 kl 16 49 36" src="https://user-images.githubusercontent.com/35466760/35397457-d751e160-01ef-11e8-871e-9dd33604dd0f.png">

**Comment by evertonfraga** [comment] 2018-02-01 18:36
Duplicate of #3097

Please refer to [this issue](https://github.com/ethereum/mist/issues/3097) for more information and our [Wiki](https://github.com/ethereum/mist/wiki) for troubleshooting steps.

**Closed by evertonfraga** 2018-02-01 18:36 UTC
Labels: Status: Triage
