### ISSUE TITLE
Yet another 0.00 balance, this is a joke right?

### ISSUE THREAD

**Issue by uclnj** [ethereum/mist#2790] opened 2017-07-18 14:42 UTC
Version: `0.8.10`
OS & Version: windows
Node type: eth
Number of blocks synchronized: all but 188 (been that way for a few hours now)

Transferred in a [little ETH](https://etherscan.io/address/0x70d019f3b9dd416c7c821ecacd70bdcff1954011), showed up for 2 days then gone, showing 0.00.  I used the ether wallet website, after making a new wallet and [transferred the ETH to that account](https://etherscan.io/tx/0xce0c5ef63c760ff35845ec624148d6d59863daabaf5612c2d9f19421fca8cfef) so new wallet has it but the wallet app still shows 0.00.

![screenshot 2017-07-18 10 30 01](https://user-images.githubusercontent.com/835685/28322428-14beb61e-6ba4-11e7-92b3-1a9c44fccada.png)

So the ether wallet website can open my wallet ID and allow me to use it but the wallet app shows nothing??

Is the wallet just a really bad idea at this point?

**Comment by sathishvj** [comment] 2017-07-18 14:56
can you post an update after all blocks are synced?

**Comment by uclnj** [comment] 2017-07-18 15:10
It's at 180 blocks to go, I've synced 8 in the past two hours (firewall shows about 30 solid connections on 30303.)  Chain structure as usual never catches up so ... it'll be a while.

![screenshot 2017-07-18 10 34 10](https://user-images.githubusercontent.com/835685/28324533-a4427c44-6ba9-11e7-82fd-d71e1baf460e.png)

**Comment by uclnj** [comment] 2017-07-18 18:23
After stalling, I used geth to erase the db and resync it finally caught up @ 25 peers.  after about 15 minutes at 100% sync, the account I transferred the ETH suddenly popped in the amount.  That isn't what I would call a rock solid system.  That was the 4th time I erased the entire blockchain and re-downloaded.

**Comment by sathishvj** [comment] 2017-07-19 05:24
As it is, I would agree that there are issues.  But I also know that the devs are working on them.  (I'm not one of them, btw)

**Comment by wital1981** [comment] 2017-07-19 08:25
hello my walet cant sync last 200 blocks more then 30 hours. how long do i wait for hull sync?? i cant see my transactions

**Comment by Foxcor** [comment] 2017-07-19 08:53
wital1981 Restart the program. It helped me.

**Comment by sathishvj** [comment] 2017-07-19 09:04
I also don't have a definite suggestion beyond things like this - restart app and it has often worked.  Also check if there is a blocking firewall or antivirus.  Try on a different network to see if there is a difference - like a work network.  If none of those, delete the entire db and then try the sync again.  

p.s. first, always backup your keystore files.

**Comment by wital1981** [comment] 2017-07-19 09:39
it download a chain structure time after times but can t sync at 100% itseems the speed of sync is too slow

**Comment by sathishvj** [comment] 2017-07-19 09:41
Even on a normal network it usually takes a few hours.  So in case yours is slower, it will take longer.

Meanwhile, while that syncs, you can always use https://www.myetherwallet.com to transact and etherscan.io to check the balance.

**Comment by wital1981** [comment] 2017-07-19 10:08
should i delete chaindata catologue?

**Comment by wital1981** [comment] 2017-07-19 10:09
and start sync again?

**Comment by Foxcor** [comment] 2017-07-19 10:12
wital1981 
Do not!!! Otherwise again several hours, or days will have to download.
Just restart the wallet from time to time.
How many peers? Maybe this is the problem?

**Comment by wital1981** [comment] 2017-07-19 10:44
2-6 peers

**Comment by uclnj** [comment] 2017-07-19 11:25
I found it fast to delete the entire folder and manually run geth with --fast and set the cache at 8GB.  I noticed the initial 2M blocks came down in 10-15 minutes with 20+ peers but then, around the 2M mark the retry count would climb along with dup and unexpected values.  The unexpected would jump from the ten's to the thousands before geth would drop a bunch of clients and reconnect.  The BTC will drop clients as needed but it seems geth drops them in batches which completely stops any incoming blocks, delaying the sync.

![screenshot 2017-07-18 10 35 11](https://user-images.githubusercontent.com/835685/28364618-407597e6-6c53-11e7-9c7e-216bbee65ec1.png)

**Comment by andrewebdev** [comment] 2017-07-19 20:26
What I did to see my ether, is to first, close ethereum wallet app. Then open a terminal and run `geth --syncmode="light"`

This runs a much lighter sync since it doesn't require the entire blockchain. While this is running, open the app and my ether amount was correctly displaying.

At the end of the day I don't think the Mist browser as it exists currently is for the general public. I think this is more suitable for developers, miners and people that would like to create and use contracts etc.

I'm using exodus (and others) wallet for my ether and it works really well with no long synctimes.

**Comment by amineshgh** [comment] 2017-07-20 03:36
Thats a big shit several das download whole database and at the end your hang out!


![546](https://user-images.githubusercontent.com/30307149/28399400-5226d3f2-6cfc-11e7-9d89-ca8e7ee99131.JPG)


IS this really the original wallet for ethereum ?!!! so bad so buggy so ........ 
Where is developer where is support team ?!!!

**Comment by naruemont** [comment] 2017-07-20 09:49
Hi, I have the same problem running on Windows 7. The balance always show 0 even all data are fully sync. Delete all data from chaindata folder and start fully sync but no luck. Still show 0 then....

**Comment by evertonfraga** [comment] 2017-07-21 13:41
For geth syncing specific issues, please head to their repository: https://github.com/ethereum/go-ethereum
thanks.

**Comment by wital1981** [comment] 2017-07-22 08:48
for 3 days i cant sync last 200 blocks

**Comment by jesse8o8** [comment] 2017-08-20 02:48
Check your wallet balance at etherscan.io or myetherwallet.com using your account address - if the Ether is there. you can relax.
You can 1) wait for your Ethereum wallet to be fully synced to show the balance (in my case, it look more than a week and it is still not fully synced. maybe because my computer is old) 2) import your Ether to another wallet.
I chose to import my Ether to a different application. I was recommended to use Jaxx because of its user-friendly interface for non-technical people. Here is what i did:
download the Jaxx application to my phone; create a wallet
go to https://www.myetherwallet.com/#send-transaction. here i chose the Keystore File to access my wallet. I uploaded my Keystore File (you can find it in your Ethereum wallet => Account => Backup).
Once the Keystore File is uploaded, I can view my private keys and download the paper wallet (the QR code with your public and private key); I downloaded my paper wallet
Go to Jaxx application on my phone. Open Tools => Transfer Paper Wallet. Here it asked me to scan the private keys (QR code) of the wallet i wish to transfer from. I confirmed.
The Ether got transferred to the new account on Jaxx.
I think here the key is if you just want to make sure you Ether is there and not missing: just check the balance online (Step 1) . If you want to trade, you either have to wait for the wallet to fully sync or use another application (https://www.myetherwallet.com or Jaxx) to access your wallet with your private keys.

**Comment by jesse8o8** [comment] 2017-08-20 02:53
If anyone would like to donate some ether after you finally retrieve it, be so kind as to send to 0x5a0a4B034f031A6c8896519854852c613fc789E5 lol it would be greatly appreciated! Thanks guys and good luck! There is also one other procedue that I know works but I have only performed it via MAC OS. PM if this method does not work for you and you use a mac!

**Comment by evertonfraga** [comment] 2017-08-20 14:39
For Geth specific issues, please refer to their repository: https://github.com/ethereum/go-ethereum

Thanks.

**Closed by evertonfraga** 2017-08-20 14:39 UTC
Labels: geth, v0.8.10
