### ISSUE TITLE
skipt password now it asks for password

### ISSUE THREAD

**Issue by sgouman** [ethereum/mist#3436] opened 2017-12-15 14:43 UTC
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.9.3`
OS & Version: windows/linux/osx
Node version: `geth 0.0.0` 
Number of blocks synchronized: 4,737,335
```

So i installed the mist wallet pressed skip when it asked for a password.
But now i cant sent coins because it asks for a password wich i didnt create.

Leaving it blank doesnt help.

Someone knows what the default password is when you press skip?

**Comment by mgeth** [comment] 2017-12-15 16:41
Similar to # 3432. This should also report as bug!

**Comment by tobiv** [comment] 2017-12-17 13:20
Same as #3432

**Comment by evertonfraga** [comment] 2018-01-14 04:59
Hi @sgouman, 

I need help reproducing this issue. Would you please answer these questions, related to when you created the account?
- Geth version
- Mist version
- What's your operating system.

Thank you.

**Comment by evertonfraga** [comment] 2018-01-14 04:59
https://github.com/ethereum/mist/issues/3513

**Comment by BigEth01** [comment] 2018-02-04 19:35
Running Windows 64bit Pro
Mist Ethereum Wallet 0.9.3

    Hi, I'm new to this forum and decided to put my problem in here after reading tons of people having the same issue but without any specific play by play of the problem.  So here goes ... 

 I downloaded Mist Ethereum Wallet from https://github.com/ethereum/mist/releases , I downloaded the 1st one which is : Ethereum-Wallet-Installer-0-9-3.exe  at 124MB.  Then I double clicked the installer, took a few seconds and install was done.  Then I double clicked the shortcut on my desktop, it loaded a window asking me if I wanted the main server or the other server, I picked the main server.  Then it asked for the .json file for pre sale, I skipped that.  Then it ASKED for a password, I skipped that.  Then It was some short reading and I pressed next 3 times and closed the window. IMPORTANT NOTICE :  --So up to this point, no account was created yet and most importantly NO PASSWORD was ever entered up to this point--.  I then double clicked the ethereum wallet on my desktop, it showed the small window where you see the "connecting to peers" and the progress bar, along with a "LAUNCH APPLICATION" that appears after a few seconds / minutes.  So I clicked the "LAUNCH APPLICATION" and I can see a "MAIN ACCOUNT" was created, but when I try to open that account on MyEtherWallet, it says that the wallet is encrypted, yet I never entered a password for it.   

  So that's pretty much all the steps I'm guessing most people used and are stuck with a "MAIN ACCOUNT" that never really got created with a password to begin with ... yet the MAIN ACCOUNT is there with a password?    

   Would be a good idea to unlock password requirement when sending ETH to another address within MIST ETHEREUM WALLET, I created a 2nd account with a password and that 2nd account with password is working on MyEtherWallet, yet I got no access to the MAIN ACCOUNT, because it is password protected, but I never entered a password since I skipped it as explained above.  

   Some input in to this problem would be appreciated please!  Thanks for taking the time in reading my issue and replying!

**Comment by evertonfraga** [comment] 2018-03-07 19:54
Please follow issue from here: https://github.com/ethereum/mist/issues/3513

I'm closing as duplicate.

**Closed by evertonfraga** 2018-03-07 19:54 UTC
Labels: Status: Information needed, Status: Triage

**Comment by philsmd** [comment] 2018-03-08 21:57
hey @BigEth01,
it's interesting how detailed your report is and you might indeed be able to help us understand the problem which we are discussing over here: #3513

Recently I found out that when clicking on the "Solo network" geth automatically creates an account with empty password, see: https://github.com/ethereum/mist/issues/3513#issuecomment-369590191 

There are some steps from your post above that are not quite clear. You say "I pressed next 3 times and closed the window". Did you wait until the sync was completed ? Why did you close it ? Did you close it after clicking on "Launch Application" or did you close it without finishing syncing ?
Did you change the network (to test net or solo network/dev/privatenet) ?

Do you still have the keystore file of the main account ? if this address doesn't contain any ether you might be able to share the keystore file, maybe we somehow can find the password.

I tried to follow your steps with a fresh installation, but in my tests there was no automatical generation of a new account (except if I click on the Solo network menu).

Did you try to reproduce the steps with a very fresh installation (without the account/keystore data, after making a backup of all your important keystore files) ? Is this problem reproducible each and every time for you with a fresh installation ?

Maybe you can help to troubleshoot this problem together. thx

**Comment by seraphinayogawitch** [comment] 2018-07-31 02:42
I clicked "skip" when I set up my Mist Wallet. I can't find any conclusive answers. It seems like a lot of people are having this issue - is there a solution out there for the "skip" password set up scenario? Can anyone offer actual direction?
