### ISSUE TITLE
Mist not syncing with Geth [Mac]

### ISSUE THREAD

**Issue by whitj00** [ethereum/mist#746] opened 2016-05-29 23:49 UTC
Running ethereum-wallet on my mac, and when I open it up, it shows no sign of actually syncing and will not show any new blocks and will progressively increase the amount of time since the last block.  However, when I quit the wallet and actually run geth via cli, I'll see that it did sync, and the block info shown in mist's header isn't accurate.  If I check the log file under the develop tab, it also confirms the wallet is syncing.  I tried this with the latest version and 0.6.2 and I have the same issues.

This doesn't always happen when I run it (sometimes when I run mist it will show syncing)

I think it's related to adding the DAO token and watching the contract, because that seems to only happen when I have the token added.

**Comment by luclu** [comment] 2016-05-30 14:02
@whitj00 thank you for reporting. You are totally right about your assumptions.
This is caused by a faulty event-listener that surfaced with **The DAO**. It simply can't cope with the sheer amount of its event. This will in the next release. For now - you are also right on that - unwatch the contract or revert to 0.6.2.
I will close this as a duplicate of https://github.com/ethereum/mist/issues/726 et al.

**Closed by luclu** 2016-05-30 14:02 UTC

**Comment by GriffGreen** [comment] 2016-06-02 00:17
This is happening in 0.6.2 for me as well.. but --mode mist works as well
