### ISSUE TITLE
"Copy Address" no longer functions 

### ISSUE THREAD

**Issue by SingularDTV** [ethereum/mist#750] opened 2016-05-30 15:12 UTC
Apologies in advance for my ignorance of procedure.  I am not a developer, am new to Github and look forward to learning...

Node type: geth/eth
OS: osx
Network type: main
Mist version: 0.7.4

ALERT: We have multiple etherbase accounts and contract/wallets in our Mist interface.  We often send ETH between contracts/wallets internally.  Since the most recent update, we have been unable to "copy address".  The "copy address" function no longer works.  It does not "Copy to Clipboard", which requires manually inputting the ETH address, which is not ideal.  As you can see corresponding Screenshot for some reason generates 2 "Copied to Clipboard" alerts.  

![mistjpg](https://cloud.githubusercontent.com/assets/19651841/15652861/2c97b724-2657-11e6-9e81-1e5655c046ca.jpg)

Add the following to issue, when possible:

- Screenshots
- Check the console, of Mist (CTRL/CMD + ALT + i) and take a screenshot.
- Log files (as ZIP archive)
-   osx: ~/Library/Application Support/Mist/node.log (Open Home folder > Show View Options > Show Library Folder)
-   windows: %APPDATA%/Roaming/Mist/node.log
-   linux: ~/.config/Mist/node.log

**Comment by luclu** [comment] 2016-05-30 15:13
@SingularDTV thanks for reporting. I will close this as it is a duplicate of https://github.com/ethereum/mist/issues/650

**Closed by luclu** 2016-05-30 15:13 UTC
