### ISSUE TITLE
Loading Node Freeze

### ISSUE THREAD

**Issue by misternils** [ethereum/mist#295] opened 2016-03-08 21:19 UTC
Not sure where to go from here
<blockquote class="imgur-embed-pub" lang="en" data-id="MRkTtQw"><a href="//imgur.com/MRkTtQw">View Error Message</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

If I try to start a geth server in cmd --rpc it does the same thing

**Comment by misternils** [comment] 2016-03-10 06:45
I guess this is techincally a geth issue. Can see a larger thread on the problem here:
https://github.com/ethereum/go-ethereum/issues/2271

running with `--nat=none --rpc` turns of UPnP which seemed to be the part causing the issue.

**Comment by luclu** [comment] 2016-05-19 22:10
I will close for now as duplicate of https://github.com/ethereum/mist/issues/292

**Closed by luclu** 2016-05-19 22:10 UTC
