### ISSUE TITLE
OS X El Capitan 10.11.3

### ISSUE THREAD

**Issue by steveraffner** [ethereum/mist#209] opened 2016-02-25 10:42 UTC
Wallet does not work on LV os os X 

<img width="436" alt="capture d ecran 2016-02-25 a 11 41 15" src="https://cloud.githubusercontent.com/assets/17151412/13317289/dba744b6-dbb4-11e5-91a8-903f832ad811.png">

App lanuches, then I get an error message : 

Process:               geth [1118]
Path:                  /Applications/Ethereum-Wallet.app/Contents/Frameworks/node/geth/geth
Identifier:            geth
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        Electron [1114]
Responsible:           geth [1118]
User ID:               501

Date/Time:             2016-02-25 11:41:14.588 +0100
OS Version:            Mac OS X 10.11.3 (15D21)
Report Version:        11
Anonymous UUID:        AFAA898B-29B0-693D-19C8-87095E363A52

Sleep/Wake UUID:       44D33953-7084-4959-9BC9-2F9D3608D209

Time Awake Since Boot: 5900 seconds
Time Since Wake:       3500 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/local/lib/libgmp.10.dylib
  Referenced from: /Applications/Ethereum-Wallet.app/Contents/Frameworks/node/geth/geth
  Reason: image not found

Binary Images:
    0x7fff68fcf000 -     0x7fff69006007  dyld (360.19) <9D05FDF4-65CE-3B53-86D4-ABE1A5BF35F3> /usr/lib/dyld
    0x7fff8e973000 -     0x7fff8e974ffb  libSystem.B.dylib (1226.10.1) <5A4257EF-3145-3BB3-87A4-0D2404A9462D> /usr/lib/libSystem.B.dylib

**Comment by frozeman** [comment] 2016-02-25 10:58
`Library not loaded: /usr/local/lib/libgmp.10.dylib`

This is a duplicate of #163.

Please follow the guidelines and look in the issues first.

**Closed by frozeman** 2016-02-25 10:58 UTC

**Comment by steveraffner** [comment] 2016-02-25 11:23
Thanks fixed.
