### ISSUE TITLE
404 file not found window in 0.8.1 mist

### ISSUE THREAD

**Issue by TR888** [ethereum/mist#1019] opened 2016-07-23 11:04 UTC
OS: windows
Network type: main
Mist version: 0.8.1

What's wrong with my wallet?
![4ec42d4272470c2405c382b75177db84](https://cloud.githubusercontent.com/assets/20611546/17077611/4621de20-50de-11e6-9f87-ccc07c200768.png) 

Day ago 0.8.1 worked fine

**Comment by luclu** [comment] 2016-07-23 11:14
Duplicate of https://github.com/ethereum/meteor-dapp-wallet/issues/240

**Closed by luclu** 2016-07-23 11:14 UTC
Labels: duplicate
