### ISSUE TITLE
ETHEREUM NODE CONNECTION ERROR

### ISSUE THREAD

**Issue by mprodbourne** [ethereum/mist#1706] opened 2017-03-05 13:57 UTC
Hi I m getting ETHEREUM NODE CONECTION ERROR on Mist 0.8.9. I just downloaded and trying to get it to go. I put some of the logs below.
It looks / feels like my computer is downloading though still which is weird

#### System information
``````
Version: `0.8.9'
OS & Version: osx
Node type: `eth/geth(default)`
``````

```
receipt{med=e0767b7d34b731d16589f4eed005e87faafaf82fc84a756406c8d173245a762c cgas=4509908 bloom=00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 logs=[]}
	receipt{med=91d3a0b773203e3a2a88ea545daa9cce6f75912d0b0f674e797d959cb839eb47 cgas=4530908 bloom=00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 logs=[]}
	receipt{med=8289c0a857fec20135dcb039e6ae35cfd077081325e42a2813ffae1c4c39d159 cgas=4551908 bloom=00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 logs=[]}
	receipt{med=316289fd40cdcf0a2e541149314a7fee37e739d79e3ea3850f6c7e05ccfd730d cgas=4572908 bloom=00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 logs=[]}
	receipt{med=d0736e5bfc571b2f65bff02b0f6ac782ddcb494954d31afcdb39c746ae6f1770 cgas=4593908 bloom=00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 logs=[]}
	receipt{med=3699823dc2234946b7b7694ccb2906baa3eb3cc85f8e38e82fd64ab2078dcfc5 cgas=4614908 bloom=00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 logs=[]}
	receipt{med=90b1a96bad73648bc248573eaee2a1b077d75e390f085f1c655da0b9c8c9d9a7 cgas=4635908 bloom=00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 logs=[]}


Error: invalid receipt root hash (remote: 9b970f487c8ddfcb52b4f6b48dea2edcb5ad6c3fdd78db6818d1e4871132868a local: 9587d532a71de2228d8bf70a5533a06bd1494a7a952f8f40b920b6ffd58c504c)
##############################
I0305 14:51:25.960378 eth/downloader/downloader.go:305] Synchronisation failed: state data download canceled (requested)
I0305 14:51:28.444740 eth/downloader/downloader.go:305] Synchronisation failed: block download canceled (requested)
I0305 14:51:52.504925 eth/downloader/downloader.go:305] Synchronisation failed: receipt download canceled (requested)
I0305 14:52:18.960314 eth/downloader/downloader.go:305] Synchronisation failed: receipt download canceled (requested)
I0305 14:53:00.933991 eth/downloader/downloader.go:305] Synchronisation failed: block body download canceled (requested)
I0305 14:53:36.568148 eth/downloader/downloader.go:305] Synchronisation failed: block body download canceled (requested)
```

**Comment by luclu** [comment] 2017-03-08 17:03
This issue can surface if the local chaindata is corrupt, e.g. after a computer crash/power loss. Please resync to the network by renaming the `~/Library/Ethereum/geth/chaindata` folder followed by starting Mist.

I will close this as a duplicate of https://github.com/ethereum/go-ethereum/issues/2674.

**Closed by luclu** 2017-03-08 17:03 UTC
