### ISSUE TITLE
Sending Bug

### ISSUE THREAD

**Issue by murraci** [ethereum/mist#258] opened 2016-03-05 20:33 UTC
I instructed Mist to send a certain amount of dollars to Kraken. I triple checked that it was denominated in dollars and it even stated underneath what the equivalent amount of ether was. When I signed off on the TX however, it was sent as ether. It gave me a big fright and I've got far more ether than I'd ever care to entrust with an exchange on Kraken now.

**Comment by murraci** [comment] 2016-03-05 20:45
Sorry just realised I'm still using 0.5.0

**Comment by alexvandesande** [comment] 2016-03-07 11:44
How many dollars did you intended to send and how many ether did it send? I wasn't able to reproduce the bug here, would you be able to send a screenshot of your send screen with the dollar amount selected? (you don't need to send it, just simulate it. Feel free to block personal info)

**Comment by murraci** [comment] 2016-03-07 12:10
I won't say the exact amount but let's say I wanted to send $10000. The wallet sent 10000 ETH instead. I've upgraded to 0.5.1 now but haven't attempted to send anything since. I'm absolutely certain it was dollars as I had initally selected to sent the amount in ether and switched back to dollars. And I even took note of the corresponding amount in ether for my records. Oddly, I did sent a test dollar before sending the larger amount and it worked as expected. 

So to summarise what happened. I opened my wallet which had been set to denominate value in USD. I sent a dollar test. The correct amount was sent. Then I switched to denomination in ether for a minute before switching back to USD and sending the larger amount. However, 11x ($11 was equal to 1 ETH at the time) more than I intended to send was sent. Although I am certain the correct amount was stated when I first inputted the data and selected to send, I can't say I paid too much attention when I was prompted to input my password (see below). Maybe the incorrect amount was stated at that stage and I failed to notice. 

This is another $1 send that appears correct. 

<img width="576" alt="screen shot 2016-03-07 at 12 00 25" src="https://cloud.githubusercontent.com/assets/15641569/13568906/990adc84-e45c-11e5-87c8-fba0eeb2a0b8.png">

**Comment by murraci** [comment] 2016-03-07 12:21
PS I know the wallet was denominated in USD as I could see the amount in USD straight after I sent the TX (and almost had a heart attack)

**Comment by murraci** [comment] 2016-03-07 12:45
I've now tried three times. Can't recreate the bug either myself.

**Comment by alexvandesande** [comment] 2016-05-03 20:06
Ok, I'll close this. Please let me know if you can reproduce the bug

**Closed by alexvandesande** 2016-05-03 20:06 UTC
