### ISSUE TITLE
Mac version does not open

### ISSUE THREAD

**Issue by paplol** [ethereum/mist#170] opened 2016-02-13 11:48 UTC
I downloaded ethereum wallet for the first time and when i try to open it, it starts and then dissapears. 
It says starting ethereum node and then it closes. I am new to this and i dont know what to do. I just want to set up my wallet and get some ether. If someone could explain everything to me from the beginning i would appreciate it.

Thanks!

**Comment by frozeman** [comment] 2016-02-15 11:07
duplicate of #163

**Closed by frozeman** 2016-02-15 11:07 UTC
