### ISSUE TITLE
etherum wallet not synching

### ISSUE THREAD

**Issue by doctorbhoo** [ethereum/mist#3525] opened 2018-01-07 16:50 UTC
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.0.0`
OS & Version: windows/linux/osx
Node version: `geth 0.0.0` 
Number of blocks synchronized: 0
```

**Comment by evertonfraga** [comment] 2018-01-08 18:04
Duplicate of #3526

**Closed** 2018-01-08 18:03 UTC
Labels: triage
