### ISSUE TITLE
I cant copy the address to clipboard on the  new 7.4 MAC version.  Help!!  Both command C and the Copy Address button creates a pop up window saying that the address has been copied to clipboard but when you try to paste its not there.

### ISSUE THREAD

**Issue by chalachala** [ethereum/mist#690] opened 2016-05-23 10:35 UTC
Node type: geth/eth
OS: linux/windows/osx
Network type: main/test
Mist version: 0.0.0

Please check the already existing issues, before creating an issue. We would like to keep duplicates at a minumim.
Read the https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide first, where we summarized a few of the known issues.

Add the following to issue, when possible:

- Screenshots
- Check the console, of Mist (CTRL/CMD + ALT + i) and take a screenshot.
- Log files (as ZIP archive)
-   osx: ~/Library/Application Support/Mist/node.log (Open Home folder > Show View Options > Show Library Folder)
-   windows: %APPDATA%/Roaming/Mist/node.log
-   linux: ~/.config/Mist/node.log

**Comment by luclu** [comment] 2016-05-23 10:37
Thanks for reporting, this is a known problem in 0.7.4.
Duplicate of: https://github.com/ethereum/mist/issues/650

**Closed by luclu** 2016-05-23 10:37 UTC

**Comment by chalachala** [comment] 2016-05-23 10:43
ah ok.  When do you expect this will be resolved?

**Comment by luclu** [comment] 2016-05-23 10:45
In the next release. ;)
