### ISSUE TITLE
Launching Erthereum-Wallet seems to hang..

### ISSUE THREAD

**Issue by wappinghigh** [ethereum/mist#127] opened 2016-01-26 08:47 UTC
Ethereum-Wallet OSX 0.3.7

Seems to hang on "Starting Ethernet node..."

Then I tried 0.3.8 and 0.3.9pre and the app now crashes..

What gives here?

Thanks

**Comment by wappinghigh** [comment] 2016-01-26 09:06
Installed OSX 0.3.8 Now the app just crashes...

**Comment by frozeman** [comment] 2016-01-26 10:36
duplicate of this: https://github.com/ethereum/mist/issues/117

Please try this version and let me know if it fixes your issues.
https://www.dropbox.com/sh/8mu15dkxlj8phu4/AACfurTFTyAg0k22g39Vgj1ka?dl=0

**Comment by wappinghigh** [comment] 2016-01-26 11:01
No problem.. the latest version still cashes.

**Comment by frozeman** [comment] 2016-01-26 11:02
Can you go into the `Ethereum-Wallep.app/Contents/Resources/nodes/geth/` and run the `geth` command from the command line?

**Comment by wappinghigh** [comment] 2016-01-26 11:21
Process:               geth [74645]
Path:                  /Applications/Ethereum-Wallet.app/Contents/Resources/node/geth/geth
Identifier:            geth
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        Electron [74639]
Responsible:           geth [74645]
User ID:               501

Date/Time:             2016-01-26 22:17:44.476 +1100
OS Version:            Mac OS X 10.11.1 (15B42)
Report Version:        11
Anonymous UUID:        3264D9B3-D3EB-F2B7-659D-A95759EB1AC0


Time Awake Since Boot: 1100000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/local/lib/libgmp.10.dylib
  Referenced from: /Applications/Ethereum-Wallet.app/Contents/Resources/node/geth/geth
  Reason: image not found

Binary Images:
    0x7fff62133000 -     0x7fff62169f5f  dyld (360.17) <03673B53-B8B7-34D1-ADCE-F449E78E39CC> /usr/lib/dyld
    0x7fff910ba000 -     0x7fff910bbffb  libSystem.B.dylib (1225.1.1) <59F79CA0-5D86-359D-A235-4F257409109E> /usr/lib/libSystem.B.dylib

Model: Macmini6,2, BootROM MM61.0106.B0A, 4 processors, Intel Core i7, 2.3 GHz, 8 GB, SMC 2.8f1
Graphics: Intel HD Graphics 4000, Intel HD Graphics 4000, Built-In
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1600 MHz, 0x873E, 0x4C49464554494D454D454D4F52592E434F4D
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1600 MHz, 0x873E, 0x4C49464554494D454D454D4F52592E434F4D
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x10E), Broadcom BCM43xx 1.0 (7.21.94.29.1a4)
Bluetooth: Version 4.4.2f1 16391, 3 services, 18 devices, 1 incoming serial ports
Network Service: Ethernet, Ethernet, en0
Serial ATA Device: APPLE HDD HTS541010A9E662, 1 TB
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: Hub
USB Device: IR Receiver
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: Keyboard Hub
USB Device: USB-PS/2 Optical Mouse
USB Device: Apple Keyboard
USB Device: USB 3.0 Bus
USB Device: My Book
Thunderbolt Bus: Mac mini, Apple Inc., 23.4

**Comment by wappinghigh** [comment] 2016-01-26 11:48
Nope.. No such file or directory...

**Comment by frozeman** [comment] 2016-01-26 11:50
Ah ok, 

this is a duplicate of https://github.com/ethereum/mist/issues/65
You are missing the `gmp` dependency, which will be removed from the next geth version.

**Closed by frozeman** 2016-01-26 11:50 UTC
