### ISSUE TITLE
Mist 0.8.4 does no longer show account names and has lost complete transaction history

### ISSUE THREAD

**Issue by SteffenIvanhoe** [ethereum/mist#1243] opened 2016-10-02 10:24 UTC
#### System information
``````
Version: `0.8.4`
OS & Version: windows 10
Node type: `geth(default)`

Mist still is in a state where it is unusable. It shows all my named accounts as "ACCOUNTX" 
where X stands for numbers. This way it is no longer possible to associate the passwords 
with the accounts. Additionally, no transactions get displayed.

**Comment by luclu** [comment] 2016-10-02 10:34
Closed as duplicate of https://github.com/ethereum/mist/issues/1240

**Closed by luclu** 2016-10-02 10:34 UTC

**Comment by Doncharly** [comment] 2016-10-03 01:32
https://kiboplatform.net/DonKibo

https://kiboplatform.net/es/advantages.html

http://huaco2016.wixsite.com/kibo-ingledoncharly

*KIBO. Loto Registracion Only 10 Ethereum Unique Pay*
*Skype Carlos.Silva522*

2016-10-02 5:34 GMT-05:00 Luca Zeug <notifications@github.com>:
