### ISSUE TITLE
IPC Connection Error at 2%

### ISSUE THREAD

**Issue by Tryggvason** [ethereum/mist#1723] opened 2017-03-12 15:34 UTC
Hello Folks,

I started with cryptocoin a few days ago. 
Now I have a main account and bought some Ethereum coins. 

I've learned that I have to wait until full sync until I see my coins. At first it didn't sync at all (then I deleted the \AppData\Roaming\Ethereum\geth\chaindata folder as I found in another issue report), now it stops at 2% with the same error:

1. Failed to load resource: net::ERR_FILE_NOT_FOUND file:///sockjs/info?cb=tvhm03epwd

2. IPC Connection Error D:\Downloads\Ethereum-Wallet-win32-0-8-9\win-ia32-unpacked\resources\app.asar\modules\preloader\inc…:44 {"code":"ENOENT","errno":"ENOENT","syscall":"connect","address":"\\\\.\\pipe\\geth.ipc"} @ D:\Downloads\Ethereum-Wallet-win32-0-8-9\win-ia32-unpacked\resources\app.asar\node_modules\web3\lib\web3\ipcprovider.js:37:17(anonymous function) @ D:\Downloads\Ethereum-Wallet-win32-0-8-9\win-ia32-unpacked\resources\app.asar\modules\preloader\inc…:44(anonymous function) @ D:\Downloads\Ethereum-Wallet-win32-0-8-9\win-ia32-unpacked\resources\app.asar\node_modules\web3\lib…:37ipcRenderer.on @ D:\Downloads\Ethereum-Wallet-win32-0-8-9\win-ia32-unpacked\resources\app.asar\modules\ipc\ipcProvid…:56emitTwo @ events.js:106emit @ events.js:191

[Ethereum Wallet Nodefiles.zip](https://github.com/ethereum/mist/files/836603/Ethereum.Wallet.Nodefiles.zip)
![screenshot console](https://cloud.githubusercontent.com/assets/26362627/23833117/87872824-0741-11e7-8563-d54999419143.JPG)

#### System information
``````
Version: `0.8.9`
OS & Version: Win 10 x64
Node type: `eth/geth(default)`
``````

**Comment by luclu** [comment] 2017-03-14 13:27
Hi @Tryggvason, I will merge this issue as a duplicate of https://github.com/ethereum/mist/issues/1701.

Please follow that issue (you can use the subscribe button).

(From the logs):
```

I0312 15:58:34.414271 core/blockchain.go:805] imported  320 receipts in  43.483ms. #86976 [26a5e74e… / 3ee1317c…]
I0312 15:58:34.503330 core/headerchain.go:342] imported 1344 headers in 471.768ms. #88320 [f8f3e7d1… / 42b3e47d…]
I0312 15:58:34.577380 core/blockchain.go:805] imported    3 receipts in   2.001ms. #86979 [f8f3e7d1… / f58ae82d…]
I0312 15:58:34.595392 eth/downloader/downloader.go:966] imported 384 state entries in  41.027ms: processed 225869, pending at least 65347
I0312 15:58:34.612403 eth/downloader/downloader.go:966] imported 117 state entries in  25.016ms: processed 225986, pending at least 65346
runtime: out of memory: cannot allocate 268435456-byte block (765853696 in use)
fatal error: out of memory

runtime stack:
runtime.throw(0xd30bbb, 0xd)
	C:/go/src/runtime/panic.go:566 +0x7f
runtime.largeAlloc(0x10000000, 0x1740001, 0x2d)
	C:/go/src/runtime/malloc.go:776 +0xb7
runtime.mallocgc.func1()
	C:/go/src/runtime/malloc.go:669 +0x31
runtime.systemstack(0x132e3400)
	C:/go/src/runtime/asm_386.s:323 +0x5e
runtime.mstart()
	C:/go/src/runtime/proc.go:1079
```

**Closed by luclu** 2017-03-14 13:27 UTC
