### ISSUE TITLE
Ether NOT showing in new wallet 

### ISSUE THREAD

**Issue by AmesEla** [ethereum/mist#1795] opened 2017-03-24 00:27 UTC
I just made a transfer from CEX.IO into Ethereum Wallet 0-8-9 (NOT mist) and it is NOT showing up - even though it is listed on https://etherscan.io as completed.  I can send you the link and a screen shot (still not sure of the security of publically sharing this info).

BTW 
- I am running the most current wallet (OS version 0-8-9) 
- I have read https://github.com/ethereum/mist/issues/1017 which talks about the fork and the cure - which is not applicable as we are many versions out 
- I have tried to review https://github.com/ethereum/mist/issues/1028 which seems to explain the fork
- the link in the article to see the current block does not show the current ethereum block but gives a redirect link to an article (I see elsewhere we are at  and my screen says 
- I removed the application, tossed the chain folder referenced in the prior support thread instructions, downloaded again, reinstalled, restarted, nothing showing
***waiting for it to finish building which may be the issue

Please do not include overly technical info but spell out the solution as if you were speaking to your grandma.  I am not overly technical. (not a granny but figured that would help put in perspective :)

Thanks!

``````
Version:  Ethereum-Wallet-macosx-0-8-9
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

**Comment by garretlaxton** [comment] 2017-03-24 05:31
You need to let the wallet fully sync, which can take up to 1-20 hours.

**Comment by frozeman** [comment] 2017-03-24 07:41
yes, if you are not synced up to the last block, your wallet can't know about transaction which happened at that time.

**Comment by AmesEla** [comment] 2017-03-24 20:51
I've been letting it resync - it went all day yesterday. I checked at 2 am and it was at 58% after being at 71% and now it is back at 7%!  I have not shut down the wallet nor the computer. WT? Is there a way to do a fast build on a mac? I am almost tempted to revert to my old wallet using time machine...so I understand now that this needs to resync but does not explain why it keeps going back after going forward.

**Comment by crsimons1** [comment] 2017-03-25 00:47
Garret - I've used several wallets online and none have been quite as challenging to use as the "Ethereum Wallet" that is downloaded from the ethereum.org website....I would assume that the app downloaded from the homepage of ethereum would be the easiest, most basic wallet to use for beginners.... but I am mistaken. I've made multiple micro deposits to the wallet and my account still shows zero balance.  I can go to myetherwallet and see there is a balance, but why is this not reflected in the main app?  If I need to wait 1-20 hours to let the blockchain sync, isn't this a notification that should pop up in the app to put my fears at rest? Where is a simple "how to set up your wallet" guide within the app?  The "help" function is a joke.  For many noobs out there putting their money into a cryptocurrency for the first time, I can imagine this experience to be a fairly nightmarish situation.  I am a believer in Ethereum, but I honestly think this "ethereum wallet" is not ready to be represented on the homepage of Ethereum.org.  Every day new people that are not programmers are discovering ethereum and coming to your page for the first time.  If you can't develop a wallet that is extremely basic and simple to use, why not just refer people to decent resources provided by third parties that are easy to understand such as myetherwallet?

**Comment by garretlaxton** [comment] 2017-03-25 01:17
@crsimons1 I agree, I think it should let users know they need to let the wallet sync before they can see their funds. However I'm not apart of the team and that feature is up to them to add, I've just had the same problem & found a solution so I'm trying to help everyone with the same problem.

**Comment by crsimons1** [comment] 2017-03-25 01:40
Understood and I appreciate your help! Hoping someone from the team can read this and make adjustments.

**Comment by mohammad1899** [comment] 2017-03-25 18:36
I have this problem too.

**Comment by APowderBlue** [comment] 2017-03-26 03:57
Next time, save yourself the headache and just use the Coinbase ETH wallet. No set up needed as it is ready to go already in most cases.
I agree with all, Mist wallet has to be easily the worst wallet within all the cryptocurrencies IMO.

If it ever finishes synchronizing for you, do yourself a favor and just send all your ETH to Coinbase and get rid of the Mist wallet.

**Comment by AmesEla** [comment] 2017-03-27 21:02
I solved the problem by dumping the chain data, then turning off the power saving feature. Then I left it on overnight and it worked. 

ApowerderBlue - I have had no end of pain with Coinbase. I tried to work with them for over two weeks and tried to autheticate dozens of times. I sent a dozen support requests - NONE were ever answered. THEY SUCK! And were a huge time vampire

Additionally it is recommended one use a secure wallet on computer or a hardware one - that leaving your currency on an exchange is a bad move. 

PLUS if you have bitcoin and it splits you will miss the doubling of your coin.

Sounds like you are paid to write this stuff and drive traffic to them - to be honest. Sounds like a spammy comment.

**Comment by APowderBlue** [comment] 2017-03-28 00:46
Paid to write, I wish. Just sharing my experiences. I haven't has a single issue with Coinbase to date. I don't care what you use. Thanx for the insult.
I've come to find that Eth seems to have the rudest people of all the Cryptocurrencies. Dash community has a feeling of being on the same page and everyone agreeing on how to fix issues, Crush people even share the wealth with each other when they hit it big, Bitcoin at least most argument are kept clean, but here I am giving my positive experience about a potentially better wallet to transfer ETH to (albeit for temp use) and Im getting called spam?! Nice. By all means, stay in ETH, you belong here, don't go infecting other communities.
Glad you got your issue resolved.

**Comment by AmesEla** [comment] 2017-03-28 00:55
APowderBlue I meant no disrespect. Sorry to offend. Test is devoid of tone, and easily misconstrued. I was giving my honest impression and if I am wrong, I apologize. My experience with Coinbase is entirely different. Peace.

**Comment by garretlaxton** [comment] 2017-03-28 01:13
@apowderblue storing crypto currencies on exchange wallets aren't safe at all. Coinbase could very easily pull a MTGOX stealing everyone's coins in their wallet. Or like Bitfinex which was hacked and users with coins on that exchange lost them all due to the hacker stealing them. I use Coinbase as well & never had a problem with them, but it could still happen which is why I keep my coins in a wallet I control.

Overall, that is a main reason people use wallets else everyone would just leave their coins on Coinbase, Gemini, Poloniex or which ever exchange they use.

**Comment by APowderBlue** [comment] 2017-03-28 01:39
@garretlaxton Yeah, I completely agree with you on coinbase. For the past 2 years I've been survive off of my Bitcoin and Crush and basically became my income, I bought in early on after the MTGox show. I only use coinbase to cash out BTC and ETH into USD since it seems to be the most convenient wallet for it. I preferred them because of the zero fees too, that was nice while it lasted. Plus their charts tends to be slightly behind on the current values, so sometimes you would get a little tiny boost in your cash out $ ;) 
Yeah longterm storage, coinbase is a no-go since you never really own your coins/eth, just an IOU from coinbase.

@AmesEla You called me spam, but I wasn't trying to be. I just mean use CB as a faster means of sending ETH since conversion platforms tend to be more friendly with CB wallets from my experience. Then just send it off to your more permanent wallet, it's not like the fee will kill you, just sayin.
Toodles

**Comment by luclu** [comment] 2017-04-01 00:04
I will close this as resolved, but feel free to continue any discussion!

**Closed by luclu** 2017-04-01 00:04 UTC

**Comment by silentsnooc** [comment] 2017-06-07 08:30
I've just made a little test run over night ( https://ethermine.org/miners/1bb0cc91ea4d007825079612fec3915d8638b80a ) but the ETH does not show up in my wallet. The blockchain should by synced - I iam at 3,833,775 at this time. However, the Ethereum Wallet shows 0.0 ETHER - any idea why?

@AmesEla I setup my coinbase account yesterday. I had to send my licence there two times, I got multiple errors when I wanted to add a credit card including a message that my card cannot be accepted do to missing 3D Secure support. After trying it again it all of a sudden worked - consistency, no? I continued trying to buy a small amount of ETH but all I got was a message saying that there was an error - no more information about that. I tried a few times and then decided to delete my card because I thought maybe that was due to the 3D Secure earlier. As I tried to re-add it I got message saying that I cannot do it for the next 24h because I had too much activity here. 8 hours later I simply added the card again without a problem yet I am still not able to buy anything. From this point of view I'd say that this company must suck pretty hard because it appears I am not the only one having issues.

**Comment by Raisyz** [comment] 2017-06-09 05:44
Ether Mist wallet will NOT SYNC it has been at 99% for hours and keeps showing between 95-120 blocks left.  it goes up and down in blocks left.  This is the 5th time I've tried to sync this wallet.  it is the latest version.  I've deleted the chaindata etc etc.  I sent ether to it 4 days ago.  It shows in the etherscan as in but it does not show up in my wallet.  Is it possible to get the ether sent to a different online wallet?? since it looks like this is never going to actually sync.  This is the worst of all the crypto wallets I've dealt with.  The worst.

**Comment by Rudde456** [comment] 2017-06-09 22:05
Same here, ETH doesn't show up in wallet (Mist) but in Etherscan. Again, is it possible to reroute the ETHs to another wallet address?

**Comment by Raisyz** [comment] 2017-06-10 02:35
I'm wondering about trying to make a copy of the keystore and then delete/uninstall the entire Mist Ethereum wallet and then reinstall it, replace the keystore and try again.   I would rather just re-route my ether if that's a possibility because I've wasted days trying to get this wallet to sync.

**Comment by silentsnooc** [comment] 2017-06-10 21:58
@Raisyz @Rudde456 I found my issue. It is the pool that I was mining on. On https://ethermine.org e.g. you have to mine a certain amount. Only then it gets transferred to your wallet. Make sure you don't have the same issue.

**Comment by Raisyz** [comment] 2017-06-11 00:56
@silentsnooc thank you for responding but that is not my issue.  I've not yet been able to sync the mist wallet for the first time so I've not even joined a pool yet
I had transferred ether from an exchange to the wallet before it had synced as I had no idea I would have so much trouble with a wallet sync.  Its the most frustrating wallet ever.  My ether shows up in etherscan as in my wallet but since I have no synced wallet I cannot get to the ether.  Its not a lot of ether but I still want it so I was wondering if there's another way to get it by using my keystore for my mist wallet and then send it to a different ether wallet

**Comment by rube08** [comment] 2017-06-11 01:13
@Raisyz Do you want to use your funds now but the problem is that it is not yet synced up with mist?  You can use it using https://www.myetherwallet.com.

**Comment by Raisyz** [comment] 2017-06-11 02:32
@rube08 how do I access the ether without the wallet that corresponds to that address?  I already have another ether wallet on myetherwallet.com which is where I want to send my ether that never showed up/synced to the mist wallet

**Comment by rube08** [comment] 2017-06-11 02:44
@Raisyz Try using these steps if you want to access the wallet right now without being synced in Mist.
[ether wallet instructions.docx](https://github.com/ethereum/mist/files/1066209/ether.wallet.instructions.docx)

**Comment by Raisyz** [comment] 2017-06-11 03:13
@rube08 Thank YOU!!.   this worked.  Now my ether is in one place in myetherwallet.   I'm getting a new system Monday.  Do you suggest trying the Mist wallet again or some other desktop/local wallet?

**Comment by Raisyz** [comment] 2017-06-11 03:17
@Rudde456   see above instructions from @rube08.   This worked for me

**Comment by rube08** [comment] 2017-06-11 03:22
@Raisyz Just use myetherwallet.  Save your UTC wallet file in a safe place to access it anytime using myetherwallet.com.

**Comment by evertonfraga** [comment] 2017-06-13 14:07
If you guys are having a hard time syncing, we'd recommend using either a third-party wallet (as http://myetherwallet.com), or the combo Metamask chrome plugin + https://wallet.ethereum.org. 

we are aware of the issues, and developing ways to make this whole process much easier. thanks.

**Comment by Rudde456** [comment] 2017-06-14 15:49
Thank you very much for your advice, I finally managed to sync the app but I will certainly try something else in the future. 
Am 13.06.2017 um 16:07 schrieb Ev <notifications@github.com>:

**Comment by FredCailloux** [comment] 2017-06-17 12:48
@rube08 are you the author of this procedure ?  ether_wallet_instructions.docx
I tried it and it almost worked fine. Me too have this problem where I transferred some ETH from an exchange to my personal wallet created with MIST. After the wallet was created I used the public key to receive my ETH into, but the amount never showed up, Even after complete sync. So I found your advise about using MyEtherWallet.com. Thanks for the tip I was able to transact my ETH. I tried to transfert the funds in the same EthereumWallet, basically from the From address to the To address being the same, just to manipulate the funds. The transaction went perfect and I can see it on EtherScan.OI. But it still do not show-up in my Ethereum Wallet on my PC.  Any advise ?  Thanks for your help.

**Comment by FredCailloux** [comment] 2017-06-17 18:12
Eureka, it seems that transfer transaction gave results. Ethereum wallet finally caught the transaction and I now have my ETH in my wallet. Basically what I did was access my wallet via MyEtherWallet.com and transferred all my funds to the same address From: and To: I got my funds visible in the PC ETH wallet about 1 hour later.  Hope this will help someone else.

**Comment by crpguru** [comment] 2017-06-21 12:11
Hi Guys, did transfer ETH form POLO and CoinB still not showing up in wallet or explorer, how long will this take did it 4 hours ago???

**Comment by crpguru** [comment] 2017-06-21 12:54
sorry not mist it was myethereumwallet.com

**Comment by frozeman** [comment] 2017-06-24 08:17
The reasons why it gets stuck at 99%, because it still downloads the state. You can only see that if you leave the splash screen open, and don't click "Launch Application"

**Comment by dhinson** [comment] 2017-07-12 21:25
Same problem.  Tried to transfer 0.1 eth to a brand new ethereum wallet account.  Etherscan shows it confirmed 16 hours ago.  Mist/wallet still doesn't see it and the blocks it says it is currently processing are well past the transfer block.  Went to myetherwallet.com and it shows there fine.  Total failure of fundamental use case.  Inexcusable for this kind of app.

**Comment by Raisyz** [comment] 2017-07-12 21:36
I bought a new computer and reinstalled the mist wallet and it worked fine.  the chaindata was on an SSD drive on my new system so I think this is why it FINALLY synced the blockchain.  I had already transferred my ether to another wallet so I didn't need the MIST but I was determined to make the Mist wallet sync for any future uses.   I would suggest an SSD drive.

**Comment by dhinson** [comment] 2017-07-13 01:25
@Raisyz That sounds like it could be helpful since it does so much disk work with the chaindata, but several times the processing has caught up with the last block according to Etherscan and still no recognition.  As others have pointed out this buggy behavior is especially bad for this particular application.  How can I possibly recommend this technology to others who may be employing me and approaching it with a healthy and legitimate skepticism when a basic tool recommended by the Ethereum Foundation itself fails in such a basic way?  I should use alternatives and hope I'm not asked why?  Not a compelling situation.

**Comment by Raisyz** [comment] 2017-07-13 17:13
@dhinson  I was having the same problem with it catching up and then it would RESTART the ENTIRE blockchain which had already taken a week to get up to that point of within a few blocks of complete.  I tried it at least 5 times with similar or worse results spending many hours of wasted time.   I transferred my ether to another wallet and gave up until I got the new system and tried it again and it worked.   
I agree you cannot suggest this wallet to an employer.  Ethereum Foundation needs to fix it or its useless to the majority of people who would want it and it makes ethereum look bad as well IMO.  I never had any trouble with any other crypto wallet.  Crypto is already a scary investment for many people and if they want it to become more mainstream they cannot have issues like this.

**Comment by dhinson** [comment] 2017-07-21 21:27
I ended up creating a new Linux instance on an SSD server and using it for the geth client.  I then RPC into it from the Win machine I had intended to use for geth.  As you and others have suggested SSD seems to be the key to getting geth synced up with the "last mile" of the blockchain copy.  Which is unfortunate for its future as not everyone has the luxury of spare SSD servers lying around.

**Comment by Raisyz** [comment] 2017-07-22 02:08
@dhinson VERY unfortunate.  Not to mention, I went to open my wallet the other day and same old problem of it taking forever to sync.   I closed it before it finished because why it should take so long for just a few days of sync that it has to go through the entire blockchain AGAIN?  What is a better wallet?  because I do not trust this Mist wallet.

**Comment by logos88** [comment] 2017-07-24 06:03
I had the same problem. I solved entering www.myetherwallet.com and closing it after. Now when I enter mist I can see the ether at last

**Comment by iThinkersTeam** [comment] 2017-12-25 19:55
I bought 8 months ago Ethereum coins and keep on my local Ethereum wallet, now I want send coins to another local Ethereum wallet, but only 1 ether transferred and others I missed. I opened my old wallet and see all my coins (including 1 which I sent). I created several transactions but nothing happen. 
I can't download whole blockchain because my Mac has 256 GB and 160 GB already use Ethereum wallet + I need to download more than 484.500 blocks. 

I make backup and import it on new wallet but I see 0 ethers. 
I have exactly same account, but on old Mac I have coins on new with same account I have 0.

Please help me, how I can fix it. 
I want to get my coins and sell Mac.

Thanks

**Comment by educob** [comment] 2017-12-25 20:04
What is your ethereum address? 
Insert it here: [https://ethplorer.io/address/0xd1dde7728264bf5bf14d01dbe768cbfa9cb8c87a](url)

**Comment by iThinkersTeam** [comment] 2017-12-25 20:07
0xf6Ac74Ec86117993D933f2f6F0BdDD15dBB98875

**Comment by iThinkersTeam** [comment] 2017-12-25 20:09
I have 0.96570958 ether 
How I can send it to my another wallet or account?

**Comment by educob** [comment] 2017-12-25 21:54
Go here: https://www.myetherwallet.com/#send-transaction
Select "Keystore / JSON File" and open your keystore and insert your password.
That should open your wallet so you can send your coins.
Good luck.

**Comment by iThinkersTeam** [comment] 2017-12-26 07:59
Thanks a lot I did it!

**Comment by educob** [comment] 2017-12-26 08:05
Good!!!!

**Comment by educob** [comment] 2018-03-15 22:39
Mist wallet is complete crap. It doesn't work (at least for me).
I discarded it as crap.

Use https://www.myetherwallet.com/ following the explanations in it.

Cheers.
