### ISSUE TITLE
Wrong message "Your computer's clock is not synced."

### ISSUE THREAD

**Issue by SteffenIvanhoe** [ethereum/mist#838] opened 2016-06-16 11:54 UTC
Node type: geth
OS: windows 10
Network type: main
Mist version: 0.7.5

I get this error message at any start of the wallet despite my clock beeing in perfect sync (checked with multiple web clocks).

**Comment by luclu** [comment] 2016-06-16 12:55
I will close as duplicate of https://github.com/ethereum/mist/issues/397.
Could you please state the output of this commend over in that issue?
```
reg query HKLM\SYSTEM\CurrentControlSet\Services\W32Time
```

**Closed by luclu** 2016-06-16 12:55 UTC
