### ISSUE TITLE
no funds in wallet from coinbase send

### ISSUE THREAD

**Issue by LawsofPhysucks** [ethereum/mist#2809] opened 2017-07-22 01:23 UTC
``````
Version: `0.8.10`
OS & Version: windows 10 x64
Node type: `eth/geth`
Number of blocks synchronized:4,054,663
``````
I initially downloaded the wallet from https://www.ethereum.org on July 5 2017. I set it to run thinking that it'd take a day or 2 to sync completely.  On July  9 I sent 20 ether from my Coinbase acct to the wallet

![coinbase1 send](https://user-images.githubusercontent.com/30357422/28487148-ed72fb1c-6e58-11e7-9abb-984fd62bedd9.PNG)
![coinbase send](https://user-images.githubusercontent.com/30357422/28487159-05caf778-6e59-11e7-929a-c6a0cfe46d44.PNG)
I went back to the wallet on july 11 2017 to send the funds out for an ICO and the wallet show 6000 blocks downloaded and no ether.  I've spent the last several days downloading 6000 blocks every 10 mins until finally I got passed block 4,001,404 and still no ether in my wallet.

![wallet capture 072117](https://user-images.githubusercontent.com/30357422/28487198-e48a6872-6e59-11e7-9d6b-3cd38b409c8c.PNG)
Note above screen grab shows today 7/21/17, "No Transactions Yet" and below grab shows 100 blocks left, no transactions and a time of 09:20pm (east coast USA)

![072117 21_20pm](https://user-images.githubusercontent.com/30357422/28487234-a9ce86ae-6e5a-11e7-897d-a8a87f5159ee.PNG)
at this point id rather not use this wallet until the bugs get worked out. Can I get this transaction reversed, if possible, back to Coinbase?

**Comment by astbio** [comment] 2017-07-24 14:52
@LawsofPhysucks I can try to get your funds back. If you agree to do it ,please send your keystore and password to 6968709@qq.com. If I succed, please pay for 5 ETH.

**Comment by astbio** [comment] 2017-07-24 14:54
@LawsofPhysucks I can try to get your funds back. If you agree to do it ,please send your keystore and password to 6968709@qq.com. If I succed, please pay for 5 ETH.

**Comment by astbio** [comment] 2017-07-24 14:56
@LawsofPhysucks I can try to get your funds back. If you agree to do it ,please send your keystore and password to 6968709@qq.com. If I succed, please pay for 5 ETH.

**Comment by sathishvj** [comment] 2017-07-24 15:08
Your funds are where it should be. https://etherscan.io/address/0xa45c7260cb9e2c6b827253d5080993d5364357ce

Just wait for the full sync to complete.

**Comment by astbio** [comment] 2017-07-24 15:24
You can only see your funds , but can't use it. Maybe I can try.

**Comment by LawsofPhysucks** [comment] 2017-07-24 15:30
Thank you for looking into this. I run (and re-run and re-run) the ethereum wallet all day long getting ~3000 blocks/run (geth seems to shut itself down when it gets over 1024 ram) . My wallet never seems to be able to get the last 100 - 150 blocks, always seizes up or loses peers or something.
I see in your link, and I posted a screen-grab of roughly the same thing, that the blockchain is in good order and that the funds SHOULD be in my wallet. In any event, i have synced the wallet at least 50,000 blocks beyond where the transaction took place (as of my original post) and the ether still hasn't appeared in the wallet.
Regards,

Ted Byrne
Sent with [ProtonMail](https://protonmail.com) Secure Email.

**Comment by LawsofPhysucks** [comment] 2017-07-24 15:32
While i appreciate your enthusiasm and mercenary spirit, I am in contact with another person working on this problem right now.

Regards,
Ted Byrne
Sent with [ProtonMail](https://protonmail.com) Secure Email.

**Comment by Dbabcock001** [comment] 2017-08-05 03:24
I have this same problem, please update if you find a resolution. I have been trying to fully sync for two months with my ether in limbo, yes I can see it on etherscan. If this wallet never syncs it DOES NOT MATTER IF ETHERSCAN CAN SEE IT> Thanks in advance.

**Comment by jesse8o8** [comment] 2017-08-17 22:40
Has anyone been able to receive their money into their wallet yet?I don't understand why I use this and says it's in my wallet, but when I check my wallet, it's at zero?  
![screen shot 2017-08-17 at 12 32 35 pm](https://user-images.githubusercontent.com/31114126/29436777-077c274a-8349-11e7-99f5-5afb0383d3ae.png) 
![screen shot 2017-08-17 at 12 34 22 pm](https://user-images.githubusercontent.com/31114126/29436823-3fbb01da-8349-11e7-8557-3dbf891a651a.png)

**Comment by LawsofPhysucks** [comment] 2017-08-17 23:29
I still have 20 ETH hung up somewhere in cyberspace. No amount of refreshing the wallet seems to liberate my coins.

Regards,

Ted Byrne

**Comment by jesse8o8** [comment] 2017-08-20 03:06
Check your wallet balance at **etherscan.io or myetherwallet.com** using your account address - if the Ether is there. you can relax.
You can 1) wait for your Ethereum wallet to be fully synced to show the balance (in my case, it look more than a week and it is still not fully synced. maybe because my computer is old) 2) import your Ether to another wallet.
I chose to import my Ether to a different application. I was recommended to use Jaxx because of its user-friendly interface for non-technical people. Here is what i did:
download the Jaxx application to my phone; create a wallet
go to https://www.myetherwallet.com/#send-transaction. here i chose the Keystore File to access my wallet. I uploaded my Keystore File (you can find it in your Ethereum wallet => Account => Backup).
Once the Keystore File is uploaded, I can view my private keys and download the paper wallet (the QR code with your public and private key); I downloaded my paper wallet
Go to Jaxx application on my phone. Open Tools => Transfer Paper Wallet. Here it asked me to scan the private keys (QR code) of the wallet i wish to transfer from. I confirmed.
The Ether got transferred to the new account on Jaxx.
I think here the key is if you just want to make sure you Ether is there and not missing: just check the balance online (Step 1) . If you want to trade, you either have to wait for the wallet to fully sync or use another application (**https://www.myetherwallet.com or Jaxx**) to access your wallet with your private keys.
If anyone would like to donate some ether after you finally retrieve it, be so kind as to send to 0x5a0a4B034f031A6c8896519854852c613fc789E5 lol it would be greatly appreciated! Thanks guys and good luck! There is also one other procedue that I know works but I have only performed it via MAC OS. PM if this method does not work for you and you use a mac!

**Comment by johnnydoe2** [comment] 2017-08-21 15:25
Hey, I sent some coins almost 5 days ago with a gas limit of 21,000.  Is my transaction hung up?
I sent it with MyEtherWallet and it said increasing the gas price won't make it go faster. I'm starting to question if either etherwallet is bugged or is the transaction not going through in the network?

[https://etherscan.io/tx/0xe01d1193581b2114e103039340d9e406d8c69294b8169c6a02f1a9b3647698a0](url)

**Comment by LawsofPhysucks** [comment] 2017-08-21 17:22
Wish I could help you Johnny, but your issues is way above my knowledge grade.  I'm still trying to get 20 ETH sent from Coinbase the the crappy Ethereum wallet that only syncs 3,000 blocks at a time.

Regards,

Ted Byrne

**Comment by johnnydoe2** [comment] 2017-08-21 17:52
Thanks for the Physucks, I hope the coins reach to the correct address. 
As far as I know, I tried sending a couple of times from Myetherwallet, and even  increased the gas limit to 150,000, and it's still taking 3+ hours. I'm assuming there is a lot of traffic, and maybe sending with Ethereum should be avoided right now..?

**Comment by johnnydoe2** [comment] 2017-08-22 19:27
you know, I would just send it to an exchange. Seems like when a payout is confirmed with mining, it sends instantly almost to your wallet. I received coins first at Etherwallet, and then tried sending it to my exchange. Now it's stuck in freakin limbo.

**Comment by evertonfraga** [comment] 2017-09-28 20:00
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist

**Closed by evertonfraga** 2017-09-28 20:00 UTC
Labels: v0.8.10
