### ISSUE TITLE
OSX precompiled build: geth - bundle error, missing dylibs

### ISSUE THREAD

**Issue by ray77** [ethereum/mist#158] opened 2016-02-10 17:35 UTC
dyld: Library not loaded: /usr/local/lib/libgmp.10.dylib
Referenced from: /Applications/Ethereum-Wallet.app/Contents/Resources/node/geth/geth
Reason: image not found

**Comment by frozeman** [comment] 2016-02-11 14:11
duplicate of https://github.com/ethereum/mist/issues/110, please read there how to resolve it. will be fixed in future releases

**Closed by frozeman** 2016-02-11 14:11 UTC
