### ISSUE TITLE
Newest (0.8.1) wallet randomly crashes

### ISSUE THREAD

**Issue by Serjster** [ethereum/mist#1072] opened 2016-08-05 04:24 UTC
#### System information

```
Version: `0.8.1`
OS & Version: Win 10 64
Node type: Geth-Win64-20160716155900-1.4.10-5f55d95
```

I looked at the other issues and the troubleshooting guide, but did not find anything related to my issue. The issue is that the wallet randomly crashes without any errors or artifacts left behind. I am also mining using ethminer and the proxy to mine in Stratum on the same machine. This is a new issue that started happening once I upgraded my wallet and geth to the new versions. Just to be clear, geth runs without crashing, it is just the wallet that crashes, most always within 24 hours of running it.

If possible add the following to your report:
- Screenshots, sadly no screenshots to show.
- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot
  ![mist-console](https://cloud.githubusercontent.com/assets/3606218/17426117/f975751a-5a91-11e6-86ab-f5a1de7fce60.png)
- Log files (Go to `menu -> accounts -> backup -> application data` and upload as zip-archive):
  node.log is empty

Let me know what else I can provide or how I may help.

**Comment by frozeman** [comment] 2016-08-05 07:36
@bas-vk can this be related to the RPC stalling?

**Comment by bas-vk** [comment] 2016-08-08 10:05
Perhaps, it is hard to make any assessment based on this information. What can happen is that geth (temporarily) doesn't send responses back and Mist queues requests until it run out of memory and Windows kills it. In that case I expect there must be an event in the Windows logs. I don't know if the can happen in Mist? If it can happen it would be nice if @Serjster checks if there is something in the Windows logs about Mist (or geth).

**Comment by Serjster** [comment] 2016-08-09 05:40
Noticed that the Mist Wallet was down again today when I got home. I went through the Windows Event log and did not find any Mist or geth Windows Logs/Application errors. I actually looked in all of the Windows Logs folders and did not find any Mist or geth errors in any of them. I am getting a lot of WMI Event ID: 10 errors, but I do not think that is related.

**Comment by Serjster** [comment] 2016-08-12 06:19
I did fix the WMI errors. And now that the wallet crashed again, I have a new error:
Cryptographic Services failed while processing the OnIdentity() call in the System Writer Object.

Details:
AddLegacyDriverFiles: Unable to back up image of binary Microsoft Link-Layer Discovery Protocol.

System Error:
Access is denied.
.

Source: CAPI2, Event ID: 513

**Comment by bas-vk** [comment] 2016-08-16 12:29
@frozeman, @hiddentao , can Mist be started from the command line and capture more information that can help to find the cause?

**Comment by frozeman** [comment] 2016-08-16 13:24
There are log files in `%APPDATA%/Mist` which contain ui console logs and geth logs.

You can start it from the commanline using cmd.exe and start the Ethereum Wallet.exe

**Comment by hiddentao** [comment] 2016-08-16 14:13
When running from the command-line get all options using `--help`.

If you want maximum logging use `--loglevel trace`. 

If you want to capture logging into a file as well (apart from the one @frozeman mentioned) then use `--logfile <path to file>`.

**Comment by BL186** [comment] 2017-05-29 05:40
I have exactly the same issue, running Ethereum Wallet 0.8.1 on Windows Server 2012 64 Bit. I leave it open for hours, then when I go back PC Ethereum Wallet is not running anymore. Something makes it crash at some point in time. Can't find anything in the event viewer too.

Where are the Ethereum Wallet logs located?

**Comment by BL186** [comment] 2017-05-29 05:45
@Serjster I will try to let the wallet run with Administrator permissions, if its some kind of permissions issue this should solve it.

**Comment by BL186** [comment] 2017-06-04 07:59
Try to run as administrator, doesn't help. Keeps crashing randomly.

Any fix for this?

**Comment by Serjster** [comment] 2017-06-04 18:21
Yep, get the latest version

**Comment by BL186** [comment] 2017-06-18 08:44
But ins't the 0.8.1 the latest version?

**Comment by Serjster** [comment] 2017-06-21 21:31
No. That is very old at this point. The newest is 0.8.10

**Comment by frozeman** [comment] 2017-06-24 08:15
Please reopen if it still persists. The log files can be found at Menu > Develop > Log files

**Closed by frozeman** 2017-06-24 08:15 UTC
