### ISSUE TITLE
Crash when select Testnet in Ubuntu

### ISSUE THREAD

**Issue by pprados** [ethereum/mist#123] opened 2016-01-25 17:54 UTC
How to reproduce:
- Ubuntu 15.10
- Start the wallet
- Select menu Develop/Network/Testnet (Morden)
=> Crash

**Comment by frozeman** [comment] 2016-01-26 10:44
Might be a duplicate of https://github.com/ethereum/mist/issues/117

Please try this version: https://www.dropbox.com/sh/8mu15dkxlj8phu4/AACfurTFTyAg0k22g39Vgj1ka?dl=0

**Comment by penelopehead** [comment] 2016-02-04 01:34
Same issue here. Newest version 0.9.3 doesn't correct. Here is my log:

=============== Feb 3, 2016 (EST) ===============
20:21:03.757610 log@legend F·NumFile S·FileSize N·Entry C·BadEntry B·BadBlock Ke·KeyError D·DroppedEntry L·Level Q·SeqNum T·TimeElapsed
20:21:03.757794 db@open opening
20:21:03.757857 journal@recovery F·1
20:21:03.758754 journal@recovery recovering @178
20:21:03.815246 mem@flush created L0@181 N·2073 S·57KiB "n:\x00..ing,v121469":"n:\xfe..ail,v120792"
20:21:03.816317 db@janitor F·4 G·0
20:21:03.816352 db@open done T·58.541927ms
20:21:03.826181 table@compaction L0·1 -> L1·1 S·646KiB Q·121572
20:21:03.916356 table@build created L1@184 N·8945 S·603KiB "n:\x00..ing,v101567":"version,v1"
20:21:03.961298 table@compaction committed F-1 S-43KiB Ke·0 D·1818 T·134.999752ms
20:21:03.961637 table@remove removed @181
20:21:03.962155 table@remove removed @180
20:22:00.557338 db@close closing
20:22:00.557590 db@close done T·286.804µs

**Comment by frozeman** [comment] 2016-02-05 12:48
Please try with the latest version and provide the log files, you can find in the `.config/Mist` folder (or so)

**Comment by penelopehead** [comment] 2016-02-08 22:48
That was from the latest version (0.3.9) from here: https://github.com/ethereum/mist/releases. Is there a newer version.

Here is node.log:

I0203 20:22:00.652840    5107 database.go:71] Alloted 16MB cache to /home/a/.ethereum/testnet/chaindata
I0203 20:22:00.712410    5107 database.go:71] Alloted 16MB cache to /home/a/.ethereum/testnet/dapp
I0203 20:22:00.717349    5107 backend.go:314] Protocol Versions: [63 62 61], Network Id: 2
I0203 20:22:00.718373    5107 genesis.go:89] Genesis block already in chain. Writing canonical number
I0203 20:22:00.718691    5107 backend.go:362] Blockchain DB Version: 3
I0203 20:22:00.720183    5107 blockchain.go:214] Last header: #334254 [ed78dd7b…] TD=1274420273213
I0203 20:22:00.720235    5107 blockchain.go:215] Last block: #334254 [ed78dd7b…] TD=1274420273213
I0203 20:22:00.720252    5107 blockchain.go:216] Fast block: #334254 [ed78dd7b…] TD=1274420273213
I0203 20:22:00.799956    5107 handler.go:92] blockchain not empty, fast sync disabled
I0203 20:22:00.816928    5107 cmd.go:114] Starting Geth/v1.3.3-c541b38f/linux/go1.5.2
I0203 20:22:00.817169    5107 server.go:311] Starting Server

Here is node.log.0:

I0203 20:21:01.656741    5029 database.go:71] Alloted 16MB cache to /home/a/.ethereum/chaindata
I0203 20:21:01.736980    5029 database.go:71] Alloted 16MB cache to /home/a/.ethereum/dapp
I0203 20:21:01.740199    5029 backend.go:314] Protocol Versions: [63 62 61], Network Id: 1
I0203 20:21:01.740690    5029 backend.go:362] Blockchain DB Version: 3
I0203 20:21:01.742700    5029 blockchain.go:214] Last header: #950062 [0fea61f8…] TD=6564627313958959506
I0203 20:21:01.742743    5029 blockchain.go:215] Last block: #950062 [0fea61f8…] TD=6564627313958959506
I0203 20:21:01.742759    5029 blockchain.go:216] Fast block: #950062 [0fea61f8…] TD=6564627313958959506
I0203 20:21:01.743214    5029 handler.go:92] blockchain not empty, fast sync disabled
I0203 20:21:01.752442    5029 cmd.go:114] Starting Geth/v1.3.3-c541b38f/linux/go1.5.2
I0203 20:21:01.752606    5029 server.go:311] Starting Server
I0203 20:21:03.816672    5029 udp.go:204] Listening, enode://e7572749a065b4d82add1a7e2d0c729409a1205b442915dd740c793a504ced3cef167d2a79f0751029f2235c211b22789bd8aecb79c5de64c44c03401499f48d@[::]:30303
I0203 20:21:03.816837    5029 backend.go:526] Server started
I0203 20:21:03.817067    5029 ipc.go:112] IPC service started (/home/a/.ethereum/geth.ipc)
I0203 20:21:03.817154    5029 server.go:552] Listening on [::]:30303
I0203 20:21:13.817706    5029 downloader.go:288] Block synchronisation started
I0203 20:21:15.980124    5029 blockchain.go:1243] imported 3 block(s) (0 queued 0 ignored) including 0 txs in 1.393860373s. #950065 [6d07f3ef / 022a1826]
I0203 20:21:16.064105    5029 blockchain.go:1243] imported 16 block(s) (0 queued 0 ignored) including 10 txs in 83.759732ms. #950081 [0703eb7c / 052d8e64]
I0203 20:21:22.876185    5029 blockchain.go:1243] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 13.677624ms. #950082 [e8b9f47e / e8b9f47e]
I0203 20:21:37.940463    5029 blockchain.go:1243] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 9.293987ms. #950083 [444b9afc / 444b9afc]
I0203 20:21:43.645218    5029 blockchain.go:1243] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 8.584308ms. #950084 [ff051896 / ff051896]

**Comment by penelopehead** [comment] 2016-02-08 22:54
And here is .../ethereum/testnet/dapp/log:

=============== Feb 3, 2016 (EST) ===============
20:22:00.712699 log@legend F·NumFile S·FileSize N·Entry C·BadEntry B·BadBlock Ke·KeyError D·DroppedEntry L·Level Q·SeqNum T·TimeElapsed
20:22:00.713046 db@open opening
20:22:00.713190 journal@recovery F·1
20:22:00.713626 journal@recovery recovering @64
20:22:00.717277 db@janitor F·2 G·0
20:22:00.717317 db@open done T·4.247942ms

**Comment by penelopehead** [comment] 2016-02-08 22:57
And .../ethereum/testnet/chaindata/log:

=============== Feb 3, 2016 (EST) ===============
20:22:00.653058 log@legend F·NumFile S·FileSize N·Entry C·BadEntry B·BadBlock Ke·KeyError D·DroppedEntry L·Level Q·SeqNum T·TimeElapsed
20:22:00.655268 db@open opening
20:22:00.657229 journal@recovery F·1
20:22:00.658248 journal@recovery recovering @14022
20:22:00.705925 mem@flush created L0@14024 N·11 S·464B "blo..um-,v10598234":"\xc5\xd2F..\x85\xa4p,v10598224"
20:22:00.710813 db@janitor F·487 G·0
20:22:00.710844 db@open done T·55.557041ms

**Comment by frozeman** [comment] 2016-02-09 10:43
Thanks, will take a look once i find time

**Comment by tveeger** [comment] 2016-02-12 10:52
Same crash with Ubuntu 15.10. Also after installing version: https://www.dropbox.com/sh/8mu15dkxlj8phu4/AACfurTFTyAg0k22g39Vgj1ka?dl=0

**Comment by frozeman** [comment] 2016-02-12 11:28
could you provide the log files, which are in the mist data folder `.config/Mist`

**Comment by tveeger** [comment] 2016-02-12 11:58
I0212 12:58:02.717725    8794 flags.go:425] WARNING: No etherbase set and no accounts found as default
I0212 12:58:02.717804    8794 database.go:71] Alloted 16MB cache to /home/tjeerd/.ethereum/testnet/chaindata
I0212 12:58:02.749641    8794 database.go:71] Alloted 16MB cache to /home/tjeerd/.ethereum/testnet/dapp
I0212 12:58:02.750949    8794 backend.go:314] Protocol Versions: [63 62 61], Network Id: 2
I0212 12:58:02.751791    8794 genesis.go:89] Genesis block already in chain. Writing canonical number
I0212 12:58:02.751847    8794 backend.go:362] Blockchain DB Version: 3
I0212 12:58:02.752097    8794 blockchain.go:214] Last header: #323 [6de28537…] TD=45280341
I0212 12:58:02.752111    8794 blockchain.go:215] Last block: #0 [435d3fbd…] TD=262144
I0212 12:58:02.752116    8794 blockchain.go:216] Fast block: #323 [6de28537…] TD=45280341
I0212 12:58:02.755275    8794 cmd.go:114] Starting Geth/v1.3.3-c541b38f/linux/go1.5.2
I0212 12:58:02.755387    8794 server.go:311] Starting Server

**Comment by frozeman** [comment] 2016-02-12 12:00
There are multiple log files, can you make sure to give the one of the crash?
This one looks like your normally started the testnet.

Do you have any other crash log, of the app itself or so? OSX gives you crash reports for example.

**Comment by tveeger** [comment] 2016-02-12 12:03
This is from ~/.ethereum/testnet/dapp:
=============== Feb 12, 2016 (CET) ===============
12:58:02.750186 log@legend F·NumFile S·FileSize N·Entry C·BadEntry B·BadBlock Ke·KeyError D·DroppedEntry L·Level Q·SeqNum T·TimeElapsed
12:58:02.750323 db@open opening
12:58:02.750352 journal@recovery F·1
12:58:02.750417 journal@recovery recovering @20
12:58:02.750910 db@janitor F·2 G·0
12:58:02.750929 db@open done T·597.645µs

**Comment by tveeger** [comment] 2016-02-12 14:17
Maybe a conflict with Geth, that is installed on my machine earlier?

**Comment by frozeman** [comment] 2016-02-15 11:12
hm actually not.

the testnet switch does nothing than stopping the running node and restarting it with the testnet flag.

Though there could be a race condition on your system where it wants to start the next one before shutting down the first one..

**Comment by tveeger** [comment] 2016-02-16 09:46
Thanks Fabian, 
After some cleaning up work, I got Mist start working on the testnet.

**Comment by frozeman** [comment] 2016-02-16 09:55
So i guess it was your systems configuration, would still be nice to know what caused it.

**Closed by frozeman** 2016-02-16 09:55 UTC
Labels: bug

**Comment by penelopehead** [comment] 2016-02-16 15:50
How do I replicate?

I can get Mist working on the testnet (by first opening geth and designating the testnet) but that is not the issue. The issue is when opening Mist without having opened geth and selecting "Develop/Network/Testnet (Morden)". Then Mist crashes.

**Comment by penelopehead** [comment] 2016-02-17 00:03
Just downloaded the new version, 0.4.0. The issue has been resolved!
