### ISSUE TITLE
Light client NOT WORKING in Mist/Ethereum wallet, stuck at "Waiting for block"

### ISSUE THREAD

**Issue by lt100** [ethereum/mist#3580] opened 2018-01-17 13:25 UTC
- [x] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.0.0`
OS & Version: windows/linux/osx
Node version: `geth 0.0.0` 
Number of blocks synchronized: 0
```

**Comment by lt100** [comment] 2018-01-17 13:25
Both latest versions

**Comment by UGatgithub** [comment] 2018-01-20 14:29
It does not help to open another thread for a known issue. Light client mode does not work for many users also due to the fact that there are not enough peers ...

**Comment by powpig** [comment] 2018-01-26 16:37
Yeah, been weeks since I could get the Light Client to work.  Mine says "no suitable peers available"
It was the only option I could get to work, absolutely no chance of it ever syncing otherwise.
Too bad, I like the platform & of course the security, but the EW is just completely unusable if it can't sync.

**Comment by evertonfraga** [comment] 2018-02-01 18:32
Duplicate of https://github.com/ethereum/mist/issues/3097

**Closed by evertonfraga** 2018-02-01 18:32 UTC
Labels: Status: Triage
