### ISSUE TITLE
MIST/GETH WILL NOT FINISH SYNC

### ISSUE THREAD

**Issue by brandallw** [ethereum/mist#3543] opened 2018-01-10 13:38 UTC
I am new to ethereum and have been mining for several weeks, I am trying to get Mist/Geth to sync so I can add the eth to my wallet from the mining pool, there have been 2 transaction from my pool sent but have not shown up in my wallet because I can not get the chain to finish syncing, this morning I have synced to block 4885172, I am 220 short of finishing, basically the same it has been, I left geth running all night and still do not get anywhere, current geth details below:

WARN [01-10|07:34:20] Stalling state sync, dropping peer       peer=4370617cc61eefb3
WARN [01-10|07:34:21] Stalling state sync, dropping peer       peer=2ec2ca0f8fbb0686
WARN [01-10|07:34:30] Stalling state sync, dropping peer       peer=d9671cf42a9c1850
INFO [01-10|07:34:36] Imported new state entries               count=0    elapsed=4.005ms   processed=158000 pending=9754  retry=68   duplicate=722 unexpected=1883
WARN [01-10|07:34:41] Stalling state sync, dropping peer       peer=34d628088618a161
WARN [01-10|07:34:47] Stalling state sync, dropping peer       peer=5ea59cefe43f725c
INFO [01-10|07:34:54] Imported new state entries               count=0    elapsed=0s        processed=158000 pending=9754  retry=456  duplicate=722 unexpected=1884
INFO [01-10|07:35:00] Imported new state entries               count=0    elapsed=16.027ms  processed=158000 pending=9754  retry=655  duplicate=724 unexpected=1890
WARN [01-10|07:35:03] Stalling state sync, dropping peer       peer=1209acba95854981
WARN [01-10|07:35:05] Stalling state sync, dropping peer       peer=39ecb25b4bafa297
INFO [01-10|07:35:07] Imported new state entries               count=0    elapsed=91.128ms  processed=158000 pending=9711  retry=663  duplicate=745 unexpected=1943
WARN [01-10|07:35:14] Stalling state sync, dropping peer       peer=d9671cf42a9c1850
WARN [01-10|07:35:29] Stalling state sync, dropping peer       peer=c78fbd03ca42737e
WARN [01-10|07:35:40] Stalling state sync, dropping peer       peer=09462a7ac00ece2f
WARN [01-10|07:35:41] Stalling state sync, dropping peer       peer=6cbe8abc23c93a30
WARN [01-10|07:35:47] Stalling state sync, dropping peer       peer=d9671cf42a9c1850
WARN [01-10|07:35:50] Stalling state sync, dropping peer       peer=bf48452372f15044
WARN [01-10|07:36:02] Stalling state sync, dropping peer       peer=4370617cc61eefb3
WARN [01-10|07:36:05] Stalling state sync, dropping peer       peer=5e25e4c90bd09d9d
WARN [01-10|07:36:09] Stalling state sync, dropping peer       peer=672b0e9ba92bae17
WARN [01-10|07:36:11] Stalling state sync, dropping peer       peer=dc6f8601de299018
WARN [01-10|07:36:17] Stalling state sync, dropping peer       peer=f549684cec5369df

I have been dealing with this for about a week now, any help on finishing the sync?  Thank you in advance.  

Version: `0.9.3`
OS & Version: windows
Node version: `geth v1.7.3` 
Number of blocks synchronized: 4885172
```


Check the already existing issues to keep duplicates at a minimum.


You'll find possible solutions for these common issues below on Mist Wiki: https://github.com/ethereum/mist/wiki.

- Ether is not shown in the wallet
- I send ether to the wallet contract but it doesn't show up
- Mist is synchronized but is stuck during the last part
- "Your computers time is out of sync!" error
- Unable to find peers
- My transaction is not confirmed
- Account can't be unlocked
- Unable to import pre-sale wallet
- Bind address already in use


When creating this issue, if possible add the following to your report:
- Screenshots
- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot
- Log files
  - Go to the menu `Develop -> Show log files`
  - Zip and upload `all.log` and any other appropriate `category/*.log` files

 -->

**Comment by evertonfraga** [comment] 2018-02-01 18:35
Duplicate of #3097.

Please refer to [this issue](https://github.com/ethereum/mist/issues/3097) for more information and our [Wiki](https://github.com/ethereum/mist/wiki) for troubleshooting steps.

**Closed by evertonfraga** 2018-02-01 18:35 UTC
Labels: Status: Triage
