### ISSUE TITLE
White GUI with Ethereum-Wallet-linux64-0-4-0

### ISSUE THREAD

**Issue by lightnetch** [ethereum/mist#229] opened 2016-03-03 12:32 UTC
After the app has started the wallet GUI starts only with white background.
I'm using Ubuntu 15.10

Please let me know if you need any further details.
Kind regards
lightnet

**Comment by frozeman** [comment] 2016-03-04 11:23
duplicate of #75

**Closed by frozeman** 2016-03-04 11:23 UTC

**Comment by racer8** [comment] 2016-06-01 10:50
Not a duplicate - other thread is for Linux
