### ISSUE TITLE
OSX Mist 0.3.9 (0.36.4) wallet withdrawal in limbo...?

### ISSUE THREAD

**Issue by glesaint** [ethereum/mist#160] opened 2016-02-11 05:15 UTC
Hello,

I transferred ETH from my wallet contract to an Exchange's deposit address.
This is the transaction: http://etherscan.io/tx/0x5afd037091c8ae965a2ab2b0f16365f911895d532b3022393a45675ebc68091d
This is the deposit address: 
(Etherscan) http://etherscan.io/address/0x55356f9b57ca3efbf8197bdf34f2e5385479af25
(Etherchain) https://www.etherchain.org/account/0x55356f9b57ca3efbf8197bdf34f2e5385479af25

The balance shows correctly on etherscan, but not on etherchain.
The exchange reports they didn't see the transaction.
Is there an issue with the transaction itself?
Kindly help! Thanks!

**Comment by frozeman** [comment] 2016-02-11 08:44
This is a duplicate of https://github.com/ethereum/meteor-dapp-wallet/issues/82

To keep it short, the exchanges won't see a transaction when you send from the contract wallet, as its an internal message call, which sends the funds.

Please contact them an redirect them to the issue linked.

To make sure its received on the exchanges, rather move the money first to an account address and then to the exchange. I will add a note to the contract wallet page.

**Closed by frozeman** 2016-02-11 08:44 UTC
Labels: question

**Comment by glesaint** [comment] 2016-02-11 10:19
Clear and thanks for the quick reply!
