### ISSUE TITLE
My Ether not Recieved 

### ISSUE THREAD

**Issue by Nergoy** [ethereum/mist#1730] opened 2017-03-14 14:37 UTC
Hello i dont recieved my 2.46315126 ETH i buyed them by Bitpanda . Ther wrote they send all succesfully away. 

my Konto is the 0x7B502EB0B53DAcFC7a5EAFF1ABf199D4879b980f but there i dont move anythink its still empty , it was my first auction so pls help me :( 

ohh and my e-mail is  linke.philip@gmail.com

#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by luclu** [comment] 2017-03-14 14:54
Please make sure that your wallet is fully synced

(Duplicate of https://github.com/ethereum/mist/issues/1720)

**Comment by Nergoy** [comment] 2017-03-14 14:58
how i can see this or do this ? :)

**Comment by luclu** [comment] 2017-03-14 15:05
On the userinterface you will see a section about the network info:

![bildschirmfoto 2017-03-14 um 16 04 01](https://cloud.githubusercontent.com/assets/10135872/23906958/dfc7e98a-08cf-11e7-9308-838c4a8220dd.png)

If instead you see a (blue) progress bar your node is still syncing to the network. In that case you will have to wait for it to finish until you will see the current balance of your accounts.

**Comment by Nergoy** [comment] 2017-03-14 15:10
the payment was before 4 days or 5 so i thnik it must be done jet. i dont see any synced point atm :(

**Comment by luclu** [comment] 2017-03-14 15:12
Please check the transaction as described in https://github.com/ethereum/mist/issues/1720 and post a screenshot of the Ethereum Wallet (please remove privacy relevant info).

**Comment by Nergoy** [comment] 2017-03-14 15:25
http://imgur.com/K8Fqtwc       this is a screen  so you can check it i hope so , thanks for the help atm :)

**Comment by luclu** [comment] 2017-03-14 17:15
@Nergoy please get in contact with the service you used. The transaction-id on the screenshot is not a valid one and the only transaction involving your address (https://etherscan.io/address/0x7b502eb0b53dacfc7a5eaff1abf199d4879b980f) seem to be a withdraw from poloniex.

The current balance of the address in question should be 2.45315126 Ether. Can you confirm this in Ethereum Wallet?

**Comment by Nergoy** [comment] 2017-03-14 17:24
my Ethereum wallet is Empty so i dont see any Changes i contact now bitpanda again , but they tell me that they send the Ethereum away and all i can see there is that they did , i send them now your massege and i hope the answer soon

**Comment by Nergoy** [comment] 2017-03-16 10:17
okay i know why i not working i need to sync my wallet , but how i can do this ? i only see verry difficult guides for this . no anti vir or somethink stops the speed , its veeery slow after 10 minutes i got 2% from 3 Million open blocks.

**Comment by luclu** [comment] 2017-03-16 19:42
>  its veeery slow after 10 minutes i got 2% from 3 Million open blocks.

I looks like you ran into this bug: https://github.com/ethereum/mist/issues/1701
A fix will be available in the next version. For now you can either:
- download and start http://geth.ethereum.org (just double-click) and start Mist/Ethereum Wallet
- use https://www.myetherwallet.com/

**Comment by luclu** [comment] 2017-03-16 19:53
>  its veeery slow after 10 minutes i got 2% from 3 Million open blocks.

I looks like you ran into this bug: https://github.com/ethereum/mist/issues/1701
A fix will be available in the next version. For now you can either:
- download and start http://geth.ethereum.org (just double-click) and start Mist/Ethereum Wallet
- use https://www.myetherwallet.com/

**Closed** 2018-02-01 18:43 UTC
Labels: Status: Duplicate
