### ISSUE TITLE
i am not seeing my ethereum in my wallet, purchased from coin base, i can see the transaction on the etheruem blockchain and it should be in my wallet but i dont see it.

### ISSUE THREAD

**Issue by kiakhh** [ethereum/mist#1756] opened 2017-03-17 07:11 UTC
#### System information
``````
Version: `0.0.0`
![screenshot 2017-03-16 23 04 13](https://cloud.githubusercontent.com/assets/26477986/24032636/3db0f83e-0aa6-11e7-8359-cca7cb541592.png)

OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by MergimHasani91** [comment] 2017-03-17 07:28
yes same by me brother i dont know where is my Ether

**Comment by luclu** [comment] 2017-03-17 11:59
Please make sure that your wallet is fully synced. This can take 1-20h depending on your systems specs.

Closed as duplicate of https://github.com/ethereum/mist/issues/1755.

**Comment by kiakhh** [comment] 2017-03-20 02:40
It has been alot longer than 20 h and i still dont see the funds in my wallet. How do i make sure the nodes are up to date


Kia Khosravi, AScT Certified TAB Technologist


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Luca Zeug <notifications@github.com> Date: 2017-03-17  4:59 AM  (GMT-08:00) To: ethereum/mist <mist@noreply.github.com> Cc: kiakhh <kia@tabco.ca>, Author <author@noreply.github.com> Subject: Re: [ethereum/mist] i am not seeing my ethereum in my wallet,
  purchased from coin base, i can see the transaction on the etheruem blockchain
  and it should be in my wallet but i dont see it. (#1756) 
Please make sure that your wallet is fully synced. This can take 1-20h depending on your systems specs.
Closed as duplicate of #1755.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ethereum/mist","title":"ethereum/mist","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ethereum/mist"}},"updates":{"snippets":[{"icon":"PERSON","message":"@luclu in #1756: Please make sure that your wallet is fully synced. This can take 1-20h depending on your systems specs.\r\n\r\nClosed as duplicate of https://github.com/ethereum/mist/issues/1755."}],"action":{"name":"View Issue","url":"https://github.com/ethereum/mist/issues/1756#issuecomment-287336405"}}}

**Comment by garretlaxton** [comment] 2017-03-20 03:36
I'm having the same problem too. You need to leave your wallet open for it to sync, at the top you will see 'blocks left' you need to let that finish while the wallet is open.. Atleast that's what I got out of reading through other issues.. I'm 70% complete now and I started about 7 hours ago.

**Comment by kiakhh** [comment] 2017-03-20 04:36
I apperciate your help, the thing is mine is at zero and its not changing, left it on for past 4 hrs.. 


Kia Khosravi, AScT Certified TAB Technologist


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: garretlaxton <notifications@github.com> Date: 2017-03-19  8:36 PM  (GMT-08:00) To: ethereum/mist <mist@noreply.github.com> Cc: kiakhh <kia@tabco.ca>, Author <author@noreply.github.com> Subject: Re: [ethereum/mist] i am not seeing my ethereum in my wallet,
  purchased from coin base, i can see the transaction on the etheruem blockchain
  and it should be in my wallet but i dont see it. (#1756) 
I'm having the same problem too. You need to leave your wallet open for it to sync, at the top you will see 'blocks left' you need to let that finish while the wallet is open.. Atleast that's what I got out of reading through other issues.. I'm 70% complete now and I started about 7 hours ago.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ethereum/mist","title":"ethereum/mist","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ethereum/mist"}},"updates":{"snippets":[{"icon":"PERSON","message":"@garretlaxton in #1756: I'm having the same problem too. You need to leave your wallet open for it to sync, at the top you will see 'blocks left' you need to let that finish while the wallet is open.. Atleast that's what I got out of reading through other issues.. I'm 70% complete now and I started about 7 hours ago. "}],"action":{"name":"View Issue","url":"https://github.com/ethereum/mist/issues/1756#issuecomment-287673278"}}}

**Comment by garretlaxton** [comment] 2017-03-20 04:43
Before you do anything else backup your account, do you know how to backup your account/have you backed up your account already?

**Comment by kiakhh** [comment] 2017-03-20 04:46
Is there a way to empty out the wallet somewhere offline and not ever use this wallet again?to be honest i expect more than this from eth 


Kia Khosravi, AScT Certified TAB Technologist


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: garretlaxton <notifications@github.com> Date: 2017-03-19  8:36 PM  (GMT-08:00) To: ethereum/mist <mist@noreply.github.com> Cc: kiakhh <kia@tabco.ca>, Author <author@noreply.github.com> Subject: Re: [ethereum/mist] i am not seeing my ethereum in my wallet,
  purchased from coin base, i can see the transaction on the etheruem blockchain
  and it should be in my wallet but i dont see it. (#1756) 
I'm having the same problem too. You need to leave your wallet open for it to sync, at the top you will see 'blocks left' you need to let that finish while the wallet is open.. Atleast that's what I got out of reading through other issues.. I'm 70% complete now and I started about 7 hours ago.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ethereum/mist","title":"ethereum/mist","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ethereum/mist"}},"updates":{"snippets":[{"icon":"PERSON","message":"@garretlaxton in #1756: I'm having the same problem too. You need to leave your wallet open for it to sync, at the top you will see 'blocks left' you need to let that finish while the wallet is open.. Atleast that's what I got out of reading through other issues.. I'm 70% complete now and I started about 7 hours ago. "}],"action":{"name":"View Issue","url":"https://github.com/ethereum/mist/issues/1756#issuecomment-287673278"}}}

**Comment by garretlaxton** [comment] 2017-03-20 04:52
I dont think so or I would've done that by now, I'm still waiting for my wallet to finish syncing.. An it isn't ETH thats causing this, it's the developers of this wallet that's causing problems, they messed something up in the last update or something.

**Comment by luclu** [comment] 2017-03-20 13:04
@kiakhh please make sure that no firewall is blocking. 

If you provide logs, I might be able to see what is happening. You can find instructions [here](https://github.com/ethereum/mist/issues/new).

**Comment by rrodasZ92** [comment] 2017-03-30 16:45
hello i am having the same issue . i bought an ethereum coin from coinbase 2 weeks ago and ive yet to see it . i have a ethereum wallet already installed on my computer and it said it was synced up . i also have the address for the wallet .

**Comment by luclu** [comment] 2017-04-08 10:07
Please make sure no firewall is blocking outgoing connections. 
Furthermore please upload your node.log as instructed below.

#### Some more generic advice:

Please, make sure you are running the [latest version](https://github.com/ethereum/mist/releases) and your node is **fully** synced.
Although this may take between 1h (SSD) and 10 hours (HDD) you should be able to see a progress bar on the *splash-screen* or in the *main-window*.

Further recommendations: 
- check your account's balance using http://etherscan.io
- make a backup of all account's keyfiles via `menu -> accounts -> backup -> accounts`
- should the initial sync take very long, consider following [these instructions](https://ethereum.stackexchange.com/questions/6554/i-am-having-trouble-doing-the-initial-sync-of-ethereum-wallet-what-can-i-do-to/6569) to speed it up
- if the peer count stays at 0 and it does not sync, verify your firewall settings
- consider using http://myetherwallet.com in the meantime

If this didn't solve your issue, please follow [these instructions](https://github.com/ethereum/mist/issues/new) and upload the `node.log` files:
> - Log files
>   - go to menu -> accounts -> backup -> application data
>   - zip and upload node.log and all other node.log.X files

**Comment by evertonfraga** [comment] 2017-09-28 20:13
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist

**Closed by evertonfraga** 2017-09-28 20:13 UTC
Labels: duplicate
