### ISSUE TITLE
Mist Wallet crash on lunch(Mac) 3.0.9

### ISSUE THREAD

**Issue by Wat3v4** [ethereum/mist#172] opened 2016-02-13 13:34 UTC
Hey, 
I'd like to start with the fact that I'm really new to all this cryptocurrency and I'm still learning, I am not a programmer and i have zero knowledge In that field.

I've downloaded the wallet beta 6 - 3.0.9 version for Mac OSX. 
I am using latest OS X - El Capitan 10.11.3.
Extracted the zip file and copied the "Ethereum-Wallet-darwin-x64-0-3-9"  folder to my desktop and ran the "Ethereum-Wallet.app" 
A little window appeared saying "Starting Ethereum node" and after about 5 secs it disappear and crashed. This happens every time i try to run it. 
Tried the other older versions but the result is the same. 

I've searched a little for this issue on this forum but i can't seem to find a solution.

Thanks a lot in advance for the help!

**Comment by Bubleek** [comment] 2016-02-13 15:46
Hi. We need some details for knowin what happen in you system. Run geth with flag --verosity 6 then peste result here(in this topic).
Read this issue first: https://github.com/ethereum/mist/issues/75 
Maybe it halp to you.

**Comment by supervitalik** [comment] 2016-02-13 18:04
hi there!

I have exactly the same problem as OP. Im on macbook pro, OS X - El Captain 10.11.3.

"A little window appeared saying "Starting Ethereum node" and after about 5 secs it disappear and crashed. This happens every time i try to run it. 
Tried the other older versions but the result is the same"

same same!

any ideas?

thanks!

**Comment by Wat3v4** [comment] 2016-02-13 22:26
@Bubleek Could you please be more specific of what to write in command? 
I already installed brew and geth but not sure what do you mean should i run?

**Comment by Wat3v4** [comment] 2016-02-14 08:21
Ok so its fixed after I did a number of things, hopefully it will help some other people with this problem.
While looking into what geth is I've found this guide and followed it:
https://github.com/ethereum/go-ethereum/wiki/Installation-Instructions-for-Mac

Installed homebrew and followed all the instruction in the link above.
While in the last part and the terminal was running the list, i lunched my Ethereum mist wallet and it said i am running a different node, after couple of seconds it started downloading blocks and peers.
Now it works without the terminal on the background(after finished downloading for few hours).

hope it helps. 

Thanks @Bubleek you helped me indirectly :D

**Comment by Bubleek** [comment] 2016-02-14 13:45
@Wat3v4 Are you already start or not?

**Comment by Wat3v4** [comment] 2016-02-14 13:49
@Bubleek What do you mean?

**Comment by frozeman** [comment] 2016-02-15 10:06
This is a duplicate of #163

**Closed by frozeman** 2016-02-15 10:06 UTC

**Comment by mikepancake** [comment] 2016-06-15 22:40
@Wat3v4 I experienced the same issues as you, and was able to get it up and running following your comments, so thank you for that. However I am unable to run the wallet after closing terminal. Can you walk me through how you may have ended that process or anything you did to make the wallet run without terminal running in the background?

**Comment by luclu** [comment] 2016-06-15 22:43
@mikepancake make sure to continue testing with the latest release `0.7.5`: https://github.com/ethereum/mist/releases/tag/untagged-36a08efca803064672a3
