### ISSUE TITLE
ETHERBASE password issue

### ISSUE THREAD

**Issue by TopRawMan** [ethereum/mist#161] opened 2016-02-11 10:26 UTC
I don't recall entering a password prior to depositing Ether into the etherbase account.  Have made other account with passwords.  Now that I'm trying to withdraw from Etherbase into other accounts, I am stuck without having made a password for the the etherbase(or so that's how I recall it.)
Armando

**Comment by frozeman** [comment] 2016-02-11 11:15
Hi,

if you can't recall the password, i can't help you :|
Try entering none?

**Comment by TopRawMan** [comment] 2016-02-11 18:55
I don't recall making one or being prompted to make one.  I have two other
accounts on the mist wallet and when I created them. I was prompted to make
a password.  Just tried to withdraw from the ETHERBASE wallet and that's
when I ran into this trouble.  I tried using NONE and ETHERBASE as a
password,but the password has conditions that I am pretty sure I would have
taken note if I made a new password.  It's just a small amount of Ether in
the account, but I wanted it to be known that I am not thinking that I lost
a password but that I never made one



---------- Forwarded message ----------

**Comment by bas-vk** [comment] 2016-02-12 07:39
How did you create the etherbase account? All methods to create an account will ask you for a password. If not, please explain how you created the etherbase account.

To be sure, when you tried NONE and EHTERBASE did you type in "NONE" and pressed enter, or did you leave the password empty and pressed enter? The latter is what you should try if you did not already.

**Comment by frozeman** [comment] 2016-02-12 10:25
It might be that you created this account in your node when you played with it before you ever ran mist?
Than its possible a password from the tutorials?

**Comment by TopRawMan** [comment] 2016-02-12 17:08
I got the Wallet from GitHub, extracted it to my desktop.  When I opened
the wallet, the etherbase account was there ready to go.  I sent some coins
from poloniex and the address worked.  I will try the no password thing
again.

**Comment by TopRawMan** [comment] 2016-02-12 17:10
I will check that out.  Whenever, I run software on Ubuntu, I do get a
password prompt to enter my os passwork.  Thanks for getting back to me.

**Comment by frozeman** [comment] 2016-02-15 11:10
I assume you had already a node pre-installed. 

Why youre asked for the OS password i don't know. Maybe the way you installed your previous geth node.

Please re-open when you find something like a bug in Mist

**Comment by TopRawMan** [comment] 2016-02-15 11:35
I did not have a node installed at all...I ran the wallet a few days before
depositing any ether...it wasn't until I created two other accounts  that I
was thinking about a password issue.  I downloaded the zip from github for
linux64, extracted to the desk top, opened the client and hit the wallet
icon and it went up and running.  I am trying to figure how to chalk it up
to my mistake, but once I made passwords for the other two accounts and
there were specifications for upper case, lower case, number and symbol, I
am pretty sure I never had to make a password..I tried the variations of no
password in the field, but no dice.  I recall wondering how to encrypt the
wallet on the desktop, ...I'm accepting the loss but I can't say that I
simply forgot the password.  to me, there is a bug in this somewhere.

**Comment by frozeman** [comment] 2016-02-15 12:13
Can you try this "y\r\n"

**Comment by TopRawMan** [comment] 2016-02-15 12:26
that didn't work.

**Comment by fgaudemar** [comment] 2016-05-18 11:51
@TopRawMan ran into the same issue after creating the Eth wallet (v0.7.3) using Github zip files for windows. Wallet was created , with an Etherbase account created initially, never asking for a password...
Did you find a solution ?

**Comment by bitcoinmeetups** [comment] 2016-05-21 10:23
I think I have had the same issue both on my Windows OS and my Linux OS (Ubuntu 15.10).

So, when I start Mist for the first time it asks for an "account password". Ok, I add a password and carefully write it down and save it.

Then, when I open Mist after syncing for the first time the Etherbase account is already there. But the password that I used as an "account password" does not work for sending funds from Etherbase. Thus, the funds are locked in there eternally unless you can figure this out. Looks like a dangerous bug. I can imagine many users haven't imported their pre-sale wallets yet, but what will happen if they do and then run into the same bug and are never able to move their funds out of Etherbase?

Please reply quite urgently if possible.

**Comment by luclu** [comment] 2016-05-21 10:26
@bitcoinmeetups please make sure to try out these tips: https://github.com/ethereum/mist/issues/669

**Comment by bitcoinmeetups** [comment] 2016-05-21 10:35
Ok luclu, I have tried out the tips.

**Comment by luclu** [comment] 2016-05-21 10:37
Are there any non-alphanumeric character you used?

**Comment by bitcoinmeetups** [comment] 2016-05-21 10:38
No, lots of digits but only alphanumeric ones.

**Comment by bitcoinmeetups** [comment] 2016-05-21 10:41
Almost everything TopRawMan says applies to my case as well as far as I can see.

**Comment by bitcoinmeetups** [comment] 2016-05-21 10:44
The password we generate when starting Mist the first time (account password) is supposed to be the Etherbase password, right? Just double checking.

**Comment by luclu** [comment] 2016-05-21 10:47
yes, you are right. Could you please try this service (it's client side in your browser; github-code is linked):
https://www.myetherwallet.com/#view-wallet-info

**Comment by bitcoinmeetups** [comment] 2016-05-21 12:49
How do I know that it's safe? Are you a core developer luclu? Are you the guy that was hired recently? Are you 100% sure that myetherwallet.com is trustworthy? Sorry but I have to ask for everyone's sake.

**Comment by luclu** [comment] 2016-05-21 13:46
+1 for your security mindfullness! 
The code is available here: https://github.com/kvhnuke/etherwallet, served directly by github and maintained by some well known community members (see links in repo). 
That said I'm generally sceptical about all client-side browser-based security-software.
If you trust github you can read about the project page-hosting's internals here: https://pages.github.com/
Or try to run it locally.

**Comment by bitcoinmeetups** [comment] 2016-05-22 09:05
> "That said I'm generally sceptical about all client-side browser-based security-software"

Yes, that's the thing. If I remember correctly there were some similar Bitcoin related services a few years back and they turned out to be dodgy. Let me think a bit, I will try to update as soon as possible.

**Comment by bitcoinmeetups** [comment] 2016-05-29 13:13
I was able to replicate the error yet another time. I removed the keystore, re-started Mist and was then  prompted to make an account password. I did so and exited Mist. Opened Geth. Tried to open the account with the password I generated minutes earlier and which I carefully wrote down. Incorrect password message.

**Comment by bitcoinmeetups** [comment] 2016-05-29 13:14
So far this issue has only occurred with the Etherbase account. Other accounts I have generated have not had any password issues.

**Comment by luclu** [comment] 2016-05-30 14:07
Another +1 for isolating this! I will try to reproduce this. What OS are you running?

**Comment by ryancharleston** [comment] 2016-06-05 22:16
I'm having the same issue. I don't remember ever being prompted to create a password for my etherbase wallet. I just installed the wallet software and let it sync for a while and then it was ready to go. I moved 1 ETH to this wallet to test and now when I try to withdraw it asks me for a password. But I never created one in the first place. I'm very adamant about storing every password I create for any site or software I use so I know if I was prompted to create one I would have written it down or stored it in my LassPass account.

**Comment by Bitbobb** [comment] 2016-06-13 07:26
I am having same issue.  I never made a password and now after 1 week of syncing with mist wallet I am asked for a password to transfer almost 6 eth coins from my etherbase main account.  I am also concerned that the above post by ryancharleston has not been answered 7 days later.  Does anybody take this problem seriously?  I just lost 6 ether coins to this bug.  Please fix so I can get the eth out!

**Comment by luclu** [comment] 2016-06-13 11:20
@ryancharleston @Bitbobb please try to open your wallet's `json`-file with [myethereumwallet.com](myethereumwallet.com) and report back if you were able to unlock your wallet. 
Mist as well as [myethereumwallet.com](myethereumwallet.com) implement the wallets according to [this specification](https://github.com/ethereum/wiki/wiki/Web3-Secret-Storage-Definition).

---

@ryancharleston If the `keystore`-folder were to be empty when starting the Ethereum-Wallet you are being prompt with the onboarding screen during which you have to specify a password (You can try this by moving all `json`-files). This password is the password for your first account thus the *etherbase* account. It is in this way that the password creation prompt differ from the one you encounter when creating additional accounts.
We are currently refactoring the onboarding process as several sources of confusion were identified among others:
 - we are not clear about the purpose of this password
 - it is possible to go back to that particular step and specify the password over and over

---

Please try out the recommendation on the top of this post, you will find a more detailed description in this issue: https://github.com/ethereum/mist/issues/669

**Comment by fgaudemar** [comment] 2016-06-13 11:39
Indeed, I agree it is the onboarding process which is confusing : I finally
found out that I entered a password during this onboarding process but did
not understand at that time it was THE wallet password, so that I did not
even notice I entered one.
Luckily, I noted it down somewhere, and finally was luckyenough to stumble
upon it : I had no recollection of being prompted for any password, but
tried it, and.. voila... I recovered my Etherbase account.


2016-06-13 13:20 GMT+02:00 Luca Zeug <notifications@github.com>:

**Comment by Bitbobb** [comment] 2016-06-14 09:45
Ran geth with the unlock command and took a screen shot.  It looked like it was asking for a password.  Maybe I can reverse the secret3 protocal to figure out my password.
this is my jaxx wallet if anyone wants to donate: 0x9c20b60d6272d4D96c07B01052Ba6c662e14B125
looks like a lot of work  to get back my 5.8 eth
    Thanks for the replies people
   I do think it is a bug because sometimes it says wrong password and other times it says cannot connect to node, did it crash in background?"

![Uploading Password2.jpg…]()

**Comment by Bitbobb** [comment] 2016-06-16 07:30
Can any respond to this bug?  I will try again the unlock command.   What am I supposed to expect.  It did something and then I was prompted for password then geth started running and loading blockchain it looks like.  I need response please.  What was purpose of unlock cammand and what do I do after executing it?  Thanks

**Comment by Bitbobb** [comment] 2016-06-16 07:31
I was unable to unlock it with myehterumwallet.com BTW thanks

**Comment by luclu** [comment] 2016-06-16 10:34
@Bitbobb good to hear, are there any special characters? What is your passwords length?

**Comment by Bitbobb** [comment] 2016-06-16 10:53
length: 9
special characters:  !
This is assuming that the password I found is correct.  I think it is but I am still being told it is wrong password.  This must be a bug I found right?  I have read about this alot since this happened.  Thanks a lot for your help with this!!!  :)  :)
     Ask me anything I want to fix this
    I can send you what I think the password is if it helps.  At this point I allready feel like my eth is gone and it is not a password I ever used before...

**Comment by luclu** [comment] 2016-06-16 13:58
1. is this your etherbase (main account)?
2. do you remember what version you used to create it?

**Comment by Bitbobb** [comment] 2016-06-16 19:11
No worries I read it that way too and I wrote it.  ahah.  We are human!!!
Yes it is the etherbase main account
I am not sure on the version because I had problems with  the latest mist which was I believe 7.4
I could not get it too do something and one of the dev's told me to solve this use 6.2
so now I am on 6.2  So that should be the version unless I created the password before the switch
but I did delete all the old files before installing the other version ans syncing.
So I think the correct answer is 6.2

**Comment by Bitbobb** [comment] 2016-06-16 20:00
Dear luclu,  
     I found another password that worked.  I feel so stupid.  I did not know I even made a password I am so sorry for the trouble.  Please forgive me.  Nobody donated anything.  I have just successfully transferred from my previously locked wallet on main ether base account.  I am willing to give some eth for your trouble.  Thanks again

**Comment by luclu** [comment] 2016-06-16 20:07
No worries @Bitbobb! Glad you solved it.
Finally... that's good to hear. ;)

**Closed by luclu** 2016-06-16 20:07 UTC

**Comment by luclu** [comment] 2016-06-16 20:09
For the future, if affected please create a new issue so this doesn't get necrobumped. Link to this if relevant.
