### ISSUE TITLE
Ether missing from my account after successful Kraken withdrawal

### ISSUE THREAD

**Issue by MrMontana** [ethereum/mist#576] opened 2016-05-07 13:08 UTC
Node type: geth
OS: osx
Network type: main
Mist version: 0.7.2

I made my first transfer from Kraken to my Ethereum Wallet today and although Kraken has said the transfer went fine it has not shown up in my wallet. I have checked the block and it has confirmed it went through, all the addresses are correct but my wallet is empty.

**Comment by obscuren** [comment] 2016-05-08 08:27
Kraken does not support withdrawals to contracts (e.g. The ethereum wallet contract) and this is shown as a warning on the Kraken website (this has to do with not providing enough gas). Is this something you've done? If so please close this issue and contact Kraken customer support, they are very helpful. If not please provide the hash of the transaction so that we may be able to debug the transaction and see what's going on.

And finally, as a reassurance, not once has someone lost his ether because of a malfunction of the ethereum system :-)

**Comment by MrMontana** [comment] 2016-05-08 12:19
Thanks Jeffery. 

I have contacted Kraken direct as that is where the transaction was done...rookie error. I hope I can get the Ether back. 

On another note, the reason I was doing this was to purchase some DAO token and with it going up in price shortly I am still trying to do it so I went into the wallet and bought some ether with BTC via shifty in the wallet and it hasn't shows up either even though it says the transaction was all good. 

Can you please help?

Many Thanks

Josh Taylor
Director/Artist Manager

Cassette Entertainment
+61 433 209 690

**Comment by MrMontana** [comment] 2016-05-08 14:17
![screen shot 2016-05-08 at 10 03 55 pm](https://cloud.githubusercontent.com/assets/19239031/15098239/56b80974-157b-11e6-8814-9b44520096eb.png)

**Comment by MrMontana** [comment] 2016-05-09 13:30
Me again, please see email below from Kraken advising that the transactions went through. So now I have two outstanding issues and no Ether in my wallet. The whole reason I did it was to buy DAO which is about to go up. I need this rectified asap and an expanation why a transfer and a purchase from the wallet hasnt worked.

"Hi Josh,

Alexander from Kraken here. Thank you for the message and sorry to hear about the issue.

To know if the transaction has went through successfully, we need to consult the blockchain:
http://etherscan.io/tx/0x554dd182f908ad7579bd8645c4b2a528ffe24624d38c8a52c4e2ef0cc58b7f37

http://etherscan.io/tx/0x7aa73171304880152205c3bd017edb58ff0b8b76af263ba2133ca3f047859864

From this we can see that your withdrawal has in fact gone through and has over 11000 and 9000 block confirmations respectively.

Please, double-check the address you sent it to (as wallets can manage many addresses) and make sure you're using the latest version of geth to sync your wallet:
https://github.com/ethereum/go-ethereum/releases

Let us know if there's anything else we can assist you with."

**Comment by luclu** [comment] 2016-05-09 15:51
Hi @MrMontana, thank you for your detailed report.
Until now we haven't had any users experiencing this. Can I ask you to kindly - if possible - run Mist on another computer and backup and copy the `keystore`-folder of your primary computer to this temporary one and ping back on the outcome?

**Comment by withtbird2** [comment] 2016-05-09 18:30
"Until now we  haven't has any users experiencing this". Say what? I have the same problem (using W7  64 bit mist 0.7.,2) noted here some days ago. I too contacted Kraken and Alexander said the same thing. My Mist wallet has zero balance when it should have 1000 ETH. Nice.

**Comment by MrMontana** [comment] 2016-05-11 03:11
Thanks @luclu fr getting back to me. Unfortunately I am a very average user and wouldn't have a clue how to do that.

Let me ask this. For me to be able to see my Ether in the account would I have to let it sync first?

**Comment by luclu** [comment] 2016-05-11 08:17
@MrMontana you will need to 
1. start the Ethereum-Wallet on the other computer and let it sync - yes this will take quite long unfortunately.
2. on both computers in the Ethereum-Wallet click on the menu --> Accounts --> Backup --> Accounts
3. copy all the json-files (your accouts) to the temporary computer's open folder ("keystore")
4. now restart the Ethereum-Wallet on the second computer and verify if everything shows up fine

**Comment by MrMontana** [comment] 2016-05-14 03:40
@luclu I have done this and successfully sync'd the wallet and added the keys from the other wallet and they come up but still with no ether in them....please help asap.

**Comment by luclu** [comment] 2016-05-19 12:56
Please provide the wallet keys. (mind the privacy-implications)

**Comment by Felixtwist** [comment] 2016-05-27 02:10
Hi, I have had the same problem when withdrawing from Kraken. the first 2 test runs I used a small amount of ether and it was confirmed successful on Kraken. However, I have proceeded to withdraw all of my ETH and it has never showed up in my account! I am currently down over 1000 ETH. I have re-synced the node and am running the latest version of MIST however still no signs of the ETH in my account!?  ANy help will be much appreciated. 

Kind Regards, 

FT

**Comment by withtbird2** [comment] 2016-05-27 02:14
Forget Mist. Try opening wallet using Myetherwallet.com. I did and managed
to salvage (send back to Kraken) my missing ETH.

**Comment by luclu** [comment] 2016-05-27 02:16
@Felixtwist for a start look up your recipient address on a block-explorer. You might want to contact kraken support to trace the transaction if no ether is shown on the block-explorer as well.

**Closed** 2016-05-29 23:43 UTC

**Comment by bodytexture** [comment] 2017-10-14 23:42
i guess i'having same trouble you apparently had about one year ago.. any update?
