### ISSUE TITLE
0 peers __ waiting for blocks

### ISSUE THREAD

**Issue by arotello** [ethereum/mist#840] opened 2016-06-16 13:49 UTC
Node type: geth 1.4.7
OS: OS X El Capitan (10.11.5)
Network type: main
Mist version: 0.7.5

I upgraded Mist, deleted the original blockchain (~13GB) and let the new version sync (~4.3GB) After syncing, the Mist application opens up but shows 0 peers __ waiting for blocks. This lasts for around 30 min before peers and blocks suddenly appear. However, Mist then says X number of minutes since last block and never syncs. At this point, the application isn't frozen but blocks never update. Starting up geth before opening Mist does not resolve the issue. Geth is running as expected in the background.

**Comment by luclu** [comment] 2016-06-16 14:57
Most likely related to https://github.com/ethereum/mist/issues/836

**Comment by luclu** [comment] 2016-06-26 17:20
I will close this as a duplicate of https://github.com/ethereum/mist/issues/292.
Please join the discussion over there.

**Closed by luclu** 2016-06-26 17:20 UTC
Labels: bug

**Comment by MinuteBar** [comment] 2017-02-21 09:20
I also have the waiting for blocks error in Ethereum Wallet. Also Mist fails to sync. 
Get this error in console: 
![image](https://cloud.githubusercontent.com/assets/17679610/23158380/fcca377a-f7ec-11e6-92be-01baa780b3db.png)
