### ISSUE TITLE
404 File not found [wallet.ethereum.org]

### ISSUE THREAD

**Issue by iamtrillion** [ethereum/mist#1006] opened 2016-07-20 17:10 UTC
Node type: geth/eth
OS: /windows 10
Network type: main
Mist version: 0.8.1

a user on [daohub](https://forum.daohub.org/t/hard-fork-implementation-update/6026/38), was getting the following error shown in the image below:
<img src="https://forum.daohub.org/uploads/default/optimized/2X/6/6fb435ccb1a4d5f0c004865d37ceb9821084332d_1_689x405.png">

**Comment by Al3ksand3r** [comment] 2016-07-20 19:21
Hi, i have the same error... what do?

**Comment by luclu** [comment] 2016-07-20 23:54
Duplicate of https://github.com/ethereum/meteor-dapp-wallet/issues/240.

**Comment by iamtrillion** [comment] 2016-07-21 00:12
ok thnx, sorry about that, you can delete this since its a duplicate thnx.

**Closed** 2016-07-21 00:21 UTC
Labels: duplicate

**Comment by korshan** [comment] 2016-07-25 14:15
Hello,

I just had this same 404 error. Unfortunately, as an end user, I have no idea how to execute "As a workaround open the base URL https://wallet.ethereum.org/ to refresh the DApp and circumvent the 404 error."

Please provide total noob instructions, e.g. how to open the base URL.

Thank you :)
