### ISSUE TITLE
Transaction from Coinbase to Mist Account confirmed over 9000 times. Not a wallet contract,  just the main account. What could have happened?

### ISSUE THREAD

**Issue by buysquared** [ethereum/mist#2099] opened 2017-03-31 17:44 UTC
#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by garretlaxton** [comment] 2017-03-31 21:02
Your wallet needs to fully sync before it can show your ETH.

**Comment by buysquared** [comment] 2017-03-31 22:03
How do I ensure that it is synced?

**Comment by garretlaxton** [comment] 2017-03-31 23:35
Watch this video [https://www.youtube.com/watch?v=wXmRdnyKKqg](url)

**Comment by luclu** [comment] 2017-03-31 23:55
Closed as duplicate of https://github.com/ethereum/mist/issues/2098.

**Closed by luclu** 2017-03-31 23:55 UTC

**Comment by buysquared** [comment] 2017-04-01 00:19
Garret. That url does not exist.
