### ISSUE TITLE
Starting Ethereum Node  screen persists 

### ISSUE THREAD

**Issue by keznerve** [ethereum/mist#88] opened 2015-12-15 00:19 UTC
hi when i go to open my wallet on my mac os 10.8 i just get this screen from my wallet any ideas , did i down load the right wallet?

**Comment by frozeman** [comment] 2015-12-15 09:56
I think your either missing `gmp` so see here https://github.com/ethereum/mist/issues/65

Or your node is upgrading the database in the background which can take a while, make sure you also update your local node

**Comment by keznerve** [comment] 2015-12-15 15:55
thanks
will have a look

**Comment by keznerve** [comment] 2015-12-15 16:08
Hi i have no Mist folder in my  Library/Application support or no Ethereum  folder in my Library. I presume i need Brew and to do what is suggested in  #65, where do i get this? (im totally new)

**Comment by keznerve** [comment] 2015-12-15 16:49
heres what happened


brew install gmp
Error: The following formula:
  gmp
cannot be installed as a a binary package and must be built from source.
To continue, you must install Xcode or the CLT from:
  https://developer.apple.com/downloads/

unknown-e0-f8-47-0f-9e-f8:~ williams$ brew install gmp
Error: The following formula:
  gmp
cannot be installed as a a binary package and must be built from source.
To continue, you must install Xcode or the CLT from:
  https://developer.apple.com/downloads/

**Comment by frozeman** [comment] 2015-12-16 08:35
```
To continue, you must install Xcode or the CLT from:
https://developer.apple.com/downloads/
```

you need those first

And if you don't have an ethereum folder, this is because the node never really started up

**Comment by keznerve** [comment] 2015-12-18 09:52
thanks

**Comment by frozeman** [comment] 2016-01-25 16:52
Closing this, because its a duplicate of #65

**Closed by frozeman** 2016-01-25 16:52 UTC
