### ISSUE TITLE
Latest Release 0-8-3 has no Ethereum-Wallet-linux64-0-8-3.zip file

### ISSUE THREAD

**Issue by githubrsys** [ethereum/mist#1224] opened 2016-09-28 16:40 UTC
#### System information
``````
nn
``````

In the 0.8.2 release there was a Ethereum-Wallet-linux64-0-8-2.zip file. Which is now missing, only a Ethereum-Wallet-linux64-0-8-3.deb file is there. Not everyone relies on deb packages. Would be awesome if added. 

Cheers

**Comment by luclu** [comment] 2016-09-28 17:04
Closed as duplicate of https://github.com/ethereum/mist/issues/1190

**Closed by luclu** 2016-09-28 17:04 UTC
