### ISSUE TITLE
SVP/Light client mode

### ISSUE THREAD

**Issue by pyalot** [ethereum/mist#2472] opened 2017-06-09 08:49 UTC
It would be a good idea to include an SVP mode with the wallet so that users don't have to wait for a d/l of the entire blockchain before being able to use the wallet. Relevant wiki entry: https://github.com/ethereum/wiki/wiki/Light-client-protocol

**Comment by PatchRanger** [comment] 2017-08-10 09:22
Thank you for suggestion! Should be closed in favor of #2372 - as it is explained in detailed manner.

**Comment by evertonfraga** [comment] 2017-10-19 18:49
Duplicate of #2372

**Closed by evertonfraga** 2017-10-19 18:49 UTC
Labels: v0.8.10
