### ISSUE TITLE
mist last 100+ blocks doesn't download

### ISSUE THREAD

**Issue by group-1-engineering** [ethereum/mist#3573] opened 2018-01-16 01:30 UTC
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.0.0`
OS & Version: windows/linux/osx
Node version: `geth 0.0.0` 
Number of blocks synchronized: 0
```

**Comment by Simsen** [comment] 2018-01-16 15:44
I have the same issue!
I can close then - the Blocks is rasied - and it begin to download again, until its 100+ blocks away.
Very frustrated!

**Comment by Frustrated101** [comment] 2018-01-17 21:05
your problem is "chain structure" download

**Comment by kinther** [comment] 2018-01-20 04:03
@Frustrated101 Can you elaborate?

**Comment by MaximusMcCann** [comment] 2018-01-25 21:04
Same issue

**Comment by alfamatrix** [comment] 2018-01-28 12:15
Same issue here from 3 weeks is repeating the same,sync. stopped and 100-200 blocks always ahead and never complete the sync.
The bad is if I restart sync. everything start from zero and must wait to sync milions of blocks again,then everyting is repeating again.

**Comment by alfamatrix** [comment] 2018-01-28 12:19
Have any staf here from the management "Ethereum mist wallet"???

**Comment by evertonfraga** [comment] 2018-02-01 18:36
Duplicate of #3097

Please refer to [this issue](https://github.com/ethereum/mist/issues/3097) for more information and our [Wiki](https://github.com/ethereum/mist/wiki) for troubleshooting steps.

**Comment by evertonfraga** [comment] 2018-02-01 18:36
@alfamatrix yes, please refer to the links above and always try to search for an existing issue before opening a new one. thanks!

**Closed by evertonfraga** 2018-02-01 18:36 UTC
Labels: Status: Triage

**Comment by alfamatrix** [comment] 2018-02-01 18:41
OK man THAKS.
