### ISSUE TITLE
My ether not recived

### ISSUE THREAD

**Issue by JamesKimKR** [ethereum/mist#1729] opened 2017-03-14 12:42 UTC
#### System information
``````
Version: `0.8.9`
OS & Version: Windows7
Node type: `eth/geth(default)`
``````

Hello, My ether not recived.

My ether wallet from address is 0x5B2A91C0aD992426da28E0438DD2BF35aFdD2d33
and to address is 0x252f1a00ca448e3fce83b90fbebdb460e4e69bed

I have transferred 40 ether on "from address" a Transaction number is 0x7aceff6dab9928544eb8f8e109ddf389b19654f33758f10b28342ae59a72ab9a
( https://www.etherchain.org/tx/0x7aceff6dab9928544eb8f8e109ddf389b19654f33758f10b28342ae59a72ab9a )

but I haven't received my ether.

what happend? Can you check my transaction?

My e-Mail id: cleartoy@gmail.com

- Screenshots
![image](https://cloud.githubusercontent.com/assets/26408414/23900477/d636618a-08fc-11e7-8931-43f09958e066.png)

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot
![image](https://cloud.githubusercontent.com/assets/26408414/23900529/06b95966-08fd-11e7-8a99-022d47737e2c.png)

- Log files 
[Ethereum Wallet.zip](https://github.com/ethereum/mist/files/841267/Ethereum.Wallet.zip)

**Comment by luclu** [comment] 2017-03-14 13:44
Please make sure that your wallet is fully synced

(Duplicate of https://github.com/ethereum/mist/issues/1720)

**Comment by JamesKimKR** [comment] 2017-03-14 14:00
https://etherscan.io/tx/0x2ddae946c02751c5da60f5ec2d3a9e868743992ba3aeefa7766e5ab026d74620

**Comment by luclu** [comment] 2017-03-14 14:42
I might be mistaken, but I think everything looks fine, i.e. the ~40 Ether seem to be available at https://etherscan.io/address/0x252f1a00ca448e3fce83b90fbebdb460e4e69bed. Is this correct?

**Comment by JamesKimKR** [comment] 2017-03-15 00:25
Thanks luclu

As you say, I have confirmed that ~40 Ether is available in My Ethereum Account(0x252~~~69bed).

My account created in exchange(market), and the InternalTransaction is not confirmed on the exchange(market), so the transaction is not processed.

Is this a problem with the exchange(market)?

**Comment by JamesKimKR** [comment] 2017-03-16 07:58
Hello luclu~

I am currently using Ethereum MIST.

I sent 40 Ethereum from MIST account into my MIST Ethereum account.

But I cannot get confirmation from other ethereum market, saying "it does not exist in transaction log". Therefore I am asking you about this.

> eth.getTransaction("0x7aceff6dab9928544eb8f8e109ddf389b19654f33758f10b28342ae59a72ab9a")
{
blockHash: "0x22e00d7652997c4d4eaae2c2875eddb5f09a82e0adb8ffdefce8ed8882efdbbc",
blockNumber: 3344571,
from: "0xd4d1774d7c0683b3384c5705249db29e00531804",
gas: 183368,
gasPrice: 20000000000,
hash: "0x7aceff6dab9928544eb8f8e109ddf389b19654f33758f10b28342ae59a72ab9a",
input: "0xb61d27f6000000000000000000000000252f1a00ca448e3fce83b90fbebdb460e4e69bed0000000000000000000000000000000000000000000000022c7fd18a852a0000000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
nonce: 2,
r: "0xe59efb73f7b8d911e5416e02ea63f2dd8300e6746d202a65333ab4b13d19febb",
s: "0x7cc2c8d0f1ba3528ae77a72c78b9058f244d0aaa0ea53b656fa2432c24051c50",
to: "0x5b2a91c0ad992426da28e0438dd2bf35afdd2d33",
transactionIndex: 38,
v: "0x26",
value: 0
}

Ethereum market says it is not processed because value is showing 0 like below log.

I wonder whether this is problem of mist, or receiving ethereum market.

**Closed** 2017-03-16 12:34 UTC
Labels: duplicate
