### ISSUE TITLE
Accounts not showing in 0.8.4 so user reverted back to 0.8.2

### ISSUE THREAD

**Issue by hiddentao** [ethereum/mist#1231] opened 2016-09-30 07:31 UTC
#### System information
``````
Version: `0.8.4`
OS & Version: linux
Node type: `geth`
``````

From https://www.reddit.com/r/ethereum/comments/556et5/just_installed_ethereum_and_mist_beta_084_wallets/

"The title says it all. I am running the Linux 64 version of both Ethereum and Mist (non-deb on Fedora 24). Both startup fine and start downloading blocks, but both say that I have no accounts. I checked the keystore and all files are there, but they are not seeing them for some reason. As soon as I reverted back to 0.8.2, the accounts showed back up. 0.8.2 no longer gets stuck on a block as it did about a week ago, but it is VERY slow, and it seems to be consuming a lot of resources (RAM and CPU).

I am stuck on poor performing 0.8.2 for now. Other that the missing accounts, the performance of 0.8.4 seemed to be a lot better: lower resource usage.

Another FYI, it appears that Ethereum wallet executable name was changed. I clicked on my old 0.8.2 launcher icon, an it failed to launch. I looked at the executable: for the last several releases, it was named "Ethereum-Wallet". In the 0.8.4 release, it was changed (inadvertently?) to "Ethereum Wallet." I changed it back to the old name and everything worked fine. Final bug: I tried to create a new account with 0.8.4, and the account creation failed. There was no explanatory message why it failed."

**Comment by luclu** [comment] 2016-09-30 07:32
This seems to be related/duplicate of https://github.com/ethereum/mist/issues/1174

**Comment by koeppelmann** [comment] 2016-09-30 16:55
same problem on a mac.
When I click on Accounts->Backup->Accounts it points to the right folder with the keystore folder and the keyfiles in it.

**Comment by luclu** [comment] 2016-09-30 20:04
This issue has been identified. It is caused by the new installer which required to setup separate config folders for Ethereum Wallet and Mist - only retaining Mist's config folder used by both in release `<0.8.3`.
> Finally this the new installer split the config-folder into separate ones for **Ethereum Wallet** and **Mist**. As a result Ethereum Wallet won't display any previous *watched custom contracts and token* as well as *contract wallets* and *wallet names*. Although they are still available in Mist and Ethereum Wallet `< 0.8.3` you will need to re-added them manually to Ethereum Wallet `>= 0.8.3`.

**Closed** 2016-09-30 20:04 UTC
Labels: bug
