### ISSUE TITLE
The endless node sync!!!

### ISSUE THREAD

**Issue by glad-zilla** [ethereum/mist#2466] opened 2017-06-08 18:24 UTC
So my ether wallet has been attempting to sync for the last 28 days.

Wallet version 0.8.10
Ether node geth 1.6.5 (Go)
MacOS Sierra 10.12.5

Will the wallet ever sync?
It seems to be downloading infinite chain structure.

Could really use some reassurance as I have coin transferred to this wallet and I'm worried it might never arrive.

**Comment by garretlaxton** [comment] 2017-06-08 21:37
You can try deleting your `chaindata` folder, you can also use myetherwallet.com to access your ETH.

**Comment by sathishvj** [comment] 2017-06-09 04:33
Your ETH balance is still viewable on ethereum blockchain browsers like etherscan: etherscan.io/address/0x...

Your local node with ethereum-wallet/mist is only accessing the public blockchain and is not necessary for the rest of the network to function.

**Comment by matthewleising** [comment] 2017-06-09 14:42
dear sathishvj  -- I have the same issue with my wallet and the node never synching, and on top of that no ether I have sent to my wallet address shows up. Can you elaborate on why you say the local nodes "is not necessary for the rest of the network to function." I'm guessing I have received no ether because the download never completes, but I could be wrong of course. Can you help?

**Comment by glad-zilla** [comment] 2017-06-09 16:47
So I used the myetherwallet.com route to send my ether to a different wallet.

Worked just fine, and now I don't have the stress of wondering if I will ever see my ether due to an endless node sync.

Thank you everyone.

**Comment by matthewleising** [comment] 2017-06-09 17:00
@glad-zilla what wallet are you using if you don't mind me asking?

**Comment by glad-zilla** [comment] 2017-06-09 17:07
@matthewleising 
Type etherum wallet into the apple app store or google play store.

You're looking for a wallet from Freewallet.org.

**Comment by sathishvj** [comment] 2017-06-10 01:48
@matthewleising as a quite crude analogy, think of how email works.  Somebody sends you an email while your computer was shut down.  Is it still received?  Yes, on your email account.  But not your computer.  You later start your computer, connect to the internet, and now the email sync happens.  The email will then show up on your local client.  In a somewhat similar way, somebody sending Eth to your account will be processed by the Ethereum network and it will be available against your account.  However, your local node might still not have the latest until it is synced with the network.

**Comment by matthewleising** [comment] 2017-06-10 01:55
@sathisvj thank you that makes perfect sense to me and I appreciate you taking the time to explain it

**Comment by Luukw12** [comment] 2017-06-10 14:44
Hey guys, i have kind of the similar problem.. I bought some ethereum and transferred it to my mist wallet, not realising it was still synchronising...
Now the Mist Wallet has been synchronizing for 10 days and is roughly at 66%. it moves as slow as one block a second and it already uses about 20Gb of space on my Macbook. I've read many advises on Geth and myethereumwallet.com, but i am quite new to ethereum and these terms and I have absolutely no idea how to make it sync any faster or how to acces my ethereum via myethereumwallet.com.

I am convinced I am doing multiple things wrong and I know it is mostly due to my complete ignorance about Ethereum and the wallets, but I really would like to acces my ethereum and I hope someone can help me accessing it faster.

Thanks!

**Comment by sathishvj** [comment] 2017-06-11 03:52
@Luukw12 It's myetherwallet.com  Don't go to any other site.  They could be phishing sites.

It would be best if you followed the tutorials for MEW (myetherwallet.com).  You can just search for them.

Yes, syncing the entire blockchain takes tens of GBs of space.

For the sync, make sure you are on a fast network, if possible put an Ethernet cable directly to the WiFi box, see if it finds peers, check the log file that there are no errors, if you are behind a proxy maybe you can try on a network without that, close other torrent/wallet/AV apps (not sure if it has an impact but you can try).

**Comment by kanna-shirakawa** [comment] 2017-06-11 12:04
maybe that I'm wrong, but I see a design flaw here, running a full node without any prune option to keep the downloaded data within a reasonable size, specially when the network seems to be under pressure like these days, the sync task never finish, I suppose that network changes faster than the most home computers can handle; just now I see that the chain structure has near 180'000 entries, and my pc follows at 160'000, one hour ago was 140'000 over 165'000, a funny race, beside the fact that the wallet is eating all my resources (memory, hard disk) :/

FYI, 8.0.10, linux version

**Comment by kanna-shirakawa** [comment] 2017-06-11 14:24
update: I can confirm that the issue is related to geth one, see https://github.com/ethereum/go-ethereum/issues/14575

I found several entries like this in node.log:
WARN [06-11|16:16:01] Synchronisation failed, retrying  err="state data download canceled (requested)"

simply said, the network is filled by new transactions and the geth client is not able to follow

**Comment by sathishvj** [comment] 2017-06-11 14:56
As far as I understand, by default Mist/Ethereum-Wallet starts geth and then connects to that.  So sync issues are definitely at the geth level.  I used to just run geth and see the log on screen.  I would see that issue once in a rare while, but stopping and starting geth usually worked for me.

**Comment by RobQuistNL** [comment] 2017-06-11 15:46
I've been syncing for about 20 days now. In the beginning the chains structure thing (the 32 million counter) went up fast, as did the block chain counter (now 1,5 million left). After the first was done, it continued (or restarted) on the second. Currently its constantly using 10% CPU, 3 to 4 GB RAM, my drive is making sound like crazy, and its increasing with about 1 block per minute. This is going to take forever. Whats going on??

**Comment by RobQuistNL** [comment] 2017-06-12 02:20
A little check;

Started Eth again. Started 
"Downloading block 2,427,186 of 3,858,460" at 03:07
Now at
"Downloading block 2,427,211 of 3,858,460" at 0407

Thats 25 blocks / hour. At a constant 10,0MB/s disk IO, 0.02 to 9Mbps on my network and 2GB RAM.

In short: Its going to take ~ 618TB of bandwidth, 2PB of disk i/o (so probably a few new disks as well) and 6,5 years for me to sync.

**Comment by RobQuistNL** [comment] 2017-06-12 02:27
I just renamed the geth folder to geth_bak2 (I did it before) and started the app again. Block downloading got fast up until 2,112 of 2,687,392.

Chain structure is still going quickly and both are increasing.

As I'm typing the blocks are downloading quickly as well. 

This time, 700MB RAM, 25% CPU (i7 7700k), 5mb/s disk and 35 mbps network.

Minute later at block 160,000 of 2,687,392 and chain structure 150,000 of 300,000 ( latter 2 are steadily increasing).

I used to have this before, and chain structure got up to like 32 million, after which it disappeared and the block download started going really slow. I wonder what will happen this time.

**Comment by matthewleising** [comment] 2017-06-12 10:55
I've been running the download nonstop for 3 days and am at 25%, 1,684,000 blocks to go with usually about 10-12 peers. At this rate it will take 10 days assuming it doesn't crash or my 5 year old unplugs the computer. Not the best UI in my opinion but none of the other ether wallets seem trustworthy to me so I'm going to stick this out in case it works

**Comment by sathishvj** [comment] 2017-06-12 11:03
It hasn't usually taken me that much time.  I recently tried setting up a new node from my office network while connected via an ethernet cable and it was very fast compared to what I did at home on a comparably slower wifi network.  Anyways, best of luck.

**Comment by RobQuistNL** [comment] 2017-06-12 14:09
![image](https://user-images.githubusercontent.com/1442796/27037855-8a2b3bd4-4f89-11e7-9f7b-03be4f6423ef.png)
12 hours in... Come on!!!

**Comment by nadimaj** [comment] 2017-08-30 17:21
This application sucks: https://www.youtube.com/watch?v=7bMANwuxx1k&feature=youtu.be

**Comment by RobQuistNL** [comment] 2017-09-11 14:12
I must say that the recent updates seem to have fixed the issues for me. It now syncs with a good speed.

**Comment by wtfiwtz** [comment] 2017-09-23 14:20
Check out this thread: https://github.com/ethereum/go-ethereum/issues/15001

**Comment by evertonfraga** [comment] 2017-09-28 19:49
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist

**Closed by evertonfraga** 2017-09-28 19:49 UTC
Labels: v0.8.10

**Comment by colevr1** [comment] 2017-12-06 11:33
you close the issue? well excellent

**Comment by keznerve** [comment] 2017-12-19 12:16
This is a problem for me also , when i run the light client my ETH goes to zero, why is that. So i tried running it as normal and i am at 17 percent after 12 hours. 

Any ideas i could use the myetherwallet but i am unsure exactly what to do.

**Comment by keznerve** [comment] 2017-12-19 12:20
Having the same problem on a Macbook pro with SSD , its taken 12hrs to sync 17 percent , what do i do , ive no idea about geth or much else...please can someone offer an alternative , maybe my Ether wallet but im not sure how that works exactly.

**Comment by nadimaj** [comment] 2017-12-19 12:23
Friends, we are all victims of being lured into downloading and installing ETH's "official" wallet. Ethereum is doing itself a terrible injustice by linking to this shit. I am just in the process of moving to Exodus and MyEtherWallet.

I will document my process for everyone and post it on YouTube. WTS!

**Comment by giantpune** [comment] 2017-12-20 04:54
I have to agree.  Being struck by this bug/poor performing wallet, I'm not feeling very confident about ethereum.  I could have walked 10 miles to the post office, bought a postal money order, filled it out, walked the 30 miles to the bus station, rode 200 miles to my friend's house and given him the money order and make it back home faster than ethereum wallet takes to sync.  

I feel embarrassed for whoever wrote this wallet.  This issue has been going on for a year now and its not fixed.

**Comment by ASDAlexander77** [comment] 2017-12-21 03:08
trying to sync my wallet. 3rd day no luck at all. Just watching how downloading chain structure is constantly growing and equals to 20 000 000 and I don't see the end

**Comment by nadimaj** [comment] 2017-12-27 13:17
If anyone is looking for a **safe alternative to Mist**, here's what I've discovered:

You can run MyEtherWallet locally and not have to ever send your key or type a password online. Download the offline version from here: https://github.com/kvhnuke/etherwallet (Click clone or download - the green button)

In the dist folder, launch index.html and import your wallet file from one of the top options. Your wallet type is JSON/keystore. Enter your private key password and et voila. You don't even need to be online. You can use etherscan.io to check any transactions you make. No blockchain to sync!

**Now, my tirade against Mist and Ethereum for tolerating this abysmal piece of software.**

Just google Ethereum mist problems and see how much noise there is out there. The UX around Mist is fraught with pain and confusion.

How can ethereum.org link to the Mist client on their home page? This client is not designed for the average user. It often needs CLI tweaks to make it run properly. The GUI which is supposed to be invoking GETH on start up, often ends up in massive sync loops but if you launch GETH first and sync up, then launch Mist, it's OK. WTF??? Currently a big percentage of the community is facing sync problems. The devs think they've cured it by designing a "Lite" client, which is still in beta (a year later). Lite appears in the CLI help as "depreciated" - wow, that's just crystal clear isn't it? Once enabled, you lose your wallet information because it doesn't look for the existing files. The noobs must freak at this point. You try to disable "Lite" client only to find you can't. There's no option. The only way is through a text file edit, not documented very well. Yeah, read that again.

Again, just follow me through with this to understand how poor the UX is.... say you're an existing full node user (because that was the default installation setting) and you've got a wallet with funds. You're having sync problems and decide to do away with the full node. The minute you switch on Lite client, Mist behaves like a different application disregarding your previous wallet files. This gives the impression your money is gone. Oh and you can't import an existing wallet either (option greyed out) so all you can do is transfer to a new wallet which you created inside Lite client (two applications in one, just you never get that impression).

Explain to me how this can be acceptable if we want ETH to become a true competitor? Why is this shit, the official choice of Ethereum? It makes no sense to me. If I wasn't semi computer literate I would've deleted my key files by mistake a long time ago in an effort to install and reinstall this client to make it work properly. I wonder how many got rid of important files only to then tell there friends Ethereum is unreliable, don't use it! Don't these guys want to make things easy? People are going to compare the ETH experience to the BTC or LTC experience. Those official wallet applications just work out of the box with no fuss. So why can't Mist? Mist is not fit for purpose, I urge the community to get it's act together to make something else the official wallet application. Just look at the way Exodus is designed. That's what people want in order to feel like they are doing something mainstream and not something extremely experimental and dangerous.

I'm yet to hear of any praises relating to Mist. Thanks for listening.

**Comment by dgn127** [comment] 2017-12-28 18:43
Yeah, I seem to be jumping around these threads all the time trying to find the magic key to fix this non-syncing issue. It wouldn't be so stressful if I didn't have tokens in my wallet, I don't want to lose them. I am trying to learn all I can about Ethereum so I know which files are vital and which ones I can rename so the sync process can start fresh. I couldn't believe that keeping all of the chaindata files would be so memory storage intensive. I hate to say that I am jumping ship, but once I finally figure out how to get my tokens out of this wallet, I will be deleting Mist, because in German Mist = shit and that's my experience with this piece of software. Of course maybe the developers are holding our tokens hostage by not letting us move them!!!

**Comment by keznerve** [comment] 2017-12-29 01:21
It took around 13hrs to run the geth-light client sync behind mist , it worked fine...i took out the chaindata file, when it was complete i threw it away, it then continued to run alot quicker. You just have to be patient , it took 13hrs to run 43,000,000 i think that was DEC , all the information related to it is on here. Just make sure you have around 38-40GB which is half the size of before.

**Comment by nadimaj** [comment] 2017-12-29 01:41
I think you're celebrating too early. It WILL break again. In my case at next startup

**Comment by scspijker** [comment] 2018-01-02 22:18
Just to let Googlers know, currently at 4.8 million blocks and 55m on the chain.
![screen shot 2018-01-02 at 23 15 11](https://user-images.githubusercontent.com/767645/34502297-2d7aa318-f013-11e7-8151-05304f0690d5.png)

**Comment by lowlanda** [comment] 2018-01-03 12:51
I got this far, after 6+ hours from scratch, and starting geth with --light. Can't win 'em all I guess lol.

Seriously though devs, please fix this sync issue, it REALLY shouldn't be this technical and difficult for users to engage in crypto-currencies and blockchain apps. I don't know anyone that would even consider delving into this world, which is sad, because it's a great world to delve into, if only it worked and didn't create financial stress and lack of confidence.

I have faith though :)

![eth](https://user-images.githubusercontent.com/20736001/34521093-0ce93218-f0e0-11e7-9d64-e7810ea61ff7.PNG)

**Comment by thelolagemann** [comment] 2018-01-03 18:17
I have now tried on 4 different computers, behind 8 different networks, tried with and without VPN, I have synced my clocks countless times, but the peer discovery is still fucked. On the fastest network I tried (around 500/250) it managed to find 3 peers, downloading on average 1 block every 5 minutes. I've tried the light client, and the fast client, and if I had a gigabit connection I would try the full chain sync. I've tried deleting the chaindata, manually added peers, and still nothing. If this was a new issue it wouldn't be too upsetting, however I was faced with the exact same issue almost exactly a year ago after I'd had mined a few eth and just wanted to store them locally. I ask around and some people have peers in the hundreds, but I can't even break past 5. Will be looking into alternatives until this has been sorted

**Comment by lowlanda** [comment] 2018-01-04 00:26
Can confirm nadimaj's workaround works.

I tried --fast after many attempts trying different things. Got sync'd, could see balance, but now I get "unable to connect to socket: timeout" errors when trying to send ether. Bloody hopeless..

**Comment by foen** [comment] 2018-01-04 13:23
https://github.com/ethereum/mist/releases
make sure you have the 64bit version if you run 64bit os

**Comment by nadimaj** [comment] 2018-01-04 13:39
#AbandonWare #WhereDoDevsGoWhenTheyDie #EthHasHit1000TimeToActLikeIt

**Comment by lowlanda** [comment] 2018-01-04 13:46
@foen, yes I've been using 64bit version. Worked last week, doesn't work this week! Might work again next week :)

Appreciate your input though, and fingers crossed devs fix it.

#NotMissingOutOnAlltimeHighEthPrice #WhereDoesMyBrainGoWhenItDiesAfterTryingTogetThisToWork

**Comment by Brendonwbrown** [comment] 2018-01-04 22:27
Synced Myst for a week until it finally caught up. Transferred in some ETH. Came back in 3 weeks and fired it up and had a "Ethereum Node Connection Error:'("

So I've been waiting for sync to complete since 16 hours ago. Not gonna hold my breath. Imagine the outcry if this were a legitimate technology people relied upon. Good thing it's just play money.

**Comment by Conrad-BlockFood** [comment] 2018-01-07 10:14
![ethereum wallet slow sync](https://user-images.githubusercontent.com/31185618/34648562-a380df56-f39b-11e7-839e-b033d902a933.png)

Almost there... I've been syncing for 4 days on an average connection. This is very slow and not a linear experience.

Do you know why the chain structure seems to start from scratch every time you interrupt the syncing process?

**Comment by nadimaj** [comment] 2018-01-07 10:27
Please read above posts, you are wasting you're time. Unless you're in the mining game, give this client up

**Comment by Conrad-BlockFood** [comment] 2018-01-07 10:29
@nadimaj Yes you are right. I've read the whole thread but I liked the idea of having a full node running using the official client... Too bad it's facing some much difficulty just to start.

**Comment by lowlanda** [comment] 2018-01-07 11:08
nadimaj's advice and instructions have kept me sane.

I'm retrying a full node sync atm, but not holding my breath.

**Comment by Evlos** [comment] 2018-01-08 16:44
![screen shot 2018-01-09 at 00 42 52](https://user-images.githubusercontent.com/517862/34681203-13f0cc2a-f4d6-11e7-9dbc-21ca437bed0a.png)

It is been 3 days, and I feel really desperate.

**Comment by m-deck** [comment] 2018-01-10 20:24
tried various things over the last 45 days to make mist work but have not been able to get a full sync. tried different computers, operating systems, fast mode, light mode. start geth first. none of the suggestions i've seen have worked. ended up doing a local install of 

https://github.com/kvhnuke/etherwallet

in order to move my ETH. i was done in <5 mins.

**Comment by cculianu** [comment] 2018-01-13 11:09
Hi -- I'm a developer with over 20 years' experience.  I've seen it all.  Never before have I seen software so horribly poorly written.

geth is the problem here -- the go-ethereum implementation.  It's like the devs never heard of performance tuning or worrying about performance.

Also the client sometimes just gives up and stalls indefinitely, requiring a restart.

It looks like a student project to me.

I've very dissatisfied with it.  I may give up on running an ETH full node completely and just use a wallet like Jaxx or something.

This is a joke.

**Comment by nadimaj** [comment] 2018-01-13 11:31
The disturbing thing is that the founders and chiefs of the Ethereum project do not give a shit about this situation. I have tried to approach them but nothing

**Comment by cculianu** [comment] 2018-01-13 11:37
I would be pretty ashamed of this software and would work to phase it out.

I'm going to give the C++ ethereum client a try after a few hours more.  Geth periodically gets stuck and needs to be stopped and restarted.

Maybe the C++ eth client is a little better.  One can only hope.

I agree -- it's a sad situation when they don't care at all.  If I were them I'd be pretty ashamed of this.

**Comment by patmoran** [comment] 2018-01-13 14:09
This is ridiculous.  I've battled the endless sync issue.  I finally decided to follow the developers recommendation to use the "experimental" beta light feature in Mist and now my wallet is stuck with one peer.  I've been running wallets for a year, including last night over night downloading ALL of the chain structure only to end up stuck 106 blocks behind the head.  Never had an issue with peers.  Now Mist can't find any.  The development team has insulted the entire eth community by brushing off this issue.

**Comment by dfalzetti** [comment] 2018-01-14 03:32
geth kept failing every 10 - 15 minutes so in windows i created a sync.cmd file with the following and that took care of it.



C:
cd "C:\Users\Dan\AppData\Roaming\Ethereum Wallet\binaries\Geth\unpacked"

:loop

 %@Try%

 call "geth.exe" --fast --cache=512 --datadir="D:\Ethereum-Wallet-win32-0-9-3"


 timeout 2

%@EndTry%
:@Catch
goto loop
:@EndCatch

goto loop

**Comment by evertonfraga** [comment] 2018-01-14 04:48
Guys, I understand the frustration while trying to use this software. 

Please keep in mind that sync is done via Geth, which repository is: https://github.com/ethereum/go-ehtereum

**Comment by keznerve** [comment] 2018-01-14 18:00
It seems to help if people post rough timings and disk storage needed, as i had to clear my computer as it was downloading the blocks. So any info like that is helpful.

**Comment by Kuzirashi** [comment] 2018-01-17 12:18
What the hell is wrong with this client? :( I downloaded blockchain 2 times already and it still downloads 11 millions of "chain structure". I'm terminating the process because it's a joke. Why in the first place it needs to download chain structure after download of all blocks is complete and why is this so bugged process? Downloading something and checking the data isn't out of range doesn't seem like 1 year of development complicated process - especially for crucial feature to work - syncing blocks.

**Comment by jalal1985** [comment] 2018-01-19 22:01
Totally Agree :)

**Comment by elie222** [comment] 2018-01-22 01:35
This is so painfulll. Any actually useful advice to get this fixed?

**Comment by wtfiwtz** [comment] 2018-01-22 06:39
@elie222 see https://github.com/ethereum/go-ethereum/issues/14647#issuecomment-335325502... note that the state entries are now in excess of 50M (maybe 70M?)

**Comment by wtfiwtz** [comment] 2018-01-22 06:56
@elie222 you can also try light mode... here are some more useful instructions:

https://github.com/ethereum/mist/issues/2749#issuecomment-359130980

**Comment by elie222** [comment] 2018-01-22 07:32
Thanks. I followed those instructions and each time I restart Geth it does the whole `Imported new state entries` from the beginning again. Leaving it for hours at a time.

**Comment by wtfiwtz** [comment] 2018-01-22 07:58
Yep unfortunately that is the case... it does a basic re-verification from the beginning :-/

**Comment by elie222** [comment] 2018-01-22 10:07
Doesn't move on from here unfortunately:
<img width="417" alt="screen shot 2018-01-22 at 12 07 07" src="https://user-images.githubusercontent.com/3090527/35215400-caaaf06c-ff6c-11e7-8340-6d9ab8e8f934.png">

**Comment by elie222** [comment] 2018-01-22 10:10
Apparently just extremely slow. Still only at 2.4 million after waiting hours:
<img width="1013" alt="screen shot 2018-01-22 at 12 09 16" src="https://user-images.githubusercontent.com/3090527/35215506-201390ea-ff6d-11e7-960d-36533051030a.png">

**Comment by Brendonwbrown** [comment] 2018-01-22 18:04
@elie222 I recommend you back up your keystore file, then load it into myetherwallet.io . Get as far away from this software as you can. https://ethereum.stackexchange.com/questions/946/how-to-backup-mist-wallets

**Comment by 4FH** [comment] 2018-01-23 06:07
![image](https://user-images.githubusercontent.com/35478599/35260242-5fde6db0-ffbf-11e7-9be7-ab005e21486f.png)
48 hours, can't download single block for 6 hours, just chain structure keeps increasing both sides with 10-30k gap. It is mesmerising... endless chase.. reminds me of Fantomas movies.

**Comment by wtfiwtz** [comment] 2018-01-23 09:49
@4FH the gap is the "pending transactions" during a particular point in time - e.g. transactions submitted for processing vs. transactions completed (with a receipt).

You will get to far in excess of 50M chain structures, as long as you don't restart Mist / geth.

**Comment by ChristBKK** [comment] 2018-01-23 16:41
Is there any solution on the horizon? :) I mean this is known now for weeks if not months.  FAST client e.g. doesn't work as well as it doesn't show all transactions.

**Comment by Evlos** [comment] 2018-01-24 03:37
BTW, Light Client is a joke, peer searching never end.

**Comment by 4FH** [comment] 2018-01-25 05:18
![image](https://user-images.githubusercontent.com/35478599/35371877-a4293832-014b-11e8-9a6d-6eb92527c3c9.png)

96hours. and going.. . i feel like im downloading the Internet.. :)

**Comment by kudiaborm** [comment] 2018-01-26 03:41
I'm also experiencing this issue. I'm not sure how so many people have this issue and no one has a solution.

**Comment by e10011972** [comment] 2018-01-26 07:53
I tried many times to connect to the client but i am in the same situation that mention above.
Is there any other software that we can use to access our Ethereum?

If so please can you send the link? I tried myetherwallet but i did not manage to figure out how to access my own account. I can create a new one but i dont know how to access the old one.

Tx in advance for your help

**Comment by cculianu** [comment] 2018-01-26 10:28
I think the conclusion we can all draw is this implementation of ethereum has serious performance problems.

There is a C++ ethereum full node implementation: "cpp-ethereum".  I haven't tried it yet.  Here's the github page: https://github.com/ethereum/cpp-ethereum

As is to be expected -- they don't provide binaries.  Maybe you can find them online.

I *expect* the C++ implementation to at least not have as bad a set of performance issues.  In general C++ programmers tend to write software that is more performance-critical -- simply because the language makes it painfully obvious to the programmer what is a slow and what is fast.  

Give it a shot.  I've given up on Ethereum for now.  I sold all my ETH and at this point am just chilling.

It's disconcerting that the recommended full node implementation of the #2 crypto is this bad. :/

Good luck!

**Comment by Brendonwbrown** [comment] 2018-01-26 17:13
> It's disconcerting that the recommended full node implementation of the #2 crypto is this bad. :/

It's not just disconcerting, but in my mind is indicative of greater issue. Ethereum team seems to want to race forward to add new features and compete among the many alts out there but can't be bothered to fix the recommended node implementation, backbone of the network.

**Comment by mtskg** [comment] 2018-01-28 04:18
I had this problem when using Rinkeby network and for me it was fixed by disabling "Sync with light client (beta)".

**Comment by michaelx2018** [comment] 2018-02-06 11:14
@4FH

on what number has it finished?

**Comment by michaelx2018** [comment] 2018-02-06 11:19
Anybody knows what is actual number when chain structure ends counting?

**Comment by rafaelosirs** [comment] 2018-02-07 07:39
If you are in a pinch and have to deploy a contract, you don't need the full node sync, just follow this simple steps instead (i found in a post and help me a lot):

1. Install https://metamask.io/ and
2. Navigate to https://remix.ethereum.org/

3. Click on settings -> choose your compiler (e.g. 0.4.19+commit.c4cbbb05). Note that optimization is unchecked.
4. Login to metmask and choose your network (i would suggest first testing using ropsten test network and using the buy button to get ETH from a free faucet)
5. Go back to the compile tab,
Delete the contents of the example contract,
Paste in your contract (it should auto compile).
6. Click on the run tab
If you contract have input data you have tu put that data on double quoute (").
Click on create.
7. Metamask will open, choose your gas price and click Submit to sign your transaction
Open metmask again, click on the transaction hash.
8. Once published. in etherscan go to the contract address and Click on Contract Code tab on etherscan, click Verify and Publish.
9. Set the name of the contract to the exact name as in remix, Compiler to the same exact version as in remix and set optimization to "No" if you didn't click it on remix in step 3.
You should now have a published contract, with source code on etherscan.

**Comment by 4FH** [comment] 2018-02-08 02:46
my sync finally completed around ~90 000 000  chain structures. Totally took a week.
After that wallet was struggling to be in sync. If for some reason (bad idea) you shut it down or restarted PC, and IMMEDIATELY launch it again, it will start syncing for few HOURS at least again.
At some point database got corrupted, and i decided to not to repair it, and removed it with "geth removedb" . Then I downloaded geth 1.7.3 and launched it. it start to sync and download blockchain again, but, this time it took only 24 hours or less. BLazingly fast compared to wallet nightmare.
Now i keep geth console open and see it syncing from time to time, and few errors from time to time,  but its ok. All other operations i do through another console window by "geth attach". Launching RPC for miner, checking balance etc. Havent tried to launch wallet yet as I dont need it. I think either 1.7.3 is better (wallet using his own earlier version it hides in appdata) .

**Comment by NotJoking** [comment] 2018-02-14 14:39
HELP - I installing the ethereum blockchain on my new laptop: 
From december 20th 2017 the sync is running. At this moment februari 14th 2018 i see file 6425793.ldb is downloading into the map chaindata. This map now contains 63787 items (117 Gb). Can anybody tell me when this thing will stop?? Its running now for almost 2 months!!  I just want to connect to my wallet

**Comment by rafaelosirs** [comment] 2018-02-15 12:45
@NotJoking  if you only want to connect to your wallet you dont need to sync the full node. you can use metamask instead. if need an example to connect metamask see this video https://www.youtube.com/watch?v=M5uq_Y41U-M   (is in spanish, but you can activate the subtitle). 

if need any help send me a email rafaelosiris@gmail DOT COM.

**Comment by paksv** [comment] 2018-02-15 20:02
After 1.5 weeks of fruitless attempts to download chain using "geth --cache=2048" on my HDD I ended up with purchasing a EUR115 samsung EVO 960 nvme SSD, got 10+ times speed increase and geth finally synchronized in just several hours.

**Comment by sg552** [comment] 2018-02-16 03:14
@rafaelosirs  you saved me lots of time.  thank you so much!  

by the way, my ethereum wallet kept synchronizing for days.  stopped at 99.99%.   a really shit software.

**Comment by zdrive** [comment] 2018-02-18 18:00
For those having this problem, it might be helpful to specify your operating system. So far I have only seen a few references to Macbook and Windows.

I've been trying to synch for months on Windows 10 without any luck... it keeps stalling after downloading a few thousand blocks. Meanwhile, yesterday I installed Ethereum Wallet (via go-ethereum AKA geth) on a laptop running Ubuntu 16.04 LTS, and synchronization was reasonably fast. This morning, I tried running both side-by-side, and Ubuntu started synching right away, while the wallet on Windows was stalled. So perhaps this is a problem with specific versions of the software, rather than a general bug.

**Comment by michaelx2018** [comment] 2018-02-22 12:26
Today I have downloaded new GETH 1.81,
updated and upgraded brew ,

I launched geth in light mode
& Ethereum Wallet

and Ethereum Wallet started in 5 minutes with all updated accounts and my balance.

awesome.

last time I was waiting 8 days non stop and it never synchronized

**Comment by keznerve** [comment] 2018-03-05 16:18
![screen shot 2018-03-05 at 16 15 07](https://user-images.githubusercontent.com/16297361/36985962-8f5798a4-2090-11e8-89c7-f715c6524cf5.png)


So after limited success , downloading the new geth i was hoping for the light client to work. I am now shut out completely (please see above). i hope it works in future.

**Comment by sg552** [comment] 2018-03-09 10:33
Hey buddies, please show your OS, I think this issue exists only in Windows?   

Please just let us know your OS is:  Windows, Linux or Mac.   and your wallet version. 

thanks

**Comment by wtfiwtz** [comment] 2018-03-11 00:56
See this issue for a detailed description of what is going on under the hood - https://github.com/ethereum/go-ethereum/issues/15001#issuecomment-370732526

**Comment by p3yot3** [comment] 2018-04-13 17:52
This software is absolutely 100% shit.

I run a plethora of wallets & have done for years - but this wallet is by far the worst one out there. Period. I've spent days trying to get this crap to sync. I've read every article I can find about the sync issues until my eyes bled & have tried every supposed fix or resolution - nothing works.

The only reason I'm trying to use this Ethereum crap is because one of my legacy coins went ECR20 & I needed to do a coin swap before I can trade them - but after days of frustration with this software I think I'll just accept the fact that Ethereum devs don't know what the fuck they're doing & my coins are lost.

Seriously. Fuck this useless dysfunctional Ethereum wallet crap. I'm done with it.

**Comment by rafaelosirs** [comment] 2018-04-14 01:32
p3yot3

What do you need to do, i left the mist because that software dosen't work, but i found another way to do the same. 

So explain what do you need to do and maybe we can look another solution.

**Comment by NotJoking** [comment] 2018-04-16 13:48
Just run Light version (from bat file) if you are not a crypto-nerd. I make every week a transaction. Therefore i deleted the old chaindata  and run the program again. The program makes a new chaindata. Afther about one hour i run my wallet and up i go.

Verstuurd vanaf mijn iPhone

Op 15 apr. 2018 om 18:36 heeft p3yot3 <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


@rafaelosirs<https://github.com/rafaelosirs>

You're right, it absolutely doesn't work. The only cure I found was to get rid of it completely (including the 70+Gb of useless data it tried to download) & use the offline myetherwallet version. Problem solved in 2 minutes.
I seriously can't believe that this software was even released, let alone recommended. If this is the best software Eth devs can come up with, the project is doomed.
