### ISSUE TITLE
wallet contracts save on my local

### ISSUE THREAD

**Issue by nav1d** [ethereum/mist#2856] opened 2017-07-29 21:46 UTC
``````
Version: `0.9.0`
OS & Version: windows
Node type: `eth/geth`
Number of blocks synchronized: 4091980
``````
Hi,
why these simple wallet contracts doesn't save on my client? each time when i open my ethereum-wallet, wallet contract removed so i should add it manually again by its address.
is this normal?

**Comment by Malte-K** [comment] 2017-08-02 15:26
Yes, i have the same Problem. Can someone help please?

**Comment by domibarton** [comment] 2017-08-13 20:46
Same here, but with Mac OS X and `0.9.0`

**Comment by evertonfraga** [comment] 2017-08-18 23:41
Duplicate of #2823. 

Please refer to this comment for a temporary solution:
https://github.com/ethereum/mist/issues/2823#issuecomment-323465126

Thanks for reporting.

**Closed by evertonfraga** 2017-08-18 23:41 UTC
Labels: duplicate, v0.9.0
