### ISSUE TITLE
Copy address to clipboard not functioning 

### ISSUE THREAD

**Issue by frankwit** [ethereum/mist#817] opened 2016-06-14 16:05 UTC
Copy address to clipboard not functioning 

Node type: geth/eth
OS: osx 10.10..5
Network type: main/test
Mist version: 0.0.0

:

-
[node.log 2.zip](https://github.com/ethereum/mist/files/314381/node.log.2.zip)
![screen shot 2016-06-14 at 18 01 44](https://cloud.githubusercontent.com/assets/19873463/16050091/9339c378-325a-11e6-9be6-e300ce965239.png)

**Comment by luclu** [comment] 2016-06-14 16:47
Thank you for reporting @frankwit. This issue will be solved in the next release.
I will close this as a duplicate of https://github.com/ethereum/mist/issues/650.

**Closed by luclu** 2016-06-14 16:47 UTC
