### ISSUE TITLE
contracts and history gone, after downloading new version

### ISSUE THREAD

**Issue by damgcrypto** [ethereum/mist#2885] opened 2017-08-04 13:54 UTC
``````
Version: `0.9.0`
OS & Version: osx
Node type: `eth/geth`
Number of blocks synchronized: 0
``````
downloaded new version as directed when starting up wallet. allowed full sync before quitting wallet and updating, updated, restarted, wallet balance was there, contracts, tokens and history of transactions all gone

**Comment by Roister01** [comment] 2017-08-05 07:50
Help! This has happened to me too. Since updating to v0.9.0, and allowing everything to synchronise, my tokens are no longer there. My ether balance is zero. There are records of transactions etc, which illustrate the balances that should be there, and also my token watch lists are still there, but no tokens in any of them, they are grayed out. What should I do?

**Comment by evertonfraga** [comment] 2017-08-19 14:03
Duplicate of #2823.

Please refer to this comment for instructions:
https://github.com/ethereum/mist/issues/2823#issuecomment-323465126

**Closed by evertonfraga** 2017-08-19 14:03 UTC
Labels: v0.9.0
