### ISSUE TITLE
0.8.0 Mist crashes on OS X

### ISSUE THREAD

**Issue by whitj00** [ethereum/mist#941] opened 2016-07-08 16:51 UTC
OS: osx 10.11.5
Mist version: 0.8.0

whit:~ whit$ /Applications/Mist.app/Contents/MacOS/Mist
[2016-07-08 09:49:48.985] [INFO] main - Running in production mode: false
[2016-07-08 09:49:49.051] [INFO] main - Starting in Mist mode
[2016-07-08 09:49:49.146] [INFO] Windows - Creating commonly-used windows
[2016-07-08 09:49:49.147] [INFO] Windows - Create secondary window: loading, owner: notset
[2016-07-08 09:49:49.245] [INFO] updateChecker - Check for update...
[2016-07-08 09:49:51.860] [INFO] Windows - Create primary window: main, owner: notset
[2016-07-08 09:49:51.872] [INFO] Windows - Create primary window: splash, owner: notset
[2016-07-08 09:49:52.310] [INFO] ipcCommunicator - Backend language set to:  en-US
[2016-07-08 09:49:52.346] [INFO] Sockets/node-ipc - Connect to {"path":"/Users/whit/Library/Ethereum/geth.ipc"}
[2016-07-08 09:49:52.774] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2016-07-08 09:49:53.779] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2016-07-08 09:49:54.784] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2016-07-08 09:49:54.907] [ERROR] updateChecker - Error checking for update TypeError: Invalid Version: 0.8
    at new SemVer (/Applications/Mist.app/Contents/Resources/app.asar/node_modules/semver/semver.js:293:11)
    at compare (/Applications/Mist.app/Contents/Resources/app.asar/node_modules/semver/semver.js:566:10)
    at Function.gt (/Applications/Mist.app/Contents/Resources/app.asar/node_modules/semver/semver.js:595:10)
    at got.then (/Applications/Mist.app/Contents/Resources/app.asar/modules/updateChecker.js:49:20)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[2016-07-08 09:49:55.770] [ERROR] Sockets/node-ipc - Connection failed (3000ms elapsed)
[2016-07-08 09:49:55.771] [WARN] EthereumNode - Failed to connect to node. Maybe it's not running so let's start our own...
[2016-07-08 09:49:55.772] [INFO] EthereumNode - Node type: geth
[2016-07-08 09:49:55.772] [INFO] EthereumNode - Network: main
[2016-07-08 09:49:55.772] [INFO] EthereumNode - Start node: geth main
[2016-07-08 09:49:55.786] [ERROR] main - UNCAUGHT EXCEPTION { Error: spawn ENOTDIR
    at exports._errnoException (util.js:949:11)
    at ChildProcess.spawn (internal/child_process.js:302:11)
    at exports.spawn (child_process.js:379:9)
    at logRotate (/Applications/Mist.app/Contents/Resources/app.asar/modules/ethereumNode.js:385:30)
    at /Applications/Mist.app/Contents/Resources/app.asar/node_modules/log-rotate/index.js:84:11
    at FSReqWrap.oncomplete (fs.js:117:15) code: 'ENOTDIR', errno: 'ENOTDIR', syscall: 'spawn' }
[2016-07-08 09:49:55.804] [INFO] main - Defer quitting until sockets and node are shut down
[2016-07-08 09:49:55.804] [INFO] Sockets - Destroy all sockets
[2016-07-08 09:49:55.805] [INFO] Sockets/7 - Disconnecting...
[2016-07-08 09:49:55.806] [INFO] Sockets/node-ipc - Disconnecting...
/Applications/Mist.app/Contents/Resources/app.asar/node_modules/solc/soljson.js:1
(function (exports, require, module, __filename, __dirname, process, global) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(fiwhit:~ whit$

**Comment by luclu** [comment] 2016-07-08 18:34
I am sorry to hear about these issues which are caused by some broken builds. Please try to redownload - the checksums have been updated accordingly.

Closed as duplicate of https://github.com/ethereum/mist/issues/940.

**Closed by luclu** 2016-07-08 18:34 UTC
Labels: duplicate

**Comment by jmlubin** [comment] 2016-07-09 17:33
Even the most recent build for OS X is crashing (not fully starting up) for a few of us at ConsenSys.

**Comment by luclu** [comment] 2016-07-09 22:47
Hi Joseph, what kind of errors do you guys get? Could you post some logs or excerpts?
