### ISSUE TITLE
Mist on Mac OS Sierra - Wallet creation stuck in creating step

### ISSUE THREAD

**Issue by rohanagarwal** [ethereum/mist#2935] opened 2017-08-13 19:40 UTC
``````
Version: `0.9.0`
OS & Version: mac os 10.12.5
``````

In the Mist application, I tried creating a Wallet Contract. The wallet says "Creating..." and has been for the last few days.

I found the transaction on etherscan here: https://etherscan.io/tx/0xa9a0e4c9e588e4e4bb1ef2e75c2709ef19f01f11411d91eeca1d5438ba7f7d60

Any ideas on why it still says creating and what the fix here is? I've tried closing and re-opening the app but it stays in the same state. Looks related to https://github.com/ethereum/mist/issues/1573 but no solution was mentioned in that issue.

I've uploaded a zip of the node logs.

[node-logs.zip](https://github.com/ethereum/mist/files/1220704/node-logs.zip)

Appreciate your help!

**Comment by evertonfraga** [comment] 2017-08-17 00:54
Duplicate of https://github.com/ethereum/mist/issues/2845.

Please follow link for quick fix. It's on our radar and should be fixed soon. Thanks

**Closed** 2017-08-17 00:55 UTC
Labels: duplicate, v0.9.0

**Comment by DecentralizedIT** [comment] 2017-09-13 10:23
A quick workaround

Open:
Develop -> Toggle developer tools -> Ethereum Wallet

In the console:
Wallets.find().fetch()
Wallets.remove("_id")

Done!
