### ISSUE TITLE
OS X - Wallet crash on startup: geth

### ISSUE THREAD

**Issue by Smiggel** [ethereum/mist#179] opened 2016-02-16 12:20 UTC
I downloaded the latest release of the wallet, but I can not start it. It crashes on executing the process Geth - /Applications/Ethereum-Wallet.app/Contents/Resources/node/geth/geth

**Comment by frozeman** [comment] 2016-02-16 13:50
duplicate of #163

**Closed by frozeman** 2016-02-16 13:50 UTC
