### ISSUE TITLE
"Wrong Password" when sending ERC 20 token with no Ether Balance

### ISSUE THREAD

**Issue by fort9520** [ethereum/mist#2773] opened 2017-07-16 14:58 UTC
``````
Version: 0.8.10
OS & Version: OSX Yosemite
Node type: Notsure
Number of blocks synchronized: 100%
``````
I am getting the "wrong password" notification when I am trying to send my ERC 20 tokens to the ethereum wallet on my new computer. I have sent ether before from this very same wallet, and I know the password is correct as I've written it down in a notebook. Am I getting this notification because I have no ether in the account to cover the transaction fees?

Thanks

**Comment by ihatecreatingaccounts** [comment] 2017-07-16 15:08
yea, its common error and nothing to be done, the software changes your password so you loose all your ether. just dont use ether anymore, its shit.
lost 500€ bc of "wrong password", which is definetly right

**Comment by fort9520** [comment] 2017-07-16 18:06
So, it's not because I had no ether in the account. I just deposited some ether from another account to cover transaction fees. What the hell could have happened? Anyone have an idea?

I wrote the password down, and I sent ether from this wallet a few times, even recently to participate in an ICO.

**Comment by ihatecreatingaccounts** [comment] 2017-07-16 18:15
here is what i think happened on me: i create my first account, skip the password, let it synch, then receive my ether, it says do password! so i do, somehow it gave me a mnethingyphrase, well i wrote it down.
i then send my ether to my mobile wallet, it asks for the pw, i copypaste it, works fine, all good. 
2-3 weeks pass, etherwallet software doesn download chain properly, so i reinstall, had the wallets backed up, all good. 
software starts, no account bc it wasnt put there. then i create a new one (it kinda happened) with another password, short and simple. i then import my old wallet. and send my mobile balance back.
since then, money is stuck bc of "wrong password". neither of them work. reinstalled many times over, nothing works. somehow the password is even wrong when i use myetherwallet.
so... the software somehow fucks your files. im happy i just lost 3 ether, as theyre dropping more i just book it as bad investment and will never return to ether, as its lightyears away from bitcoin and honestly, its just a fucking scam.

**Comment by fort9520** [comment] 2017-07-16 18:23
I also had to re-sync as I got a new computer. Backed up the wallet file and ported over. Fully synced now, but password is wrong. It can't be wrong because I wrote it down and have sent ether from it recently. I've spent all day trying to figure this out... pulling my hair out.

**Comment by ihatecreatingaccounts** [comment] 2017-07-16 18:44
i feel you, but i dont know where else to go. i tried https://github.com/ryepdx/pyethrecover but no success, also myetherwallet didnt let me access it either, but i suggest you to try this before giving up.

my last option i suppose is to mail my wallet + passwords i assume possible to some trusted dev, but theres the problem, i dont trust them :)

**Comment by fort9520** [comment] 2017-07-16 18:52
Thanks man. Do you know where I can find instructions to run/install that for a complete noob

**Comment by ihatecreatingaccounts** [comment] 2017-07-16 19:06
yeah, sure why not ^^ but did you check myetherwallet first? its the easier approach and i saw people had success with that. ALSO you can try to manually unlock your account, for that use GETH. i had to download standalone geth, then, when etherwallet running, do in CMD geth attach and it will open a console with geth running. there you can use "personal.unlockAccount("id")" to be prompted for the pw and enter, maybe works.

for the cracker you need python, version 3 didnt work for me, so i installed version 2.
after that run python, do pip install bitcoin and pip install joblib as you will need them.
then download the pyeth recover, put your keystore file in the folder and a textfile with passwords you wanna try.
now go to cmd, cd into your pyethrecover and do python pyethrecover.py -w wallet.json -f password.txt
press enter. 
thats how far i came, but couldnt find my pw. maybe it helps you

**Comment by Madebyivan** [comment] 2017-12-01 17:16
I never entered any password and I ask for the letter to get the ethers, this is a scam, a big scam, do not ask for the password when putting money or when starting ... I've been developing for 20 years, so the story that forget my password does not filter, I need a solution, I see that there are many people more affected, I install the application that you have on the web, which nothing more to install than I have to update, it seems unprofessional on your part ...

**Comment by evertonfraga** [comment] 2018-02-01 20:14
This seems like a duplicate of https://github.com/ethereum/mist/issues/3513.

I'm closing this for now, please follow the discussion link for updates.

**Closed by evertonfraga** 2018-02-01 20:14 UTC
Labels: Status: Triage, v0.8.10
