### ISSUE TITLE
Mist Couldn't connect to node error

### ISSUE THREAD

**Issue by jordimorris** [ethereum/mist#715] opened 2016-05-25 20:11 UTC
Mist has been working fine for many weeks until today. 
The following window appears on 6.2 and 7.4

What can I do to have the full node up and running again?
thanks
![image](https://cloud.githubusercontent.com/assets/10827671/15554635/7774305a-22c5-11e6-8d65-3bcc566a659e.png)

**Comment by oneala** [comment] 2016-05-27 13:50
i have the same problem for about 2 weeks and still no fix.. i have tried anything..

**Comment by bas-vk** [comment] 2016-05-30 15:21
Could you download and try the latest geth version? You can find it [here](https://github.com/ethereum/go-ethereum/releases). Download it and start it with `geth.exe` (no arguments). You should see simular output as in your screenshot. If everything works as intended something like `IPC endpoint opened...` will appear. In that case you can try to start the wallet (version 0.7.4) and see if that works for you.

If the last line is the same as above and geth seems to be stuck for a minute hit control-c to stop geth. Start geth with `geth.exe --nat=none` and see if it still stalls. If it starts but you don't get any peers stop geth again and restart geth with `geth.exe --nat=extip:<YOUR_PUBLIC_IP>`.

Please let us know if you need more help or if its working for you.

**Comment by oneala** [comment] 2016-05-30 19:49
@bas-vk i just downloaded geth and started it and i think is running and downloading the blocks, here is a screenshot https://gyazo.com/c15b7e09d032defa04b383328c7749c8

Should i leave it to finish downloading or i can close it and start the wallet?

thanks!

**Comment by datashaman** [comment] 2016-05-31 05:47
leave that running in one window and start the wallet. usually the wallet starts that process on its own if it's not running, but I've had issues with the latest versions not being able to connect to the geth process. It looks like there's a very long time after report that synchronization has started and the next line is output. I think the app is hitting a timeout.

**Comment by oneala** [comment] 2016-05-31 20:11
@datashaman thanks! right now i am using geth.exe to update chaindata also i am able to start the wallet. ill post an updated once everything is done. 

thanks!

**Comment by bas-vk** [comment] 2016-06-01 07:03
Thx for reporting back, glad dat it did work for you.
@jordimorris, could you try the same?

**Comment by jordimorris** [comment] 2016-06-01 07:21
@bas-vk after re-installing, purging cache and re-downloaded the whole chain data it works that well that I don't dare to touch it. 6.2 up and running and won't upgrade until a better version is relesed. Good to keep following this post!

**Comment by luclu** [comment] 2016-06-01 23:50
Thanks @jordimorris. 
I will close this for now but feel free to.. you know the drill.

**Closed by luclu** 2016-06-01 23:50 UTC
