### ISSUE TITLE
Bitcoins lost(?) after incorrect transaction (shapeshift)

### ISSUE THREAD

**Issue by MennoRosmalen** [ethereum/mist#683] opened 2016-05-22 10:51 UTC
Just transferred BTC to my wallet, but I think I made a mistake by putting in the same amount BTC as ETHER. So, let's say, I transferred 0.10 BTC and received 0.10 ETHER. What can I do to regain my lost amount? (sorry, also quite new with this)

**Comment by luclu** [comment] 2016-05-22 16:40
duplicate of: https://github.com/ethereum/mist/issues/684

Please try to get in contact with shapeshift as they are able to trace your transaction. They can provide meaningful insides into this. Please give me a small pingback on the outcome!
Also look at this one: https://ethereum.stackexchange.com/questions/1717/how-to-recover-btc-that-wasnt-converted-into-eth-by-shifty-via-mist

**Comment by luclu** [comment] 2016-05-22 17:03
I created some pool with tips on this: https://github.com/ethereum/mist/issues/687

**Closed** 2016-05-22 18:55 UTC
