### ISSUE TITLE
New mist version: entire blockchain to sync again!!!!!

### ISSUE THREAD

**Issue by HuguesDohmen** [ethereum/mist#1707] opened 2017-03-05 19:07 UTC
#### System information
``````
Version: `0.8.9`
OS & Version: windows 10
Node type: `geth1.5.9`
``````

If possible add the following to your report:

- Screenshots/
![afbeelding](https://cloud.githubusercontent.com/assets/23154595/23590338/0bf38b5c-01de-11e7-86e8-c5c601baa4cb.png)

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot
![afbeelding](https://cloud.githubusercontent.com/assets/23154595/23590356/88b19238-01de-11e7-9f48-a69ca2772e6c.png)

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files 
 

[MistNODELOGXFILES.zip](https://github.com/ethereum/mist/files/819647/MistNODELOGXFILES.zip)

**Comment by luclu** [comment] 2017-03-06 15:01
@HuguesDohmen I'm sorry for the inconvenience.
Unfortunately there was a breaking change to the config paths while refactoring our build system during the `0.7.x` -> `0.8.x`.

**Comment by luclu** [comment] 2017-03-08 17:20
I will close this as a duplicate of https://github.com/ethereum/mist/issues/1708

**Closed by luclu** 2017-03-08 17:20 UTC
