### ISSUE TITLE
Ehtereum Wallet on windows completely uselless, eats up 10 GB of memory is and completely inresponsive.

### ISSUE THREAD

**Issue by Guido1234** [ethereum/mist#732] opened 2016-05-28 14:37 UTC
Node type: geth/eth
OS: linux/windows/osx
Network type: main/test
Mist version: 0.0.0

Please check the already existing issues, before creating an issue. We would like to keep duplicates at a minumim.
Read the https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide first, where we summarized a few of the known issues.

Add the following to issue, when possible:

- Screenshots
- Check the console, of Mist (CTRL/CMD + ALT + i) and take a screenshot.
- Log files (as ZIP archive)
-   osx: ~/Library/Application Support/Mist/node.log (Open Home folder > Show View Options > Show Library Folder)
-   windows: %APPDATA%/Roaming/Mist/node.log
-   linux: ~/.config/Mist/node.log

**Comment by Guido1234** [comment] 2016-05-28 17:13
![ethereum wallet memory usage](https://cloud.githubusercontent.com/assets/19624421/15628711/500380d0-2508-11e6-8399-bac7df0e06dd.PNG)

**Comment by shawn-j** [comment] 2016-05-30 03:57
the same thing happened to me after I unlocked an account..  mist got really slow, started sucking up all my ram.  I took this screenshot at 600MB; it eventually used up everything.  when I opened the console, mist started running fast again.

![untitled](https://cloud.githubusercontent.com/assets/19638200/15639394/0035f60e-25f9-11e6-8dd5-d5fbe49366a7.jpg)

**Comment by luclu** [comment] 2016-05-30 13:32
Thank you for reporting! 
I will close this issue as it is a duplicate of https://github.com/ethereum/mist/issues/726.
Please feel free to append any new/missed out information over there.

**Closed by luclu** 2016-05-30 13:32 UTC
