### ISSUE TITLE
Your stub contract has no original wallet address set, please restart your wallet!

### ISSUE THREAD

**Issue by stefek99** [ethereum/mist#51] opened 2015-10-15 07:11 UTC
```Version 0.3.1 (0.3.1)```

> Your stub contract has no original wallet address set, please restart your wallet!

I restarted, still occurring.

From readme:

> Currently you need an instance of `geth` running when you want to use the wallet.

It seems like running ```geth``` helps.

----

You probably know better what is happening and how to circumvent it.

**Comment by frozeman** [comment] 2015-10-15 19:03
Did you sync you chain before?

**Comment by ReidCoin** [comment] 2015-10-19 21:16
I am getting the same error on my MacBook OSX. I have Ether in 2 of 2 accounts. 2 I created with the command line in Geth... and 2 I created with the Ethereum-Wallet App. In the Ethereum-Wallet App it will not show any accounts even though it creates them (2 of them). 
With the Mist & Meteor DApp Wallet when I "add wallet" under: CONTRACT BASED WALLETS... Follow the steps... then I get the error [above]: Your stub contract has no original wallet address set. 
![eth_error](https://cloud.githubusercontent.com/assets/6446459/10591542/555a4e8c-767c-11e5-8548-e09017777f99.png)

Example 1 [ Mist & Meteor DApp Wallet ]:
![eth_command_line_wallet](https://cloud.githubusercontent.com/assets/6446459/10591580/7e21aa7c-767c-11e5-902d-a19a76b1b9a3.png)
<br>
Example 2 [ Ethereum-Wallet App ]:
![ethereum-wallet - errora](https://cloud.githubusercontent.com/assets/6446459/10591598/98433e8e-767c-11e5-95a3-bfee96f428d8.png)
<br>
If anyone can help with a way to fix either, please let us know. I am quite certain that they are the same issue though (hopefully fix one, fix both). Everything else works fine so far...

**Comment by frozeman** [comment] 2015-10-20 13:50
I will look into this, thanks for posting such detailed screenshots.

**Comment by frozeman** [comment] 2015-10-20 15:29
I assume you have a a few errors in your console, could you open it? Menu->develop->...
You're on block 0 still, this could cause some issues i believe

**Comment by ReidCoin** [comment] 2015-10-20 19:09
Sure I'm new to Ethereum's Command Line "Frontier". If you could just give me details of what to do ill try my best. For example, when you say Menu-> develop-> are you talking about the Ethereum-Wallet? Because I don't see Menu-> develop-> in the Terminal...

**Comment by frozeman** [comment] 2015-10-20 19:22
GO to the wallet menu on the top, click on develop and then Toggle the developer tools to open the wallet/browser console

Look there for the errors.

But the problem will be gone if you sync you node to the latest block.

**Comment by ReidCoin** [comment] 2015-10-20 19:27
So how do I get the Blockchain to download correctly? 
You know currently this is the Blockchain Readout:
I1020 14:22:17.357272    1363 chain_manager.go:661] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 17.893368ms. #413727 [dfee7330 / dfee7330]
Also, I think part of the problem is that the accounts are locked and I cannot unlock them (Even though I have the passwords). It tells me to start Geth using this command: $geth --rpc --rpccorsdomain "http://localhost:3000" --unlock <Account>. Now I assumed it meant the accounts from $geth account list so I typed in: $geth --rpc --rpccorsdomain "http://localhost:3000" --unlock 0. (My assumption it would unlock the account on the list named #0. Whats strange is it actually worked and ask for my password for a few times, now it doesn't ask for my password, only says (and inputs a password which Is not anything close to my password): 
Unlocking account 0 | Attempt 1/3
Passphrase: I1020 14:17:49.124777 [I changed that passphrase readout in case it somehow is a passphrase that works I am not aware of... So that is not the exact passphrase it automatically enters for me now]. But the point is, It no longer ask for the password. 
Am I entering the Account in correctly? Do I enter the #0, #1, #2, #3, #4 (minus the number) or should I enter the output from the $geth account list; within {   }?

**Comment by ReidCoin** [comment] 2015-10-20 19:36
Okay so here are the pics of the wallet/browser console from Ethereum-Wallet (I assume thats what you meant). <br>
![thereum_wallet1](https://cloud.githubusercontent.com/assets/6446459/10618831/bd48d28c-7737-11e5-91fa-4d7945d67152.png)<br>
![thereum_wallet2](https://cloud.githubusercontent.com/assets/6446459/10618832/bd53e8b6-7737-11e5-9bb2-0001888d111d.png)<br>
![thereum_wallet3](https://cloud.githubusercontent.com/assets/6446459/10618833/bd5a7442-7737-11e5-9996-d580a2884b8a.png)<br>
You know I've been in this wallet/browser console before and theres been ALLOT more than 3 error messages. But this is what its showing as we speak.

**Comment by frozeman** [comment] 2015-10-20 20:27
Is it possible that your geth node is old? Could you just start the wallet without any node started before?
The wallet will come with its own node.

**Comment by ReidCoin** [comment] 2015-10-20 21:01
I suppose anything is possible, I haven't run an update on 'nodes' ever (don't know how). How would I do such a thing? I have tried starting the Ethereum-Wallet without Geth running before and it wouldn't do anything... Is the a certain way to do this? 

Also (just to be clear) are you talking about starting the Ethereum-Walet or the Mist & Meteor Wallet without any nodes started?

(By the way I figured out how to unlock the accounts and have added two more Contract Based Wallets. Should all these account be showing up in the Ethereum-Wallet App?)
![localhost_wallet_working](https://cloud.githubusercontent.com/assets/6446459/10620928/473d01c4-7743-11e5-93b3-6db5aa746814.png)

**Comment by ReidCoin** [comment] 2015-10-20 21:21
Another curious thing. Why are there "0 Peers" and the Error "Cannot read property 'startingBlock' of undefined" seems strange. There are 25 Peers and 400,000+ Data Blocks on the Mist & Meteor Wallet. 
![thereum_wallet-questionablethings](https://cloud.githubusercontent.com/assets/6446459/10621309/92c0252a-7745-11e5-935a-c2ca7b3ad11b.png)
Also why can't it read/connect to the 'startingBlock'?
<br>
This is the most interesting thing I found though... Look at this:
![thereum_wallet-accounts](https://cloud.githubusercontent.com/assets/6446459/10621425/69c81500-7746-11e5-98b5-ef5ffb9fff16.png)<br>
There are 3 of the accounts... Yet is says "false". I mean this is very confusing to me but hopefully you can make heads or tails from it...

**Comment by ReidCoin** [comment] 2015-10-20 22:32
So this is what happened when I try to start the new Node just with the Ethereum-Wallet:
![ethereum-wallet-node_starting](https://cloud.githubusercontent.com/assets/6446459/10622891/d63d9a58-774f-11e5-9073-789625ae77d7.png)<br>
![ethereum-wallet - ipcpath](https://cloud.githubusercontent.com/assets/6446459/10622897/df2e6c32-774f-11e5-99fc-cad8d8a4ddec.png)
<br><h3>My --IPCPATH seems to be perfect; take a look:</h3>
![mimocomroot- ipcpath](https://cloud.githubusercontent.com/assets/6446459/10622911/fbe7b022-774f-11e5-91dd-301e4483e10a.png)
<br>That was a photo taken before I ran the Geth command [regardless if it said it was correct or not]. So I ran:
$ geth —ipcpath /Users/MimocomRoot/Library/Ethereum/geth.ipc
Then tried to open Ethereum-Wallet alone to hopefully create a new node... I got the same error message as the photo above.

**Comment by frozeman** [comment] 2015-10-21 11:30
Ok it seems you have a synced node, but when you start the wallet it can't use it. And it doesn't run its own either. 

I assume something is fishy with the IPC for you.
Could you tell me which geth version you have? you can see that when you start geth.

**Comment by ReidCoin** [comment] 2015-10-21 19:47
<h4>So this is my version of geth:</h4>
![mimocomroot_ _geth_ _191x48_and_mimocomroot_ _bash_ _80x24](https://cloud.githubusercontent.com/assets/6446459/10648157/86a9d6e2-7802-11e5-8125-fd202d351d27.png)
<br>Starting Geth/v1.1.0/darwin/go1.5

**Comment by ReidCoin** [comment] 2015-10-21 21:54
Okay, so I thing I found the answer to my question "is that the correct version". At the url:
https://build.ethdev.com/builders/OSX%20Go%20master%20branch/builds/-1 

It mentions that Geth VERSION, cmd/geth: version 1.2.3 
exists... My question is:
- How do I update without messing up the Geth Accounts and Wallets I already have that work with Meteor & Mist.
also...
- I found a Mist.dmg that I downloaded and put in my Applications. When I open it is closes immediately. What does this Mist App do thats different from the one I installed via Command Line?

**Comment by ReidCoin** [comment] 2015-10-21 22:34
I had an issue while installing the $ brew update && brew upgrade:

Warning: EVMJIT needs the latest version of LLVM (3.7 or above), currently only available with --HEAD. If an older version was already installed or it did not install automatically, make sure to install it with `brew install llvm --HEAD --with-clang`
==> cmake -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FLAGS_RELEASE=-DCMAKE_INSTALL_PR
==> make
==> make install

Error: No such file or directory - test/testeth
_____________End Output_____________________________________________________
<br>Thats weird right? Im going to keep trying things all night... 

If "anyone" can please help me with upgrading my Geth Version from v1.1.0 to version 1.2.3 (or most current) please help me...

**Comment by ReidCoin** [comment] 2015-10-21 23:44
So I figured out how to get the Geth Updated:
![go-ethereum-master_ _geth_update_v1 2 3](https://cloud.githubusercontent.com/assets/6446459/10653052/6db2998e-7821-11e5-9db2-c27f37ac37b2.png)
I am about to try to run the Ethereum-Wallet with out any nodes running but this happened when I opened my Mist & Meteor Wallet:
![fullscreen_10_21_15__6_32_pm](https://cloud.githubusercontent.com/assets/6446459/10653296/c39f5ef2-7823-11e5-9551-6d402f2d460a.png)
I don't quite understand what that means...

**Comment by ReidCoin** [comment] 2015-10-22 01:01
Okay; so my Meteor Wallet has gone to 0 ETH all my accounts are 0.
![fullscreen_10_21_15__6_32_pm](https://cloud.githubusercontent.com/assets/6446459/10654258/ae6e9430-782d-11e5-89ca-cdfb9314617e.png)
It gave me a message that I needed to send 1 ETH to a new Address so it could create a Stub Contract Account and that I was on Testnet? Am I supposed to be on TestNet?<br>
I just also found the reason that the Ethereum-Wallet isn't working on it Node. It seems I have to use command:
<h4>$ build/bin/geth to get it to open Version 1.2.3 </h4>

So I suppose there is no way the Ethereum-Wallet is opening geth with $ build/bin/geth
Im guessing the way I installed (or tried to install the newest geth version wasn't the correct way... any suggestions?

**Comment by ReidCoin** [comment] 2015-10-22 03:44
Is there a way to "Uninstall" everything? I'd like to start over from the beginning (unless you think there is a easy way to fix this). Honestly though, I think if I knew how to uninstall everything and then knew where to start correctly it could be a whole lot simpler in the long run...

**Comment by frozeman** [comment] 2015-10-22 09:02
To update you can simply run the line from the ethereum.org website:
`bash <(curl https://install-geth.ethereum.org -L)`

I'm not sure what is going wrong on your side, i can offer you to make a skype session with screen sharing so we can figure out whats wrong on your end.

Basically your account are in `~/Library/Ethereum/keystore`, so keep them safe. You could try to remove the chainData and other folders besides the keystone and re-sync from scratch.

The wallet data is here `~/Library/Application Support/Mist`, if you don't have any wallets created or important stuff, just delete this folder.

**Comment by frozeman** [comment] 2015-10-22 09:27
Can you try the version which will be released soon:
https://www.dropbox.com/sh/8mu15dkxlj8phu4/AACfurTFTyAg0k22g39Vgj1ka?dl=0

**Comment by ReidCoin** [comment] 2015-10-22 15:49
Thanks so much. I am doing the update as we speak. See I haven't known how to update correctly. I downloaded the new wallet but I want to try the old one after the update. 
Actually It just finished and said it updated to V1.2.0

Let me ask you this, do you think I need to update other parts of my install? for example I was reading last night and I have cpp-ethereum installed and now it sounds like cpp-ethereum is outdated and there is a new thing called webthree-umbrella... Well I don't have it installed and reading how to do that wasn't really clear.

Do you have any other command line updates I can do that could update me Eth or Geth or any other part of Ethereum?

Okay... Let me try this new Geth v1.2.0
Ill let you know what happens in a minute. Thanks so much!

**Comment by frozeman** [comment] 2015-10-22 16:12
The umbrella repo is only for managing dependencies in cpp. Follow the steps on the ethereum.org page to update.

The wallet also comes with its own node, so you don't need to update.

**Comment by ReidCoin** [comment] 2015-10-22 16:52
Hey! Got it to work (the first version not the new one you gave me the link to). It was all just about the Geth Version... I thank you so much for your help. Take a look:
![thereum_wallet](https://cloud.githubusercontent.com/assets/6446459/10671794/37a17950-78b2-11e5-9e8a-413e8c1b1827.png)<br>
If you notice compared to my Meteor Wallet though, the Contract Wallets are not in the Ethereum-Wallet:
![thereum_wallet-terminal](https://cloud.githubusercontent.com/assets/6446459/10671810/55560ccc-78b2-11e5-940f-1659d510a731.png)
<br>Are those Contract Wallets just not working or something (I sent one of them 1ETH and it doesn't show up). If I add a Contract Wallet via Ethereum-Wallet will it add to those 3 in Meteor or overwrite them? What do you think I should do? Should I install that new Ethereum-Wallet?

Once again... I thank you so much for helping me figure this out throughout the week! I really appreciate it and am really trying to learn Ethereum but don't know where to start (Ive read Frontier but may need to go over it again now that I see how it works a little better) and I really believe in what you guys have built!

**Comment by frozeman** [comment] 2015-10-23 08:43
Thanks!
im happy that its working.

The contract wallets are stored in the Wallets DB, if you want to move them over to you wallet, simple press "create wallet" and then import it via the address. You can then forget about the browser wallet and only use the wallet app..

**Closed by frozeman** 2015-10-23 08:43 UTC
Labels: bug, question
