### ISSUE TITLE
Unable to sync the last couple of Nodes

### ISSUE THREAD

**Issue by Pheriannath69** [ethereum/mist#2555] opened 2017-06-18 09:44 UTC
Hi all,

I have been trying to sync my Mist wallet on my computer for over a month now. after leaving it on for many days and nights, and used the known ``trick`` to delete the chaindata to speed up the downloading, i have reached 3.392.020 out of 3.392.133 Nodes. 

However, it now seems to be stuck downloading only the chain structure. it goes up to over a million without downloading any more nodes. every now and then when i close and start the app again, it would download 50-100 nodes, but then the required amount of Nodes would increase as well!

im getting very frustrated as i`ve been trying to get it synced for so long now, but it seems something is blocking it. My knowledge about the blockchain and syncing these nodes is limited and i cannot seem to figure it out.

Does anyone has any tips on steps i could take to figure out what is stopping my computer//account to sync completely? 

any help is extremely appreciated!!!!!

**Comment by remyroy** [comment] 2017-06-19 01:20
This is most likely a duplicate of #2466 . There is a few unpleasant alternatives like using a SSD, using parity as the backend or using an online wallet/node to broadcast your transactions until the issue with Geth is solved.

**Comment by Pheriannath69** [comment] 2017-06-19 06:34
Hi Remyroy. thanks for refering me to the other topic. There i`ve read that i can actually transfer my ETH to another wallet via https://myetherwallet.com/. ill give that a try when i get off work. 

Cheers!

**Comment by piqdesigns** [comment] 2017-06-20 02:06
having same issue except i tried to send my eth from mist without being in sync and now the transaction will not show up on blockchain. . or in my mist wallet. help

**Comment by evertonfraga** [comment] 2017-09-28 19:51
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist

**Closed by evertonfraga** 2017-09-28 19:51 UTC
Labels: v0.8.10
