### ISSUE TITLE
Ethereum Wallet freezes after launching

### ISSUE THREAD

**Issue by derongdat** [ethereum/mist#1036] opened 2016-07-26 10:01 UTC
Version: 0.8.1
OS & Version: osx 10.11.6
Node type: geth

I was running Ethereum Wallet 0.7.5 and updated to 0.8.1 some days ago. After the update, upon launching the app, it got unresponsive (unable to click on tabs, buttons). 
Since I was past block 1920000, I figured I needed to resync and followed the instructions at https://github.com/ethereum/mist/releases

However, this did not solve the issue for me. I followed the instructions here: https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide

Lauching geth manually I see the blocks being in sync:
```

I0726 11:37:40.823548 core/blockchain.go:963] imported 1 block(s) (0 queued 0 ignored) including 27 txs in 22.486712ms. #1955126 [f6e23b77 / f6e23b77]
I0726 11:37:44.275576 core/blockchain.go:963] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 3.468205ms. #1955127 [ec2945ba / ec2945ba]
I0726 11:37:49.845139 core/blockchain.go:963] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 2.859262ms. #1955128 [2b93c82e / 2b93c82e]
I0726 11:37:53.239897 core/blockchain.go:963] imported 1 block(s) (0 queued 0 ignored) including 7 txs in 8.46479ms. #1955129 [0d9f0b03 / 0d9f0b03]
I0726 11:38:05.088869 eth/handler.go:295] Peer 6b2a1fbb95f0bbd3 [eth/63]: timed out DAO fork-check, dropping
I0726 11:38:18.617589 core/blockchain.go:963] imported 1 block(s) (0 queued 0 ignored) including 1 txs in 6.355902ms. #1955130 [193a4624 / 193a4624]
I0726 11:38:26.705696 core/blockchain.go:963] imported 1 block(s) (0 queued 0 ignored) including 26 txs in 18.136243ms. #1955131 [ffa99a4e / ffa99a4e]
I0726 11:38:27.248867 core/blockchain.go:963] imported 1 block(s) (0 queued 0 ignored) including 26 txs in 16.3546ms. #1955131 [fa0101d1 / fa0101d1]
I0726 11:39:34.265384 core/blockchain.go:963] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 3.506989ms. #1955132 [c549a93b / c549a93b]
I0726 11:39:44.463873 core/blockchain.go:963] imported 1 block(s) (0 queued 0 ignored) including 8 txs in 16.905631ms. #1955133 [fa3adb2d / fa3adb2d]
I0726 11:39:47.898334 core/blockchain.go:963] imported 1 block(s) (0 queued 0 ignored) including 44 txs in 40.910149ms. #1955134 [53981d73 / 53981d73]
I0726 11:40:10.626953 core/blockchain.go:963] imported 1 block(s) (0 queued 0 ignored) including 2 txs in 6.497308ms. #1955135 [04a14d7b / 04a14d7b]
I0726 11:40:16.458581 core/blockchain.go:963] imported 1 block(s) (0 queued 0 ignored) including 14 txs in 13.985827ms. #1955136 [b726b765 / b726b765]
I0726 11:40:50.540822 core/blockchain.go:963] imported 1 block(s) (0 queued 0 ignored) including 1 txs in 4.410114ms. #1955137 [9d086e21 / 9d086e21]
I0726 11:40:51.544225 core/blockchain.go:963] imported 1 block(s) (0 queued 0 ignored) including 14 txs in 12.861993ms. #1955138 [71894274 / 71894274]
I0726 11:41:24.429392 core/blockchain.go:963] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 6.73248ms. #1955139 [c7384efe / c7384efe]
I0726 11:41:43.726376 core/blockchain.go:963] imported 1 block(s) (0 queued 0 ignored) including 36 txs in 27.147372ms. #1955140 [1c586440 / 1c586440]
I0726 11:41:46.795295 core/blockchain.go:963] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 4.507485ms. #1955141 [764effd0 / 764effd0]
I0726 11:41:58.646526 core/blockchain.go:963] imported 1 block(s) (0 queued 0 ignored) including 7 txs in 7.939107ms. #1955142 [014993ba / 014993ba]
I0726 11:42:01.902061 core/blockchain.go:963] imported 1 block(s) (0 queued 0 ignored) including 4 txs in 5.690385ms. #1955143 [549d7331 / 549d7331]
I0726 11:42:08.966857 eth/handler.go:295] Peer 22eece380d7b4c75 [eth/63]: timed out DAO fork-check, dropping
```

I tried to check the WalletUI via
`Open the console via the top menu -> develop -> Toggle developer tools -> Wallet UI`
But I am not sure this debugging tool is working for me, since I do not get any output from the console (ex. web3.eth.blockNumber does not produce any error or output).
![ethereum_wallet](https://cloud.githubusercontent.com/assets/20659421/17133902/5680cba4-5328-11e6-862c-5c115629cd3e.jpg)

Any hint is highly appreciated!
thanks

**Comment by Diztinct** [comment] 2016-07-26 11:21
I'm getting same issue with the Wallet UI.

Freezes after first launching and initial syncing has completed or runs for around 10 minutes and screen just goes white and app has to be relaunched.

When launching Mist this just keeps crashing once initial syncing has completed. 

I'm running the hard fork version to confirm and these are the first issues encountered with any of the UI releases for the past 4 months.

**Comment by derongdat** [comment] 2016-07-26 13:12
Just to add, exact same behavior with the white screen after some 10 minutes. I have to force quit the app, but as soon as I relaunch I am back to square one.

**Comment by Quixil** [comment] 2016-07-26 14:41
Hi Guys,

same issues with my Wallet. I went back and downloaded the older version as per someone's advice. No results whatsoever. I see the exact balance at the beginning, but I can't access any of the options. It turns white after syncing finishes. Task manager needs to be use to close down the entire thing.

I hope somebody can help us.

**Comment by neerven** [comment] 2016-07-27 12:21
Yep same for me.

**Comment by luclu** [comment] 2016-07-27 13:37
Could you kindly start Ethereum-Wallet via the terminal?
On windows this can be achieved the following way:

1. copy the Ethereum-Wallet-...-0.8.1 folder to C:\ (makes step 3 easier)
2. type `Win+r` to open the run prompt and start cmd
3. type `cd c:\Ethereum-Wall…` to change into the wallet's folder
4. type `.\Ethereum-Wallet.exe` to start the wallet

**Comment by Diztinct** [comment] 2016-07-27 14:30
Hi
As requested started "Ethereum-Wallet" via terminal.

The application took longer to sync node and started at 2 peers reaching 12 peers after 8 minutes.

On completion of sync the GUI opens with 0 peers and "Waiting for Blocks" and no UI controls can be accessed and it stays like this.

My problems started when approving and refunding DAO via "https://slacknation.github.io/medium/12/12.html" loaded within Mist. As soon as my coins landed within the wallet the freeze set in. Hope this info helps. 

Thanks

**Comment by Quixil** [comment] 2016-07-27 18:39
Thanks luclu!

I followed your suggestions. It seemed at the beginning that it will work as I could access & open certain filed within the followed. It then got stuck at 99% of the sync and finally turned white again...

I don't know if it helps, but I am attaching the screenshot for the entire activity:

![wallet](https://cloud.githubusercontent.com/assets/20650267/17187592/2a9e1452-543a-11e6-980d-06620c0116d0.PNG

**Comment by Quixil** [comment] 2016-07-27 18:43
Thanks luclu!

I followed your advice. It looked that it might work at the beginning as I could access ceratin options within my wallet. It then got stuck at 99% of the sync and finally turned white again. 

I am attaching a screen shot of the entire activity;

![wallet](https://cloud.githubusercontent.com/assets/20650267/17187723/b72bdb52-543a-11e6-9dd9-95966127994a.PNG)

Please help.

**Comment by jnicolau** [comment] 2016-07-28 06:17
Same problem here, totally frozen. Can't do anything. I'm running on Mac OS. Launching from terminal doesn't help or improve anything for me.

**Comment by luclu** [comment] 2016-07-28 10:43
Could you please try to remove the `mist.lokidb` file. This might be the same issue as https://github.com/ethereum/mist/issues/1002#issuecomment-234385118.

**Comment by Quixil** [comment] 2016-07-28 11:59
Hi luclu,

I've removed this file and tried again. Got stuck at 99% for about 10 minutes and then turned white again...
![capture](https://cloud.githubusercontent.com/assets/20650267/17211722/67e1fba8-54cb-11e6-968d-2260c2e488f0.PNG)

**Comment by derongdat** [comment] 2016-07-29 09:10
@luclu 
I deleted the mist.lokidb file, launched Ethereum-Wallet, but the issue persists :-(

**Comment by luclu** [comment] 2016-07-29 11:24
@Quixil @derongdat thank you for trying this out. 

Pinging @hiddentao

**Comment by hiddentao** [comment] 2016-07-29 11:25
Ok, will try this myself.

**Comment by jnicolau** [comment] 2016-07-30 10:09
Is there any alternative to manage my DAOs? I can't access my wallet. I'm getting worried that I have no Idea what's going on in my wallet... :(

**Comment by luclu** [comment] 2016-07-30 12:25
@jnicolau try out https://myethereumwallet.com - it's a great piece of software. (runs client side and is hosted on github)

**Comment by jnicolau** [comment] 2016-07-30 13:54
https://myethereumwallet.com says that I have no DAOs in my account. Is this accurate? Isn't it the case that DAOs have been returned to the investors after the hard fork?

**Comment by derongdat** [comment] 2016-07-30 14:01
@jnicolau: did the site https://myethereumwallet.com work for you? For me it just times out at some point...so I thougth luclu meant myetherwallet.com (https://github.com/myetherwallet/myetherwallet.github.io). It says it is completely client side javascript, but I am a bit reluctant to upload my private key...
@ luclu: can you confirm the site being at https://myethereumwallet.com? Could you paste the github link (I could not find a project "myethereumwallet" either, just the one called "myetherwallet" mentioned above).

**Comment by jnicolau** [comment] 2016-07-30 14:08
yes I've used myetherwallet.com, I thought he had mispelled it. I'm completely confused with this nonsense of not being able to see whats going on in my wallet. Never have issues with the wallet client before until the latest version.

**Comment by jnicolau** [comment] 2016-07-30 14:18
I was able to open the wallet form the Mist browser. The problem is that after clicking in the Contracts tab I see no contracts or custom tokens there (there used to be DAO). Am I missing something?

**Comment by luclu** [comment] 2016-07-31 09:30
Sorry, the link is https://www.myetherwallet.com not https://myetherwallet.com.

**Comment by Quixil** [comment] 2016-07-31 21:57
Hiddentao, sorry for being impatient, but did you make any progress? It is otherwise strange that among tens of thousands of users there are only 4 of us experiencing the same kind issue.
If we'll be forced to use myetherwallet, how do you get to see and additional wallet if you have created them. I've been able to see only my main account.

Thanks again for your help!

**Comment by hiddentao** [comment] 2016-08-01 06:34
Guys, we need more debugging information to try and pinpoint the problem. Could you run it from the command-line and turn on trace logging please:

```bash
Ethereum-Wallet.exe --loglevel trace
```

Please upload the file somewhere and post a link here so that we can check it out.

Thanks.

**Comment by derongdat** [comment] 2016-08-01 08:25
@hiddentao:
Here you go
Part 1: http://pastebin.com/VRMJ9ymG
Part 2: http://pastebin.com/zRbA8Kyf

Thanks so much for your support

**Comment by hiddentao** [comment] 2016-08-01 08:53
@derongdat So you waited until it blank-screened and then exited? What was the last thing you did before it blank-screened?

**Comment by derongdat** [comment] 2016-08-01 09:03
Exactly, I launched the app, waited for it to sync (so the main window comes up). Then I tried to click buttons for a minute or so (which has no effect). After that I hit ctrl-c.

**Comment by hiddentao** [comment] 2016-08-01 09:11
So it didn't blank screen. You could see the UI but you couldn't click buttons. Is that right?

**Comment by derongdat** [comment] 2016-08-01 09:59
Correct. I could see the UI but button clicks do not work (see screenshot first post). Only after about 10 minutes the window will final turn white (like in Quixil's screenshot).

**Comment by belgacoin** [comment] 2016-08-02 06:35
Hope to see this issue clear out soon, I have the same problem and it's really annoying. I have a second install via another user on the same machine (for ETC) and this seems to work ok.

**Comment by hiddentao** [comment] 2016-08-02 07:12
This sounds like it could be the contract freeze problem again. @alexvandesande  your thoughts?

**Comment by belgacoin** [comment] 2016-08-02 08:22
@hiddentao possibly, the version that freezes has TheDAO and DGD contracts. The ETC version has no contracts and seems to work fine.

**Comment by Quixil** [comment] 2016-08-03 22:09
Cheers guys,

did we give up on this? 
Can somebody please help me understand how to access additional wallet I've created in Ethereum Wallet via myetherwallet. Thanks in advance.

**Comment by jnicolau** [comment] 2016-08-04 00:45
I have the problem mentioned in here with the Ethereum wallet but with the Mist browser I can see the wallet properly without freezing.

**Comment by neerven** [comment] 2016-08-04 03:10
Same Wallet problem and MIST always crashes after syncing.... I moved temporarily to Windows (a tablet, but seems to work for now), and soon (back) to a linux compu dedicated to ETH. OSX does nor seem to be the best platform in my experience of the last months...

**Comment by hiddentao** [comment] 2016-08-04 08:18
@alexvandesande Didn't we fix the DAO wallet freezing issue a while ago?

**Comment by hiddentao** [comment] 2016-08-04 19:09
Just had it freeze myself, and saw DAO token transfer notification on Mac. That definitely is still an issue then.

**Comment by hiddentao** [comment] 2016-08-04 19:39
Short-term fix (please let me know if this works):

**NOTE: This is destructive will remove all contracts, tokens, etc. But NOT your accounts.**

Launch the Wallet and open up the Developer Tools and run in the Console:

```js
Wallets.remove({});
CustomContracts.remove({});
PendingConfirmations.remove({});
Events.remove({});
Tokens.remove({});
```

Quit and restart the Wallet again and see if it still freezes.

**Comment by Quixil** [comment] 2016-08-04 20:50
Thanks hiddentao! Just to be sure before I do this - I have created additional wallet contract and moved majority of my ETH there from my main account. Will this remain intact? If not what happens to those ETH? Thanks!

**Comment by belgacoin** [comment] 2016-08-05 16:44
@hiddentao thank you. 
As temp solution: is it safe to copy my keystore and accounts folder to a fresh installed Mist wallet in Windows? Will I be able to see my DAO and DGD tokens too?

**Comment by usukan** [comment] 2016-08-06 04:55
I have the same problem on all Win10 computers with DAO and DAORefund contracts watched. Freezes on opening.  Resources being used by 1 of the 3 Electrons just keeps growing larger and larger.  

I believe its caused by the contract watches. I cant get to the trashcan to delete.  

I can open the console/wallet in the frozen wallet but CustomContracts.find().fetch() returns gibberish "value value" (so I cant get the contract ID's to run a delete).

Is there any other way to delete contract watches? Manually somehow - somewhere?

**Comment by hiddentao** [comment] 2016-08-06 12:15
@belgacoin This code does not affect your actual stored folder data, only what's in the Mist browser storage. But you can and should backup your keystore data anyway. It should however clear your DAO and DGD token views, meaning you'll have to re-add those tokens.

**Comment by hiddentao** [comment] 2016-08-06 12:17
@usukan There is no other easy way to delete contract watches - I think we need to add deletion capability to the Mist UI.

**Comment by belgacoin** [comment] 2016-08-06 13:39
@hiddentao hm, I prefer to wait for a wallet update then. I don't feel like going over those DAO/DGD contracts tutorials again. Thanks anyway for your assistance ;-)

**Comment by luclu** [comment] 2016-08-06 14:17
To unwatch those contracts and token you could give version `0.6.2` a try. As far as I'm concerned that one won't freeze as it misses some relevant logic. Please give it a try and jump back on `0.8.1` afterwards. Ping me on the outcome!

**Comment by belgacoin** [comment] 2016-08-06 15:10
@luclu will try that but what with the fork? Won't 0.6.2 follow the ethereum classic chain??

**Comment by luclu** [comment] 2016-08-06 19:16
@belgacoin you are right you won't be able to sync any further with `0.6.2` but you should be able to delete the contracts.

**Comment by neerven** [comment] 2016-08-07 01:40
I deleted all application data, removed Wallet & Mist, reinstalled Mist, and it seems to work.

**Comment by usukan** [comment] 2016-08-07 02:00
@neerven  - you deleted ALL application data?

Chain data
Dapp
Keystore
Nodes
Nodekey

and it still works?  

You would have deleted your keys and all the the blockchain - so you would have to do a full resync - and import your private keys again.

Or was there some specific part of Ethereum  AppData that you deleted?

I don't want to have to do a full resync (and import keys again)

I will try @luclu idea of firing up Wallet version 0.6.2 - deleting watch contracts - then reverting to 0.8.1 again (but can't help thinking the 0.6.2 wallets going to go spastic when it connects to a synced blockchain post fork?)

**Comment by usukan** [comment] 2016-08-07 02:39
@luclu 

I am happy to report that your suggestion to run Ethereum Wallet version 0.6.2 to delete contract and token watches works 100%.

When I run 0.8.1 again - no issues - syncs, wallet opens - no freezing (and all contract and token watches are gone) Hallelujah! 

Its a simple and safe work around for the wallet freezing issues that I had been having.  I have repeated 3 times on diff computers all Win10 - and all my problems are solved.

Much appreciated - cheers - usukan

**Comment by neerven** [comment] 2016-08-09 01:43
@usukan I was actually prepared to do a full sync etc. I thought I removed all data, but I had both Mist and the Wallet, so I suppose I only deleted the Wallet related info. Thereafter Mist works as a charm. No more tokens, nor contracts that I am going to watch for the moment...

**Comment by derongdat** [comment] 2016-08-09 14:58
Great! Finally able to access my Ether again, thanks a bunch!
Steps:
1. download Ethereum-Wallet 0.6.2
2. Delete the DAO contract:

In the Ethereum Wallet (Mist) menu, click on Develop -> Toggle Developer Tools -> Wallet UI. Click on the Console tab.
Enter CustomContracts.find().fetch() in the console, finding the _id of the Custom Contract, then entering the command CustomContracts.remove({your Custom Contract _id}).

3. Reinstall Ethereum-Wallet 0.8.1
4. Done!

**Comment by Quixil** [comment] 2016-08-09 15:30
I am really sorry, but I need a hand here. How do you delete the DAO contract?

**Comment by usukan** [comment] 2016-08-09 20:20
@Quixil 
"How do you delete the DAO contract?"
easier still - just click on DAO Contract - hover over DAO Contract - trash can will appear - click trash can

**Comment by Quixil** [comment] 2016-08-10 11:24
Thank you derongdat, thank you usukan! It works perfectly.

**Comment by belgacoin** [comment] 2016-08-10 11:31
Well, gonna try tonight. Installed the 0.6.2 wallet yesterday but it has problems to update. Can anyone confirm, when I deleted all watch contracts (DAO and DGD), can I still see how many tokens there are in the wallet?

**Comment by belgacoin** [comment] 2016-08-10 18:15
@usukan @hiddentao it worked, just deleted the DAO watch contract and reinstalled 0.8.1. Many thanks for your assistance.

**Comment by kranfnus** [comment] 2016-08-18 17:06
@derongdat I followed step-by-step your explanation.
Still Ethereum-Wallet 0.8.1 stalls!

**Comment by usukan** [comment] 2016-08-18 20:04
Install EthWallet 0.6.2
MAKE SURE you delete ALL token and contract watches (I suspect you may have some left)
just click on DAO Contract or other watch - hover over DAO Contract - trash can will appear - click trash can (dont neet to use the commands).
Go back to EthWallet 0,8.1

**Comment by kranfnus** [comment] 2016-08-20 22:45
@usukan deleted everything but still the problem remains...

**Comment by kranfnus** [comment] 2016-08-25 16:35
Could anybody else help me here?
Like @derongdat I'm also a bit reluctant to send my private key over https://myethereumwallet.com
Thanks in advance!

**Comment by usukan** [comment] 2016-08-25 19:50
try the new release of the Ethereum Wallet - 0.8.2

**Comment by GuutBoy** [comment] 2016-09-02 12:23
Thanks for the advice. I had this problem as well (on OS X running on the testnet). I solved it by getting the 0.6.2 version of ethereum wallet and then running the series of commands in console recommended by hiddentao, i.e.,
`Wallets.remove({});
CustomContracts.remove({});
PendingConfirmations.remove({});
Events.remove({});
Tokens.remove({});`

**Comment by kranfnus** [comment] 2016-09-04 20:20
@usukan thx for the tip. The app is not freezing anymore yet the synch stalls and cannot complete. Here is the error message:

![image](https://cloud.githubusercontent.com/assets/10200293/18233675/accb0e2c-72ed-11e6-8d18-0802457071e9.png)

Do you have any additional advice?

**Comment by usukan** [comment] 2016-09-04 20:52
Not sure if this is related  but syncs were very slow for me and some stalled - but started again after a wallet restart. To fix this I deleted my "chaindata" folder - and did a complete resync of the blockchain.  The full sync was faster than the catchup syn taking about 2 hrs.  I suspect the structure of the chaindata file has changed over time and on old chaindata there is some conflict with the latest wallets.

I have resynced all my wallets now and syncs are fast and without issues in 0.8.2 Ethereum Wallet  

Be sure to ONLY delete the "chaindata" folder - **and always have a backup of your "keystore" folder**.

**Comment by kranfnus** [comment] 2016-09-09 20:57
@usukan it finally worked out! Thanks!

**Comment by luclu** [comment] 2016-09-17 04:02
I will close this issue as it seems to be resolved for:
 - @derongdat 
 - @kranfnus 
 - @usukan 
 - @GuutBoy 
 - @belgacoin 
 - @Quixil 
 - @neerven 
 - @jnicolau 

Assuming it is also solved for:
 - @Diztinct (last post on 27th of July)

**Closed by luclu** 2016-09-17 04:02 UTC

**Comment by awishformore** [comment] 2017-02-11 23:57
This is not solved. On MacOS Sierra, the Ethereum Wallet still freezes if you add a few tokens. It seems to be related to the scanning of all old token contract logs, because every once in a while, a (very) old token transactions pops up that happened on one of your accounts. It's a shame, because other than that, the Ethereum Wallet is quite a bit more usable than Mist, which still is rather rough around the edges.

**Comment by Zaxdoe** [comment] 2017-12-21 16:34
Shame , it's not solved still , i have same issues so i cant test my smart contracts __

**Comment by ipsec** [comment] 2017-12-23 00:00
Same problem here. Please fix this.

**Comment by Excruciates** [comment] 2018-01-09 13:11
Same problem. Using MacOS Yosemite. The UI window more often than not doesn't even load now, just stuck with the small window with 'Ethereum node connected'. Toggle Full Screen brings up the UI but it's the white screen and nothing loads.
