### ISSUE TITLE
Unsolved problem - No confirmations - is ethereum a soon to fail project?

### ISSUE THREAD

**Issue by maverick85** [ethereum/mist#3684] opened 2018-02-12 16:52 UTC
I have addressed this issue before here: [ethereum / mist issue #3653 ](https://github.com/ethereum/mist/issues/3653)

```
Version: `0.9.3`
OS & Version: macOS 10.13.3
Node version: `geth 1.7.2`
Number of blocks synchronized: in sync, light client
```

- My transaction is not confirmed

Ok people so all the info was already on the original issue that got abandoned without any resolution or comments, the link is above you can check it out;

I want to transfer 0.03 ether I'm not going to pay 0.3 fee.
Looking at [ETH Gas Station](https://ethgasstation.info) the transfer fee is perfectly in range.

Your wallet keeps throwing me values of 0.2 ether and 0.05 ether (140 euro and 35 euro respectively) for transfers. Are you kidding me?

I am documenting this, I can only imagine the amount of people who missing to look at the fees are being robbed in hundreds of dollars. Either this issues come up with solutions really fast or I'm blowing the horn on ethereum, this is inadmissible, I am using the official wallet, got thousands of euro stuck on it, support is non-existent. WTF?!

<img width="616" alt="screen shot 2018-02-12 at 16 31 12" src="https://user-images.githubusercontent.com/10200278/36108585-1563459c-1015-11e8-83c4-d4597a2168ee.png">

**Comment by evertonfraga** [comment] 2018-02-28 03:19
Seems like a duplicate of #3653.

The gas estimation issue is a known one, although unfortunate. It's being addressed already. Thanks for reporting.

**Closed by evertonfraga** 2018-02-28 03:19 UTC
Labels: Status: Triage
