### ISSUE TITLE
Sync eta feature

### ISSUE THREAD

**Issue by simontfs** [ethereum/mist#2649] opened 2017-06-28 15:42 UTC
Not so much as an issue as a feature request. I think it might be of use especially for new users to have 
 an (full sync in %dd%hh%mm) placed somewhere close to the block count.

**Comment by evertonfraga** [comment] 2017-08-14 21:39
Duplicate of https://github.com/ethereum/mist/issues/2249. I recommend you to follow from there.

Thanks for the suggestion!

**Closed by evertonfraga** 2017-08-14 21:39 UTC
Labels: v0.8.10
