### ISSUE TITLE
ETH Wallet, stuck syncing

### ISSUE THREAD

**Issue by Eyedol-X** [ethereum/mist#1257] opened 2016-10-05 00:20 UTC
#### System information
``````
Version: `0.8.4`
OS & Version: windows 10
Node type: `eth/geth(default)`
``````
For more than 24 hours now I have been unable to get my wallet to completely sync in Windows 10.

I've tried deleting the chain data with -removedb. I have tried manually deleting the chain data and doing a fast sync via Geth CLI, I've tried different internet connections 45mb/5mb and a 100mb/100mb. Everywhere I go, no matter how many times I restart the wallet it just hangs here or something similar to this, earlier today I had 13 peers on the 100/100 and it basically would download like 5 blocks then sit for 30 minutes. If I quit/restart the wallet it will just begin sync'ing at a different place but eventually hang just like the example below (with a different amount of blocks remaining)

![capture2](https://cloud.githubusercontent.com/assets/22627805/19097043/1ed4d238-8a67-11e6-83e4-4347e6e200f1.JPG)

This has only recently become an issue for me and I'm not sure if has something to do with DDOS attacks or something else going on. I've found reports of people having similar issues but I see no solution to them anywhere except more of the above.

Any assistance would be appreciated.

**Comment by cryptojunky** [comment] 2016-10-05 01:09
I too am experiencing difficulties. Syns very slow now than stops. Seems I am getting same log error as before: I am also using windows X/ether wallet 0.8.4/geth


I1004 21:04:25.819120 eth/downloader/downloader.go:319] Block synchronisation started
I1004 21:04:40.820666 eth/handler.go:290] Peer f1e3d34a0ad0f193 [eth/63]: timed out DAO fork-check, dropping
I1004 21:04:43.607337 eth/handler.go:290] Peer ab3ef5ddb42a5bd7 [eth/63]: timed out DAO fork-check, dropping
I1004 21:05:00.199289 eth/handler.go:290] Peer ab3ef5ddb42a5bd7 [eth/63]: timed out DAO fork-check, dropping
I1004 21:05:21.268992 core/blockchain.go:975] imported 3 block(s) (0 queued 0 ignored) including 3 txs in 54.4597523s. #2372218 [c08060da / 8753239b]
I1004 21:05:50.018652 eth/handler.go:290] Peer ab3ef5ddb42a5bd7 [eth/63]: timed out DAO fork-check, dropping
I1004 21:06:20.584018 eth/handler.go:290] Peer ab3ef5ddb42a5bd7 [eth/63]: timed out DAO fork-check, dropping
I1004 21:06:37.923674 eth/handler.go:290] Peer df06514adc6eed3a [eth/63]: timed out DAO fork-check, dropping

**Comment by Mordong** [comment] 2016-10-05 03:39
#1254

**Comment by Eyedol-X** [comment] 2016-10-05 09:35
9+ Hours later since my original post, here is now what I see.

![capture3](https://cloud.githubusercontent.com/assets/22627805/19108141/1a9f544c-8ab5-11e6-99a7-0d37f05ff641.JPG)

For those reading, I want to reiterate that this has only recently become a problem for me, I've never had a problem in the past.

**Comment by Eyedol-X** [comment] 2016-10-05 09:43
@Mordong - If I understand the post you referenced, I would need to load parity locally on my system (which downloads the entire chain again) and then launch the ETH wallet to get it to sync properly?

I will test this later today when I get back on my 100/100 connection.

**Comment by Mordong** [comment] 2016-10-05 11:50
@Eyedol-X - yep, correct, load Parity locally, launch it from shortcut with "--geth" switch as described, then launch Wallet and it will get back on rail after downloading whole chain from scratch

**Comment by Eyedol-X** [comment] 2016-10-05 15:38
@Mordong Works awesome! Thanks for this workaround.

**Comment by perkdave56** [comment] 2016-10-05 17:59
@Mordong -   I'm having the same problem with my wallet sync.  Where do I add the "--geth" switch?  I've tried adding it to the target properties at the end but there is no effect. My wallet is stuck at about 8000 blocks left to download.  I've cleared my chaindata and ran the wallet again and it downloads 99% of the blocks but then it stops short of finishing.

**Comment by Eyedol-X** [comment] 2016-10-05 18:04
@perkdave56 where you put the switch in is referenced in the other thread but this is where you place it. I created a copy of the parity shortcut and called it Parity - Geth, then edited the shortcut properties as illustrated below.

![shortcut](https://cloud.githubusercontent.com/assets/22627805/19125312/3b39c100-8afc-11e6-8302-098259481bec.JPG)

**Comment by perkdave56** [comment] 2016-10-05 18:20
@Eyedol-X    Sorry to be dense on this.  I searched my whole drive and found no directory named Ethcore and no file named Parity.exe.  I guess I need to download that somewhere.  Up to this point I had very little problem with Ethereum Wallet until I download 0.8.4.  

Where would I locate the Parity.exe program?

**Comment by perkdave56** [comment] 2016-10-05 18:27
Nevermind..... I did some searching and found it.  After adding the --geth the sync process is starting over.  Hopefully it all works fine now.  Thanks, Eyedol-X

**Comment by luclu** [comment] 2016-10-16 21:25
@Eyedol-X, @cryptojunky, we just published [release `0.8.6`](https://github.com/ethereum/mist/releases/tag/v0.8.6) which will download **geth** `1.4.18` on-the-fly. 
*Please* update to easily roll with the upcoming [Hard Fork](https://blog.ethereum.org/2016/10/13/announcement-imminent-hard-fork-eip150-gas-cost-changes/) on Tuesday.

**Comment by cryptojunky** [comment] 2016-10-16 22:06
Ok thanks. Will do.

**Comment by matthewsdk** [comment] 2016-10-19 02:43
I have the same problem and I'm a non tech guy.  Do I just wait until ethereum.org publishes an update I can download that will sync?  I've got Win7 64 bit, I downloaded 0.8.6 and validated my Geth is 1.4.18 stuck on block 2,391,546 of 2,466,334.  I'm scared to download anything not worthy as I have a lot of ETH and I'm getting frustrated.  Why would they publish something that doesn't work?  Is the only fix to download this Parity?  If so, what website can I do that?

**Comment by luclu** [comment] 2016-10-19 10:25
I will close this for now as the syncing problems seems to be resolved for everyone one way or another.

**Closed by luclu** 2016-10-19 10:25 UTC

**Comment by gentlejack** [comment] 2016-10-19 11:02
But my syncing problem still remain unsolved.

**Comment by Eyedol-X** [comment] 2016-10-19 12:13
Sorry to report that 0.8.6 didn't resolve this issue for me. Tried to Sync all day yesterday and again today. Several peers connected now with 0.8.6 but either it syncs at snail pace or not at all. I had it running for several hours yesterday and it only downloaded 2,000 blocks.

**Comment by matthewsdk** [comment] 2016-10-19 15:35
Have you tried deleting the folder Chain data and relaunching 0.8.6? It will re download and should correct the problem.

**Comment by luclu** [comment] 2016-10-19 15:48
Please expect considerable longer syncing times caused by the current attacks. I recommend one of the following:
 - use http://myetherwallet.com in the meantime
 - update to a SSD
 - wait for the [LES-implementation](https://github.com/zsfelfoldi/go-ethereum/wiki/Light-Ethereum-Subprotocol-(LES)) (light-client)

**Comment by Kaden14** [comment] 2017-05-29 20:22
OMG - I have the same problem trying to download the Ethereum wallet from https://ethereum.org - It just stops mid way and when I shut it down and reopen it, it starts loading again, but then it stops.

**Comment by cryptojunky** [comment] 2017-05-29 20:33
Try version 0.8.10 from here https://github.com/ethereum/mist/releases

You may need to delete chaindata folder and resync. Usually syncs in a few hours from scratch. Try just installing latest version and running first.

**Comment by Kaden14** [comment] 2017-05-29 20:41
Few Hours? wow.

**Comment by Kaden14** [comment] 2017-05-29 20:41
Is that the newest version? Because I just got it today.. if that is the latest then I dont have to worry about it.

**Comment by cryptojunky** [comment] 2017-05-29 20:47
Yes that's the latest version.

**Comment by Kaden14** [comment] 2017-05-29 20:53
sweet potatoes - thanks for the help

**Comment by cryptojunky** [comment] 2017-05-29 21:04
You're Welcome. Hope it all works out.

**Comment by wallstreet3333** [comment] 2017-05-30 17:54
Hi there guys, facing the same issues with the latest version. Now I removed all files and tried to install again the same version from scratch but in another way. If you see the wallet files list, thee are 3 versions for Windows, 32 bit, 64 bit and another one (first from list) that have about 116 MB. With that version in under 15 minutes i'm at 500k+ and is sync very fast, 1k at every 2 sec. Hope will it work. I will kep you updated.

OS: Windows 7 Professional 64 bit.
Wallet: Ethereum-Wallet-installer-0-8-10.exe 116 MB (ETH Classic wallet)

**Comment by wallstreet3333** [comment] 2017-05-31 07:00
Update:

Same issue, after 1 million, the wallet start to be super slow in sync and after some time he restart from 0 and become more slower than first time. Not a good feeling when you want to access your wallet...In other words, is not trustable.

**Comment by cryptojunky** [comment] 2017-05-31 09:41
Save your keystore file and other backup files. Delete everything including appdata ethereum folders and wallet. Start totally fresh. Once up and running shut down ethereum wallet than put your backup files back in appdata. 

 Are you using an older laptop by any chance? If so you may need an upgrade. Also make sure your plugged in and not on wifi for faster sync.

**Comment by wallstreet3333** [comment] 2017-05-31 21:54
I tried and didnt worked. I installed Windows 10 and here the problem is more bad than before. On win 10 doesnt start the syncing...This is the 4th day of tryings....

**Comment by cryptojunky** [comment] 2017-05-31 22:11
Did you try previous version 0.8.9?

**Comment by wallstreet3333** [comment] 2017-06-01 06:16
Morning mate, yes. I tried last 3 versions. Now i installed Win 8.1 and i will retake the setup.

**Comment by wallstreet3333** [comment] 2017-06-01 08:08
Everything dead on Windows 8.1 too. Windows 8.1 has the same problem as Windows 10. Sync is not starting. Tested with 3 version and also with latest Geth 3.4.0. Waste of time...

**Comment by cryptojunky** [comment] 2017-06-01 08:50
Sync not starting? Make sure Date & Time are correct too, that was a issue in the past. Go to Date & Time / Internet Time / Change Settings/ Update Now. Make sure it says time update was successful. Thats about all I got for ya. You may want to upload a log file and let one of the pros help you out after checking date and time. Good Luck!

**Comment by wallstreet3333** [comment] 2017-06-01 10:57
Solved the problem for the moment. I fixed some errors with time syncing. Now am at 1 million block and i loose peers. From 25 now i have only 2-4 peers and syncing becomes slow. Is there any way to get more peers? I also added port 30301 near 30303 to be sure that everything is ok. I'm afraid of sync restarting after some time.

**Comment by cryptojunky** [comment] 2017-06-01 11:02
FYI: on average it took 3-5 hours. On old slower computers many more.

**Comment by wallstreet3333** [comment] 2017-06-01 11:07
Thanks for info. Btw, is the Ethereum Classic wallet the same as Ethereum? Can i use different account on just one Ethereum wallet?

**Comment by cryptojunky** [comment] 2017-06-01 11:39
You can use ethereum classic wallet on two different computers. 1 running ethereum classic (non support fork) and one running ethereum (support fork). Atleast thats the old way. Or you can make life easier and just use jaxx wallet for your ethereum classic. No block sync necessary.

**Comment by wallstreet3333** [comment] 2017-06-01 11:57
I already saved keystore files so im waiting for Eth wallet to sync. Two more questions. Eth and Eth classic are 2 different wallets? Can i use keystore files from Ethc on Eth wallet? Also if you have any tips on how to increase the peers on sync.

**Comment by cryptojunky** [comment] 2017-06-01 12:25
Yes 2 different wallets. I have not done in a while but here it goes. When you first install ethereum wallet it should ask you do you support the fork ( if yes that downloads ethereum chain) if no ( that downloads ethereum classic chain). You cant have 2 different chains on 1 computer unless you start changing file names. i.e. cant have a chaindata folder with ethereum classic and ethereum chain in it. So if you install a ethereum wallet on one computer and than on another you install ethereum classic you are good to go. I believe you can put the keystore on each ( i may be wrong) if it doesnt work where you have ethereum classic on one chain and ethereum on another. You will have to run a split which can be done pretty easy using myetherwallet and classicetherwallet. There are tutorials on the web.

**Comment by wallstreet3333** [comment] 2017-06-01 12:32
When i install it does not ask anything just firewall popup for private or public. Do you think is a good idea to still mining on Ethc or move on to Eth?

**Comment by cryptojunky** [comment] 2017-06-01 12:48
Check your antivirus make sure its not blocking ethereum or geth. Check firewall settings in virus software and allow access.

As far as mining all depends on personal preference. Check cryptocompare.com if you are looking to mine strictly for profit.

Not sure if newer wallet asks you if you support you could try version 0.8.1 ( may want to ask a pro here if its a good idea to use an older wallet. Not sure ) However you may just want to install jaxx. Write down your pass phrase and not have to install another blockchain. Split your ethereum. Keep your ether in ethereum wallet and put your classic in jaxx wallet.

**Comment by wallstreet3333** [comment] 2017-06-01 13:12
Thanks for tips. I will try Jaxx for Ethc. The problem is that i already have sent Ethc to an Ethc address and i didnt see an option on Jaxx to import the keystore file. I think i must mining directly ti Jaxx address right?

**Comment by cryptojunky** [comment] 2017-06-01 13:33
You can import your ethereum classic wallet file that you sent your etc to into classicetherwallet website and than send them to your jaxx wallet. I dont believe you can use keystore file in jaxx. Yes mine to jaxx wallet for your etherem classic. DO NOT FORGET TO WRITE DOWN YOUR BACKUP PHRASE IN JAXX WALLET. Lose that and lose your coins forever. You can also enter private key into Jaxx wallet if you have it.

**Comment by cryptojunky** [comment] 2017-06-01 13:48
Here is what I would do. Make a new account in ethereum wallet. Put a new password and save. Send your ethereum to the new account address. Upload old ethereum wallet (keystore) to Classic ether wallet & Note: ClassicEtherWallet is only served at https://classicetherwallet.com/ and https://ethereumproject.github.io/etherwallet/. Beware of the phishing scams!

Send your ethereum Classic to jaxx wallet.

From now on send ethereum to your new account in ethereum wallet and send any etc to jaxx address.

Reason I suggest you setup a new account is because you are sending your passcode for your ether account in your browser ( unless you do offline transaction which may be confusing for some ) its much easier and safer just setting up a new account in ethereum wallet.

**Comment by wallstreet3333** [comment] 2017-06-01 13:59
I only have Ethc. Problem solved via Jaxx. I'm shocked how fast the coins was transfered :) Ty so much for your time mate. I saw that Jaxx is not good to minimg directly on it (is not designed to receive mining payouts) so i will continue to sens to my old Ethc keystorr and then transfer it to Jaxx.

**Comment by cryptojunky** [comment] 2017-06-01 14:03
Ahh! Than I learned something new too about mining and jaxx. Ill have to do some research, thanks.

Your Welcome, anytime.

**Comment by wallstreet3333** [comment] 2017-06-01 14:46
Thanks! Visit HELP section in Jaxx and there you will find the paragraph about mining directly to it.

**Comment by nazimran** [comment] 2017-06-01 22:47
The wallet must be synchronized without downloading the entire chain.
There are big troubles like this.
very slow.  very slow.

**Comment by sylido** [comment] 2017-06-03 04:57
0.8.10 windows 7 64 bit -> stuck at block 76,565 downloading blocks from 22 peers. If I stop it and start it it again it continues from that block for a while it's pretty fast, but then it gets stuck again, this time at 159,004....it's really annoying to stop and start it to get the whole blockchain. I've left it for hours and it didn't proceed on it's own.

**Comment by nazimran** [comment] 2017-06-03 08:14
geth-windows-amd64-1.6.5-cf87713d.exe Install the program
And it works:
cmd hungry
cd\
cd program files
cd geth
geth.exe --light
ok
             Open wallet

**Comment by azarus** [comment] 2017-06-09 20:59
I have the same issue here, i downloaded the wallet to my desktop and its not syncing since 5 days now.
https://i.imgur.com/7WwtUtu.png

**Comment by cryptojunky** [comment] 2017-06-09 22:20
Try above what zanimran said. Run geth first than open ethereum wallet. Try everything else above as well.

**Comment by cryptojunky** [comment] 2017-06-09 22:21
Sorry meant nazimran

**Comment by azarus** [comment] 2017-06-09 23:28
And where am i supposed to find this geth.exe since i can't find it neither the wallet or the program files.

**Comment by azarus** [comment] 2017-06-09 23:40
**Great:** 
c:\Users\<user>\AppData\Roaming\Ethereum Wallet\binaries\Geth\unpacked\

But still what causes the issue? It would be great if someone could look into it.

**Comment by alank89** [comment] 2017-06-10 15:45
Running the light client worked. Thanks!

**Comment by tommasog** [comment] 2017-06-11 14:05
Light option didn't work for me so far. I am using Ethereum Wallet (not Mist) v 0.8.10 (geth-based) on Debian. I downloaded it and tried to set it up freshly on a Core i7 machine with 8 GiB RAM and SSD. Normal sync would take forever, same for the --fast option, now I'm trying the --light but the problem persists: it looks like it's downloading a lot of blocks, but whenever it's close to 90-99% it "resets" the counter and starts again.

**Comment by evertonfraga** [comment] 2017-06-12 19:29
@tommasog 

Please expect considerably long times due to chain size. We recommend using http://myetherwallet.com in the meantime.

**Comment by azarus** [comment] 2017-06-12 19:33
I am using that wallet and this is sort of an issue and i would like to ask to please look into it. You xant just really ask every user to dig for an exe file somewhere installed in a compiter and start the command line app just to sync the block chain. I imagine the chain is big but its still something that shouldnt be an issue ans it just should work fine.

**Comment by phattrent** [comment] 2017-06-19 15:28
Can we reopen this issue please? I am experiencing the same thing.  It's not a matter of a "long" download time.  The download never finishes, you have to start/stop/restart your client 100 times or more before you get the full chain.  Terrible user experience it needs to be fixed.  Yes I can use another wallet, but this is the official wallet! People will download this first, and some people don't want to use an online wallet.

**Comment by tommasog** [comment] 2017-06-19 20:46
Agreed @phattrent , thanks everybody for the suggestion but please stop recommending using online wallets: usually there are reasons if people try to run a full node.

On a side note, I finally managed to sync my ethereum wallet. It took a bit less than forever, and I had to hard-close it and restart it 20 times or so, but eventually it worked out. It gets super slow when it approaches the last few blocks, and for each of them it downloads a lot of "blockchain structure". The trick is: if you see that it gets stuck, don't be afraid to close and restart it, it will resume faster. It also has problems finding peers (very often it takes a few minutes just to connect to the network) and, even more annoyingly, if you keep it disconnected for a day or two, then it takes AGAIN forever to resync when you start it (unlike, e.g., bitcoin, which is super slow the first time you start it, but then it's OK to keep it in sync every few days).

So, yeah, sorry for the rant, but it sucks. It would really push me to use an online wallet if I were not paranoid.

**Comment by labago** [comment] 2017-06-23 15:40
I am experiencing exactly what @tommasog described. I have hard closed it a bunch of times, it is only a couple hundred blocks behind now but when you restart it has to download THOUSANDS of block structures for some reason? Very strange

**Comment by elgailhouste** [comment] 2017-06-28 17:15
Got the same problem

**Comment by elgailhouste** [comment] 2017-06-28 17:16
Same problem here as labago. Keep syncing forever.
It's been like this for weeks.

**Comment by Natizyskunk** [comment] 2017-06-28 18:08
Same problem for me ...

**Comment by DarthKegRaider** [comment] 2017-06-28 23:16
+1 for insanely slow!  My poor laptop has been online trying to sync for the last 3 days on ADSL2+.  Sure, it's not the quickest in the world, but how is the world supposed to embrace this if it's this difficult to get anything in or out?

I got sick of the wallet app stalling, so i wrote a quick batch file to auto launch the geth command upon crashing too.  It seems to swell up to about 1.3GB of memory usage then crash.  64bit windows 7 with 16GB RAM, so I don't think it's me.  At least I'm slowly making progress.

[ethsync.bat]
cd "\Users\Username\AppData\Roaming\Ethereum Wallet\binaries\Geth\unpacked"
geth.exe --fast --cache 512 console
cd \users\Username
ethsync.bat

**Comment by azarus** [comment] 2017-06-29 09:31
Yes guys please ethereum is amazing dont let the users suck with it and ask them to manually start some random thirdparty processes. Simple because most users dont know how to do that. Neither they bother to figure out if theres an issue. They just use an online wallet that is less secure.

**Comment by TuitionCoin** [comment] 2017-06-30 15:06
Came across same issue. Here is my solution

- Install Geth from geth.ethereum.org (Might not be needed as geth may already be installed)
- Delete the ChainData folder under \Users\Username\AppData\Roaming\Ethereum
- Create a .bat file that does the following. (The light command only loads part of blockchain, under 1Gig)

cd geth directory
start geth --light --cache 512
cd EthereumWallet.exe directory
start EthereumWallet.exe

In case someone that has something to do with Ethereum reads this. The Wallet should have a "Pro" and "Light" mode. The Pro mode would use the full block chain. The "Light" mode would use light mode of Geth. This would increase adoption for non-tech people checking out ethereum. And anyone else that doesn't want 20Gig on the hard drive hidden in the AppData directory.

**Comment by tommasog** [comment] 2017-07-07 07:43
Guys, this thing is unusable! Sorry for the rant, but I disconnected my PC for 24 hours, and after that I cannot sync anymore, even if I let it download overnight it's so slow that it doesn't catch up with the blocks!

**Comment by burrocampeador** [comment] 2017-07-11 20:08
I am new in Ethereum and I have tried to install the default wallet, recommended with a huge button in ethereum.org webpage... but I have the same frustrating problem. Is it serious? Any easy step-to-step solution?

**Comment by DarthKegRaider** [comment] 2017-07-11 21:08
@burrocampeador : Head up a few posts and do what @TuitionCoin or myself suggested.  If you need help in the DOS command prompt area sing out.  I'll be home later today and can whip up a quick guided tour of the cmd.exe world.

**Comment by burrocampeador** [comment] 2017-07-12 10:42
Thank you for your help, but that's impossible! I have tried your solution and tuitionCoin's solution and they don't work, with many problems (and i am software engineer... I don't want to imagine someone non-tech). The good and definitive solution is to fix "Ethereum wallet.exe" in order to work properly without executing geth.exe. I give it up. Ethereum doesn't seem a serious project.

**Comment by TuitionCoin** [comment] 2017-07-12 11:18
It should work if you follow our directions above. 

Use the --light setting of geth 

Never start the wallet with the exe. Always use the bat file to start.  If you use the exe the wallet starts geth with crappy settings. If you did run without bat you'll need to delete the chaindata folder located here \Users\Username\AppData\Roaming\Ethereum. 

I'm guessing it helps to download geth instead of using the one that comes with the wallet.

Ethereum people, please fix the Wallet to have light mode by default, you are losing fans.

**Comment by burrocampeador** [comment] 2017-07-12 12:02
"--light" option appears as "deprecated" and "experimental"...

**Comment by Twinstar2** [comment] 2017-08-01 19:58
@TuitionCoin how do you expect people to use this wallet, if they can't open it as a normal program? Most people are not Tech Freaks and can't comprehend what you guys write here. My sync takes forever, even if i ran my PC 24/7 it never catches up, no one will use such a program. So we are ending up with less full Nodes, which is of course bad for the decentralized idea behind ETH. Please fix your mist wallet.

**Comment by TuitionCoin** [comment] 2017-08-02 10:44
@twinstar2 I agree. I don't expect people to use the mist wallet. It is unusable. 

The Ethereum/mist people need to fix the wallet so it works for everyone. 

What we wrote is a technical work-around that worked for us.

**Comment by Roister01** [comment] 2017-08-03 23:36
Hi folks...
I made a .bat file as suggested, and it worked great for a couple of weeks. However, on opening, it now says 'failed to retrieve current release' and 'no suitable peers available'.  If I then open up mist, it just says 'started swarm', but doesn't ever progress from this...any tips folks?

**Comment by TuitionCoin** [comment] 2017-08-23 02:53
Mist has a new release with lots of improvements. See installs near bottom of this link. https://github.com/ethereum/mist/releases/tag/v0.9.0. (Great work Ethereum )

I made a change to the .bat file we recommended earlier in this thread. Replace the "--light" flag with "--syncmode light".

**Comment by elboletaire** [comment] 2017-08-29 20:23
> Mist has a new release with lots of improvements. See installs near bottom of this link. https://github.com/ethereum/mist/releases/tag/v0.9.0. (Great work Ethereum )

I'm using that version; same issue than described...

**Comment by nioschka** [comment] 2017-09-09 09:20
I'm not sure if I'm on the write thread (if not please advise) but I do have a problem: Syncing is doing apparently fine, wallet downloaded more than 3.5 mil blocks, but after I start the application it shows **correct number of downloaded blocks** and **0%** of progress? Here's the pic:
![untitledet_1](https://user-images.githubusercontent.com/31793942/30238888-ac10fcc2-9550-11e7-86c9-b0a439085223.jpg)
Is that wrong, did anyone have an issue like that, and should I do something about it? Thanks in advance!

**Comment by nazimran** [comment] 2017-09-09 17:13
Do not bother, the blocks do not go down.

2017-09-09 12:20 GMT+03:00 nioschka <notifications@github.com>:

**Comment by TuitionCoin** [comment] 2017-09-09 21:24
I have a really old laptop and can only make the mist ethereum wallet work if I launch geth first using syncmode light. If you start mist first it tries to download the full blockchain which is over 20g and is tough for many laptops to handle. 

Delete the data folder if your system is already having issues.
Download Geth separately. 

Each time you want to open up mist
First `start geth --syncmode light --cache 512`
Only after geth is running launch the ethereum wallet.

**Comment by Hiturunk** [comment] 2017-09-26 01:20
@TuitionCoin 

Your solution (and concise direction) was exactly what I needed to get my wallet to sync properly.
(...And I'm on a decent rig!)
Thank you for posting!

**Comment by Joz3d** [comment] 2017-11-25 00:59
I'm also finally trying Ethereum out for the first time with installing official Wallet and trying to sync for over a week and never finishing the last 2,000-4,000 blocks, and wondering "Vitalik, what is this crap?"

[This is a good post](https://ethereum.stackexchange.com/questions/143/what-are-the-ethereum-disk-space-needs#826) explaining that it's pretty much impossible to sync the full blockchain at this point (very concerning).

@TuitionCoin's solution is your best bet.  I found that instead of doing the whole batch file thing, you can pass commands to the node (geth) from the wallet, and instead just edited the Ethereum Wallet.exe shortcut target to:

`"C:\Program Files\Ethereum\Ethereum Wallet.exe" --node-syncmode light --node-cache 512`

...still had to restart it one time when it got within 2,000 blocks, but took about 10m to get light sync'd.
