### ISSUE TITLE
Ethereum Wallet restarts sync

### ISSUE THREAD

**Issue by adamabyss** [ethereum/mist#2259] opened 2017-05-13 16:11 UTC
Hello,

I have a new computer - trying to sync a new Ethereum Wallet on it.

The most it has ever got to is about 2.5 million blocks out of approx. 3.7 million, then when I am not looking (e.g. over night) it has gone back to the start.

Anyone got any ideas how to stop this and finally sync my Ethereum Wallet?

Thanks,

Adam.

#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by jamesray1** [comment] 2017-05-13 21:13
This is a bug and needs a bug label. I left my computer on overnight. When I checked this morning the sync level was on 20%. I noticed before that the sync restarted. I accidentally closed Mist and the sync reset to 0%. Try to not close Mist and change your computer power settings so that it doesn't go to sleep, doesn't turn off the hard drive and uses 100% of the CPU as a minimum.

**Comment by jamesray1** [comment] 2017-05-15 10:58
Another possible fix or alternative enhancement is on closing Mist, or shutting down or restarting the computer, prompt the user that doing so will cause the sync to stop (and unless the bug is fixed it will restart), and ask them to confirm whether they still want to do this.

**Comment by adamabyss** [comment] 2017-05-15 21:37
Thanks your help James, but nothing is working. I have been trying to update the Ethereum Wallet on two computers and it never gets to full sync no matter what I try. I think I'll go back to using MyEtherWallet web-based. It's pretty pathetic that they can't build a wallet that actually works in a reliable fashion - they've had enough time to do this.

**Comment by jamesray1** [comment] 2017-05-18 12:49
Yeah, give it time and the bugs should be fixed. If more people learn Solidity and help with the development that would speed up the process. Then it will be easier to use Ethereum, use dApps, and reduce transaction costs!

**Comment by jamesray1** [comment] 2017-05-18 13:56
https://sustergy.co/2017/05/18/one-way-to-buy-eth-in-australia/

**Comment by frozeman** [comment] 2017-05-22 07:20
If your sync stops and resets to 0, the next sync cycle will NOT be fast sync and therefore take forever.

You need to then delete the "chaindata" folder again, and restart Mist to enable fast sync again. Then let it sync until the end. Be aware that when it is almost finished syncing it still downloads the states, which can take very long. This can sometimes look like the sync is stuck at 90% or so.

**Comment by frozeman** [comment] 2017-05-22 07:22
I do agree that the syncing is a pain. And especially now where we have already a two year old chain. Once youre synced its not so hard to keep up, but the initial sync is what sucks. We are working on some solutions, one would be to switch to a remote node while syncing etc. I will also talk with @karalabe if we can add warp sync, checkpointing, or simply enforce fast sync on every sync from block 0.

**Comment by jamesray1** [comment] 2017-05-22 08:21
I was just downloading Mist v 0.8.9 on my work computer as I read this, but I will try deleting the chaindata folder and restarting Mist on my home computer.

**Comment by frozeman** [comment] 2017-05-22 08:40
I just heared that geth 1.6.1 has a regression introduced, will be fixed in 1.6.2

**Comment by adamabyss** [comment] 2017-05-22 11:22
I've tried deleting the 'chaindata' folder and starting again loads of times - it still never makes a difference - it always gets stuck somewhere.

And this is on two completely separate computers.

Also, I'm not talking about Mist, I'm talking about Ethereum Wallet.

Why is there even two different downloads?

Every time I ask a question about Ethereum Wallet, I get an answer about Mist.

In one thread, I even said 'please note, I'm using Ethereum Wallet, not Mist - please don't give me answers about Mist' - and yet I still got answers referring to Mist!

I'm just about to give up on this software and use MyEtherWallet from now on.

Thanks anyway.

**Comment by adamabyss** [comment] 2017-05-22 11:24
I hope your potential improvements to the sync work.

Regarding the problem (I'm assuming that's what a 'regression' is) with 1.6.1 then do you suggest just waiting until the new version comes out?

**Comment by frozeman** [comment] 2017-05-22 11:48
@adamabyss i can't really answer for the go ethereum team, but i think a fix is coming.
Concerning the ethereum wallet vs mist.
Its technically the same software, just once it loads only the wallet ui.

The reason is that we started releasing only the wallet first, as the Mist UI and functionality was not ready. But aAny answer, should apply to both equally.

**Comment by adamabyss** [comment] 2017-05-22 12:05
Ok thanks frozeman.

**Comment by tomholub** [comment] 2017-05-22 23:02
Same issue here,will always switch back to 0 sometime throughout. Trying to sync for days.

**Comment by jamesray1** [comment] 2017-05-23 08:41
I'm using it on a work computer, I opened Mist not long after I got into the office. It has been stuck at 52% for a long time. I will leave my computer and the program on to see how it goes.

**Comment by jamesray1** [comment] 2017-05-23 09:37
Oops, I accidentally closed Mist. Now it has been stuck at 0 blocks, 0 peers and 47 years for several minutes. How do I access the chain data folder? There are no results when I search on file explorer for chain or data. The only result for "chain", "data" or "chain data" when I search on file explorer (Windows 7) is for a licenses.html file.

**Comment by frozeman** [comment] 2017-05-23 09:40
%APPDATA%\Ethereum\chaindata

**Comment by tomholub** [comment] 2017-05-23 14:32
If anyone needs to use their wallet urgently, starting geth with `--light` before you start Mist or Ethereum Wallet made it usable for me, it synced in a few hours without looping to zero.

**Comment by adamabyss** [comment] 2017-05-23 16:24
"starting geth with --light before you start"

Sorry, I don't know what this means or how to do it.

I tried to look it up but couldn't make head nor tail of what I found in Google.

I don't know why a wallet hasn't been released yet that ordinary Joe Soaps like myself can find easy to use.

What is the point of trying to get the general public on board with Ethereum if people are required to have coding experience just to store a few USD worth of Ether?

Considering there is about 15 Billion dollars in the Ethereum ecosystem I can't believe that no one has brought out a wallet that is fit for purpose.

Mist and Ethereum Wallet certainly don't fit the bill.

**Comment by tomholub** [comment] 2017-05-23 16:53
@adamabyss I consider myself a fairly advanced user and I still struggled to get Mist working enough to send a few coins. It's just not there yet.

Now, when Mist/Wallet is starting, it will run this "geth" service on the background. It will run it with standard settings. "geth" is the Ethereum node under the hood that is trying to sync up with the network.

If "geth" was already somehow started before you run Mist or Wallet, the app will just use the one that's already running.

If you run geth yourself first, you get to start it with settings of your choice. `--light` is a switch that will tell get to not really download all Ethereum blockchain history, but just headers or something like that. Anyway, when I did that, my Mist synced and was usable.

Now, this will involve starting `geth` from the command line. The full command should be `geth --light`. I have no clue how to do this on Windows. On Linux or mac you'd just copy this into the terminal, let it run and start Mist/Wallet after that.

Here is some info: https://github.com/ethereum/go-ethereum/wiki/Installation-instructions-for-Windows

I'm **guessing** that when you're ready to run it in the terminal, you'd use `geth.exe --light`. It should print out a warning that Light Mode is an experimental feature or something like that.

**Comment by gryzor2** [comment] 2017-05-25 07:00
Greetings,

I'm hitting this bug as well, on Linux, with 0.8.10 and geth 1.6.1.
This is a real pain and a really blocking bug, I cannot sync my wallet, I cannot manage my accounts.

I managed to "sync" with "geth --light" but then any order I tried was unsuccessful.

Do you happen to know when this can be fixed, please ?

**Comment by tommasog** [comment] 2017-06-11 14:02
Similar issue here, I am using Ethereum Wallet (not Mist) v 0.8.10 (geth-based) on Debian. I downloaded it and tried to set it up freshly on a Core i7 machine with 8 GiB RAM and SSD. Normal sync would take forever, same for the --fast option, now I'm trying the --light but the problem persists: it looks like it's downloading a lot of blocks, but whenever it's close to 90-99% it "resets" the counter and starts again.

I'm confused, and I don't want to rely on a non-Desktop wallet.

**Comment by toshko4** [comment] 2017-06-12 08:02
Same problem here, as described by tommasog. I'm using Kubuntu 14.04 32bit.

**Comment by mkrista** [comment] 2017-06-13 01:17
tomholub it worked for me ! thank you so much all I did was fire up a command line were my chaindata  was.
mine was in .ethereum/geth/chaindata/   (hidden in linux)
then I typed 
geth --light
after that it Dloaded a ton of headers maybe took it 6 mins or so . after that it started just importing one header at a time . I left it run and fired up Ethereum Wallet . it was all sync-ed up
hope this helps someone else !
thank you 
system info
Kubuntu 16.10 
AMD 1800x oc 4.2 air
960 EVO 1TB
32 gig mem 
Nvidia 1070
Internet 70MB Down 6 up

**Comment by jamesray1** [comment] 2017-06-15 21:27
With v. 0.8.10, I've downloaded all of the headers and the blocks are slowly downloading; it downloaded 32,000 blocks overnight. I had issues with my computer before which have been fixed. The internet download speed was about 1 Mbps last night, now it is about 10 Mbps. I have not seen it reset to 0, and I also restarted my computer.

**Comment by drpenny** [comment] 2017-06-19 21:14
I'm using 0.8.10 w MIST on a Mac and seeking to run on testnet.

I ran successfully with older code about a month or so ago -- sync was very reasonable, now stuck.

I deleted chaindata and used: 

./geth --testnet --fast --cache 1024

And sync was quite fast -- got to about 99% in a couple of hours.

Then I started MIST and it just seems stuck at 99%

Any suggestions?

**Comment by drpenny** [comment] 2017-06-19 21:22
Actually, I found if I just deleted chain data then restart MIST (but didn't launch it)  the block download very quickly, but still seems stuck at 99%

![mist sync](https://user-images.githubusercontent.com/17439181/27306515-e908bb24-5513-11e7-8474-d07e89a621d7.png)

**Comment by drpenny** [comment] 2017-06-20 13:27
It completed overnight

**Comment by roadh0use** [comment] 2017-06-27 05:12
I'm having the same problem trying to save blockchain sync to another hdd other then C. It gets close to done then restarts. If I run geth --fast/--light (either one) it will sync but does not save data to E but rather to C. I'm only working with a 128 C drive so it is highly important that the blockchain data is on my E drive.

**Comment by jamesray1** [comment] 2017-06-27 10:43
For me, it is still syncing 6 days after my last post. The computer has been off accidentally a few times (the power cord came out). I don't need to transfer any Ether, let alone urgently.
![2017-06-27 20_42_00-mist](https://user-images.githubusercontent.com/16969914/27583847-297f4c34-5b79-11e7-885b-b7152a4931f4.png)
![2017-06-27 20_42_16-ethereum wallet restarts sync issue 2259 ethereum_mist](https://user-images.githubusercontent.com/16969914/27583848-2983496a-5b79-11e7-886c-6096ecf3f7a2.png)

**Comment by adamabyss** [comment] 2017-06-27 11:29
It's a piece of crap software that is never going to work for me. I bought some Trezors and am going to transfer my Ether to them using MyEtherWallet.

**Comment by jamesray1** [comment] 2017-06-27 13:24
Fair enough, a Trezor is probably more secure and private than a third party website with a server.

**Comment by jamesray1** [comment] 2017-06-27 13:35
Trezor is another way to secure MyEtherWallet, but the Ethereum is still stored using MyEtherWallet.

**Comment by jamesray1** [comment] 2017-06-28 09:15
It's finished syncing on my computer, more or less, just 14 blocks behind now.

**Comment by ArcadeEngine78** [comment] 2017-07-04 19:32
I have been reading along with the same issue on Mac. Can anyone tell me where to find the AppData file on the mac to delete the data and restart?

**Comment by tommasog** [comment] 2017-07-07 07:44
Guys, this thing is unusable! Sorry for the rant, but I disconnected my PC for 24 hours, and after that I cannot sync anymore, even if I let it download overnight it's so slow that it doesn't catch up with the blocks!

**Comment by jamesray1** [comment] 2017-07-09 13:02
I deleted all the chaindata because Mist was crashing. Now it is not crashing but syncing went back to the beginning when it previously had only a few thousand blocks to sync. Now that it has started to sync, can I run geth --fast in geth? I tried closing Mist and opening geth, but nothing happens when I type.

**Comment by jamesray1** [comment] 2017-07-09 13:05
@ArcadeEngine78

See [here](https://github.com/ethereum/mist#installation):

> Config folder
> 
> The data folder for Mist is stored in other places:
> 
> Windows %APPDATA%\Mist
> macOS ~/Library/Application\ Support/Mist
> Linux ~/.config/Mist

[~ is your user home directory](https://superuser.com/questions/211355/what-does-the-mean-in-a-file-path).

**Comment by jamesray1** [comment] 2017-07-09 13:09
@roadh0use I can't remember if it asks where to install the chaindata folder when you install Mist, but you may need to uninstall then reinstall, installing Mist and the chaindata folder on your external HDD E drive.

**Comment by jamesray1** [comment] 2017-07-09 13:16
@frozeman @evertonfraga it'd be really good if you made it easier to install Mist and sync it quickly without having to use the command like, like in these instructions:

https://github.com/ethereum/go-ethereum/wiki/Installation-instructions-for-Windows

**Comment by jamesray1** [comment] 2017-07-12 09:18
I've been stuck on this number for more than a day:
![2017-07-12 19_16_46-](https://user-images.githubusercontent.com/16969914/28110779-be7f2d22-6736-11e7-8da5-b12e7bad2bea.png)
I tried deleting the chain data, and it started again from 0, when previously it had got to the point where it had nearly finished syncing. So I don't see the point of deleting the chaindata again. I'll leave it for longer.

**Comment by jamesray1** [comment] 2017-07-18 03:45
@frozeman @evertonfraga I give up. Already tried deleting the chaindata and restarting. I can't install it on my C drive as there isn't enough space.
![2017-07-18 13_43_47-ethereum wallet restarts sync issue 2259 ethereum_mist](https://user-images.githubusercontent.com/16969914/28299922-29665ca0-6bbf-11e7-80af-c3f7c4d5512a.png)

**Comment by serbazo** [comment] 2017-07-29 12:34
If the your computer's time is off, the sync stalls. Try going to your system clock settings and clicking update time. (Hover over your time -> date and time settings -> internet time -> Change settings -> update now).

**Comment by nicolman** [comment] 2017-09-17 14:45
Hi fox . I have the same problems! after is finish sincing with a command geth --rpc console --fast 2048 !  my ethereum mist 0.9.0 restart in zero ?
I'm on Ubuntu 16.04.2 LTS .
So if you find a solution for that ? it will be good . Thanks

**Comment by sushilraghav** [comment] 2017-12-08 15:52
@adamabyss @jamesray1 @frozeman @tomholub @gryzor2  ///  How much money you charge or Is there someone who can help me or can create a cryptocoin based on ETH Fork or BTC Fork or X11 or IOAT Fork ? Contact me at skype : sushilraghav or email is bitcoinemxmx@gmail.com.

**Comment by evertonfraga** [comment] 2018-01-10 13:58
Please refer to Geth repository. They've discussed about this on their repo.

https://github.com/ethereum/go-ethereum/issues/2639

**Closed by evertonfraga** 2018-01-10 13:58 UTC
Labels: bug, v0.8.9
