### ISSUE TITLE
0.8.6 won't sync last 1000+ blocks

### ISSUE THREAD

**Issue by CaptainSkywave** [ethereum/mist#1316] opened 2016-10-18 07:28 UTC
#### System information

```
Version: `0.8.6`
OS & Version: windows
Node type: default
```

I've tried both the wallet and mist to no avail.
They both scream: need to sync please wait, and every time I open either of them they appear to start sync the last few blocks but then stalls when missing about 1000+ blocks.
All the time the downloading chain structure races along with no end in sight...
If I launch the app it shows my wallets but they have 0 balances - my keystore folder holds all accounts.
What to do? Is a new version coming to solve this?
I can't be the only one with this problem? 
FYI I had the full chain on earlier versions, and the scenario described above is after having done a clean install and downloading the chain from scratch.
I hate to say it, but these constant Ethereum wallet problem issues is starting to wear me out, and wanting to drop ETH completely.
It is not at all user-friendly to a normal UI user as me. 
It can't be good for the future stability and trust for the project?
And no, I don't want to use an online wallet. I have used earlier versions of the wallet locally here on my PC with the full chain downloaded, working fine. It's only after all the DDOS and such in the last many versions that I've had problems opening/using the wallet.

edit: also FYI the win-x64 does not hold the get.exe only now. It has many different files and exe 
![win-x64-folder](https://cloud.githubusercontent.com/assets/8870171/19469232/b873b61c-951a-11e6-9769-c75972af3d74.png)

**Comment by vincc54** [comment] 2016-10-20 06:15
Hello, I have a similary Problem. This synchronisation is very slow. 
I try to synchronize my wallet since two weeks. 
the blocks are created more than I synchronizes.

In the image below I raised client Monday
![image](https://cloud.githubusercontent.com/assets/22951754/19548182/352dc49e-969d-11e6-893c-98762cd23ed2.png)

Sorry for my english

**Comment by mista66** [comment] 2016-10-21 06:58
Could be related to this issue
https://github.com/ethereum/mist/issues/1322

Definitely something wrong, I've tried to sync from several computers all seem to get caught in endless loop as described in issue/1322

**Comment by vincc54** [comment] 2016-10-21 07:33
I solved my problem by deleting folder contentc:\user\%username%\appdate\ethereum\chaindata and reload a sync

**Comment by sboutzen** [comment] 2016-10-23 21:45
Same problem. I am a newcomer and was going to try Ethereum Wallet out. It syncs to a point, then I see a TCP Disconnect in process monitor. Around block 760k, I get the disconnects almost immediately after restarting the application.

**Comment by prashantprabhakar** [comment] 2016-10-24 06:04
hmmm.. I am also facing exactly same issue on my linux machine. This is definitely independent of OS and most probably related to geth 1.4.18. There are lot of issues realted to this version like

- [Accounts doesn't show ethers
](https://github.com/ethereum/mist/issues/1333)
- Last 1000 blocks don't download (I'm stuck on block 2496092 for more than an hour)

- [Blockchain starts resyncing ](https://github.com/ethereum/mist/issues/1322#issuecomment-255317099)

- [Accounts are in keystore folder but Wallet doesn't show them](**https://github.com/ethereum/mist/issues/1308**) (although geth does)

Hope to get some solution soon.

**Comment by meeDamian** [comment] 2016-10-24 13:57
Same happens on darwin :(

**Comment by 9-9-0** [comment] 2016-10-24 23:58
Experiencing this as well on my linux machine.

Tried clearing the data, resyncing from scratch, and every time thus far it hangs on the last thousand blocks, continuously downloading chain structures.

**Comment by 9-9-0** [comment] 2016-10-29 21:53
Any definite fixes for this yet?

As a note: I'm using the latest stable version of geth to fast sync with the latest wallet open to monitor the progress through the UI.

**Comment by prashantprabhakar** [comment] 2016-10-31 03:44
I have not found any concrete solution yet. I just let the syncing go on and finally after 2-3 hours when I checked again, my blockchain was in sync. All blocks were downloaded. And now my account shows my ether balance and everything works good except When I add new accounts or delete accounts from keystore the effect does not replicate in Mist. Mist still shows old accounts. Rest all is good.

**Comment by luclu** [comment] 2016-11-02 22:55
As this issue is caused by the bloated state you won't be relieved until after the [upcoming HF](https://www.reddit.com/r/ethereum/comments/5afory/update_hard_fork_block_number_delay_10312016/?st=iv1itw9k&sh=7f1d3102).

**Comment by 9-9-0** [comment] 2016-11-03 16:47
@luclu Can this bloated state be averted by using syncing with Parity instead?

**Comment by luclu** [comment] 2016-11-03 22:36
@9-9-0 you can try Parity's new *warp-sync* - perhaps it will help.

**Comment by luclu** [comment] 2016-12-08 19:24
I will close this for now as it should be resolved. Please follow this if you still encounter problems:
>Please try to do a fresh re-sync now that the [state-clearing](https://www.reddit.com/r/ethereum/comments/5fob4s/state_clearing_100_complete/) did finish. 
>
>Doing a fresh sync will reduce the blockchain replica on your computer to ~10G and won't take much longer than 1h on a SSD.
>
>Please make sure to have the [latest version of Mist / Ethereum Wallet](https://github.com/ethereum/mist/releases) installed and follow [this how-to](https://ethereum.stackexchange.com/questions/6554/i-am-having-trouble-doing-the-initial-sync-of-ethereum-wallet-what-can-i-do-to/6555#6555) to reset the chaindata folder and initiate the fresh sync.

**Closed by luclu** 2016-12-08 19:24 UTC
Labels: sync

**Comment by picojoule** [comment] 2017-07-27 03:25
i seem to still be facing this issue as of yesterday. is there an active issue about this?

![image](https://user-images.githubusercontent.com/1388908/28653089-3e0afabc-72a9-11e7-93aa-2f417b515527.png)

**Comment by mauricelacerda** [comment] 2017-08-25 02:23
Hi guys,

I'm having the same problem as everyone else it seems. Is there a way I can restore my wallet with another client using my private keys?

I'm done with Mist...

I already have my Trezor to use with MyEtherWallet, but I have to get my ether out of Mist...

Anyone have any ideas?

Thanks!

**Comment by 9-9-0** [comment] 2017-09-03 04:10
@mauricelacerda AFAIK, you need a synced node to broadcast the transaction to the network. In the case of Mist, your node is synced locally with geth. I believe you can use [MEW's node](https://www.myetherwallet.com/#send-transaction) if you import your keyfile to send the ETH stored in that file to a new address given that you trust them enough.

**Comment by mauricelacerda** [comment] 2017-10-12 18:33
@9-9-0 Thanks for the tip! That's exactly what I did. I now transact with Trezor.io in MEW.
