### ISSUE TITLE
Ether without wallet

### ISSUE THREAD

**Issue by Itojanovich** [ethereum/mist#1734] opened 2017-03-14 18:24 UTC
Hi! I've an account in Mist, i want to create a wallet, but i don´t have Ether.   I send ether to my account trough Shapeshift and Poloniex, but i dont receive the ether in my account.    It´s becouse i don´t have a wallet?  

Thanks!

**Comment by luclu** [comment] 2017-03-14 18:38
Please make sure that your wallet is fully synced

(Duplicate of https://github.com/ethereum/mist/issues/1720)

**Closed** 2018-02-01 18:43 UTC
Labels: Status: Duplicate
