### ISSUE TITLE
no etherum https://blockchain.info/address/1CRNSDJTJyHBwWVAynkHufmYsteFsmnNLh done all the checks ether payment confirmed but nothing in my wallet

### ISSUE THREAD

**Issue by grtt** [ethereum/mist#2068] opened 2017-03-27 17:56 UTC
#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by luclu** [comment] 2017-03-31 23:27
Closed as duplicate of #2070.

**Closed** 2017-03-31 23:29 UTC
Labels: duplicate
