### ISSUE TITLE
Ethereum Wallet not fully syncing on Windows 10

### ISSUE THREAD

**Issue by chrishobcroft** [ethereum/mist#2747] opened 2017-07-11 17:01 UTC
``````
Version: 0.8.10
OS & Version: Windows 10 Pro
Node type: geth; Ethereum Wallet
Number of blocks synchronized: "100 blocks left, 53%"
``````

I have been trying to sync Ethereum Wallet for 2 weeks now, and it is still not showing any funds from my shapeshift transfer.

**Link to Bitcoin transaction**

https://blockexplorer.com/tx/7319a3c61105173b28213dc898ef9084ac41b0820acc32fd9f20c3dbf7ea93d9

**Screenshot**

![image](https://user-images.githubusercontent.com/2212651/28079561-2dc445ce-6669-11e7-9fe6-a44a85314862.png)

**Comment by mauricelacerda** [comment] 2017-07-11 23:58
I have the same issue, but I'm on Fedora 25.

It stops syncing at 99% and it simply won't complete. I've made two Shapeshift transfers already, I've confirmed the funds ARE in my wallet through Etherscan, but they won't show up in my wallet.

Many people report the same issue since 2016, and I couldn't find a definitive solution yet.

How is this possible?

**Comment by garretlaxton** [comment] 2017-07-12 03:09
First you should make a backup of your `keystore` folder to a USB, you can then use myetherwallet.com to access your ETH using your backup.

**Comment by evertonfraga** [comment] 2017-09-28 19:39
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)


I'm closing this issue. Should you have any trouble, please refer to this canonical issue: https://github.com/ethereum/mist/issues/3097

**Closed by evertonfraga** 2017-09-28 19:39 UTC
Labels: v0.8.10
