### ISSUE TITLE
Wallet stops syncing at 1,200 blocks left

### ISSUE THREAD

**Issue by creatoratnight** [ethereum/mist#2130] opened 2017-04-11 10:46 UTC
#### System information
``````
Version: `3.8.5`
OS & Version: windows
Node type: `geth`
``````

![ether](https://cloud.githubusercontent.com/assets/26556663/24905252/9a6c0804-1eb3-11e7-9dd3-ecfaa7401ab2.png)

![ether2](https://cloud.githubusercontent.com/assets/26556663/24905411/36578f5e-1eb4-11e7-99bb-e8caaa20e29a.png)

[node_logs.zip](https://github.com/ethereum/mist/files/912900/node_logs.zip)

My wallet get's stuck when there are only 1,200 blocks left to sync.
I've tried removing the blockchain folder several times without succes. My computer clock is only of by 0,0019 seconds, so that couldn't be the problem. I've also installed the latest version of Mist but it won't sync at all.

I also wonder why it has so much troubles finding peers, wouldn't it be easy with so many people using Ethereum?

Hopefully someone can help me solve this issue, I'm trying to do a transaction for multiple days now but it just won't sync those last 1,200 blocks.

Let me know if I need to provide more info, and thanks in advance! : )

**Comment by joediaz1** [comment] 2017-04-11 16:31
I have this same issue it stops syncing on the last blocks 74 or 54 and stops the weird thing is its stilll connected to like 25 peers.

**Comment by joediaz1** [comment] 2017-04-11 16:31
IT NEVER COMPLETES THE SYNC

**Comment by joediaz1** [comment] 2017-04-11 16:32
I cant even use this damn wallet. like I sent some ETH to it and that block should of been caught up to the wallet as i sent it last week. and it just doesn't show in the wallet

**Comment by joediaz1** [comment] 2017-04-11 16:33
and the transaction was confirmed I double checked the address

**Comment by luclu** [comment] 2017-04-12 03:06
@creatoratnight please make sure you are using the latest version `0.8.9`.

#### Some generic advice:

Please, make sure you are running the [latest version](https://github.com/ethereum/mist/releases) and your node is **fully** synced.
Although this may take between 1h (SSD) and 10 hours (HDD) you should be able to see a progress bar on the *splash-screen* or in the *main-window*.

Further recommendations: 
- check your account's balance using http://etherscan.io
- make a backup of all account's keyfiles via `menu -> accounts -> backup -> accounts`
- should the initial sync take very long, consider following [these instructions](https://ethereum.stackexchange.com/questions/6554/i-am-having-trouble-doing-the-initial-sync-of-ethereum-wallet-what-can-i-do-to/6569) to speed it up
- if the peer count stays at 0 and it does not sync, verify your firewall settings
- consider using http://myetherwallet.com in the meantime

If this didn't solve your issue, please follow [these instructions](https://github.com/ethereum/mist/issues/new) and upload the `node.log` files:
> - Log files
>   - go to menu -> accounts -> backup -> application data
>   - zip and upload node.log and all other node.log.X files

**Comment by creatoratnight** [comment] 2017-04-13 17:25
@luclu Thanks for your reply! Downloading the latest version of Ethereum Wallet (not Mist) helped me to get everything synced again and I was able to send my transaction. : )

**Comment by AmesEla** [comment] 2017-04-13 19:50
I am having some serious issues with my wallet and one of your guys prematurely closed the thread thinking it is a common issue with updating the ledger. It is NOT! And now all the coin I mined disappeared! Please see this thread and reopen until my issue is solved. I would greatly appreciate as I am beyond upset about losing all the Ether I mined, and I want to get it back!

https://github.com/ethereum/mist/issues/2142

**Comment by davedavis** [comment] 2017-05-11 05:19
@createoratnight

Did you just install the wallet instead/in tandem? Did that resolve it or did you need to do anything else? 

Did your wallet install use the same chain data?

**Comment by AmesEla** [comment] 2017-05-11 23:31
I just let it run for days and it finally updated it was very tedious and terrible. And then I learned that any of the ether I earned in the test net is worthless. I lost it all as well so I can't test for that. I would like very much some advice on the best way to mine if they are him is. Is there someway to use the Wallet actually mine for real if Arionne? Or is there something else I can use? All of the information I see seems to be oriented to people who are more technical than myself. I would love a tool that I can just run on my system

___________________________
The only constant is change.

**Comment by evertonfraga** [comment] 2017-09-28 19:49
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist

**Closed by evertonfraga** 2017-09-28 19:49 UTC
Labels: v0.8.9
