### ISSUE TITLE
Wallet syncs, then on wallet restart it ends up synching back around block 4,340,000 

### ISSUE THREAD

**Issue by njwest** [ethereum/mist#3569] opened 2018-01-15 02:12 UTC
- [X] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.
```
Version: `0.9.3`
OS & Version: macOS Sierra 10.12.6
Node version: `geth 1.7.3-stable` 
Number of blocks synchronized: All, then back to around 4,370,000

SSD: 1 TB capacity, 521GB free
```
Have been trying to several days to synch this wallet, downloaded fresh from version 0.9.3. My sync method:

1. `geth removedb`
2. `geth --syncmode "fast" --cache 1024 console`
3. Open ethereum wallet.

The wallet appeared to synch over a period of a day after I ran the above commands. The wallet would open on click, and showed over 4,900,000 blocks. 

After writing a basic smart contract, I got the following error: `Unable to connect to socket: timeout`

I restarted my wallet, now it is synching from around 4,370,000 again.

**Comment by Narratheon** [comment] 2018-01-17 19:24
Same issue here, it started synching around block 4.190.000 after a restart. It took half another day to get to ~5.000.000 again. Now it only has to download the blocks that weren't synched because of the closed wallet.

**Comment by evertonfraga** [comment] 2018-02-01 18:35
Duplicate of #3097

Please refer to [this issue](https://github.com/ethereum/mist/issues/3097) for more information and our [Wiki](https://github.com/ethereum/mist/wiki) for troubleshooting steps.

**Closed by evertonfraga** 2018-02-01 18:35 UTC
Labels: Status: Triage
