### ISSUE TITLE
Node Crashed - Mist Wallet 0.5.0 (Beta 8) - Windows 7

### ISSUE THREAD

**Issue by Film54** [ethereum/mist#232] opened 2016-03-03 17:16 UTC
![node-crash](https://cloud.githubusercontent.com/assets/17620974/13502625/8c56beca-e120-11e5-862b-6871dc72ac01.jpg)

Also, when I attempt to run geth in console, it also gets stuck at "starting server"

![node-crash-2](https://cloud.githubusercontent.com/assets/17620974/13503054/67fdb5ea-e122-11e5-9b6a-ac1415caeea3.jpg)

**Comment by dobcrypto** [comment] 2016-03-03 17:33
The same problem =(
https://github.com/ethereum/mist/issues/231

**Comment by frozeman** [comment] 2016-03-04 10:10
Thanks, duplicate of #235

**Closed by frozeman** 2016-03-04 10:10 UTC

**Comment by alexvandesande** [comment] 2016-03-15 16:01
Thanks for reporting. I'm also linking this issue: https://github.com/ethereum/mist/issues/243
