### ISSUE TITLE
Heavy Memory Leak

### ISSUE THREAD

**Issue by taoteh1221** [ethereum/mist#738] opened 2016-05-28 22:40 UTC
Node type: geth
OS: linux ubuntu
Network type: main
Mist version: 0.7.4

See screenshot. This is on a 4GB RAM system. System froze right after I barely got this screenshot. Highest wallet thread RAM usage hit 2.6GB max before system froze. Mist wallet memory usage increased slowly over 3GB RAM used until system was not responsive.
![snapshot1](https://cloud.githubusercontent.com/assets/1760489/15630315/78494af2-2503-11e6-8353-07eaf9aaf815.png)

**Comment by hautdoge** [comment] 2016-05-29 05:44
I have the same issue in Windows 10 64bit. When I try to watch the DAO contract, the Wallet completely freezes, and I can see it eating up 10GB+ of my RAM

**Comment by m0se** [comment] 2016-05-30 11:39
I can confirm this as well, strange enough that I didn't experience this with the same Mist/geth version on my old slow 4GB Debian MBA,.. but now on my new machine with 16GB one of the "Ethereum-Wallet" processe eats all my memory.

I as well watch Maker/theDAO token and contracts.

Node type: geth 1.4.4-stable-94ad694a
OS:Linux 4.5.0-2-amd64 / Debian stretch
Network type: main
Mist version: 0.7.4

**Comment by luclu** [comment] 2016-05-30 15:14
Thank you for reporting! 
I will close this issue as it is a duplicate of https://github.com/ethereum/mist/issues/726.
Please feel free to append any new/missed out information over there.

**Closed by luclu** 2016-05-30 15:14 UTC

**Comment by larspensjo** [comment] 2016-06-01 09:23
This report (memory leak in Mist) is not the same as #726 (memory leak in geth).

I added theDAO as a watch contract, Mist got unresponsive, and is currently using 17GB of RAM.

**Comment by luclu** [comment] 2016-06-01 10:02
@taoteh1221 This is caused by an unoptimized event-handler which bombardes geth with requests. Both issues are the same although the title of #726 is misleading.

**Comment by taoteh1221** [comment] 2016-06-01 17:45
@luclu I agree with you, it was @larspensjo who said it was different, not me. When I created this issue I only saw geth in the subject line on that other issue, so I though it was separate.

**Comment by luclu** [comment] 2016-06-01 23:32
@taoteh1221 my fault! sorry for that ;=)

**Comment by taoteh1221** [comment] 2016-06-01 23:40
@luclu No problem, thanks for all your hard work! :-)

**Comment by FloydStash** [comment] 2017-11-15 00:13
i'm experiencing the issue where the memory used will just skyrocket to 3k then get's stuck and starts soaking up all my memory to the point that my fps becomes a slideshow on desktop even.

process causing it Geth.exe
average time till it reaches 3k stuck point = 10-20 mins
Version 0.9.2

**Comment by taoteh1221** [comment] 2017-11-15 01:04
@FloydStash I'd open a new issue in the get repo here: https://github.com/ethereum/go-ethereum/issues
