### ISSUE TITLE
ether not showing in my wallet

### ISSUE THREAD

**Issue by fabiorem** [ethereum/mist#2412] opened 2017-06-01 21:00 UTC
Downloaded the Ethereum Wallet nearly one week ago, version 0.8.10. 

Funded with 0.25 Ethereum using my bitcoin client, which is Btc-Core. Theres is a option in the Ethereum wallet to do that. Very useful, I think. 

Last five or six days were trying to synch it. Had to use geth with --fast tag to be able to finish, my computer stayed on for four days, constantly. 

Finished right now, and... theres 0 (ZERO, nothing) Ethereum in my wallet. 

Transaction address show more than a thousand confirmations: https://blockchain.info/address/1HzT3xeMNdKbiix3qVyww29GJAb5wi6pF2

Value is 0.01943974 BTC. The money is not showing in my wallet. 

#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by jcantieri** [comment] 2017-06-02 03:10
I have the same problem, but still not fully synced yet (2 full days but it keeps going up and down around 1380600) but i transferred my coins to my wallet and can't see them yet--if I use the fast tag to finish, will my wallet be affected?  cheers xx

**Comment by UncleWetnaps** [comment] 2017-06-02 06:47
Likewise if anyone gets any solid answers pass them on!

**Comment by fabiorem** [comment] 2017-06-02 14:41
Last night the Ethereum Wallet restarted the synch. That's the reason why it didn't showed any ETH, it was not fully synched. Today I restarted Geth and put the --fast command again, now with --cache=8192, since I have 16gb of RAM. Some three hours passed and it is still synching, even with --fast --cache=8192. However, I installed Parity and was able to access my account on Geth through there, and the 0.25 ETH is now showing. My only concern is that Parity is used through the web browser, which I dont think it is safe. I wanted to have a copy of the blockchain stored in a external drive, just in case.

**Comment by glad-zilla** [comment] 2017-06-02 21:35
So how did you use Parity to access you account?

**Comment by Dbabcock001** [comment] 2017-06-02 23:43
I have had the same problem.using version 0.8.9 bought 1.29 ether weeks ago and still nothing in my wallet. Sent from Coin base which shows transaction successful. Etherscan shows the  ether in my wallet but  my Ethereum wallet still reads 0. would it help to download new version? any tips would be appreciated.

**Comment by fabiorem** [comment] 2017-06-03 19:26
Theres a option in the Parity web page called Geth Keystore, so I imported the key from there, and used the downloaded blockchain through Geth to access it. 

But Mist is still not working. The download was complete yesterday, I got 21gb of data in --fast mode. But when I opened Mist, the connection failed. Tried more times, until it connected, but then started to overwrite from block zero, the same issue that had happened before. Fortunatelly, I made a copy of the blockchain this time, so I close Mist and restored the data. Will be using Parity instead.

**Comment by jcantieri** [comment] 2017-06-04 01:06
@fabiorem thank you --i'm trying the same thing. we'll see if i can figure this out :)

**Comment by fabiorem** [comment] 2017-06-04 01:49
Did nothing more. But I downloaded the blockchain through Geth before this, until it reached 21gb. I used the --fast command.

**Comment by jcantieri** [comment] 2017-06-05 00:25
Ah I see, thanks. Mine still is stuck downloading unfortunately, hopefully will start again soon ugh.

Janice Cantieri
Fulbright National Geographic Storytelling Fellow
Comer Scholar for Environmental Reporting @ Medill School of Journalism
Northwestern University

**Comment by nicholas104** [comment] 2017-06-06 01:45
so I have also had massive problems with this mist and ethereum wallet. my honest opinion of this wallet is it is shit !!! 

I have been trying to download this blockchain for a month now and have literally tried everything... 

my ether is in the account, as I have seen it on the parity account. 

is there any way of sending that ether from your parity account to another wallet as I am never going to use this stupid mist wallet.......

**Comment by jcantieri** [comment] 2017-06-06 15:09
is there any way to restart the syncing? mine is still totally stuck but not sure how to reset it. thanks!

**Comment by Haisenbang** [comment] 2017-06-08 21:03
"Accounts can't display incoming transactions, but can receive, hold and send Ether. To see incoming transactions, create a wallet contract to store Ether"
I create a wallet contract a fives times and still not working. What can I do?

**Comment by garretlaxton** [comment] 2017-06-08 21:50
@Haisenbang you don't need to create a contract, you just need to let your wallet fully sync. You can use myetherwallet.com if you'd like to access your ETH while your wallet syncs.

**Comment by JX88230** [comment] 2017-06-10 11:27
@fabiorem Hi all, I am new to the cryptocurrency world too. Have encountered the same issue - downloaded Ethereum Wallet from the official site, created an account, bought Ether (before the wallet has been fully synced), Ether not showing in the wallet, frustrated.

Here is how i solved it and some learning
1. Check your wallet balance at etherscan.io or myetherwallet.com using your account address - if the Ether is there. you can relax.
2. You can 1) wait for your Ethereum wallet to be fully synced to show the balance (in my case, it look more than a week and it is still not fully synced. maybe because my computer is old) 2)  import your Ether to another wallet. 
3. I chose to import my Ether to a different application. I was recommended to use Jaxx because of its user-friendly interface for non-technical people. Here is what i did: 
1) download the Jaxx application to my phone; create a wallet 
2) go to https://www.myetherwallet.com/#send-transaction. here i chose the Keystore File to access my wallet. I uploaded my Keystore File (you can find it in your Ethereum wallet => Account => Backup). 
3) Once the Keystore File is uploaded, I can view my private keys and download the paper wallet (the QR code with your public and private key); I downloaded my paper wallet
4) Go to Jaxx application on my phone. Open Tools => Transfer Paper Wallet. Here it asked me to scan the private keys (QR code) of the wallet i wish to transfer from. I confirmed. 
5) The Ether got transferred to the new account on Jaxx. 

I think here the key is if you just want to make sure you Ether is there and not missing: just check the balance online (Step 1) . If you want to trade, you either have to wait for the wallet to fully sync or use another application (https://www.myetherwallet.com or Jaxx) to access your wallet with your private keys. 

If anyone technical knows the pros and cons of each application, welcome to comment. 

Hope this is helpful.

**Comment by fabiorem** [comment] 2017-06-10 16:43
But in this case of Jaxx, it would not store the ether inside your cellphone, since the blockchain have 21gb, right? I would need a solution to store the blockchain in a external hard drive, alongside the wallet (or keystore) to use as a cold storage. I do this with bitcoin already as I dont fully trust leaving all the money in the exchanges. 
The keystore import is also available on Parity, that's how I got access to the ether. But I don't known in what Mist folder the key is located. I copied the address, tough.

**Comment by jcantieri** [comment] 2017-06-13 01:14
Thank you for this! I haven’t been able to access mine on Ethereum Wallet or on Parity yet even though it says I’ve downloaded most of the blockchain. 

I am trying your approach with Jaxx now—I am at Step 4—but I don’t see a way to “Confirm” after it scanned my paper wallet. There is no button on the screen to click “ok” even, just scans it and then stays there with nothing confirmed. Did this appear differently for you? Hoping it goes through :)

Thanks again!

Janice Cantieri
Fulbright National Geographic Storytelling Fellow
Comer Scholar for Environmental Reporting @ Medill School of Journalism
Northwestern University

**Comment by jcantieri** [comment] 2017-06-13 01:29
Nevermind I got it!! Woohoo finally! Thank you so so so much! 

Janice Cantieri
Fulbright National Geographic Storytelling Fellow
Comer Scholar for Environmental Reporting @ Medill School of Journalism
Northwestern University

**Comment by evertonfraga** [comment] 2017-09-28 20:02
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist

**Closed by evertonfraga** 2017-09-28 20:02 UTC
Labels: v0.8.10

**Comment by braravind** [comment] 2018-02-24 04:49
Hello,

 I didn't get ether balance in wallet.My client send ether to my address before two days ago.But i did not get yet why ?

After how many day's getting balance ?
