### ISSUE TITLE
On my Mac I can't seem to send money from my wallet to another wallet

### ISSUE THREAD

**Issue by ayubx9900** [ethereum/mist#3401] opened 2017-12-09 12:14 UTC
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.0.0`
OS & Version: windows/linux/osx
Node version: `geth 0.0.0` 
Number of blocks synchronized: 0
```

**Comment by kevinquillen** [comment] 2017-12-09 23:11
Same issue. I have tried to do about 8 transactions, they sat for hours (some for a few days), no confirmations, and it never appeared on etherscan. MacOS High Sierra

**Comment by rwdim** [comment] 2017-12-10 22:53
That's happening on Linux too.. the just sit pending. No errors. They don't show up in Etherscan unless you search by sending or originating account... Odd thing... Receiving account *IS NOT* what I entered in the UI. It's completely different. Is this normal?

**Comment by ayubx9900** [comment] 2017-12-10 22:58
Here is an update.  It took a couple of days for my eth to transfer over. However I think the problem was that I wasn't update with the latest block. I was approximately at 50% updated when it fully sent. I am unsure why there was such a huge delay.

**Comment by ayubx9900** [comment] 2017-12-10 23:00
@rwdim I think you may have to wait for a couple of days like I did. Make sure that mist is updated with the latest block. It may send everything once it is updated

**Comment by rwdim** [comment] 2017-12-10 23:01
I have been in sync for a week..  Have sent and received before, and it was instantaneous... and now nothing...  Also, Creating contracts does not work. It just sits spinning on "Creating..."

**Comment by rwdim** [comment] 2017-12-10 23:03
@ayubx9900 .. If ethereum takes "a couple days" to send crypto, they need to close their doors right now. It should be a couple seconds at worst.

**Comment by kevinquillen** [comment] 2017-12-10 23:04
None of mine ever transferred. I can only send in,
Not send out. This is ridiculous.

**Comment by ayubx9900** [comment] 2017-12-10 23:07
@rwdim It shouldn't take a couple of days. For me it happened to be that. I was frustrated and I watched a couple youtube videos trying to explain that if I wasn't in sync it wouldn't work. However are you running the latest update of mist ? Just wondering because I wasn't when I started my first transfer

**Comment by rwdim** [comment] 2017-12-10 23:22
So many errors in my console when I open dev tools.. Guys, this is a financial tool... if your bank account website had these errors and ignored them, you'd be burning down the buildings...  Why aren't these errors being trapped and reported back across the network to the devs automagically?

**Comment by kevinquillen** [comment] 2017-12-11 02:04
I am deleting the chaindata folder and trying again as others have said. All this trouble over some Eth...

**Comment by kevinquillen** [comment] 2017-12-11 13:28
Okay. I had to delete the chaindata folder in macOS (~/Library/Ethereum) and let it resync for what seemed like six hours. I did not touch the app at all and did not let the computer go into suspend mode. 

The first time I set it up, I thought it was stuck, and clicked "Check for node updates" a few times because its not clear when setting up the wallet if activity is happening or not.

This time my transaction sent in about a minute. There must be some bug here.

**Comment by rwdim** [comment] 2017-12-11 15:50
I did the same thing (on Linux) and it never syncs.. it's always 155 blocks
back and my balance is zero with no confirmed transactions.

**Comment by alexvandesande** [comment] 2018-02-08 16:37
Sorry about the experience. Pending transactions probably meant that the gas price was too low, which can happen in days that the network is very clogged. We will work on making that clearer on the transaction window

I am closing this issue due to inactivity. **Please feel free** to reopen should you still have some considerations about it.

**Closed by alexvandesande** 2018-02-08 16:37 UTC
Labels: Status: Triage
