### ISSUE TITLE
Strange items in the last transactions

### ISSUE THREAD

**Issue by Cervenka** [ethereum/mist#815] opened 2016-06-14 11:35 UTC
Node type: geth
OS: osx
Network type: main
Mist version: 0.7.4

I'm seeing transactions that do not belong to me.

![bildschirmfoto 2016-06-14 um 13 29 52](https://cloud.githubusercontent.com/assets/2852105/16041160/4259dac2-3234-11e6-8941-d3c034957a91.png)

**Comment by luclu** [comment] 2016-06-14 11:52
This is caused by `0.7.4.`'s event-logging notifiying you when token transfers happen to your watched contracts. This will be fixed on the next release.
I will close this as duplicate of https://github.com/ethereum/mist/issues/739.

**Closed by luclu** 2016-06-14 11:52 UTC
