### ISSUE TITLE
block chain not syncing

### ISSUE THREAD

**Issue by coolminer104** [ethereum/mist#1336] opened 2016-10-22 07:39 UTC
```
C:\>geth --fast --cache=1024
I1022 12:25:13.705924 cmd/utils/flags.go:678] You're one of the lucky few that w
ill try out the JIT VM (random). If you get a consensus failure please be so kin
d to report this incident with the block hash that failed. You can switch to the
 regular VM by setting --jitvm=false
I1022 12:25:13.705924 ethdb/database.go:82] Alloted 1024MB cache and 1024 file h
andles to C:\Users\Administrator\AppData\Roaming\Ethereum\chaindata
I1022 12:25:13.799682 cmd/utils/flags.go:842] ----------------------------------
--------------------------------------------------------------
I1022 12:25:13.799682 cmd/utils/flags.go:843] Geth is currently configured to SU
PPORT the DAO hard-fork!
I1022 12:25:13.799682 cmd/utils/flags.go:844] You can change your choice prior t
o block #1920000 with --support-dao-fork or --oppose-dao-fork.
I1022 12:25:13.799682 cmd/utils/flags.go:845] After the hard-fork block #1920000
 passed, changing chains requires a resync from scratch!
I1022 12:25:13.799682 cmd/utils/flags.go:846] ----------------------------------
--------------------------------------------------------------
I1022 12:25:13.799682 ethdb/database.go:169] closed db:C:\Users\Administrator\Ap
pData\Roaming\Ethereum\chaindata
I1022 12:25:13.799682 ethdb/database.go:82] Alloted 1024MB cache and 1024 file h
andles to C:\Users\Administrator\AppData\Roaming\Ethereum\chaindata
I1022 12:25:13.987196 ethdb/database.go:82] Alloted 16MB cache and 16 file handl
es to C:\Users\Administrator\AppData\Roaming\Ethereum\dapp
I1022 12:25:14.002823 eth/backend.go:172] Protocol Versions: [63 62], Network Id
: 1
I1022 12:25:14.002823 eth/backend.go:201] Blockchain DB Version: 3
I1022 12:25:14.299721 eth/backend.go:247] WARNING: Wrote default ethereum genesi
s block
I1022 12:25:14.299721 core/blockchain.go:206] Last header: #0 [d4e56740.] TD=171
79869184
I1022 12:25:14.299721 core/blockchain.go:207] Last block: #0 [d4e56740.] TD=1717
9869184
I1022 12:25:14.299721 core/blockchain.go:208] Fast block: #0 [d4e56740.] TD=1717
9869184
I1022 12:25:14.315348 p2p/server.go:313] Starting Server
I1022 12:25:15.971729 p2p/discover/udp.go:217] Listening, enode://fad3152919c165
2c32865948c2c701f086621dd971e5a70c2f1261180242c6e096af147bd68edb64731727eaf0b12a
c83e8d5ed1f73ab5f76f370bff9105d27f@[::]:30303
I1022 12:25:15.987355 p2p/server.go:556] Listening on [::]:30303
I1022 12:25:15.987355 node/node.go:296] IPC endpoint opened: \\.\pipe\geth.ipc
I1022 12:25:48.766735 p2p/discover/ntp.go:58] ----------------------------------
---------------------------------------------------
I1022 12:25:48.767736 p2p/discover/ntp.go:59] System clock seems off by 12h26m12
.645592571s, which can prevent network connectivity
I1022 12:25:48.767736 p2p/discover/ntp.go:60] Please enable network time synchro
nisation in system settings
I1022 12:25:48.767736 p2p/discover/ntp.go:61] ----------------------------------
---------------------------------------------------
```
It stuck here.. please help!!

**Comment by luclu** [comment] 2016-10-22 11:36
Duplicate of https://github.com/ethereum/mist/issues/947

**Closed by luclu** 2016-10-22 11:36 UTC
Labels: duplicate
