### ISSUE TITLE
Ethereum Wallet Password Recovery

### ISSUE THREAD

**Issue by onesunbeingnow** [ethereum/mist#256] opened 2016-03-05 18:12 UTC
Hi

I recently moved some ETH to the Ethereum Wallet for the first, but I must have committed a typo by accident when creating the password on login as I cannot send it from the account now.

Can someone please help me understand how to use 'pyethrecover-master' https://github.com/burjorjee/pyethrecover as I have no clue how to.

I can pay for the time you help me also. If it is successful I do not mind paying upwards of 200 USD.

Many thanks, Onesun.

**Comment by Kosmyn87** [comment] 2016-03-07 00:34
I`m in the same boat as you , pls let me know if you find something out thanks in advance.

**Comment by onesunbeingnow** [comment] 2016-03-07 04:35
try restarting your computer, it worked for me

**Comment by frozeman** [comment] 2016-03-07 10:09
@Kosmyn87  Please restart and try again. This seems to be an connection issue with windows named pipes, which sometimes "drops"

**Comment by Kosmyn87** [comment] 2016-03-07 13:27
nope still not working sadly , trying to figure out how to use python.

**Comment by onesunbeingnow** [comment] 2016-03-07 18:20
well whatever you do do not give what you think your password is to anyone,
you can always pay someone to teach you how to rebuild your password
yourself, you don't want some opportunistic scammer to rob you, I had some
guy try that on me, don't click the link they send you either, they can
trace you IP and hack your computer

**Comment by Molite** [comment] 2016-03-08 10:51
This happened to me then it started working again a couple things you might try

1 if you have more than one wallet in your keystore folder you might try pulling them out and restarting you computer one at a time. I had some that I didnt remember creating if they are on top it might be trying to access the wrong wallet. On a pc it is C:\Users\_Username_\AppData\Roaming\Ethereum\keystore

2. Make sure your entirely updated with the ethereum blockchain.  Not sure if this matters but mine didnt work until i was in sync with current block.

hopefully this helps it sucks being locked out

**Comment by Kosmyn87** [comment] 2016-03-10 00:59
Thank you i tried everything , i`ll keep researching regarding how to use python to recover the password , since i know half of it :D cheers , best of luck.

**Comment by ethereumyogi** [comment] 2016-05-09 22:38
I'm also stuck don't have any idea on how to use python

**Comment by msam4444** [comment] 2016-05-10 00:03
Each account in Mist may have a different unique password depending where account was from originally, ex. if it's imported from different jason files or from presale account. The original Mist account that you also create for the first time has its own password that you first used to create it.  This may be obvious to some, but could also be the cause here.

**Comment by luclu** [comment] 2016-05-19 11:14
Also please have a look at this and report back here! #669

**Comment by luclu** [comment] 2016-05-19 21:53
I will close this for now. Feel free to continue to discuss!

**Closed by luclu** 2016-05-19 21:53 UTC
Labels: bug

**Comment by dilovancelik** [comment] 2017-02-08 15:31
Hey onesunbeingnow, 

did you have any success with https://github.com/burjorjee/pyethrecover, I'm going to try it with the never wallet types. 

I will get back to you when I have looked at it, but if you have some experience, let me now.

Br,
Dilovan

**Comment by ethereumyogi** [comment] 2017-02-08 19:43
I highly appreciate the attempt

**Comment by dilovancelik** [comment] 2017-02-17 14:50
I made it work, but not with pyethrecover. I used what these two wonderful people had made.
http://ethereum.stackexchange.com/questions/6845/how-to-apply-pyethrecover-py-on-v3-json-transfor-v3-json-to-v1/12249#12249

If anyone is having issues implementing what these guys have made, let me know. I'm willing to help with consultancy services on how to implement it. However if you know python your self, it should not be difficult to implement the solutions used by these guys.

**Comment by Danword93** [comment] 2017-03-15 20:15
Hi! Amm... well, I have an ETH Wallet and it was supposed that I wrote down the correct **password** but is **not working** sadly and already have some ETH inside of that wallet. I **don't know how to use python** and of course I don't how to implement the solution. So can someone **help** me with that please.

**Comment by dilovancelik** [comment] 2017-03-15 20:24
Hey Dan, 
What kind information do you have on your password? Is it possible for you to narrow it down to some combination of words (does not matter if there is several thousand possible combinations). 

you can contact me directly on dilovan.celik@gmail.com, maybe we can figure something out. 

Br,
Dilovan

**Comment by dilovancelik** [comment] 2017-03-15 20:55
Haha :) Great indeed. Now remember to have it somewhere you remember. A lot of people store it offline (notebook and such). Another important thing to remember is to back up your wallet file in case something were to happen with you computer (I have mine on a usb drive as well).

**Comment by jeroenvandisseldorp** [comment] 2017-06-14 09:13
I found pyethrecover a mess to run, but figured out a way to do without, using the `geth` command line tool. My case required scanning the permutations of possible passwords as supported by `pyethrecover`. Here's the simplified python script that generates those permutations:

```
import itertools
import sys
print(sys.version)

# Taken from pyethrecover
combinations=[
    ('hello', 'bonjour', 'hola'),
    ('', 'mister', 'president'),
    #('brother', ),
    ('smith', 'jefferson')
]

pwds=[]
def generate_all(el, tr):
    if el:
        for j in range(len(el[0])):
            for w in generate_all(el[1:], tr + el[0][j]):
                yield w
    else:
        yield tr

pwds = itertools.chain(pwds, generate_all(combinations,''))
pwds_l = list(pwds)
n_pws = len(pwds_l)

print('Number of passwords to test {0} '.format(n_pws))

i=1
found = 0
for l in pwds_l:
    print "%s" % l
```

You can run it with:
`python generate.py > pass.txt`

After that I used the `geth` command line tool to test possible passwords. The following bash script tries them all on the first available account (account #0):

```
#!/bin/bash

for PASS in `cat pass.txt`; do
	echo "Trying $PASS"
	echo "$PASS" | geth account update 0 2>&1 | grep Unlocked
	if [ "$?" = "0" ]; then
		echo "Found: $PASS"
		exit 0
	fi
done

exit 1
```

After only 10 minutes I found my own password using a generated list of +- 2000 passwords, so I'd thought I'd share the mechanism for others to benefit. Hope it helps!

**Comment by ethereumyogi** [comment] 2017-06-14 23:33
Thank you so much for the help if I recover it I will send you some the ethers I have lock up

**Comment by Jlafinancial1** [comment] 2017-11-13 22:20
I don't believe I forgot my password after all I used it to login. why is there not a password recovery set up
or a 1 800 customer service line. Any help is worth 0.01 of bit coin or 65 dollars usd
