### ISSUE TITLE
Wallet will not since stuck at 73 blocks left. I have deleted the block chain 5 times and done fast with set cache via geth in command prompt still same issue all five times fresh load still the problem.

### ISSUE THREAD

**Issue by arsine37** [ethereum/mist#2547] opened 2017-06-17 18:57 UTC
#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by evertonfraga** [comment] 2017-06-21 22:29
Hi @arsine37

Can you check the highest block that you've managed to sync? 
1. menu Develop > Toggle Developer Tools > Mist UI
2. go to console tab and run `web3.eth.blockNumber`
3. check on etherscan for https://etherscan.io/block/3910154 replacing the 3910154 with the number returned on the console. 
4. See the amount of transactions on that block.

Let's take into consideration the high amount of transactions on blocks due to the recent ICOs. That can be one of the causes. 

One way or another, this seems to be a Geth problem, not Mist specifically. Geth is the software that runs along with Mist, and is responsible for downloading blocks from the chain. You could take a look at their issue pages to search for a solution. 

https://github.com/ethereum/go-ethereum/issues?utf8=%E2%9C%93&q=is%3Aissue%20stuck

I'll close this for now, thanks.

**Closed by evertonfraga** 2017-06-21 22:29 UTC
