### ISSUE TITLE
Can't see my ether Balance

### ISSUE THREAD

**Issue by Linolotzin** [ethereum/mist#3597] opened 2018-01-19 14:16 UTC
Hello,

I send 1 Ether from my cionbase to my ether wallet, but i cant see my credit.
i think it is the sync but i have no idea how to fix it even after reading the help. 
can you help me fix my Problem?

dear regards

i.A. Mario von Gemünden

Version: `0.9.3`
OS & Version: windows 10
Node version: `geth 1.7.2` 
Number of blocks synchronized: na(see in the pictures)
```
![etherwallet3](https://user-images.githubusercontent.com/35566273/35154433-896fddae-fd2a-11e7-8461-c4e1e026d467.PNG)

![etherwallet2](https://user-images.githubusercontent.com/35566273/35154432-887a686a-fd2a-11e7-8cbc-d35153ffd94f.PNG)

![etherwallet1](https://user-images.githubusercontent.com/35566273/35154429-87a02b3c-fd2a-11e7-877e-e6d5a59fbcd8.PNG)


[logsetherwallet.zip](https://github.com/ethereum/mist/files/1646750/logsetherwallet.zip)



 -->

**Comment by devinfinn** [comment] 2018-01-23 04:47
@Linolotzin  "Accounts can't display incoming transactions, but can receive, hold and send Ether. To see incoming transactions create a wallet contract to store ether."

**Comment by Linolotzin** [comment] 2018-01-24 13:10
@devinfinn i send this like 4 month ago. its shows up in the blockchain but i cant do anything with my ether in my wallet cant send it and i dont see it in the wallet. you can see that in my sceenshot

**Comment by Linolotzin** [comment] 2018-01-26 09:19
What is the Problem why cant i access my funds?

**Comment by evertonfraga** [comment] 2018-02-01 18:40
Duplicate of #3097.

Please refer to [this issue](https://github.com/ethereum/mist/issues/3097) for more information and our [Wiki](https://github.com/ethereum/mist/wiki) for troubleshooting steps.

**Closed by evertonfraga** 2018-02-01 18:40 UTC
Labels: Status: Triage
