### ISSUE TITLE
light sync doesn't work.

### ISSUE THREAD

**Issue by unknown1235** [ethereum/mist#3361] opened 2017-12-03 19:05 UTC
- [x] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.
The light sync doesn't sync at all.  Tried it on two different computers.  Just nothing.
Looked at the log and it showed stuck here: IPC endpoint opened: \\.\pipe\geth.ipc

Anyone else having similar problems.  I remember trying this a month ago and it was working fine.

```
Version: `0.9.3`
OS & Version: windows/linux/osx
Node version: `geth 1.7.2` 
Number of blocks synchronized: 0
```

**Comment by cryptojunky** [comment] 2017-12-03 19:17
Open ethereum wallet. Leave till it syncs. It will eventually sync. Issue definitely needs to be addressed by developers asap.

**Comment by unknown1235** [comment] 2017-12-03 19:18
does the light sync mode still works?  Should I still leave it in light sync mode?
worked fine about a month ago.  Now its completely down???  what is going on?

I been trying to at least run a node when doing my transactions to increase security but I got to admit, every single time I use this etherum/mist wallet some issues comes up.  Never once did it just worked out the box.  

Last time it was the syncing problem which I got around by switching to light sync.  Now light sync is like dead completely.  I don't really know what else to do.  The full sync works but it will never finish cause its taking literally weeks.  (I tried that before, it is a night mare and very painful process to sync.  Some time geth.exe just crashes and then you have to restart.)

**Comment by unknown1235** [comment] 2017-12-03 19:20
Light sync mode was like a miracle last time I synced this stuff.  It literally be a night mare to go back to regular syncing.

I hope they fix light sync soon.  Do you know what is wrong with it?

**Comment by cryptojunky** [comment] 2017-12-03 19:27
I posted this below yesterday cause it worked. But im not sure what the issue is. If I roll back geth or ethereum wallet it made no difference but I did this and it worked. Than it stopped. Now I start ethereum wallet and walk away and keep checking back. It definitely has to do with geth and light mode cause geth and downloading blockchain normally works fine.

I deleted geth file here: C:\Users\USERNAME\AppData\Roaming\Ethereum Wallet\binaries\Geth\unpacked [delete single file that says geth]

Deleted ethereum win-unpacked from zip file.

Redownload ethereum and run again. It will download updated geth file automatically and sync should start withing 5 or so minutes.

UNDER NO CIRCUMSTANCE SHOULD YOU DELETE YOUR KEYSTORE FILE

**Comment by unknown1235** [comment] 2017-12-03 19:31
Thanks
I am using the fast sync now.  The one you get when you first start up Ethereum wallet.  I deleted everything and started from scratch.

My concern is that the fast sync will crash half way some point and then I have to revert back to normal syncing which is very painful.  In all my previous attempts in the past 2 years, it always crashed some where in the middle.

Wish me luck this time and thanks for your comment and help.

**Comment by unknown1235** [comment] 2017-12-03 19:36
I just noticed that ethereum wallet 0.93 is still using geth-windows-amd64-1.7.2-1db4ecdc

Is that correct?  Shouldn't it be using the 1.7.3 wallet instead?  thoughts?

**Comment by cryptojunky** [comment] 2017-12-03 19:44
Your Welcome.

1.7.3 is the latest version of geth. Are you looking at the folders in the directory above or the geth single file directly?

When you run wallet you should be promoted a newer version is available . If not you can delete geth file from directory above and run wallet and newest version should download.

**Comment by unknown1235** [comment] 2017-12-03 20:41
I am using the 0.9.3 version of ethereum wallet.  The latest released I believe.  However the geth file it download is in \AppData\Roaming\Ethereum Wallet\binaries\Geth\unpacked\geth-windows-amd64-1.7.2-1db4ecdc

So does this mean ethereum wallet is still using the 1.7.2 version? and not the 1.7.3 version?

So fast fast sync is still going.  Says I am on 3900000 out of 4600000 something.  So hopefully when it reaches 4600000 it will be done.
Wish me luck.

**Comment by cryptojunky** [comment] 2017-12-03 21:53
Do you see a geth file in unpacked? Before windows-amd64-1.7.2-1db4ecdc

**Comment by unknown1235** [comment] 2017-12-03 23:11
yes
I am stuck on block 4670389.  It is not moving.  Only 200 blocks more to go but will not sync.

**Comment by dsb333** [comment] 2017-12-04 01:03
When checking to see if a confirmed deposit is finally in your Mist wallet (and it's not), the software says "If your balance doesn't seem updated, make sure that you are in sync with the network." But it doesn't say "how" to make sure you are in sync or what to do and it's not. I'm assuming this is the "sync with light" feature you are all referring to. Do I simply continue to click on the sync with light feature or is there something else I can do?

**Comment by cryptojunky** [comment] 2017-12-04 01:37
At the top it should have a progress bar with a counter to show how many blocks are left to download. If progress is counting up by the seconds and restarting the timer usually under a minute than you are all caught up on blocks.

You will not see your transaction in the wallet till the blockchain is finished downloading or atleast till the block that contained the transaction has downloaded but in some instances when first downloading the entire blockchain transactions won't show until the entire chain finishes. 

If you want to see if your transaction has made it to your address thats in your wallet. Click copy address from your wallet and paste it on etherscan.io

**Comment by Hatshepsut93** [comment] 2017-12-04 13:58
I have similar issue, but my light sync always gets stuck at around block 4,300,000 - I've tried to delete lightchaindata folder and start the process again, always the same. 
Geth returns this error:
ERROR[12-04|15:55:37] Failed to retrieve current release       err="missing trie node 4fa9d08a93cbf2a624eb7d382830de507ab7dc849fe5b1b98bea16b9355e6a26 (path )

**Comment by cryptojunky** [comment] 2017-12-04 14:30
Had same issue. Open ethereum wallet and walk away till it syncs. Eventually it syncs. You can try whats posted above but eventually it runs into same problem. Hopefully developers will fix issue soon.

**Comment by apatsekin** [comment] 2017-12-05 02:34
Sync in light mode became completely unstable. And until it completely up-to-now it shows ridiculous transfer fees: 0.1-2.0 eth. So currently it hangs for 3 hours without any peers, 3 hours behind, with 0.1-2.0 eth transfer fees.

**Comment by JC-000** [comment] 2017-12-05 21:47
geth-darwin-amd64-1.7.2-1db4ecdc

--light with --verbosity 4 shows the following.  BTW I love that the timestamps are all dec 31 1969 in /Users/XXXXXX/Library/Application Support/Ethereum Wallet/binaries/Geth/unpacked

DEBUG[12-05|16:39:20] invalid neighbour (212.47.254.155) from b356499aea30e49d@169.57.134.228:30304: metadata mismatch: got {212.47.254.155 30304 30304 86ebc843aa51669e08e27400e435f957918e39dc540b021a2f3291ab776c88bbda3d97631639219b6e77e375ab7944222c47713bdeb3251b25779ce743a39d70}, want enode://86ebc843aa51669e08e27400e435f957918e39dc540b021a2f3291ab776c88bbda3d97631639219b6e77e375ab7944222c47713bdeb3251b25779ce743a39d70@212.47.254.155:1245 
DEBUG[12-05|16:39:20] invalid neighbour (139.59.212.114) from b356499aea30e49d@169.57.134.228:30304: metadata mismatch: got {139.59.212.114 5068 5068 1ad53266faaa9258ae71eef4d162022ba0d39498e1a3488e6c65fd86e0fb528e2aa68ad0e199da69fd39f4a3a38e9e8e95ac53ba5cc7676dfeaacf5fd6c0ad27}, want enode://1ad53266faaa9258ae71eef4d162022ba0d39498e1a3488e6c65fd86e0fb528e2aa68ad0e199da69fd39f4a3a38e9e8e95ac53ba5cc7676dfeaacf5fd6c0ad27@139.59.212.114:5067 
DEBUG[12-05|16:39:20] invalid neighbour (52.178.130.158) from de864b55b970b824@128.199.217.146:30304: low port 
DEBUG[12-05|16:39:20] invalid neighbour (95.91.247.28) from 21754d664afaee4b@67.205.160.17:30304: missing TCP port 
DEBUG[12-05|16:39:20] invalid neighbour (163.172.157.61) from de4f084d0fa0ce2d@45.33.71.62:30304: metadata mismatch: got {163.172.157.61 30304 30304 88c2b24429a6f7683fbfd06874ae3f1e7c8b4a5ffb846e77c705ba02e2543789d66fc032b6606a8d8888eb6239a2abe5897ce83f78dcdcfcb027d6ea69aa6fe9}, want enode://88c2b24429a6f7683fbfd06874ae3f1e7c8b4a5ffb846e77c705ba02e2543789d66fc032b6606a8d8888eb6239a2abe5897ce83f78dcdcfcb027d6ea69aa6fe9@163.172.157.61:1275 
DEBUG[12-05|16:39:21] Discovered new entry                     id=3f1d12044546b763
DEBUG[12-05|16:39:21] invalid neighbour (87.15.71.5) from 85c85d7143ae8bb9@40.118.3.223:30309: missing TCP port 
 DEBUG[12-05|16:39:21] invalid neighbour (145.20.21.106) from d3cfa5eb9a3fdb2e@67.205.160.17:3889: metadata mismatch: got {145.20.21.106 30304 30304 8dd7adbd8461f77ca80db0d402b2ad802506d36249028d3f895b5daf5e718eb1e3d355cc5640096dbdad1e2d91668725d4f68bd4b0f9da5c3611f06906b860d7}, want enode://8dd7adbd8461f77ca80db0d402b2ad802506d36249028d3f895b5daf5e718eb1e3d355cc5640096dbdad1e2d91668725d4f68bd4b0f9da5c3611f06906b860d7@145.133.238.60:30304

**Comment by sushilraghav** [comment] 2017-12-08 15:32
Is there someone who can help me or can create a cryptocoin based on ETH Fork or BTC Fork or X11 or IOAT Fork ? Contact me at skype : sushilraghav

**Comment by sushilraghav** [comment] 2017-12-08 15:45
@unknown1235 @cryptojunky @dsb333 @Hatshepsut93 @apatsekin  /// How much money you charge or Is there someone who can help me or can create a cryptocoin based on ETH Fork or BTC Fork or X11 or IOAT Fork ? Contact me at skype : sushilraghav or email is bitcoinemxmx@gmail.com.

**Comment by KainniaK** [comment] 2017-12-16 03:42
We need a fix for this please? hardy any peers available to sync in light mode, ethereum wallets get stuck on node connected. Having to sync in light mode can take a couple of days right now because of peers continually dissonecting.

**Comment by lowlanda** [comment] 2018-01-03 02:37
I'm not the only one then... I uninstalled Ethereum Wallet, deleted all folders (after backing up Keystore folder), then reinstalled. Set it the light sync mode but it started downloading from block 0. After 10-15mins I'm up to block 200,000 or so. Might trying going back to fast mode, see what happens.

**Comment by lowlanda** [comment] 2018-01-03 16:51
No good, got to within 9 blocks (after 12+ hours) then stalled. Can't see my balance either

**Comment by lowlanda** [comment] 2018-01-04 00:20
Tried again with --fast. Got sync'd, could see balance, but now I get "unable to connect to socket: timeout" errors when trying to send ether. Bloody hopeless..

This solution works (or workaround): https://github.com/ethereum/mist/issues/2466 Find nadimaj's post about MyEtherWallet

**Comment by kilbymiz** [comment] 2018-01-11 21:46
light sync shows my CRPT tokens as well as my couple hundred in ether with CRAZY transaction fess up to 9,000 USD at on point.. Regular sync shows my CRPT tokens NO ether with good transaction fees

**Comment by evertonfraga** [comment] 2018-01-14 05:04
Mist spawns a Geth instance, responsible for syncing with the blockchain. Please refer to their repository in order to get help directly from their devs.

https://github.com/ethereum/go-ethereum

**Closed by evertonfraga** 2018-01-14 05:04 UTC
