### ISSUE TITLE
Copy address does not work

### ISSUE THREAD

**Issue by marcofranssen** [ethereum/mist#806] opened 2016-06-12 20:35 UTC
Node type: geth/eth
OS: windows
Network type: main/test
Mist version: 0.7.4

When using the copy address button, the address is not copied onto the clipboard. Same applies for selecting the address and using ctrl+c. The UI however tells that the address is copied to the clipboard in both situations.

**Comment by hellwolf** [comment] 2016-06-13 10:42
Confirmed, including Linux client.

**Comment by luclu** [comment] 2016-06-13 11:02
Thanks for reporting, though I will close this as a duplicate of https://github.com/ethereum/mist/issues/650

**Closed by luclu** 2016-06-13 11:02 UTC
