### ISSUE TITLE
Ethereum Wallet Password wrong

### ISSUE THREAD

**Issue by JacoBooster** [ethereum/mist#3244] opened 2017-11-04 14:24 UTC
I have seen a lot of issues with wrong passwords, see [2411][2610][2077]. From these posts I can conclude that somehow ethereum changes characters of the wallet (especially if you have Apple OSx). I am not very tech savvy, but can someone explain me how this works? I used for example the character @ in my password, how can I see in what characters this is translated?

**Comment by korry86** [comment] 2017-11-07 13:49
Yep, my password worked great until I sent Ether to my address in Mist. Now, not only does Mist not fully sync, but i can not spend or create a contract because it says my password is wrong. I know its not wrong. Very lame, very very frustrating. Shouldnt happen.. These guys are apparently genuis', yet i haven't had this work properly once. I do not have problems with Bitcoin core, Monero etc... Just stupid Ethereum...

**Comment by Madebyivan** [comment] 2017-12-02 15:10
This is a scam, I never entered any password, there is a bug at some time that does it, they wash their hands, tiny clowns

**Comment by elpollitodiablo** [comment] 2017-12-05 18:45
I am having this issue, too. I could circle my problem to a special character which I was using in my Password. Do the following:

````console
geth attach
personal.newAccount()
````
use passphrase `FusRoDah`
`0xAccountA` is created (replace `0xAccountA` with hash)

````console
personal.newAccount()
````
use passphrase `FußRoDah`
`0xAccountB` is created (replace `0xAccountB` with hash)

Run this:
````console
personal.unlockAccount('0xAccountA', 'FusRoDah')
true
````
and then
````console
personal.unlockAccount('0xAccountA', 'FußRoDah')
Error: could not decrypt key with given passphrase
````

My setup:  Windows 10 64-bit - CMDER (PowerShell produces the same error)
````console
instance: Geth/v1.7.2-stable-1db4ecdc/windows-amd64/go1.9
modules: admin:1.0 debug:1.0 eth:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0
````

Mist version 0.9.3 won't let me do any transactions, which lockes my wallet.

**Comment by anormore** [comment] 2017-12-21 01:43
Could you try this same process with regular special chars, such as @ ! $ % and so forth?

**Comment by sebd-davra** [comment] 2018-01-06 12:02
I can always reproduce the error with geth in command line : 
geth attach
personal.newAccount()
Passphrase:
Repeat passphrase:
I copied pasted the password from notepad++ (64 characters alphanumeric without special characters)
the account is created and the keystore created in the appData keystore folder in windows 10 
I am trying to unlock the account with the command 
personal.unlockAccount("0xblablablamynewaccount","mylongpasswordalphanum64char")
Error: could not decrypt key with given passphrase

get version : VERSION:  1.7.2-stable-1db4ecdc

**Comment by marcgarreau** [comment] 2018-01-08 21:21
@sebd-davra I wasn't able to reproduce that on my VM; will double-check on a windows machine when I'm able. Make sure you don't have a copy/paste issue - in your case, see if you can unlock the account with an empty string as the password.

Closing this issue in favor of https://github.com/ethereum/mist/issues/3513. If you're able to reproduce any related bug, please help us out by documenting the detailed steps in that issue. Thanks!

**Closed by marcgarreau** 2018-01-08 21:21 UTC

**Comment by sebd-davra** [comment] 2018-01-08 21:26
@marcgarreau I already tried with an empty string before and after, just before, just after my password, with a space only as well and all the combinations of my password 1 to 64 char left to right and right to left.

**Comment by marcgarreau** [comment] 2018-01-08 21:35
@sebd-davra Sorry if I'm misunderstanding you, but what I meant was to check with just an empty string: i.e. `personal.unlockAccount("0xblablablamynewaccount", "")`. Sounds like you can unlock the testing account already though, so we may have lost that experiment.

**Comment by sebd-davra** [comment] 2018-01-08 21:37
@sebd-davra I already tried personal.unlockAccount("0xblablablamynewaccount", "")

**Comment by evertonfraga** [comment] 2018-01-10 02:23
**Calling all users that can't access their accounts.**
Please help us get more structured information about your "Wrong password" issues. 

https://goo.gl/forms/jznmHV6Fpui7Ijds1

**Comment by pal-presaleWrongPW** [comment] 2018-02-08 06:35
@evertonfraga what shape is the data taking?
