### ISSUE TITLE
Lost DAOs after restoring from backup

### ISSUE THREAD

**Issue by itredd** [ethereum/mist#968] opened 2016-07-14 06:51 UTC
Hi, yesterday after wallet failed for searching for nodes , i restored from backup,i got both eth adresses with the funds but DAOs are gone,

**Comment by luclu** [comment] 2016-07-14 08:52
Closed as duplicate of https://github.com/ethereum/mist/issues/967.

**Closed by luclu** 2016-07-14 08:52 UTC
Labels: duplicate
