### ISSUE TITLE
ethereum wallet shows zero balance after upgrade

### ISSUE THREAD

**Issue by bkhoeini** [ethereum/mist#1187] opened 2016-09-23 08:23 UTC
hi guys
please accept my apologies for reporting issue like this.
i was using ethereum wallet version 8.1 .
3 day ago i wanted to update my wallet, i had several issues, wallet hanging and ...
last time i left the wallet for syncing at night so at morning i found my laptop crashed down
when i powered on it again it reported recovery and bsod
i ran again wallet this time it say node connection error and also some error report about wandevice
so i decided to update
i ran ver 8.3 but when i ran wallet it report error that the file is being used by another process
so i copied chaindata folder to other directory and deleted it and ran again v 8.3
the wallet started to sync it after several hours it now updated but it shows my balance zero!
also all my send trans have zero confirmation
i checked blockchain site and it report my wallet and my balance true
so i decided to copy original chaindata again
and again no success for loading
please help 
please tell me what can i do! i am so confused!
if any log needed please tell me
how i can recover my wallet
tanx

**Comment by luclu** [comment] 2016-09-23 08:54
Duplicate of https://github.com/ethereum/mist/issues/1185#issuecomment-249104680
> Be patient. Resyncing is timetraveling.

**Closed** 2016-09-23 10:26 UTC
Labels: duplicate

**Comment by silentsnooc** [comment] 2017-06-07 08:33
@luclu In my case I look at the block count. It's not moving and the timer on the right tells me there was no block for the last x seconds. Still my wallet shows 0.0 ETHER for my waller ( https://ethermine.org/miners/1bb0cc91ea4d007825079612fec3915d8638b80a ). Any idea?

**Comment by evertonfraga** [comment] 2017-06-13 13:57
@silentsnooc can you check your balance on http://etherscan.io ?
