### ISSUE TITLE
Ethereum not received in my Ethereum Wallet when exchanged BTC to ETH through shapeshift via Mist web app

### ISSUE THREAD

**Issue by AnshBtc** [ethereum/mist#1726] opened 2017-03-13 19:39 UTC
Hello. I am new to this and I exchanged BTC to ETH through Ethereum wallet app but did not receive any ETH in my wallet.
My btc deposit also had enough confirmations and also I mailed shapeshifter support team, they also told me that the transaction of ETH to my wallet address is complete and yet there is no sign of any ETH in my wallet please fix the issue!

**Comment by AnshBtc** [comment] 2017-03-13 19:51
Here is the transaction if of ether transaction 0xce7714549d83ef438988cbf5226594bfc34e32e441eea1dfde72416c1ac3a5e9

**Comment by luclu** [comment] 2017-03-14 13:42
Could you please check if your wallet is fully synced?

(Duplicate of https://github.com/ethereum/mist/issues/1720)

**Comment by hrayrwannis** [comment] 2017-06-21 19:20
Same issue transferred BTC to Eth wallet, showed on that shapeshift received and transferred to my Eth wallet address.. but nothing received. 

Similarly transferred from cex.io and nothing received yet and both don't show up on ether scan...

So what's the deal? Just to transfer some ether is it that complicated??

PS. My wallet is fully synced.

**Comment by aphilsmith** [comment] 2017-09-20 17:59
hraywannis - I have the same problem after 72 hours and multiple sync's. Did your Eth ever show? If so, how long did it take?

**Comment by AnshBtc** [comment] 2017-09-20 18:17
I stopped using mist and started using myetherwallet.
That's what helped me.

**Closed** 2018-02-01 18:43 UTC
Labels: Status: Duplicate
