### ISSUE TITLE
Wallet stop syncing at block 2,283,415

### ISSUE THREAD

**Issue by altralizer** [ethereum/mist#1165] opened 2016-09-19 09:58 UTC
Today all my Wallets (V0.8.2) are stopped syncing at block 2,283,415.

I have reading somethings about a eventually DOS attack on geth. I'm not sure it is because of that.
But i feel it is.

any suggestions, ideas???

**Comment by yrrv1980** [comment] 2016-09-19 13:51
Hi .. I'm Having the same Issue.  Ver. 0.8.2 block 2,283,415.

**Comment by marienuac** [comment] 2016-09-19 14:42
same problem
something about "connection timed out on request to api.github.com wtf? why does sync depend on a connection to github......

**Comment by luclu** [comment] 2016-09-19 15:15
Duplicate of https://github.com/ethereum/mist/issues/864#issuecomment-248021268

> I don't know if this is even related to this issue, but today I'm having a really bad memory leak. I still have the previous exception flooding my terminal and while the splash screen says "Downloading blocks (X peers)", geth process memory usage go from 200 MiB to over 1GiB in about 2 minutes and then went up to 6GiB in a manner of seconds before I killed the process.

This was caused by a faulty instruction within geth:
https://blog.ethereum.org/2016/09/18/security-alert-geth-nodes-crash-due-memory-bug
 
Bug-Report: https://github.com/ethereum/go-ethereum/issues/3002
Pull-Request: https://github.com/ethereum/go-ethereum/pull/3006

Ethereum-Wallet `0.8.3` with a hotfix will be released tomorrow.

**Comment by marienuac** [comment] 2016-09-19 15:17
will that hotfix fix "Connection timed out on request to api.github.com" ???

**Comment by luclu** [comment] 2016-09-19 15:22
> will that hotfix fix "Connection timed out on request to api.github.com" ???

This sounds like you are affected by https://github.com/ethereum/mist/issues/1124 - which is unrelated to this bug and hotfix.

**Comment by kruisdraad** [comment] 2016-09-19 17:38
@luclu i dont see a windows build get for this new release?

**Comment by crazybcoin** [comment] 2016-09-19 18:07
hello, I am also stuck at the same block. So are we still waiting for an update? I am running windows 10. Is there any possibility of loss of coins in wallet?

thanks

**Comment by cryptobroker** [comment] 2016-09-19 20:47
I'm stuck at the same block 2,283,415. I also had the same memory issues as luclu on my mac.

**Comment by alxcarrasco** [comment] 2016-09-20 00:08
@luclu Hi, any idea when the update for mac will be released? Thanks!

**Comment by alxcarrasco** [comment] 2016-09-20 02:19
@luclu "Ethereum-Wallet 0.8.3 with a hotfix will be released tomorrow.
If you are tech-savvy and don't want to wait you can swap the geth binary with the new one from https://github.com/ethereum/go-ethereum/releases." You will really need to explain it on detailed way, as you see, there are many files, so how do you suggest to do it?, Ethereum Wallet is having lots of issues.

Sorry to say, but, I don't really know how you guys expect people that is not tech-savvy to make a wallet (that is supposed to work perfectly) work when your entire environment is quite full of complex situations even for your own development team. It has been quite frustrating this "up & down, jam & crash" with my wallet and my ETH, I think I will just take my money somewhere else. At the moment I can't access my funds, I need to withdraw my ETH IMMEDIATELY, fix it, so I can take my money somewhere else.

... Thanks ... ?

![screen shot 2016-09-20 at 10 06 05 am](https://cloud.githubusercontent.com/assets/22308325/18655285/18e07dee-7f1a-11e6-93b8-aa2f9028867d.png)

**Comment by luclu** [comment] 2016-09-20 03:50
We are currently having problems uploading the binaries to github as the Chinese Firewall can be quite nasty.

In the meantime follow [this instructions](https://github.com/ethereum/mist/issues/1166) to replace the geth binary bundled in our releases.

**Comment by manzeric** [comment] 2016-09-20 04:00
I’m using Ethereum Wallet 0.8.2. on Linux Mint 18. My wallet is stuck at the same block, plus, Geth crashes my computer.  Here's the  terminal output:

I0919 07:46:54.774949 cmd/utils/flags.go:678] You're one of the lucky few that will try out the JIT VM (random). If you get a consensus failure please be so kind to report this incident with the block hash that failed. You can switch to the regular VM by setting --jitvm=false
I0919 07:46:54.775070 ethdb/database.go:82] Alloted 128MB cache and 1024 file handles to /home/dad/.ethereum/chaindata
I0919 07:46:54.938303 cmd/utils/flags.go:842] -----------------------------------------------------------------------------------
-------------
I0919 07:46:54.938332 cmd/utils/flags.go:843] Geth is currently configured to SUPPORT the DAO hard-fork!
I0919 07:46:54.938348 cmd/utils/flags.go:844] You can change your choice prior to block #1920000 with --support-dao-fork or --oppose-dao-fork.
I0919 07:46:54.938360 cmd/utils/flags.go:845] After the hard-fork block #1920000 passed, changing chains requires a resync from scratch!
I0919 07:46:54.938371 cmd/utils/flags.go:846] ------------------------------------------------------------------------------------------------
I0919 07:46:54.938495 ethdb/database.go:169] closed db:/home/dad/.ethereum/chaindata
I0919 07:46:54.939344 ethdb/database.go:82] Alloted 128MB cache and 1024 file handles to /home/dad/.ethereum/chaindata
I0919 07:46:55.090367 ethdb/database.go:82] Alloted 16MB cache and 16 file handles to /home/dad/.ethereum/dapp
I0919 07:46:55.097903 eth/backend.go:172] Protocol Versions: [63 62], Network Id: 1
I0919 07:46:55.098085 eth/backend.go:201] Blockchain DB Version: 3
I0919 07:46:55.099820 core/blockchain.go:206] Last header: #2283415 [0f5e095c…] TD=62361165787070130295
I0919 07:46:55.099853 core/blockchain.go:207] Last block: #2283415 [0f5e095c…] TD=62361165787070130295
I0919 07:46:55.099875 core/blockchain.go:208] Fast block: #2283415 [0f5e095c…] TD=62361165787070130295
I0919 07:46:55.105383 p2p/server.go:313] Starting Server
I0919 07:46:56.888880 p2p/nat/nat.go:111] mapped network port udp:30303 -> 30303 (ethereum discovery) using UPNP IGDv1-PPP1
I0919 07:46:56.912587 p2p/discover/udp.go:217] Listening, enode://111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111@111.111.111.1:30303
I0919 07:46:56.912835 p2p/server.go:556] Listening on [::]:30303
I0919 07:46:56.926429 node/node.go:296] IPC endpoint opened: /home/dad/.ethereum/geth.ipc
I0919 07:46:56.947952 p2p/nat/nat.go:111] mapped network port tcp:30303 -> 30303 (ethereum p2p) using UPNP IGDv1-PPP1
I0919 07:47:06.926500 eth/downloader/downloader.go:320] Block synchronisation started
I0919 07:47:13.615942 eth/handler.go:295] Peer e6c3cebd1eb860ac [eth/63]: timed out DAO fork-check, dropping
I0919 07:47:13.629014 eth/handler.go:295] Peer b0ea89416b004e09 [eth/63]: timed out DAO fork-check, dropping
I0919 07:47:33.186477 eth/handler.go:295] Peer e6c3cebd1eb860ac [eth/63]: timed out DAO fork-check, dropping
I0919 07:47:58.981087 eth/handler.go:295] Peer e6c3cebd1eb860ac [eth/63]: timed out DAO fork-check, dropping
I0919 07:48:00.643373 eth/handler.go:295] Peer 20a6cd8a9bf3a8b2 [eth/63]: timed out DAO fork-check, dropping
I0919 07:48:09.992410 eth/handler.go:295] Peer 4b53b097e5880dcb [eth/63]: timed out DAO fork-check, dropping
I0919 07:48:15.651302 eth/handler.go:295] Peer c609fafc8330605d [eth/63]: timed out DAO fork-check, dropping
I0919 07:48:18.025587 eth/handler.go:295] Peer e6c3cebd1eb860ac [eth/63]: timed out DAO fork-check, dropping
I0919 07:48:23.892411 eth/handler.go:295] Peer 484d2fc418c895f1 [eth/63]: timed out DAO fork-check, dropping
I0919 07:48:36.828333 eth/handler.go:295] Peer e6c3cebd1eb860ac [eth/63]: timed out DAO fork-check, dropping
I0919 07:48:40.897416 eth/handler.go:295] Peer e6c3cebd1eb860ac [eth/63]: timed out DAO fork-check, dropping
I0919 07:48:56.424024 eth/handler.go:295] Peer e6c3cebd1eb860ac [eth/63]: timed out DAO fork-check, dropping
Terminated

At this point Geth was using 3.4G ram and on it's way to crashing my computer again. Any ideas?

**Comment by Mordong** [comment] 2016-09-20 08:59
still consuming whole memory and doesn't proceed any further

**Comment by prashantprabhakar** [comment] 2016-10-13 06:44
Same issue with me. Why is this happening? What is the precise solution?

**Comment by luclu** [comment] 2016-10-13 09:55
yes @prashantprabhakar, always make sure to run the [latest version](https://github.com/ethereum/mist/releases) (currently `0.8.5`) especially during the ongoing network attacks.
Please mind that most low performance PCs might struggle with the current attack's workload - you are advised to use parity or http://myetherwallet.com should you encounter issues.

**Comment by luclu** [comment] 2016-10-16 21:26
We just published [release `0.8.6`](https://github.com/ethereum/mist/releases/tag/v0.8.6) which will download **geth** `1.4.18` on-the-fly. 
*Please* update to easily roll with the upcoming [Hard Fork](https://blog.ethereum.org/2016/10/13/announcement-imminent-hard-fork-eip150-gas-cost-changes/) on Tuesday.

**Comment by luclu** [comment] 2016-10-20 13:02
I will close this in favour of the recent DoS-related issues in our tracker.

**Closed by luclu** 2016-10-20 13:02 UTC
