### ISSUE TITLE
well i downloaded 7.5 and still hangs looking for peers?

### ISSUE THREAD

**Issue by ORIELLY** [ethereum/mist#876] opened 2016-06-22 18:52 UTC

**Comment by luclu** [comment] 2016-06-22 21:57
Please do the following:

1. make sure your are ntp timesynced. Deactivating and Reactivating seems to solve this especially on win 10 - https://github.com/ethereum/mist/issues/397
2. some users reported that the synchronisation only starts after several minutes. This is most likely due to a bad peer selection and no portforwarding/NAT on your network side - https://github.com/ethereum/mist/issues/840 
You can try to specify this argument `--nat=none`. See https://github.com/ethereum/mist/issues/292 for more information.

**Comment by ORIELLY** [comment] 2016-06-23 00:42
OK luclu now peer issue is over and we have screen like below with no sync !
![untitled](https://cloud.githubusercontent.com/assets/20030117/16288419/a5aa3dd4-38b9-11e6-9cb5-c2589d669af7.jpg)

**Comment by ORIELLY** [comment] 2016-06-23 01:36
and now this it keeps lading new blocks but no sync.

![image](https://cloud.githubusercontent.com/assets/20030117/16289224/3580ad10-38c1-11e6-9e0a-2a1ecc9b8d84.png)

**Comment by luclu** [comment] 2016-06-23 09:15
Could you please open up the console with `CTRL+ALT+i` and type `web3.eth.syncing`.
State the `current block` and the currently shown block on the splash screen.

**Comment by FrankHold** [comment] 2016-06-24 20:32
OK with "Ethereum-Wallet.exe -- --nat=none" it works - why?? Wait - ist starts form block 400k not form 1,7M?? I will let it run over night - we will see.

**Comment by FrankHold** [comment] 2016-06-25 12:40
I have the same problem – stuck on block  1,735,990.

Time is correct (difference 0,8 seconds)
Used “Ethereum-Wallet.exe -- --nat=none ” 
Version “Ethereum-Wallet-win64-0-7-6”   Tried 7.2, 7.4, 7.5 and 7.6
http://i.imgur.com/8jUjm8C.jpg
The last files “95940.ldb” ... in chaindata seem to be with 1KB a bit small. 

If I delete them “Ethereum node connection error :’(“ occurs. 
http://i.imgur.com/PC3LK2R.jpg
It doesn’t seem that many people have this problem. 
PS: Average user here - web3.eth.syncing doesn’t say me anything.

**Comment by luclu** [comment] 2016-06-25 13:35
@FrankHold you most likely corrupted geth's chain replica by doing so. 
Please delete/move/rename the whole `chaindata` folder and resync.

**Comment by FrankHold** [comment] 2016-06-25 15:11
Ok thanks - this will take a while.

**Comment by FrankHold** [comment] 2016-06-26 07:36
It worked !!! – and 16 hours download time was much better than I expected. Thanks again.

**Comment by luclu** [comment] 2016-06-26 17:18
I will close this as a duplicate of https://github.com/ethereum/mist/issues/292.
Please join the discussion over there.

**Closed by luclu** 2016-06-26 17:18 UTC

**Comment by ORIELLY** [comment] 2016-07-05 13:34
hi @luclu sorry for the delay. my problem persists. this is the printscreen of the splash screen you told me to do.

 http://imgur.com/3EPydLf

Also I did start the wallet on the commandline with  Ethereum-Wallet.exe -- --nat=none  and I got this errors as soon as it started to run

http://imgur.com/xWUHsjF

should I delete/move/rename the whole  chaindata  folder and resync????

**Comment by luclu** [comment] 2016-07-05 14:54
@ORIELLY you seem to be affected by a corrupt chain: https://github.com/ethereum/go-ethereum/issues/2289 https://github.com/ethereum/go-ethereum/issues/2568

For new the fastest way is to check if your AV is blacklisting any files or to remove the `chaindata` folder and resync.

**Comment by luclu** [comment] 2016-07-05 14:55
Also please don't hijack unrelated issues.

**Comment by ORIELLY** [comment] 2016-07-05 16:31
ok @luclu thank you very much. the wallet is synchronizing again
