### ISSUE TITLE
What problem?

### ISSUE THREAD

**Issue by MasteSteve** [ethereum/mist#262] opened 2016-03-06 06:28 UTC
![default](https://cloud.githubusercontent.com/assets/17682687/13552669/9ebdd344-e3a7-11e5-808b-4982ac77c5fd.PNG)
What problem?

**Comment by MasteSteve** [comment] 2016-03-06 06:36
All the problem is solved! I deleted the entire folder "chaindata" i'm again download block-_-

**Comment by alexvandesande** [comment] 2016-03-07 11:35
Duplicate of 
https://github.com/ethereum/mist/issues/263

**Closed by alexvandesande** 2016-03-07 11:35 UTC
