### ISSUE TITLE
Copying address does not copy to clipboard

### ISSUE THREAD

**Issue by Cervenka** [ethereum/mist#749] opened 2016-05-30 10:53 UTC
Node type: geth
OS: OS X 10.11.5
Network type: main
Mist version: 0.7.4

Using any of the methods of copying an address (keyboard shortcut, application menu, copy-address-button) result in the address being copied to the clipboard.

I see two notifications that the address has been copied. The content of the clipboard is the same is it was before.

**Comment by luclu** [comment] 2016-05-30 12:19
@Cervenka thanks for reporting. I will close this as it is a duplicate of https://github.com/ethereum/mist/issues/650

**Closed by luclu** 2016-05-30 12:19 UTC
