### ISSUE TITLE
will not sync last 200 blocks??

### ISSUE THREAD

**Issue by piqdesigns** [ethereum/mist#2564] opened 2017-06-19 14:19 UTC
Wallet version 0.8.10
Ether node geth 1.6.5 (Go)
MacOS Sierra 10.12.5

Will the wallet ever sync? been on last 200 blocks for a week now. 

This is my problem: I  found some old eth in an older mist wallet- before syncing the fist time (clicking launch application), I sent 3 eth as a test to a to MEW address.  That worked, so I sent the other remaining ETH (the same way) and those eth did not show up in MEW yet they are showing 0.00 balance now?  I assume this is because my wallet is not synced up to the latest block but how did the first tx go through and the following 3 did not?   Now its been a week and it seems I cant download these last 200 blocks (chain structure keeps increasing, thus so does the blockchain?

seems to find peers after node sync, but if I skip this part and click "launch application"  it says i have downloaded 95% of blocks and finds 0 peers.  not sure what is happening.  

these are the errors i can see in geth:
![screen shot 2017-06-19 at 08 17 55](https://user-images.githubusercontent.com/26945546/27297607-d12a6952-54e2-11e7-8e95-9a0b484865d1.png)
![screen shot 2017-06-19 at 11 31 02](https://user-images.githubusercontent.com/26945546/27297606-d11565d4-54e2-11e7-9de8-36a4e2566dca.png)

ERROR[06-19|08:48:11] Failed to unregister sync peer           peer=3412b19a08a88a9e err="peer is not registered"

ERROR[06-19|08:48:25] Peer removal failed                      peer=3412b19a08a88a9e err="peer is not registered"

I am about to go nuts waiting for this to never snyc.  any help would be great, thx.

**Comment by miketricking** [comment] 2017-07-09 07:47
I have exactly the same problem, did you ever find out a way around this?

**Comment by Latham13** [comment] 2017-07-10 02:04
same

**Comment by piqdesigns** [comment] 2017-07-10 15:57
i stopped trying to sync.  its making me mad.  will wait for fixes and hopefully my eth is safe.

**Comment by Silur** [comment] 2017-07-25 10:59
exact same problem tried `geth removedb` 5 times, no success

**Comment by meacreatio** [comment] 2017-08-14 06:33
Same here. Stops at 240 and never finishes.  However, "Downloading Chain Structure" continues to run and run with no apparent end.  Tried just about everything.

**Comment by miketricking** [comment] 2017-08-14 07:50
Mine worked if I left it downloading and updating first before hitting "launch application"

**Comment by hlogeon** [comment] 2017-08-15 21:42
Same thing on 0.9.0

**Comment by bmesnick** [comment] 2017-08-24 04:31
Has anyone figured this issue out?  I cannot get into my wallet and it keeps stopping around 300 blocks left.  My time is updated and correct, and I have tried everything.  I need to transfer eth from that wallet, but it wont sync....  Any help is appreciated.

**Comment by hlogeon** [comment] 2017-08-24 10:43
@bmesnick finally I just used parity and it worked well.

**Comment by shado-senpai** [comment] 2017-08-24 18:38
I can't download last 200 blocks+/-

**Comment by hlogeon** [comment] 2017-08-24 21:42
Anyone from the team will try to figure out the reason? You loose your users now, guys!

**Comment by bmesnick** [comment] 2017-08-24 22:24
I already did it with myetherwallet.  Worked great.  Fuck mist geth

Thanks,
Brent

**Comment by ElectronHarvester** [comment] 2017-09-09 00:17
Seriously why is this a thing. 4 million blocks down like 200 to go after 3 days

**Comment by bmesnick** [comment] 2017-09-09 01:35
Use my ether wallet worked great. 

Thanks,
Brent

**Comment by nioschka** [comment] 2017-09-24 09:52
Jesus, this geth/mist/blockchain download is total waste of time... Same issue. Is there a solution to this?

**Comment by jurajseffer** [comment] 2017-09-24 23:03
This wallet is a joke. Geth too slow to run on a non SSD disk, gets stuck at last few hundred blocks and then I'm back to 1970s transactions. Bye bye ether.

**Comment by evertonfraga** [comment] 2017-09-28 19:51
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist

**Closed by evertonfraga** 2017-09-28 19:51 UTC
Labels: v0.8.10

**Comment by Tosainu911** [comment] 2017-10-21 04:28
Sync reaches 99% and stops have been waiting 2 day for it to finish, tried to create new wallet and it never finishes, ether has been sent checked with scan, very frustrated

**Comment by piqdesigns** [comment] 2017-11-01 13:51
this makes no sense for me.   I sent eth to my other wallet from mist without fully syncing as it worked for the first transaction no problem.  so i tried sending the rest as i was sick of waiting for mist to never sync.  the eth never got to the wallet i sent to and it is showing me nothing on the tx's.  here is a screen - when i use the new "light client" it skips my transactions completely and i have no eth in those wallet anymore.  I tried MEW but same thing.  no eth populating??  where did my eth go? 
![screen shot 2017-09-29 at 12 49 32](https://user-images.githubusercontent.com/26945546/32277880-852baf64-bed9-11e7-9d48-0f3d22df45bb.png)
i have missing eth out there now.  anyone help me?

**Comment by Tosainu911** [comment] 2017-11-01 16:48
If it is still pending, just take your private key go to myetherwallet and move all of your ether to another wallet

**Comment by lunobird** [comment] 2017-11-02 03:00
Same here,  stuck at 99 percent and never can get to a full 100 percent. It's been two days and I missed out of the raiden token sale unfortunately due to this issue.   I noticed when mining with cc miner it interrupts my mining connection when I try to sync the mist wallet.  Why is this wallet so crap? I expected better out of the eth development team and they can't even get a decent working wallet. Now my funds are stuck in limbo till it syncs somehow

**Comment by Tosainu911** [comment] 2017-11-02 03:57
use myetherwallet and your private key and take all of your ether out. I had a ether transfer pending in Mist for a week, and had to do this to get my ether.

**Comment by piqdesigns** [comment] 2017-11-02 14:15
ok, so I tried that,  when i open MEW, it shows i have .001 eth, not 5.375 like i should? 
![screen shot 2017-11-02 at 08 09 10](https://user-images.githubusercontent.com/26945546/32330454-cbad1956-bfa5-11e7-8cee-deb621725394.png)

0x38882e33D4e258979b28178bc31A3b081B37b850  (account 3)

https://etherscan.io/address/0x38882e33d4e258979b28178bc31a3b081b37b850  (account 3 history,  no tx for 6/11)

https://etherscan.io/address/0xfc326af7ca0e0ac19fefaebee81e4aaec848ed7b (address sent to, only first of 4 tx showing up but my eth is gone out of my wallets?)

![screen shot 2017-11-02 at 08 09 22](https://user-images.githubusercontent.com/26945546/32330476-dbd7a896-bfa5-11e7-9941-38beb9cfe666.png)

so there is no tx for this and my eth is missing because mist didnt sync.  wtf is going on here?

**Comment by Tosainu911** [comment] 2017-11-02 14:47
i was having all kinds of problems with this shit wallet, that is why i ditched it. 

Make sure your clock on your computer is synced. Also trying waiting for the whole thing to sync before opening it. From what i can remember if asks you to wait. Is it still saying pending?

James

**Comment by 3esmit** [comment] 2017-11-02 15:30
I had this problem but it took long but synced. Took 4 days to sync in a 2,5 MBit/s internet speed.

To better visualize your sync, run geth separatedly with `geth --vmodule=sync=6,downloader=6`

**Comment by raahil190** [comment] 2017-11-02 17:32
@3esmit how does that help to speed it up ? I'm stuck with last 200 blocks of geth sync

**Comment by 3esmit** [comment] 2017-11-05 23:19
@raahil190 no, it helps  you understand the problem.

**Comment by lordlucas999** [comment] 2017-11-08 10:30
Wallet: 0.9.2
Geth: 1.7.2
System: Windows
Location: Poland

I have the same problem. Still +/-200 blocks left. I can't use my Ether because sync no full and balance still 0. Etherscan show ok.

![console](https://user-images.githubusercontent.com/33482596/32544216-29dfe54a-c478-11e7-945a-aa9b0fdb2fac.PNG)
![wallet](https://user-images.githubusercontent.com/33482596/32544247-3bd7c1f0-c478-11e7-8f88-3ea04b5522d6.PNG)
![etherscan](https://user-images.githubusercontent.com/33482596/32544256-3f7c4ed4-c478-11e7-8829-5f97cf92f709.PNG)

**Comment by bibz0r** [comment] 2017-11-30 10:06
Same problem here, downloaded newest version of the wallet 2 days ago. Now its stuck on the last 84 blocks..

**Comment by mhogstedt** [comment] 2017-12-01 09:21
Same issue here. Stops short at around 200 blocks. Balance stays at 0. Cannot transfer any ETH.

**Comment by batmaster** [comment] 2017-12-01 11:15
Last 100 blocks are not synced. Latest Block is always 0.

**Comment by Lazare-42** [comment] 2017-12-01 11:43
Hi everyone. I encountered the same problem and "bruteforced" my way out of it. 
I ran the following command : 

`geth --syncmode "full" --cache=6144 --maxpeers 100`

You need to have at the necessary RAM.

Hope that that helps :)

**Comment by kulpaporn19** [comment] 2017-12-01 11:57
เมื่อ 1 ธ.ค. 2017 18:43 "Lazare-42" <notifications@github.com> เขียนว่า

**Comment by awslyall** [comment] 2017-12-02 09:00
Sorry for the dumb question. 

Im on Windows and have 

geth -syncmode "full" -cache=6144 -maxpeers 100

running. Its nicely ticking over and showing "Imported New State Entries"

Will it will me when its finished?

**Comment by Lazare-42** [comment] 2017-12-02 09:21
Hi.

When you are finished, you should see "Imported new chain segment".
You can check your progression by typing in a new console, geth attache (to open a JS console linked to the one before), then eth.syncing
To see your progression in percentages just input 
100 *eth.syncing.currentBlock / eth.syncing.highestBlock
Hope that helps.

**Comment by piqdesigns** [comment] 2017-12-04 16:32
this is bullshit vitalik.

**Comment by colevr1** [comment] 2017-12-07 02:15
waste of time, less cryptokitties!

**Comment by ethancrist** [comment] 2017-12-13 19:08
To those worried about funds not showing up:

Search up your address on [Etherscan](https//etherscan.io) to see the actual amount that's in your wallet. It only doesn't display correctly on geth/the like because of this syncing issue.

Ultimately, so long as if you still have your keystore folder, your funds are still safe, you just can't interact with them. If you must you can import your keys to [MEW](https://myetherwallet.com), just know this isn't nearly as secure as a truly private wallet.

My recommendation in the light of these continuous syncing issues: 
1) [Buy a hardware wallet](https://www.ledgerwallet.com) (the most secure type of wallet, and doesnt require a full node to use)
2) Once it ships, get your address from this wallet.
3) Import your keystore to MEW, then immediately send your funds from MEW to your new hardware wallet.

Don't wait for this syncing nonsense to end, it's been happening for months.

**Comment by DiKol** [comment] 2017-12-16 02:32
I guess they leave this behavior to avoid big amount of transactions, because it can stop working at all. Same as you can not buy cat on crypto kitties

**Comment by gregl83** [comment] 2017-12-20 01:45
i guess im joining the party... after waiting for hours to get my node synced everything comes to a complete halt at with less than 100 blocks remaining.
this is pretty serious for a fintech.

**Comment by epo-git** [comment] 2017-12-22 21:10
At last Its running. I had the same issues as described in the former posts. I found out the following facts.
(Ubuntu 16, Ethereum Wallet 0.9.3)
I connected apt with the ppa: sudo add-apt-repository -y ppa:ethereum/ethereum
and updated the package list. Then took a look in synaptic and tagged the packages ethereum, ethereumwallet, bootnode, geth, puppeth, wnode (may be overkill but who cares).

I mounted an external drive (vanilla sata HD) and created a folder for ethereum. 
next I started from terminal: geth --syncmode "fast"  --datadir "/<path-to-my-external-hd>" --cache=1024

Then I went sleeping. Next morning I stopped geth and created a link from my home folder .ethereum to the external drive and started "/opt/Ethereum Wallet/ethereumwallet" from terminal and got issues as above. 

First I cleared the way by "chmod -R <path-to-my-external-hd>" as I saw there was a permission problem. But no real progress.

Then  I tried:
opt/Ethereum Wallet/ethereumwallet" --syncmode light

Now the issues vanished and I observed a clean start recovering the missing blocks and starting the client when done. 

I stopped the app and started again. It took 15 minutes or so to start and I observed this lines in the start sequence:
[2017-12-22 10:54:21.923] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2017-12-22 10:54:22.916] [ERROR] Sockets/node-ipc - Connection failed (3000ms elapsed)
[2017-12-22 10:54:22.918] [WARN] EthereumNode - Failed to connect to node. Maybe it's not running so let's start our own...

This means ethereum wallet expects a working node to connect to. If there isnt one, it builts its own. This is probably a time consuming step. But after that the client started as before.

I watched also that there was heavy cpu use of etherium daemon. So I decided to calm down the hungry beast:
nice -15 "/opt/Ethereum Wallet/ethereumwallet" --syncmode light 

![ethereum wallet 2017-12-22 17 37 21](https://user-images.githubusercontent.com/22756087/34312496-e344f85e-e764-11e7-960b-0a4cba99aebc.png)

I observed the wallet lags in a range from 10'' to a few minutes when active. 

If the wallet stops updating for more than 15 minutes observe the log. There may be an error event  responsible. I found for example:
ERROR[12-22|21:52:18] Failed to retrieve current release       err="can't fetch trie key 80bace31c97b672967ed85d1050bcdab68cf944f2dec7f80c53e4e34feb79b6e: no suitable peers available" 
and no more updates.

Imho: There is some work left for the developers to make it run out of the box and the documentation/wiki have to explain the parameters.

**Comment by genosse** [comment] 2017-12-23 06:24
It does not work for me too. Complete halt just for 100-200 last blocks. I've tried to remove and reinstall everything, tried to start it on different PCs. 
Nothing helps. Developers, could you explain this?

**Comment by epo-git** [comment] 2017-12-23 16:05
@genosse: Which syncmode did you use? fast or light? I observed this behaviour only in fast mode.

**Comment by genosse** [comment] 2017-12-23 18:13
I deleted everything and restart it in light mode, it stucks with following message:
`ERROR[12-23|21:11:46] Failed to retrieve current release       err="can't fetch trie key e78f1dc71a26c210a9dc3255cc3c3698fac49fcbfbd9e26314a02cc2a4afb891: no suitable peers available"
`

**Comment by epo-git** [comment] 2017-12-23 18:26
This seems to be a temporary error. My recent log is:
ERROR[12-23|19:03:12] Failed to retrieve current release       err="can't fetch trie key 3d84877bffd0a7f44134cf192dc53ec47c414c78070c3aa55e55d0a39cc0db19: no suitable peers available"
INFO [12-23|19:18:21] Imported new block headers               count=384 elapsed=209.167ms number=4783762 hash=a588fe…3a7b86 ignored=0
INFO [12-23|19:18:23] Imported new block headers               count=182 elapsed=1.020s    number=4783944 hash=af9aaf…5d80d6 ignored=0
INFO [12-23|19:18:34] Imported new block headers               count=1   elapsed=11.475ms  number=4783945 hash=fbcd93…2f2cb8 ignored=0

Look at the number and the timestamp: its 20 minutes ago.

**Comment by 304805** [comment] 2017-12-26 04:00
I'm not impressed with this.

**Comment by stantoncbradley** [comment] 2017-12-31 19:42
waited hours just to get hung up on last 200 blocks. looks like this issue was opened in June and is still an issue? why is this closed? looks like I'm not the only person still experiencing this

**Comment by ajthemacboy** [comment] 2018-01-01 22:06
Same here. I synced the first 50 GBs really quickly, but can't get quickly past 4831152 at the moment.

**Comment by ryanstull** [comment] 2018-01-07 05:30
Same issue

**Comment by dreamwagon** [comment] 2018-01-07 15:59
I recently got a new computer and had to reinstall the mist wallet and I am now unable to sync. It doesn't appear related to any specific number of blocks remaining. The app just fails to sync even after days of waiting. Probably a good idea to switch to another wallet at this point. Mist is broken.

**Comment by neytron4** [comment] 2018-01-07 20:21
This is bullshishit. WTF is going on??? I spent a bunch of time to figure this out. WHY IT IS NOT SYNCING???????????????????????? FUCK MIST, FUCK GETH!!!

**Comment by coralnode** [comment] 2018-01-09 05:21
yeah, this is seriously a joke... can someone at least explain why this is happening?

**Comment by ajthemacboy** [comment] 2018-01-09 12:12
Light mode may or may not help people with this problem. Light mode only works for me about a third of the time, and never works while the network is congested, and some people have wallet issues in light mode. I left light mode syncing a few days and now it even syncs blocks more recent than those listed on explorers like Etherchain. Right now though I think geth is currently pretty unusable and people should consider Parity or similar.

**Comment by tedkimzikto** [comment] 2018-01-14 15:30
Still? I want to make a contract so bad... still 195 blocks left...

**Comment by toriningen** [comment] 2018-01-14 17:44
Syncing for almost a week now to no avail. Regardless of whether I hit "launch app" or wait at the splash.

**Comment by gurglespuge** [comment] 2018-01-19 08:26
Also tried this 5 different times fails  200 ish blocks before !!! frustrating

**Comment by coralnode** [comment] 2018-01-19 08:27
Is someone going to provide some info about this problem and the plan to fix it?

**Comment by ajthemacboy** [comment] 2018-01-19 11:25
@evertonfraga closed the ticket and no other devs have replied in months, I'm not sure they care.

**Comment by gregl83** [comment] 2018-01-19 11:53
read the entire thread guys, i failed to before commenting, closed by @evertonfraga in favor of this issue: https://github.com/ethereum/mist/issues/3097

i'd expect eta to be dependent on how many users are experiencing the issue and the complexity of fixing it.

some issues are not so trivial while others affect only a tiny subset of a user base and developers are forced to prioritize.

usage of github issue labels could perhaps prevent knee jerk reactions to unresolved "closed" issues.

**Comment by evertonfraga** [comment] 2018-01-19 13:57
@gregl83 best practices in these cases include put a reaction (👍 ) as a signal of "me too", instead of creating new issues. If people do that on issues with [Type: Canonical](https://github.com/ethereum/mist/labels/Type%3A%20Canonical) label, such as that #3097, it would be of an immense help. So we can spend more time coding than managing issues.

**Comment by tunggad** [comment] 2018-01-20 09:10
me too!!!
geth-1.7.3 node has been stucking at block 4937010 since 3 fucking days. real current block at writing time was 4939653. How can i start to learn coding Dapp without a complettly  synced private node????

**Comment by dorianr666** [comment] 2018-01-20 16:55
Can confirm. Cant sync last 210 blocks.

Using the fast sync mode, i was able to sync the entire thing until the last ~200 blocks in under a day, yet the last 200 blocks will never ever get synced.

Time of my machine is synchronized.

**Comment by coralnode** [comment] 2018-01-20 16:57
It is 2 weeks that I am stuck at last 200 blocks… 
Obviously developers don’t care about this report from so many people. I am wondering how they manage to sync their blockchain?

**Comment by desertainment** [comment] 2018-01-20 19:02
Bummer!  Same issue as everyone else in this thread.  Really wanted to create a contract but Etherium doesn't live up to the hype.  I'll be uninstalling the entire mess.

**Comment by tedkimzikto** [comment] 2018-01-21 04:40
So for me... I've launched an instance on AWS and installed geth.

geth --fast --cache=2048 

gave me same result. 

So, I tried geth --cache=2048

I waited 2 days and it actually finished syncing, which means eth.syncing gave me false.

**Comment by sudoman999** [comment] 2018-01-22 16:26
**Here are four points that could solve your issue:**
1. Update to the latest version. At the time of writing this post, the latest version was  0.9.3
2. Make sure that you have at least  20GB of free space on your hard drive.
3. Use a high-speed internet of about 100MBPs
4. Use an SSD Hard Drive.

**_Mostly point 1 and 2 will solve the issue. Point 3 and 4 are optional._**

**Bonus Tips**
1. To clear your memory space, you can use 'Disc Inventory X'. Link: http://www.derlien.com/
2. If you don't have any of the above requirements i.e.  Memory Space, High Speed and SSD then you can use a VPS on Digital Ocean. Here is a link to get free $10 credits: https://m.do.co/c/679338b50344

**Explanation of why I think this will work:**
I was stuck at 99% with 210 Blocks left. Nothing moved for about 8 hours. I had 6GB of free space and was on 1 MBPS internet connection. I simultaneously did two points. i.e. Removed the extra memory and moved to a high-speed internet. One of the two points seems to have worked.

My MacBook Air already had an SSD so not sure if it is a must but I read in multiple places that it is suggested to have an SSD. Let me know if my solution helps.

If it helps, you might want to show some love 😁. Here is my address for Etherium wallet: 0x22C1C345830fC82b1D1E26aBc26a32B7ad7D4D7A

**Comment by ChristBKK** [comment] 2018-01-23 09:12
Me too. Please fix this

**Comment by yihaient** [comment] 2018-01-24 08:50
Sync reaches 99% and stops 
I cannot locate my private key at the moment
So I need the wallet to sync just so I can send it to another wallet.
Please help and tell me what I need to do to access my ether. Thank you

**Comment by sudoman999** [comment] 2018-01-25 03:15
Which version of Ethirium Wallet are you on right now? Also, what is the
free memory space?

**Comment by taarushv** [comment] 2018-01-25 04:10
Same. I'm running a geth --testnet and it doesn't work either.

**Comment by tedkimzikto** [comment] 2018-01-25 05:29
I was having these problems for days... now it's solved.

Last 200blocks took nearly 3days. Trust me. Just leave the computer for couple days. Make sure you sync your time with network and it should all do.

**Comment by jay-loudway** [comment] 2018-01-25 17:43
This is happening for me and my friend as well. He has 215 blocks left with 25 peers connected and I have 126 blocks left with 10 peers connected. I managed to sync 4.9 million blocks though in under 4 hours and it just halted.

**Comment by coralnode** [comment] 2018-01-25 17:47
I find a dirty solution:
I removed the whole .ethereum folder  (back up your wallet files first), then used the unofficial 1.8 unstable release. Finally it fully synced. The official stable release never finished syncing after 3 weeks.

**Comment by yihaient** [comment] 2018-01-26 06:14
The latest version - I downloaded it in late December 2017 and I have over 200gb of memory.

**Comment by antekotarac** [comment] 2018-02-05 03:51
0.9.3, I'm supposed to get ether, I can check if I got it, cause this crappy wallet is in sync last 3 days.
Guys are you retarded??
This kind of software should be illegal.

**Comment by xSevithx** [comment] 2018-02-07 17:55
I have been trying to sync on the mainnet for weeks now. I have only succeeded ONCE in syncing MIST fully on the mainnet. I have zero problems with Rinkeby, but the mainnet will not fully sync, it delays when there is roughly 200~ blocks left. I removed everything, geth removedb, deleted all the files and restarted from scratch, let it sit, and it still did not fully sync on the main net. I understand that the sync has to download all 70m+ entries for the chain data, but the sync stalls when its almost finalize, is the implementation broken? Is this actually being working on or looked at? This has been an issue for *well over a year*. As far back as I can tell, I have never had sync on mainnet fully synced. It appears to blow up on itself if you need to stop syncing and resync, and also never fully syncs. This is a real issue, and this needs to be resolved, far too many people are experiencing this issue.

**Comment by alexgalkin** [comment] 2018-02-20 17:06
I have the same issue. Trying to sync main network for few days. Tried to remove all files and start from scratch. I am using v0.9.3 (the latest available at Releases section). Note: I have tried both Mist and MyEthereumWallet apps - result is the same at the moment. If no luck today will start check the CLI version.

**Comment by alexgalkin** [comment] 2018-02-20 17:08
This should be re-opened. Issue is not solved.

**Comment by xSevithx** [comment] 2018-02-20 17:30
I agree this issue needs to be reopened and resolved. I think the dev team should look at the network sync implementations and fix it. It's clearly broken. I have been running mist for weeks and even when the node goes offline for a few hours, I can't completely sync back up. It's been running for over a week, still behind, download 1 or 2 blocks per minute. I have 30mbps. Plenty space..

**Comment by piqdesigns** [comment] 2018-02-21 20:31
so i am missing 9 eth.  this is bullshit. honestly.  where did they go?

**Comment by 304805** [comment] 2018-02-21 20:32
complete BS
________________________________

**Comment by piqdesigns** [comment] 2018-02-21 20:33
how can eth grow with these issues. 9 eth is going to be a lot of money soon.

**Comment by 304805** [comment] 2018-02-21 20:42
Could you all imagine what kind of BS Ethereum really is if this

is from their website ??
________________________________

**Comment by micahcatlin** [comment] 2018-02-21 20:52
My guess is that this is a P2P connectivity problem, and not strictly a bug.

When a new Ethereum node is being started up and syncing, it may be too many "network hops" from the nodes which are in possession of the newest mined blocks to receive them quickly.

Right after a new confirmed block is available, it takes time for that block to be distributed widely, during which time an even-newer block may appear.  A new node which is distant from the action may never catch up.

**Comment by evertonfraga** [comment] 2018-02-28 03:26
Hi all, 

syncing with the default mode is now impractical for users with consumer computers. The recommended way is to use the Light Client (Develop menu > Sync with light client). Also, make sure you are using Geth 1.8.1.

It'll soon be the default option.

**Comment by evertonfraga** [comment] 2018-02-28 03:27
Here you'll find information about sync types: 
https://github.com/ethereum/mist/issues/3097
