### ISSUE TITLE
Wallet doesn't start on Windows XP

### ISSUE THREAD

**Issue by alzzz** [ethereum/mist#971] opened 2016-07-14 22:19 UTC
OS: Windows XP SP3 32 bit
Mist version: 0.8

ethereum-wallet.exe (win32, I tried 0.7.2 and 0.8) crashes on start with message: ethereum-wallet.exe is not a valid Win32 application.

**Comment by luclu** [comment] 2016-07-15 10:20
@alzzz unfortunately we can't support legacy software that does not receive security updates any more.
Closed as duplicate of https://github.com/ethereum/mist/issues/550.

**Closed by luclu** 2016-07-15 10:20 UTC
Labels: duplicate
