### ISSUE TITLE
Accounts Locked - No transactions getting confirmed or completed (selected one transaction fee too low)

### ISSUE THREAD

**Issue by larrysmith1000** [ethereum/mist#719] opened 2016-05-26 21:43 UTC
Today, from Mist Ethereum Wallet, I tried to send ether from my contract wallet to my account (the owner of the contract wallet.  For the first time, I selected the lowest possible transaction fee, to see how long it would take.  The transaction appeared (greyed) in the "latest transactions" list.  After about 5 minutes, (~20 blocks), the transaction disappeared from the list, and the transaction was never confirmed or transferred.  I checked the blockchain for the transaction with an explorer.  No luck.  Then the real problem started.

I assumed that the fee I selected was too low, and no miners took it, so I tried to do the transaction again (from my contract wallet to my account), and this time selected a high fee -- The same thing happened.  The transaction appeared (greyed in the list), no confirmations came for several blocks, then the transaction disappeared from the list.

I then tried to transfer some ether to The DAO from my contract wallet.  Same thing happened.
I then tried to transfer some ether from the owner account to another account (second owner of the Contract Wallet).  No luck there either!

It seems that the first transaction I requested is not getting picked up by miners due to me selecting too low of a fee, and with that transaction request still out there, my contract wallet and owner accounts are locked.  Has anyone experienced this?

Is there an expiration time for transaction requests?  Can I delete the queue of transaction requests?  If that first transaction goes through, will all the other ones I tried going to go through right after?

I want to buy some DAO Tokens before the deadline, but I am locked up here.  Any help would be appreciated.

Thanks!

**Comment by larrysmith1000** [comment] 2016-05-26 21:54
Here is a very old thread that looks like a similar issue, but using geth console:
https://github.com/ethereum/go-ethereum/issues/906

All my ether is locked up.  Please help!  Thx!

**Comment by larrysmith1000** [comment] 2016-05-27 01:16
I don't know if it was a coincidence, but now (3 hours later) I tried sending one more transaction (1 eth) from the owner's account, and again chose maximum fee.  On the very next block, the transaction went through, and so did all the prior transactions simultaneously.

Can anyone explain why this happened?  It is definitely a usability problem for noobs like me, which we should be trying to attract.

**Comment by luclu** [comment] 2016-05-27 02:05
I was able to observe this behaviour.

**Comment by larrysmith1000** [comment] 2016-05-27 05:17
I did read one thread about that, and it does sound very similar:
https://github.com/ethereum/go-ethereum/issues/906

**Comment by FaguiCurtain** [comment] 2016-05-29 03:14
it looks like I have a similar problem, initially due to sending myself a wrong transaction ?

https://github.com/ethereum/mist/issues/739

**Comment by alexvandesande** [comment] 2016-08-26 13:41
Yes, transactions are removed by the node after going unconfirmed for long. As it seems you've been able to send transactions again I'm closing this issue

**Closed by alexvandesande** 2016-08-26 13:41 UTC
Labels: bug

**Comment by david-sg** [comment] 2016-10-20 09:06
I have the same issue- 10 days later when my account balance hit the initial amount, the transaction was mined, sending my ether to the other account. This happened twice.
