### ISSUE TITLE
Can't import presale wallet

### ISSUE THREAD

**Issue by cayblood** [ethereum/mist#255] opened 2016-03-05 17:28 UTC
In pre-release 0.5.1, I'm told that my password is wrong when trying to import a presale wallet. However, this wallet seems to import just fine with geth.

**Comment by mudanoman** [comment] 2016-03-06 02:27
I also installed 0.5.1 Mac and experienced the same issue with "Wrong Password" despite it being the correct password.

**Comment by alexvandesande** [comment] 2016-03-07 11:55
This is a duplicate of https://github.com/ethereum/mist/issues/182

As far as we've been able to tell it's not a password issue, but some other problem that the node incorrectly reports as wrong password. Please try to import it directly with geth or the kraken presale import tool to test your password. If you have successfully swept your wallet and the password doesn't contain any personal information, the I'll kindly ask you to send me the file and password to avsa at ethdev.com, so I can test it myself and try to figure it out.

**Closed by alexvandesande** 2016-03-07 11:55 UTC

**Comment by adamluc** [comment] 2016-03-08 23:54
I have the same issue, the password I am entering is correct, but saying the password is incorrect. Trying to import a pre-sale wallet. Tested on kraken's tool, decryption worked.

**Comment by edwolf** [comment] 2016-03-16 16:17
Also had this issue on a mac but it worked on PC.  I then copied the keys generated on the PC version and pasted them into the mac version..worked perfectly.

**Comment by pal-presaleWrongPW** [comment] 2018-01-22 07:07
@cayblood what version of geth did you run to decrypt your presale wallet?

**Comment by pal-presaleWrongPW** [comment] 2018-01-22 07:09
@alexvandesande would there be any downside to running such an old version of [Wallet 0.5.1 (Beta 9)](https://github.com/ethereum/mist/releases/tag/0.5.1)?
