### ISSUE TITLE
Wallet empty!

### ISSUE THREAD

**Issue by vollkommenegal2017** [ethereum/mist#1713] opened 2017-03-07 14:58 UTC
I purchased some ethereum today and after more than 4 hours my wallet is still empty.

https://etherscan.io/address/[WALLETID] shows everything is fine, but in Mist my wallet is empty.

I can't also create a wallet contract. After typing in the name and pressing the button nothing happens.
I closed the application after 20 min. and started it again.
A second window appears ("Create contract" - 0.00 ETHER), but after typing in my password it says "Exceeds block gas limit". 
Typing password again: "Couldn't connect to the node, did it crash in the background?"
-> Yes, it did.  :-(

I tried 2 different computers.

What is going on?

#### System information
``````
Version: `0.8.9`
OS & Version: windows
Node type: default, i guess
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by luclu** [comment] 2017-03-08 17:49
Closed as duplicate of https://github.com/ethereum/mist/issues/1714.

**Closed by luclu** 2017-03-08 17:49 UTC
