### ISSUE TITLE
hard to create new account in ethereum

### ISSUE THREAD

**Issue by wangmorgan** [ethereum/mist#4050] opened 2018-08-05 10:23 UTC
- [x] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.0.0`
OS & Version: windows/linux/osx
Node version: `geth 0.0.0`
Number of blocks synchronized: 0
```

**Comment by evertonfraga** [comment] 2018-08-21 00:49
Duplicate of #4012. 

please follow from here: https://github.com/ethereum/mist/issues/4012#issuecomment-414512125

**Closed by evertonfraga** 2018-08-21 00:49 UTC
