### ISSUE TITLE
Mist 0.8.1 on Mac crashes after syncing

### ISSUE THREAD

**Issue by rveeblefetzer** [ethereum/mist#1010] opened 2016-07-21 05:56 UTC
Node type: geth
OS: osx
Network type: main
Mist version: 0.8.1

After working twice, Mist is now unexpectedly quitting right after syncing. On initial run, I saw what looked like the 0.7.4 Ethereum wallet, with my ETH in there. The next time I ran Mist, I got the browser, and saw no ETH, and it asked me for a new account. Now, it crashes. Running Mist from terminal ended with segfault 11.

Uploading a zip of node.log keeps failing, so here is the text. Below that, I'll paste the text from terminal:

node.log:
```
I0721 13:34:50.119659 cmd/utils/flags.go:678] You're one of the lucky few that will try out the JIT VM (random). If you get a consensus failure please be so kind to report this incident with the block hash that failed. You can switch to the regular VM by setting --jitvm=false
I0721 13:34:50.119806 ethdb/database.go:82] Alloted 512MB cache and 1024 file handles to /Users/hotsauce/Library/Ethereum/chaindata
I0721 13:34:50.208957 cmd/utils/flags.go:842] ------------------------------------------------------------------------------------------------
I0721 13:34:50.208978 cmd/utils/flags.go:843] Geth is currently configured to SUPPORT the DAO hard-fork!
I0721 13:34:50.208986 cmd/utils/flags.go:844] You can change your choice prior to block #1920000 with --support-dao-fork or --oppose-dao-fork.
I0721 13:34:50.208991 cmd/utils/flags.go:845] After the hard-fork block #1920000 passed, changing chains requires a resync from scratch!
I0721 13:34:50.208996 cmd/utils/flags.go:846] ------------------------------------------------------------------------------------------------
I0721 13:34:50.210464 ethdb/database.go:169] closed db:/Users/hotsauce/Library/Ethereum/chaindata
I0721 13:34:50.211338 ethdb/database.go:82] Alloted 512MB cache and 1024 file handles to /Users/hotsauce/Library/Ethereum/chaindata
I0721 13:34:50.334375 ethdb/database.go:82] Alloted 16MB cache and 16 file handles to /Users/hotsauce/Library/Ethereum/dapp
I0721 13:34:50.338840 eth/backend.go:172] Protocol Versions: [63 62], Network Id: 1
I0721 13:34:50.338979 eth/backend.go:201] Blockchain DB Version: 3
I0721 13:34:50.340518 core/blockchain.go:206] Last header: #1923924 [37c8283a…] TD=39717243037304104998
I0721 13:34:50.340544 core/blockchain.go:207] Last block: #1923924 [37c8283a…] TD=39717243037304104998
I0721 13:34:50.340555 core/blockchain.go:208] Fast block: #1923924 [37c8283a…] TD=39717243037304104998
I0721 13:34:50.340851 eth/handler.go:116] blockchain not empty, fast sync disabled
I0721 13:34:50.342283 p2p/server.go:313] Starting Server
I0721 13:34:53.538738 p2p/discover/udp.go:217] Listening, enode://a47e33c9b0ec721300e486629fb1a22bfc090af0f2ccbaa6fd834b3e37da0a2022b962cd29756c52b63eea5c3c90c883d5c9991677e17e02a80754515fbbeb7a@192.168.1.48:30303
I0721 13:34:53.539444 p2p/server.go:556] Listening on [::]:30303
I0721 13:34:53.540141 node/node.go:296] IPC endpoint opened: /Users/hotsauce/Library/Ethereum/geth.ipc
I0721 13:34:53.626615 p2p/nat/nat.go:111] mapped network port udp:30303 -> 30303 (ethereum discovery) using UPNP IGDv1-IP1
I0721 13:34:53.718130 p2p/nat/nat.go:111] mapped network port tcp:30303 -> 30303 (ethereum p2p) using UPNP IGDv1-IP1
I0721 13:35:23.541262 eth/downloader/downloader.go:320] Block synchronisation started
I0721 13:35:27.395972 eth/downloader/downloader.go:1087] Peer 2b4ae107c2fbd1ba [hs 0.00/s, bs 0.00/s, rs 0.00/s, ss 0.00/s, miss    0, rtt 20s]: head header set (item 0) broke chain ordering: requested 1919809, got 1923958
I0721 13:36:14.133443 eth/handler.go:295] Peer 0423e07df36ab59e [eth/63]: timed out DAO fork-check, dropping
I0721 13:37:23.542791 eth/handler.go:295] Peer 44edbd96ed7087e2 [eth/63]: timed out DAO fork-check, dropping
I0721 13:38:19.240420 core/blockchain.go:963] imported 5 block(s) (0 queued 0 ignored) including 18 txs in 1.223694164s. #1923929 [85e97c3f / 80f29e6a]
I0721 13:38:19.267203 core/blockchain.go:963] imported 2 block(s) (0 queued 0 ignored) including 8 txs in 26.67397ms. #1923931 [9963e3f9 / a33bf00b]
I0721 13:38:44.339811 core/blockchain.go:963] imported 42 block(s) (0 queued 0 ignored) including 106 txs in 336.643109ms. #1923973 [9289913e / 2a78f885]
 ```
terminal output: 
```javascript
macjawn:MacOS hotsauce$ ./Mist
[2016-07-21 13:34:44.156] [INFO] main - Running in production mode: true
[2016-07-21 13:34:44.210] [INFO] main - Starting in Mist mode
[2016-07-21 13:34:44.271] [INFO] Db - Loading db: /Users/hotsauce/Library/Application Support/Mist/mist.lokidb
[2016-07-21 13:34:44.283] [INFO] Windows - Creating commonly-used windows
[2016-07-21 13:34:44.283] [INFO] Windows - Create secondary window: loading, owner: notset
[2016-07-21 13:34:44.368] [INFO] updateChecker - Check for update...
[2016-07-21 13:34:45.938] [INFO] Windows - Create primary window: main, owner: notset
[2016-07-21 13:34:45.946] [INFO] Windows - Create primary window: splash, owner: notset
[2016-07-21 13:34:46.247] [INFO] ipcCommunicator - Backend language set to:  en-US
[2016-07-21 13:34:46.831] [INFO] (ui: splash) - Web3 already initialized, re-using provider.
[2016-07-21 13:34:46.970] [INFO] Sockets/node-ipc - Connect to {"path":"/Users/hotsauce/Library/Ethereum/geth.ipc"}
[2016-07-21 13:34:47.068] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2016-07-21 13:34:47.695] [INFO] updateChecker - App is up-to-date.
[2016-07-21 13:34:48.072] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2016-07-21 13:34:49.078] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2016-07-21 13:34:50.065] [ERROR] Sockets/node-ipc - Connection failed (3000ms elapsed)
[2016-07-21 13:34:50.067] [WARN] EthereumNode - Failed to connect to node. Maybe it's not running so let's start our own...
[2016-07-21 13:34:50.067] [INFO] EthereumNode - Node type: geth
[2016-07-21 13:34:50.067] [INFO] EthereumNode - Network: main
[2016-07-21 13:34:50.067] [INFO] EthereumNode - Start node: geth main
[2016-07-21 13:34:53.125] [INFO] EthereumNode - 3000ms elapsed, assuming node started up successfully
[2016-07-21 13:34:53.126] [INFO] EthereumNode - Started node successfully: geth main
[2016-07-21 13:34:53.138] [INFO] Sockets/node-ipc - Connect to {"path":"/Users/hotsauce/Library/Ethereum/geth.ipc"}
[2016-07-21 13:34:53.139] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2016-07-21 13:34:54.145] [INFO] Sockets/node-ipc - Connected!
[2016-07-21 13:34:54.145] [INFO] NodeSync - Ethereum node connected, re-start sync
[2016-07-21 13:34:54.146] [INFO] NodeSync - Starting sync loop
[2016-07-21 13:34:54.147] [INFO] Sockets/7 - Connect to {"path":"/Users/hotsauce/Library/Ethereum/geth.ipc"}
[2016-07-21 13:34:54.148] [INFO] main - Connected via IPC to node.
[2016-07-21 13:34:54.166] [INFO] Sockets/7 - Connected!
[2016-07-21 13:34:54.176] [INFO] (ui: splash) - network is mainnet
[2016-07-21 13:38:46.201] [INFO] NodeSync - No more sync necessary
[2016-07-21 13:38:46.204] [INFO] main - Loading Interface at file:///Applications/Mist.app/Contents/Resources/app.asar/interface/index.html
[2016-07-21 13:38:46.263] [INFO] NodeSync - Sync loop ended
[2016-07-21 13:38:46.524] [INFO] Sockets/8 - Connect to {"path":"/Users/hotsauce/Library/Ethereum/geth.ipc"}
[2016-07-21 13:38:46.528] [INFO] Sockets/8 - Connected!
[2016-07-21 13:38:47.088] [INFO] (ui: mist) - Web3 already initialized, re-using provider.
[2016-07-21 13:38:47.224] [INFO] (ui: mist) - Exception in queued task: TypeError: Cannot read property '0' of null
    at file:///Applications/Mist.app/Contents/Resources/app.asar/interface/c9ff965333ca5e3d10036d86b347421e075d9886.js:88:29320
    at Object.o.nonreactive (file:///Applications/Mist.app/Contents/Resources/app.asar/interface/c9ff965333ca5e3d10036d86b347421e075d9886.js:15:4471)
    at Object.changedAt (file:///Applications/Mist.app/Contents/Resources/app.asar/interface/c9ff965333ca5e3d10036d86b347421e075d9886.js:88:29174)
    at Object.changedAt (file:///Applications/Mist.app/Contents/Resources/app.asar/interface/c9ff965333ca5e3d10036d86b347421e075d9886.js:84:2673)
    at changed (file:///Applications/Mist.app/Contents/Resources/app.asar/interface/c9ff965333ca5e3d10036d86b347421e075d9886.js:48:4342)
    at Object.r.applyChange.changed (file:///Applications/Mist.app/Contents/Resources/app.asar/interface/c9ff965333ca5e3d10036d86b347421e075d9886.js:48:3614)
    at file:///Applications/Mist.app/Contents/Resources/app.asar/interface/c9ff965333ca5e3d10036d86b347421e075d9886.js:46:4063
    at runTask (file:///Applications/Mist.app/Contents/Resources/app.asar/interface/c9ff965333ca5e3d10036d86b347421e075d9886.js:3:4319)
    at flush (file:///Applications/Mist.app/Contents/Resources/app.asar/interface/c9ff965333ca5e3d10036d86b347421e075d9886.js:3:4578)
    at drain (file:///Applications/Mist.app/Contents/Resources/app.asar/interface/c9ff965333ca5e3d10036d86b347421e075d9886.js:3:4679)
[2016-07-21 13:38:47.359] [INFO] (ui: mist) - Meteor starting up...
Segmentation fault: 11
```

**Comment by luclu** [comment] 2016-07-21 06:52
Duplicate of https://github.com/ethereum/mist/issues/1002

**Closed by luclu** 2016-07-21 06:52 UTC
Labels: duplicate
