### ISSUE TITLE
_.mixin is not a function

### ISSUE THREAD

**Issue by lazukars** [ethereum/mist#472] opened 2016-04-06 01:06 UTC
Node type: geth
OS: Ubuntu 14.04
Network type: main
Mist version: 0.0.0 ( On master branch. Pulled 04-05-16 )

I've followed the install instructions here, https://github.com/ethereum/mist, to a tee. When I run `electron .`, the following error occurs. Please see the screenshot.

![error__mist](https://cloud.githubusercontent.com/assets/250052/14302720/fed390d4-fb71-11e5-9128-2978f06488c8.png)

**Comment by hiddentao** [comment] 2016-04-13 07:42
I just tried this on the latest `master` and didn't see this error. I get the GUI showing up and sync begins.

**Comment by lazukars** [comment] 2016-04-15 01:52
Hmm. Just tried pulling master again. I got the same issue. What OS did you try this on?

**Comment by hiddentao** [comment] 2016-04-15 06:39
OS X El Capitan 10.11.2

**Comment by frozeman** [comment] 2016-04-15 09:19
Can you try the `wallet` branch? that should have fixed it

**Comment by lazukars** [comment] 2016-04-19 00:59
So it looks like this was an issue with electron. I was running the wrong version. 

However, when running `npm install -g electron-prebuilt@0.37.2`, as instructions state, the error in the attached  screenshot occurs. 
![electron-bug](https://cloud.githubusercontent.com/assets/250052/14624399/5ccaa7a0-05a8-11e6-8173-6805e7f23228.png)

Note: About a month ago, I had none of these issues, and Mist worked fine.

**Comment by hiddentao** [comment] 2016-04-19 01:01
Could you try running `npm cache clean` and then again doing it? It looks like a possibly corrupted `package.json` in one of Electron's depenencies.

**Comment by hiddentao** [comment] 2016-04-19 01:01
Also, `npm uninstall -g electron-prebuilt` followed the installation call again.

**Comment by lazukars** [comment] 2016-04-19 01:16
I've done the following:


`npm uninstall -g electron-prebuilt`
`npm cache clean` which fixed that last screenshot error. 
`npm install -g electron-prebuilt@0.37.2`
`electron -v` : output: v0.37.2

`cd mist`
`git pull && git submodule update` ( on master branch )
`npm install`
`cd interface && meteor`

Now, when running `electron .` inside the mist dir, I'm getting the initial issue error again, _.mixin is not a function. See initial screenshot. I've tried `electron . --mode wallet` as well. The same _.mixin is not a function occurs.

**Comment by hiddentao** [comment] 2016-04-19 01:23
Could you try it on the `develop` branch please - that's always the actively developed branch. Just want to rule out branch differences.

**Comment by lazukars** [comment] 2016-04-19 01:27
Sure. Just tried the same commands, from the last comment, on the `develop` branch. Outcome is the same: `_.mixin is not a function` when running `electron .`

**Comment by hiddentao** [comment] 2016-04-19 01:42
Ok, can you check within `node_modules` to see if you have `underscore` installed. And if you do please tell us what the `version` number is from its `package.json`.

**Comment by lazukars** [comment] 2016-04-19 01:46
Sure. In mist/node_modules/underscore/package.json. Looks to be v 1.8.3. See screenshot.
![package-json](https://cloud.githubusercontent.com/assets/250052/14625195/ede7f7e6-05ae-11e6-8113-37587a876612.png)

**Comment by hiddentao** [comment] 2016-04-19 01:54
Great. Inside `node_modules/underscore` could you open up `underscore.js` and search for `_.mixin` to see if it exists. 

If it does then the next step is to open up `modules/utils/underscore.js` and place the following code after the import at the top:

```js
const _ = module.exports = require('underscore');

console.log(_.VERSION, Object.keys(_));
```
 Then run the app - this way we can make sure that the version of underscore being loaded at runtime is the same as what's installed. And it will also output what methods are available on the object.

**Comment by lazukars** [comment] 2016-04-19 02:03
No problem. `node_modules/underscore/underscore.js` is an empty file

**Comment by hiddentao** [comment] 2016-04-19 02:28
Ah so looks like `underscore` didn't install correctly. What I would do is remove your `node_modules` folder and re-run `npm install`.

**Comment by lazukars** [comment] 2016-04-19 02:43
Ok. Doing what you suggested worked. When I pull down new code locally, is there some command that should be run so this issue can be avoided in the future? Or just delete the node_modules folder and run `npm install` after each pull?

There's a new problem now, once the _mixin problem was fixed. When I run `electron .` the UI loads for about 5 seconds and immediately crashes.

**Comment by hiddentao** [comment] 2016-04-19 02:45
For the crash, if you're on the `develop` branch could you run: `electron . --loglevel trace` and paste the output in here. Might give us some clues.

As for the module issue, usually you shouldn't have to remove the node_modules folder everytime. It should just work. But if you encounter this again it's worth a try.

**Comment by lazukars** [comment] 2016-04-19 02:50
Thanks for the tips. Here's the log trace:
![trace](https://cloud.githubusercontent.com/assets/250052/14626263/f90e3456-05b7-11e6-996d-fe51df650b0c.png)

**Comment by hiddentao** [comment] 2016-04-19 03:29
Ok, this is hard to debug right now. We will hopefully be capturing UI logs too soon, see #502. In the meantime you could try stopping your existing geth instance and then running electron - it should start up its bundled copy of geth. Maybe that will make a difference.

**Comment by hiddentao** [comment] 2016-04-19 04:59
Are you able to start the app in `wallet` mode?

**Comment by hiddentao** [comment] 2016-04-19 05:00
I'm also having trouble starting in `mist` mode.

**Comment by lazukars** [comment] 2016-04-19 12:12
Wallet mode opens, but it opens to a blank white screen, with the toolbar
on top.
-- 
Ryan Lazuka

**Comment by frozeman** [comment] 2016-04-19 12:31
It seems something might be wrong with your web3.js you've pulled. Can you install web3@0.15.2 manually from inside your mist folder?

**Comment by lazukars** [comment] 2016-04-19 17:05
Here's what I have done on the develop branch

`cd mist/node_modules`
`rm -rf web3`
`cd .. && npm install web3@0.15.2`
`cd ~/meteor/interface`
`meteor`
`cd ../ && electron .`

Result: Same problem. The UI loads for about 5 seconds then crashes. I've tried stopping my geth instance, like previously suggest,and that does not work either and the results are the same.

**Comment by rolandkofler** [comment] 2016-04-25 18:33
Maybe I'm the only one who didn't know it, but: the error occurs at Line 27 in mistUI.js

`window.web3 = new Web3(new Web3.providers.IpcProvider('', ipcProviderWrapper));`

More precisely when Web3 is instantiated (not when the IpcProvider is constructed).
I will continue with my research tomorrow afternoon, but if you have any idea would be great to hear it!

**Comment by hiddentao** [comment] 2016-05-02 07:18
I don't seem to get an error at the Web3 construction point. Am still investigating.

**Comment by hiddentao** [comment] 2016-05-02 07:53
I've narrowed it down to the window creation line:

```js        
global.mainWindow = new BrowserWindow({
            title: global.appName,
            show: false,
            width: 1024 + 208,
            height: 720,
            icon: global.icon,
            titleBarStyle: 'hidden-inset', //hidden-inset: more space
            backgroundColor: '#D2D2D2',
            acceptFirstMouse: true,
            darkTheme: true,
            webPreferences: {
                preload: __dirname +'/modules/preloader/mistUI.js',
                nodeIntegration: false,
                'overlay-scrollbars': true,
                webaudio: true,
                webgl: false,
                textAreasAreResizable: true,
                webSecurity: false // necessary to make routing work on file:// protocol
            }
        });
```

When I comment out the `nodeIntegration` line I don't get a crash - but I also just get a blank window. When I uncomment the line I start to see the UI contents show, but then the whole thing crashes.

**Comment by hiddentao** [comment] 2016-05-02 08:05
So `nodeIntegration` must be disabled for the Meteor app to work, which means the Meteor app itself might be the cause - but then I'm still getting no errors from within.

**Comment by hiddentao** [comment] 2016-05-02 09:55
Narrowed it down. The Mist interface shows a couple of default "tabs". One renders `about:blank` and the other shows `http://ethereum-dapp-wallet.meteor.com`. I actually am able to see neither tab but in any case the `<webview>` tag used to render `about:blank` doesn't work - and causes the whole app to crash.

**Comment by hiddentao** [comment] 2016-05-02 10:01
At least on my machine the `<webview>` tag fails to render and thus the Mist dapp content section is empty.

**Comment by hiddentao** [comment] 2016-05-02 10:20
@frozeman Here is my proposed fix for this crash issue: 

1. Change `about:blank` to `ethereum.org` for default browser tab in Mist. 
2. Add command-line option to reset Mist interface tabs - I had to do this to get the `webview` working, as otherwise it keeps using what's in localforage. A command-line option is required since an in-app GUI option won't be usable if the app keeps crashing. We could still, however, add an in-app GUI option to reset the interface as this may be something people wish to use more than once.

**Comment by hiddentao** [comment] 2016-05-03 06:11
PR in #548

**Comment by luclu** [comment] 2016-07-18 19:08
PR merged.

**Closed by luclu** 2016-07-18 19:08 UTC
Labels: bug
