### ISSUE TITLE
Mist crashes everytime I try to switch accounts

### ISSUE THREAD

**Issue by bamos01** [ethereum/mist#1149] opened 2016-09-08 02:34 UTC
#### System information'

Mac OSX
Version: 0.82

Node type: geth

it seems to work but if I switch accounts by clicking in top corner, it crashes

```

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files (Go to `menu -> accounts -> backup -> application data` and upload as zip-archive):
  -   osx: `~/Library/Application Support/Mist/node.log` 
  -   windows: `%APPDATA%/Roaming/Mist/node.log`
  -   linux: `~/.config/Mist/node.log`
```

**Comment by bamos01** [comment] 2016-09-08 02:38
Note- it seems to not crash if i open Mist separately.  Before I was opening a geth terminal from the console and then starting Mist

**Comment by evertonfraga** [comment] 2016-09-08 03:08
Hi, I would kindly ask you to attach a related log entry, if possible.

Thanks!

**Comment by evertonfraga** [comment] 2017-08-14 16:59
Seems like a duplicate of #1154.

**Closed by evertonfraga** 2017-08-14 16:59 UTC
